### ISSUE TITLE
Setup wizard

### ISSUE THREAD

**Issue by breiler** [winder/Universal-G-Code-Sender#1009]
## Feature request
I would like to see a setup wizard that would make it easier to get started with UGS configure a controller. 

I've started the implementation on a minimum viable product and would like your input. 

* Connecting to GRBL:
![screenshot 2018-04-15 21 38 19](https://user-images.githubusercontent.com/8962024/38782625-a99c00de-40f6-11e8-8c1d-003a1a46c314.png)
![screenshot 2018-04-15 21 38 37](https://user-images.githubusercontent.com/8962024/38782627-ad10c916-40f6-11e8-98d8-960ee74a6379.png)
* Motor wiring
![screenshot 2018-04-15 21 38 59](https://user-images.githubusercontent.com/8962024/38782680-850b3cac-40f7-11e8-80cd-2da46d376c7f.png)
* Calibrating step lengths
![screenshot 2018-04-15 21 39 11](https://user-images.githubusercontent.com/8962024/38782703-cbfc1384-40f7-11e8-9d4d-7903ee3dc8ee.png)
* Configuring limit switches
![screenshot 2018-05-03 14 45 29](https://user-images.githubusercontent.com/8962024/39577163-cdc70178-4ee0-11e8-810b-c585033abad2.png)
* Configuring homing
![screenshot 2018-05-03 14 46 07](https://user-images.githubusercontent.com/8962024/39577133-bfa4acb2-4ee0-11e8-8878-b99c4769cbe9.png)
* Configuring soft limits
![screenshot 2018-04-15 21 40 16](https://user-images.githubusercontent.com/8962024/38782721-ee2fcfae-40f7-11e8-924b-89c7375d3516.png)

**Comment by vMeph** [comment]
great job!!!

**Comment by RecceDG** [comment]
I'd like to see a UI button that is "set soft limit on [X|Y|Z] axis here"

**Comment by breiler** [comment]
@RecceDG you mean a button somewhere more accessible than in the last step of a setup wizard, like in the toolbar menu?

There is a problem that, in order to use soft limits you need to have homing enabled (assuming you are using a GRBL based controller). And now we are just talking about enable/disable. There is a lot of other parameters that should be available eventually; direction, debounce, pull-off, seek rate and feed rate.

A prerequisite to enabling homing is that you need hard limits enabled.

So there is a lot of stuff that needs to be configured before being able to enabling soft limits. 
How should such a button behave if the requirements for enabling soft limits isn't met?

**Comment by jahnj0584** [comment]
I think he means like use current machine POS as the soft limit length.

I just jog until i hit my hard stops. Whatever that value is i go 1mm less

**Comment by RecceDG** [comment]
> A prerequisite to enabling homing is that you need hard limits enabled.

That isn't the case. My machine will happily crash the limit stops.

I have limit switches on X, Y, X minimums. First thing I do on startup is home the machine to set machine zero. That works great. But currently, the machine does nothing with limits, hard or soft.

Yes, I can manually set them via the $ codes - I just haven't done it yet. But really, these should be UI elements. There should be a light "hard limits engaged", "soft limits engaged". If you try and jog past a soft limit, it should jog up to the soft limit, then light "[Z|Y|Y] Limit" and maybe sound a tone?

And yes, it would be helpful to be able to set current machine position to either min or max soft limit (so you can protect fixtures, etc) plus be able to *clear* soft limits (which should reset the mins to machine zero, and the max to the configuration value in your wizard.

I'm OK with soft limits being conditional on homing.

I've been doing a lot of complicated carves with my XCarve lately, and I keep tripping on UGS UI and usability problems. I keep meaning to do a quick MSPaint mockup of what I think needs to be on the UI.

**Comment by breiler** [comment]
@RecceDG in the issue #983 you had neither hard limits ($21) or soft limits ($20) enabled. Have you changed your configuration?

@jahnj0584 setting software limits by jogging to that location is a good idea, I might add it later.

**Comment by breiler** [comment]
The setup wizard is now available in the latest nightly build. Please give it a try and any feedback is appreciated.

This is first version and there's room for a lot of improvements.  I have a backlog with stuff that I want to change or add. But it would be nice to know if it works this far! =)

**Comment by breiler** [comment]
I tweaked the timeout.
The wizard is in place and it looks like it's working.
