### ISSUE TITLE
MacOS Port not in list for CNC machines using CH340 chips

### ISSUE THREAD

**Issue by MarkiiD** [winder/Universal-G-Code-Sender#1016]
## Problem description 
I have a cheap Chinese Woodpecker CNC machine that uses the CH340 serial/USB chip. When I plug it in to my Mac it doesn't appear in the drop down port list. I can enter the port name manually and connect successfully.

### Expected Behavior
The serial port list should show the CNC port on the list

### Actual Behavior
The serial port isn't shown.

### Steps to Reproduce the Problem
1. Start UGS
2. Plug in the CNC machine
3. Refresh the port list
4. An error dialog pops up 'No serial ports found'

#### Version
Universal Gcode Platform (Version 2.0 [nightly] / Jul 23, 2017)

I've also downloaded the latest code and built it - I get the same results

#### Operating system
Mac OSX High Sierra

#### Platform
GRBL 0.9j

#### Other
I tried the Arduino app and the port appears, shown in the list as **/dev/cu.wchusbserial1440** so I went and downloaded the Arduino source code... they appear to be using a different version of jssc/SerialPortList.java (looks like they've copied it in and updated it).

The commit comment for this change seems to be exactly what I'm hoping can be fixed for UGS

https://github.com/arduino/Arduino/commit/f91670e0d039a237ecf73ad902bd5a487308ea64

"Fixed JSSC upload problem with Arduino Due on MacOSX
JSSC, on unix based systems like linux and MacOSX, when listing serial ports
tries to open each port to ensure its existence. While this check works well for
linux ports /dev/ttyS0..31, it leads to unexpected behaviuors on MacOSX in
particular with USB-CDC virtual serial ports.
This patch disable the check and keep it enabled only for linux ttySxx ports.

This adds also tty.* and cu.* to the list of available serial ports on MacOSX."

**Comment by winder** [comment]
I've known about this issue for a while but have been reluctant to pull in the additional dependency. Unfortunately, JSSC seems to be practically abandoned to there may be no other option:
https://github.com/winder/Universal-G-Code-Sender/issues/704#issuecomment-322241643
https://github.com/winder/Universal-G-Code-Sender/issues/261#issuecomment-122441168
