### ISSUE TITLE
Need focus back to the command line after last command.

### ISSUE THREAD

**Issue by AbySet** [winder/Universal-G-Code-Sender#1019]
## Suggestion
Give back the focus to the command line for the next command.
After taping a command and press ENTER, a cursor is lost somewhere but not in command line.
Please let the cursor stay in command line unless we click somewhere else.

#### Version
UGS Platform 2.0 - Nightly Build April 22, 2018

#### Operating system
Windows 8.1 x64

#### Platform
 grbl_v1.1f.20170801

**Comment by winder** [comment]
This will be fixed in the next build, thanks @breiler!
