### ISSUE TITLE
"GRBL has not finished booting." issue after the windows update

### ISSUE THREAD

**Issue by mateuszbugaj** [winder/Universal-G-Code-Sender#1022]
Hi, some time ago i build a cnc based on a grbl that was running by UGS and it worked without a problem for few months. Two days ago there was some Windows 10 update and my guess is that this caused my problems.

![screenshot 1](https://user-images.githubusercontent.com/38944068/39574112-3ad03862-4ed6-11e8-991d-c9080ec30b15.png)

I'm using Arduino UNO (clone but without CH340) with CNC shield (GRBL 0.8c compatible as Ebay description says) and UGS v2 [nightly]

I tried to use diferent versions of UGS like version 1.0.9 or Universal Gcode Platform. I also changed Arduino Uno and reloaded grblUpload sketch. I instaled java actualisation.
I read some similar issues on this forum but my setup worked and sudenlly stoped while usualy those issues are posted by people who have problem with new setup. I would be happy to see your suggestions. Thanks

**Comment by winder** [comment]
Some common causes and steps to try for this issue are described here:
http://winder.github.io/ugs_website/guide/troubleshooting/#grbl-has-not-finished-booting

**Comment by mateuszbugaj** [comment]
I already tried these, also grbl works when I'm using Arduino IDE

**Comment by winder** [comment]
What version of GRBL are you using? The 9600 baud rate hasn't been used in a very long time.

**Comment by mateuszbugaj** [comment]
V0.9, worked well with 9600 baud rate till now

**Comment by winder** [comment]
Have you tried 115200? That is the default setting for v0.9.

**Comment by mateuszbugaj** [comment]
It's working! It was set by default to 9600 and i didn't change it. I had no idea it should be 115200 because i never had any problems with that. Any way, I am very grateful, thanks, Mr. Winder.
