### ISSUE TITLE
UGS and Java

### ISSUE THREAD

**Issue by mholmberg120** [winder/Universal-G-Code-Sender#1037]
Hi 
I am a total beginner.  I get this error message  when  try to open UGCS.  I have a new computer and I had no problems on my old computer run and cutting with autodesk 360 and UGCS?  I know Java is installed because I can run other Java programs.  please any help would be appreciated? 

![screenshot 1](https://user-images.githubusercontent.com/39389757/40215515-d5b060b0-5a15-11e8-967b-15e2959b499f.png)

Java Installation not completed
Unable to install Java
There are errors in the following switches:

Java Installation not completed
Unable to install Java
There are errors in the following switches:
C:\Users\mholm\OneDrive\Desktop\MonkeyBirdyDesign\UniversalG
CodeSender.jar
Check that the commands are valid and try again

Thank you
Michael

**Comment by winder** [comment]
Does it work if you run using the .bat file?

**Comment by breiler** [comment]
With no answer we are not able to help any further, closing this issue.
