### ISSUE TITLE
UGS Platform not opening

### ISSUE THREAD

**Issue by wolfspaw** [winder/Universal-G-Code-Sender#1047]
When I open UGS Platform it loads half way then closes

**Comment by winder** [comment]
Please provide the log file located here:
http://winder.github.io/ugs_website/guide/troubleshooting/#property-files

**Comment by breiler** [comment]
Interesting, could you post the contents of the file:
C:\Users\adam\.ugs\UniversalGcodeSender.json

The work around would probably be to delete this file and restart. But it would be nice to know how this happened in the first case.

**Comment by wolfspaw** [comment]
I can’t find that file. I’ve also deleted everything and tried to download it again. Am I missing something that I need to delete?

**Comment by wolfspaw** [comment]
I’ve deleted everything again and downloaded ugs platform again and everything is working now. Thanks for the help.

**Comment by carneeki** [comment]
@winder - I've noticed a couple of tickets that were solved with deleting
the config files (perhaps key/value pairs change over time?). I wonder if
it's worth putting this hint in a troubleshooting guide.

**Comment by winder** [comment]
@carneeki I think the latest version should detect the error and re-initialize everything to the default values. I'm not sure why this same problem cropped up a couple times recently though.
