### ISSUE TITLE
Pendant very slow motion on last release

### ISSUE THREAD

**Issue by Subteblu** [winder/Universal-G-Code-Sender#1073]
I have very slow movement in pendant when use the lastest version of July. Work fine using the screen controller or keyboard.

Another question: Sometimes, if i dont remember include a final M5 in my gcode, the spindle does not stop when the work is finished. Is it possible to add an option with automatic m5 after M30?

Thanks, its a great software.

**Comment by JacksCrafts** [comment]
I am wondering about this too.
Does the pendant only work with mm?
And can you change the feedrate?

When I hit the X or Y direction it goes at feedrate F1
 $J=G91X10F1
ok
>>> $J=G91Y5F1
But if I click on Return to zero it is very fast.

ok
>>> G90 G0 Z0
>>> G90 G0 X0 Y0
>>> G90 G0 Z0
It does not state a F-rate

Product Version: Universal Gcode Platform 2.0 [nightly] / Dec 18, 2018
Java: 1.8.0_211; Java HotSpot(TM) 64-Bit Server VM 25.211-b12
Runtime: Java(TM) SE Runtime Environment 1.8.0_211-b12
System: Windows 10 version 10.0 running on amd64; Cp1252; en_US (ugsplatform)

**Comment by breiler** [comment]
If you upgrade to the latest build of UGS and you'll get the brand new pendant. Let me know if this works better for you!

**Comment by JacksCrafts** [comment]
I thought I was the only one up at 5AM.
Thanks Breiler I will try the latest build again, I had trouble with it freezing up on me so I went back to Dec 18. But I have since then uninstalled and reinstalled java and that may have been my trouble. I will let you know.

**Comment by breiler** [comment]
It's not 5AM in Sweden! 😜

**Comment by JacksCrafts** [comment]
Good news the nightly build works fine now.
ran the pendant with my inches set in the jog module.
And it is the same, F1
So I set to mm and closed the program and the pendant and restarted but it is the same.
Also I could only activate the buttons one. I hit +x and it went 10 mm at F1 but I could not get it to go another 10mm in the positive direction, I could get it to go -10mm but only once.
![Pendant SpeedF1](https://user-images.githubusercontent.com/44066988/57919769-86338a00-7867-11e9-8dae-6c71dbe11fe1.jpg)
![Pendant SpeedF2mm](https://user-images.githubusercontent.com/44066988/57919770-86338a00-7867-11e9-8dd0-4ba088a9e803.jpg)

**Comment by breiler** [comment]
It looks like you still have the old pendant. Can you do a complete refresh in the browser (CTRL+F5)

**Comment by JacksCrafts** [comment]
Well after F5 I got a blank
Does this mean my IE is out of date?
![Pendant SpeedF3mm](https://user-images.githubusercontent.com/44066988/57920701-a2382b00-7869-11e9-9878-2cd4a0f09663.jpg)
![Pendant SpeedF4mm](https://user-images.githubusercontent.com/44066988/57920702-a2382b00-7869-11e9-82ee-ceddef13d570.jpg)

**Comment by breiler** [comment]
I think IE 11 is a bit outdated I can try to make it working with that version but that would require some time.

May I suggest trying Google Chrome or Firefox in the meantime?

**Comment by JacksCrafts** [comment]
So I tried Micrsofts Edge and it works.
![Pendant SpeedF5mm](https://user-images.githubusercontent.com/44066988/57921549-98afc280-786b-11e9-80aa-fbbf4f9f66b5.jpg)
Thanks for your help
Jack

**Comment by JacksCrafts** [comment]
Oh no I do not need to use IE, dah me I just had this misconception that google's chrome did not play well with Java. So I never tried it. This pendant is very nice I did not know what I was missing.
Thanks again I am glad to know I did not wake you up at 5AM for something that turns out to be so simple.
