### ISSUE TITLE
"zed step size" not enbled

### ISSUE THREAD

**Issue by jiarko** [winder/Universal-G-Code-Sender#1077]
## Problem description 

 Hi, I'm trying to use the uGS platform on my old netbook equiped with windows 7 home 32 bit.

I've realized that both UGS platform and the std unoversal gcode sender have the "zed step size" spin box not enabled. If anyhow I send z movement command the machine behaves correctly with both software.

here a screenshot

![image1](https://user-images.githubusercontent.com/24867746/42575824-9928707e-8521-11e8-8a11-7c9d2318f1b7.jpeg)

any suggestion on how to fix this issue?

thanks
Andrea

**Comment by winder** [comment]
Are you asking how to enable that setting? There is a “separate z step
size” setting in the program menu or settings menu.

**Comment by jiarko** [comment]
Could you pls tell me where this setting is?

cause if I use another pc without touching anything (I mean just unzip the folder and start the program)  the "ZStep size" is enabled by default. that's why I've thought it is an issue.

thanks

**Comment by breiler** [comment]
You should find it in the menu:
![image](https://user-images.githubusercontent.com/8962024/42576975-ec290336-8523-11e8-8834-134c080dcdc4.png)

**Comment by jiarko** [comment]
thanks, I'll check this setting!!
thanks!!!

**Comment by jiarko** [comment]
the "issue2 is fixed as you suggested!!!

dont know why same program started oin 2 different machine has this setting not set in the same way

thanks a lot for the quick answer!!!
