### ISSUE TITLE
4th axis support

### ISSUE THREAD

**Issue by yaroslavVl** [winder/Universal-G-Code-Sender#1084]
## Feature request
I've added 4th axis for STM32F103 (usbcnc), and tested it for a long time.
Now it's work.
https://github.com/usbcnc/grbl/issues/51
Сan I expect to support the additional axis in the future in your software?
(without visualization of course)
Now it's work with Universal Gcode Platform 2.0 [nightly] / Jul 15, 2018
but there is no comfort navication for 4th (A) axis.

#### Platform
  GRBL 1.1f on STM32F103 USBCNC https://github.com/usbcnc/grbl

**Comment by winder** [comment]
Working on this in #1068
