### ISSUE TITLE
Make the jog plugin the default jog controller

### ISSUE THREAD

**Issue by breiler** [winder/Universal-G-Code-Sender#1089]
The new jog plugin supports continuous jogging, dark theme and is better adjusted to the given window size. 

Make it the default jog module and remove the old.

We've also got some support issues where users want separate step sizes for XY and Z. Should we reenable this as the default again?

**Comment by winder** [comment]
Yes, I think it's time to deprecate the old jog controller in the platform. Separate XY/Z axis should be the default value, I wonder if this even needs to be configurable maybe it can always be on.
