### ISSUE TITLE
 "Home machine" button causing G28 to crash hard limit

### ISSUE THREAD

**Issue by fruktbomb** [winder/Universal-G-Code-Sender#1097]
Hi there!

I have been using the classic version for two years never updating, but now I had to change my computer due a breakdown and thought I'll upgrade to platform UGS. 

### Problem
I think common action "home machine" is acting differently compared to classic from two years ago. after homing by clicking "Home machine", G28 will cause a crash to hard limit. G28 should return to $H bounce position and not to limit switches. 

Now every fusion360 generated nc-file end up crashing in the beginning though they worked nicely before upgrade.

### expected behaviour
Previous classic version from two years ago (I don't remember the version) acted so that g28 returned to homing bounce position, and thus, not activating hard limits. 

### Proposal
Should the "home machine" button call a macro $H; $G28.1 instead of just $H? 

### Steps to Reproduce the Problem
  1. Click common actions "Home machine" button
  2. Jog anywhere
  3. Issue command $G28 --> always ends up Hard limit alarm.

### Specifications
UGS Platform 2.0 - Nightly Build Jul 27, 2018
Windows 7
 GRBL 0.9j

**Comment by breiler** [comment]
I'm going to close this as a "wont fix" and there are a couple of reasons for this.
1. I don't think that it's safe to assume that all machine wants to have the G28.1 reset every homing operation.
2. The $H command will not enter the GRBL planner, so the G28.1 will be executed first. So to make this work it will require us to figure out if the homing process has been finished successfully.

In your case, I would execute the G28.1 one time after you have made an homing operation. This will be stored in the EEPROM and should work: https://github.com/gnea/grbl/wiki/Grbl-v1.1-Commands#h---run-homing-cycle
