### ISSUE TITLE
no serial ports found in linux

### ISSUE THREAD

**Issue by open-project** [winder/Universal-G-Code-Sender#11]
When starting Universal-G-Code-Sender I get an error that no serial ports are found. My Arduino is however connected and accessible at /dev/ttyACM0.
It would be good to be able to manually specify which device to use.

**Comment by winduptoy** [comment]
@winder Running as root solved this for me. Any ideas how I might correct permissions on my system?

**Comment by winder** [comment]
It has to do with your user permissions, I think it varies distro to distro so you might have to search around for a solution that works for you:

http://unix.stackexchange.com/questions/14354/read-write-to-a-serial-port-without-root

**Comment by winduptoy** [comment]
@winder :+1:
`dialout` group needed for Ubuntu, for anyone else who stumbles here.

**Comment by tapnair** [comment]
@winduptoy THANKS!!!! This solved my problem.  I didn't do anything else except add my user to dialout group.

UGS now running on Ubuntu.
