### ISSUE TITLE
cannot be run from folder that contains non-ASCII characters in path 

### ISSUE THREAD

**Issue by sua88** [winder/Universal-G-Code-Sender#1101]
os: windows 7pro
ugs version: platform 2.0 (beta)
software full path: C:\Users\Propriétaire\Downloads\ugsplatform\ugsplatform

I can't start ugs platform on my second computer, I have got this message : 
cannot be run from folder that contains non-ASCII characters in path 

it's working pretty good on my another one ( I did the instalation at the the same time)

I dont know what to do!
please help

**Comment by sua88** [comment]
thanks breiler, I just updated my first post;

**Comment by breiler** [comment]
A similar issue exists on MacOSX and probably Linux as well. The problem is probably the `é` in `Propriétaire`. Place it in another directory or rename that directory and it should work.

**Comment by sua88** [comment]
thanks breiler it's working like a charme now 
thanks for the help

**Comment by DmitryEvdochenko** [comment]
была такая же ошибка. Изначально разархивировал в директорию, где по пути были папки, в названии которых содержались символы (!!). После того, как переместил в другое место все заработало
