### ISSUE TITLE
No Serial Ports found ?

### ISSUE THREAD

**Issue by CCTofol** [winder/Universal-G-Code-Sender#1109]
No Serial Ports found.

 ####Expected Behavior
connect to CNC board / Arduino uno

####Actual Behavior
Not finding any serial ports even tho Arduino udi can see usb port that is connected to board. 
I have tried with two different Macs. Both see port in Arduino udi but not with UGS
I have tried two different UNOs loaded with grbl (grbl_v0_9a_edge_328p_16mhz_9600_build20121210) , issue persists on both. 
I have tried switching to JSerilCom, appears connected but no jogging possible and reports 'not connected'  when I hit reset zero.
I have tried different USB cables in muliple ports.
I have tried pasting /dev/cu.wchusbserial1d11130 and /dev/tty.wchusbserial1420 into port, 
Nothing.

Then suddenly I was able to connect.
Started configuring grbl for a few hours.
Then lost connection and haven't been able to get it back, computer, cables, Arduino, and settings all the same as when connection made.

 Steps to Reproduce the Problem
  1. Open the program
 No serial ports found
2. click refresh
No serial ports found

#### Version

  What versions of the application does the issue exist in.  You find the version 
  in the title bar of the application. Example:
  
  UGS Platform 2.0 - Nightly Build Aug 12, 2018
  UGS Classic 2.0 - Nightly Build Aug 12, 2018

#### Operating system

  Mac OSX 10.13.5

#### Platform

  GRBL grbl_v0_9a_edge_328p_16mhz_9600_build20121210

**Comment by breiler** [comment]
Is it possible for you to try out a later version of GRBL, the build you are using seems pretty old?

**Comment by CCTofol** [comment]
I thought that was the one I downloaded from https://github.com/gnea/grbl yesterday.
Anyway, downloaded again replaced 'old' version in Arduino library.
Opened Grblupload.
Compiles ok.
But when I upload It stalls at around 90% of write and says "avrdude: stk500_recv(): programmer is not responding" repeatedly.

Tried uploading a different sketch and it uploaded fine, so my guess is Arduino is ok.
Anything else I should try?

**Comment by breiler** [comment]
You could try fetching a binary version and try uploading it using HexUploader:
https://github.com/grbl/grbl/wiki/Flashing-Grbl-to-an-Arduino

**Comment by CCTofol** [comment]
Thanks breiler, some degree of success from your suggestion.
Managed to upload grbl using Hexuploader.
UGS now sees a usb port in the ports window. 
when I click 'open' the console reports
**** Connected to /dev/tty.usbmodem1D11141 @ 115200 baud ****
The jog buttons etc become active but do not operate the machine.

With machine powered off and usb disconnected I get the exact same behaviour as above.

**Comment by CCTofol** [comment]
This morning I'm back to the beginning. No ports found.

**Comment by breiler** [comment]
Is the Arduino a genuine or a cheaper China version?

**Comment by CCTofol** [comment]
I just got another Arduino Uno (knock off I think) and it works.
Phew.
The other two I was trying where a Freetronics eleven and another generic knock off.
Both work fine with other projects and play nice with Arduino UDI which is what was frustrating me.
Nothing pointed to the Arduinos in my mind

Got my fingers crossed this one continues to work.
Thank you for you help and your patience.

**Comment by breiler** [comment]
Is everything working as expected now, can we close this issue?

**Comment by CCTofol** [comment]
Yes, thank you Joacim, all is working fine at the moment.

P +64 21 724 943
e chris@chriscameron.co.nz
s cctofol
u chriscameron.nz
