### ISSUE TITLE
UGS Plataform - Autoleveler

### ISSUE THREAD

**Issue by ALL1991** [winder/Universal-G-Code-Sender#1110]
Good afternoon,
I have a problem with Autoleveler, when I send it to scan it performs perfectly, when I create generate test data and apply to gcode, the original speed parameters of the gcode are changed to a very slow speed, being not feasible to use, the original and generated code in Artcam.
If anyone can help, I appreciate it.

**Comment by ALL1991** [comment]
(error:22) Feed rate has not yet been set or is undefined.(error:22) Feed rate has not yet been set or is undefined.

**Comment by alecarvalhof** [comment]
Hello friends.
I am desperately looking for the solution to this same problem that is making me no longer use the UGS that I like so much.
Someone could provide a solution.
@ ALL1991 already managed to solve this problem? if so please inform.
I continue with hope!

**Comment by breiler** [comment]
This should now be fixed, it should respect the units of the original Gcode, please try the latest version of UGS.
