### ISSUE TITLE
Setup wizzard does not support board

### ISSUE THREAD

**Issue by CW3Davis** [winder/Universal-G-Code-Sender#1111]
# Problem description 
I can connect to my tinyg but it will not control it. I tried using the setup wizard. After it connects I get a message stating wizard does not support my board. 

#### Version

  What versions of the application does the issue exist in.  You find the version 
  in the title bar of the application. Example:
  
  UGS Platform 2.0 - Nightly Build Mar 23, 2018
  UGS Classic 1.0.9
-->both

#### Platform
<!-- 
  What hardware are you using. Example:
  
  Tinyg newest version

**Comment by breiler** [comment]
The build from March 23 is too old. Please upgrade to the latest nightly build: https://github.com/winder/Universal-G-Code-Sender#downloads

The setup wizard does not yet support TinyG so you need to configure manually using the "Firmware settings"

**Comment by CW3Davis** [comment]
Not exactly sure how to do the firmware setup. Is this a download file? Can you point me in the right direction? Thanks

**Comment by breiler** [comment]
Just download the latest version of UGS: https://github.com/winder/Universal-G-Code-Sender#downloads

For configuring TinyG you can use the Firmware Settings from the menu to set the parameters:
![screenshot 2018-08-22 15 27 39](https://user-images.githubusercontent.com/8962024/44466416-8c6e4000-a620-11e8-90dc-bb569a18bf17.png)

![screenshot 2018-08-22 15 27 50](https://user-images.githubusercontent.com/8962024/44466441-96903e80-a620-11e8-84ee-dbc4b98f7e54.png)

**Comment by CW3Davis** [comment]
I had a chance to check the firmware. When I clicked on it I got a message now firmware found.

**Comment by breiler** [comment]
So it's ok to close this issue?

**Comment by CW3Davis** [comment]
No I cannot configure the Universal Gcode Sender to work with my tinyg board. I have downloaded the most recent copy of UGSplatform. I tried to use the firmware to configure it as suggested, but I get a message "No firmeware found".

**Comment by winder** [comment]
Is this your first time setting up this board? Are you able to connect to your TinyG with something like Coolterm according to the directions here:
https://github.com/synthetos/TinyG/wiki/Connecting-TinyG#establish-usb-connection

**Comment by CW3Davis** [comment]
I have been using the board for about a year. I usually use Chillipeper. The machine works perfectly, but I don’t like being dependent on the internet connection. I live in an area with crappy internet.

**Comment by momiccioli** [comment]
Has this been resolved?  I am having the same issue, yes the TinyG is working fine and accessible.  UGS will do some basic stuff but Jog controls are greyed out.  The Home button works.  I am using a nightly build from April 23, 2019.  Here is the version info of the TinyG

tinyg [mm] ok>
[fb]  firmware build            440.20
[fv]  firmware version            0.97
[hp]  hardware platform           1.00
[hv]  hardware version            8.00
[id]  TinyG ID                    3X3566-EUZ

Would love to see this work with Autoleveling

**Comment by breiler** [comment]
@momiccioli  Could you post the console message from when you first connect to the contromler?

**Comment by momiccioli** [comment]
Here is a screen shot when I fire up UGS:
![image](https://user-images.githubusercontent.com/17304109/59612120-90f17100-90ea-11e9-9993-85ac2673c042.png)

Here is a screen shot when I connect to the TinyG

![image](https://user-images.githubusercontent.com/17304109/59612271-cdbd6800-90ea-11e9-824b-c7de2f7d4ae4.png)
The only message in the console area is:
`**** Connected to COM3 @ 115200 baud ****`
Which is correct for the TinyG

**Comment by JacksCrafts** [comment]
Are you on the right Com Port?

**Comment by momiccioli** [comment]
Yes I am it can be accessed by other software and some very basic functions with UGS work.  I can send commands via the command line in the console area.  The home button works.  None of the jog buttons work though.  And I can't manually code firmware settings.  Is there a specific version of the TinyG that is supported?

**Comment by JacksCrafts** [comment]
![ArduinoConnect](https://user-images.githubusercontent.com/44066988/59615371-61456780-90f0-11e9-865c-3f9a5bdabf3f.jpg)

I am using Arduino. But when I connect it automatically shows my settings.

**Comment by momiccioli** [comment]
When I test with an Arduino I get the same result you do.   It clearly understands the Arduino.  I can connect to the TinyG but when I go the wizard I get the following:

![image](https://user-images.githubusercontent.com/17304109/59615939-72db3f00-90f1-11e9-9e10-10a580b9e2d5.png)

Its as if it does not what to do with the TinyG

**Comment by breiler** [comment]
I suspect that this has to do with the initialization of the TinyG-board which behaves differently than g2core (which is the platform I've developed against).

When connecting to the controller UGS expects a message from TinyG (a "r"-response with the message "SYSTEM READY"). But it's not shown in the screenshots that you've provided which is why some functions isn't working. When such a message is retrieved from the controller and additional setup is done by UGS.

You could try hit the button "Soft reset" which will send a reset command to TinyG and reinitialize the board.

**Comment by breiler** [comment]
Oh, and the setup wizard doesn't not yet work with TinyG/g2core boards. You'll see the board version, but that's about it. =(

**Comment by momiccioli** [comment]
I saw that the setup wizard is not working yet.  If I do a soft reset it does start talking to the TinyG a little better.  I can live without the Firmware setup since I can do that via terminal.  There are some other buttons that don't appear to work like soft set to zero and I am thinking because UGS does not understand the responses.  Is that because I have an older TinyG.  How hard would it be to include support for older TinyGs if that is the issue.  I would be willing to help by testing maybe coding etc depending on the complexity.

**Comment by breiler** [comment]
I don't think it will be that hard if you got the hardware, which I don't. =(

The g2core/tinyg implementations should probably be splitted apart so the differences in the protocols could be handled. 

The current controller implementation is found here:
https://github.com/winder/Universal-G-Code-Sender/blob/master/ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java

This is the part of the initialization that didn't work on your hardware:
https://github.com/winder/Universal-G-Code-Sender/blob/master/ugs-core/src/com/willwinder/universalgcodesender/TinyGController.java#L181

**Comment by momiccioli** [comment]
Let me see if I can interpret this, been a while since I coded.

**Comment by norru** [comment]
@breiler I am using UGS with g2core and I get the same results.

**Comment by norru** [comment]
> When such a message is retrieved from the controller, additional setup is done by UGS.

I don't see this message in the terminal either.

**Comment by norru** [comment]
@breiller Let me know if you want anything tested.

**Comment by breiler** [comment]
@norru and @CW3Davis I would really appreciate if you had the time to try both TinyG and g2core. They now have different firmware selections in the drop down box.

I've seen some smaller issues eg. when switching between different unit modes (g20/g21), where the DRO gets confused. The M0-command will also cause some weird behaviour creating offsets in the visualiser. Once people start using it we will probably find more stuff...

**Comment by breiler** [comment]
Please create a new issue if this still is a problem.

**Comment by doanhung2691** [comment]
![image](https://user-images.githubusercontent.com/98507736/151293650-234e746a-4290-4c5e-9b08-63e8a0fb37de.png)
![image](https://user-images.githubusercontent.com/98507736/151293660-1fe20410-8b1a-4189-84d8-721f031d99c7.png)
I'm operating a cnc pen plotter, but it's not working, so you guys can help me? how can I fix it?
I use UGS 2.9 and win 10
Thanks

**Comment by breiler** [comment]
@doanhung2691 please create a new issue and provide details about your controller board.
