### ISSUE TITLE
USG Platform 2.0 Fails to Start up on Windows 7 

### ISSUE THREAD

**Issue by NEMA34** [winder/Universal-G-Code-Sender#1112]
USG Platform Fails to Start on Windows 7

I Have Just Done a Clean Install of Windows 7 (32 Bit) HPE & Installed the Latest Java 8 & Nightly Build of UGS PLATFORM 2.0 & Installed the Arduino Com Port Driver.

When i Open the 32bit UGS Platform .EXE File i Get the Splash Screen & Status says " Reading Module Storage " after this the Program just Quits !

If i Run The Standard USG ( Non Platform Version ) - Runs Perfect.

So i Installed Windows 7 (32 Bit) HPE Exactly the same as a Virtual Machine on my Mac & it Works Just Fine ?

Is it a PC Hardware Compatability Issue ?

Hardware INFO

2.9Ghz Core2Duo - 4GB Ram - 500GB HDD - Old Nividia 7300GT GPU 

Router Controller is a Clone Arduino 2560 Mega Running GRBL 1.1

**Comment by breiler** [comment]
Please try the version with the bundled java from here:
https://github.com/winder/Universal-G-Code-Sender#downloads
