### ISSUE TITLE
UGS - interface modification *newbe*

### ISSUE THREAD

**Issue by QurChuck** [winder/Universal-G-Code-Sender#1115]
Hey,

I'm looking for a tips for adding something to interface of UGS. I've already installed Windowbuilder and Swing addons, but still can't edit MainWindow.form or MainWindow.java as clickable window designer, only source code.

The button I want to add will be for graphic software, which will create gcode/nc files.

I've been following this tutorial, but stuck in place right now
[https://www.youtube.com/watch?v=oeswfZz4IW0&list=PLS1QulWo1RIbYMA5Ijb72QHaHvCrPKfS2&index=3](url)

For my current skills, adding buttons in code will be extremly difficult.

I'll be thankful for any tips or good tutorials

**Comment by winder** [comment]
Very few GUI elements in UGS use a GUI Builder these days. You could look at making a UGS Platform plugin, and in your plugin you can use the GUI builder. It isn't super straight forward to get started though.

I have an out of date tutorial here:
http://winder.github.io/ugs_website/dev/plugin/

Here is an archetype to help with setting up a new plugin:
https://github.com/winder/Universal-G-Code-Sender/tree/master/new-module-archetype
