### ISSUE TITLE
Problems with Universal Gcode Sender - Error while processing resoponse

### ISSUE THREAD

**Issue by cncvictor** [winder/Universal-G-Code-Sender#1116]
Hello everyone, I have a problem, when I connect the Universal Gcode Sender it shows a message and it keeps appearing this message without stopping.

I need help, please.

Victor
![ugc1](https://user-images.githubusercontent.com/42901333/44958741-c1994e80-aeba-11e8-8a70-5495792ba076.png)
![ugc2](https://user-images.githubusercontent.com/42901333/44958743-c5c56c00-aeba-11e8-9fad-ad5ced118c0e.png)

**Comment by cncvictor** [comment]
I have a mini CNC, those with pen, I'm studying the whole mechanism to be able to make a bigger one. Take a look on my youtube channel that you will see my machine when it was working up to 1 week ago
https://youtu.be/xUxPWlC78ZE

**Comment by breiler** [comment]
A lot has been changed with the processing of the responses in UGS, please upgrade to the latest nightly build.
