### ISSUE TITLE
Nightly Build Visualizer Not warking

### ISSUE THREAD

**Issue by Baybeyya** [winder/Universal-G-Code-Sender#1120]
My old UGS stopped showing visualizer. I removed old one and downloaded new nightly build UGS but still the visualizer is not working. 
I am on Windows 10. 
Appreciate suggestions. Thanks.

**Comment by winder** [comment]
Could you share the log file? You can find it's location here:
http://winder.github.io/ugs_website/guide/troubleshooting/#property-files

**Comment by Baybeyya** [comment]
I sorry I am not very familiar but trying hard. I cannot find UGS logs in
the location. Here is screen shot.
c:\user\AppData\Roaming
Thanks

**Comment by winder** [comment]
The directory is also listed in the about page while UGS is running.

**Comment by Baybeyya** [comment]
Sorry. I could not find. will there be help guide for windows 10?

**Comment by winder** [comment]
No, my guess is that it's the same as in Windows 7

**Comment by Baybeyya** [comment]
{
  "Name": "GRBL",
  "Version": 4,
  "Controller": {
    "name": "GRBL"
  },
  "GcodeProcessors": {
    "Front": [
      {
        "name": "CommentProcessor",
        "enabled": true,
        "optional": false
      },
      {
        "name": "FeedOverrideProcessor",
        "enabled": false,
        "optional": true,
        "args": {
          "speedOverridePercent": 60
        }
      },
      {
        "name": "M30Processor",
        "enabled": true,
        "optional": false
      },
      {
        "name": "ArcExpander",
        "enabled": false,
        "optional": true,
        "args": {
          "segmentLengthMM": 1.3
        }
      }
    ],
    "Custom": [],
    "End": [
      {
        "name": "DecimalProcessor",
        "enabled": true,
        "optional": true,
        "args": {
          "decimals": 4
        }
      },
      {
        "name": "WhitespaceProcessor",
        "enabled": true,
        "optional": true
      },
      {
        "name": "M3Dweller",
        "enabled": false,
        "optional": tr

**Comment by Baybeyya** [comment]
Now I get it. I am using classic version so I have to give Jason file. 
{
  "firmwareVersion": "GRBL",
  "fileName": "C:\\Users\\user\\Desktop\\Test2.nc",
  "port": "COM3",
  "portRate": "115200",
  "manualModeEnabled": false,
  "manualModeStepSize": 1.0,
  "useZStepSize": true,
  "zJogStepSize": 1.0,
  "jogFeedRate": 51.0,
  "scrollWindowEnabled": true,
  "verboseOutputEnabled": false,
  "commandTableEnabled": true,
  "mainWindowSettings": {
    "xLocation": -17,
    "yLocation": 12,
    "width": 1382,
    "height": 754
  },
  "visualizerWindowSettings": {
    "xLocation": -32000,
    "yLocation": -32000,
    "width": 160,
    "height": 39
  },
  "singleStepMode": false,
  "statusUpdatesEnabled": true,
  "statusUpdateRate": 200,
  "displayStateColor": true,
  "defaultUnits": "mm",
  "probeAxis": "Z",
  "probeFeed": 5.0,
  "probeDistance": -10.0,
  "probeOffset": 0.0,
  "showNightlyWarning": true,
  "showSerialPortWarning": true,
  "autoConnect": false,
  "autoReconnect": false,
  "toolbarIconSize": 0,
  "autoLevelSettings": {
    "autoLevelProbeZeroHeight": 0.0,
    "autoLevelProbeOffset": {
      "units": "UNKNOWN",
      "x": 0.0,
      "y": 0.0,
      "z": 0.0
    },
    "autoLevelArcSliceLength": 0.01,
    "stepResolution": 10.0,
    "probeSpeed": 10.0,
    "zSurface": 0.0
  },
  "fileStats": {
    "minCoordinate": {
      "units": "MM",
      "x": 0.0,
      "y": 0.0,
      "z": -1.0
    },
    "maxCoordinate": {
      "units": "MM",
      "x": 59.60659898477157,
      "y": 58.91878172588832,
      "z": 15.0
    },
    "numCommands": 34
  },
  "macros": {
    "1": {
      "gcode": "G91 X0 Y0;"
    }
  },
  "language": "en_US",
  "pendantConfig": {
    "stepSizeList": [
      {
        "value": ".1",
        "label": ".1",
        "selected": false
      },
      {
        "value": "1",
        "label": "1",
        "selected": false
      },
      {
        "value": "5",
        "label": "5",
        "selected": false
      },
      {
        "value": "10",
        "label": "10",
        "selected": true
      },
      {
        "value": "50",
        "label": "50",
        "selected": false
      }
    ],
    "shortCutButtonList": [
      {
        "label": "Return to Workpiece 0",
        "gCodeCommandList": [
          "G90 G0 X0 Y0 Z0"
        ]
      },
      {
        "label": "Start Spindle",
        "gCodeCommandList": [
          "M3"
        ]
      },
      {
        "label": "Stop Spindle",
        "gCodeCommandList": [
          "M5"
        ]
      },
      {
        "label": "Coolant On",
        "gCodeCommandList": [
          "M7"
        ]
      },
      {
        "label": "Coolant Off",
        "gCodeCommandList": [
          "M9"
        ]
      }
    ]
  }
}

**Comment by winder** [comment]
@Baybeyya you'll have to run from the command line to get the error log in that case

**Comment by winder** [comment]
Maybe this will help you with that: https://www.youtube.com/watch?v=MhwX8_ohOD8

**Comment by Baybeyya** [comment]
Here is screen shot from cmd prompt

**Comment by winder** [comment]
You'll have to share from github, your screenshots aren't showing up.

**Comment by Baybeyya** [comment]
![image](https://user-images.githubusercontent.com/43090651/45316146-acbe5a00-b54f-11e8-91fb-0e3e88239566.png)

**Comment by winder** [comment]
I don't see any errors, maybe try updating your graphics drivers. Does the UGS Platform visualizer work?

**Comment by Baybeyya** [comment]
UGS Platform could not run because Cannot Find Java 8.1 or higher

**Comment by Baybeyya** [comment]
![image](https://user-images.githubusercontent.com/43090651/45316977-13dd0e00-b552-11e8-979d-18797c44366c.png)

**Comment by Baybeyya** [comment]
![image](https://user-images.githubusercontent.com/43090651/45341476-44559400-b5b4-11e8-890d-5f14bc908cc0.png)

**Comment by Baybeyya** [comment]
![image](https://user-images.githubusercontent.com/43090651/45341510-66e7ad00-b5b4-11e8-83ac-b086a54ff7eb.png)

**Comment by Baybeyya** [comment]
Unsupported command

**Comment by winder** [comment]
Java 8 is required, I'm not sure how you're able to run the classic UGS without it. Make sure you have the right version and you can also try the latest UGS platform.
