### ISSUE TITLE
UGS 2.0 Starts and i get massige but i cant clik on the OK button

### ISSUE THREAD

**Issue by andreb70** [winder/Universal-G-Code-Sender#1121]
Hi,

I did download ugsplatform 2.0 and after starting the program i get a screen!

This version of Universal Gcode Sender is a nightly built.
It contains all of the latest features and inprovements,
but may also have bugs that still need to be fixed.

If you encounter any problems, please report them on github.

Now, i clik on OK noting is clik on RED X.... nothing!!

So just close and thats that. But what is the problem and how to fix this??

Thanks, Andre

**Comment by winder** [comment]
Could you share the log file? You can find it's location here:
http://winder.github.io/ugs_website/guide/troubleshooting/#property-files

**Comment by andreb70** [comment]
Sorry dont have a log there is non.
I have it on 2 computers Windows 10 32bit and Windows 7 64bit
And this software isnt installed i unziped it and started ugsplatform.exe on one and ugsplatform64.exe on they other both the same problem.

**Comment by andreb70** [comment]
I found a log but not were you did say it was at C:\Users\I5\AppData\Roaming\.ugsplatform\dev\var\log

I hope this gives you a idea what wrong?

-------------------------------------------------------------------------------
>Log Session: Monday, September 10, 2018 4:22:42 PM CEST
>System Info: 
  Product Version         = NetBeans Platform 8.1 (Build 201510222201)
  Operating System        = Windows 7 version 6.1 running on amd64
  Java; VM; Vendor        = 1.8.0_20; Java HotSpot(TM) 64-Bit Server VM 25.20-b23; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 1.8.0_20-b26
  Java Home               = C:\Program Files\Java\jdk1.8.0_20\jre
  System Locale; Encoding = nl_NL (serverlaunch); Cp1252
  Home Directory          = C:\Users\I5
  Current Directory       = D:\cnc\ugsplatform-2.0.0-stable\ugsplatform
  User Directory          = C:\Users\I5\AppData\Roaming\.ugsplatform\dev
  Cache Directory         = C:\Users\I5\AppData\Roaming\.ugsplatform\dev\var\cache
  Installation            = D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform
                            D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\ide
                            D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\extra
                            D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\java
                            D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\ugsplatform
                            D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform
  Boot & Ext. Classpath   = C:\Program Files\Java\jdk1.8.0_20\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_20\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_20\jre\lib\sunrsasign.jar;C:\Program Files\Java\jdk1.8.0_20\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_20\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_20\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_20\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_20\jre\classes;C:\Program Files\Java\jdk1.8.0_20\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_20\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_20\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_20\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_20\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_20\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_20\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_20\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_20\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_20\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_20\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_20\jre\lib\ext\zipfs.jar
  Application Classpath   = D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\boot.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\org-openide-modules.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\org-openide-util-lookup.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\org-openide-util-ui.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\org-openide-util.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\boot_ja.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\boot_pt_BR.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\boot_ru.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\boot_zh_CN.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\org-openide-modules_ja.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\org-openide-modules_pt_BR.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\org-openide-modules_ru.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\org-openide-modules_zh_CN.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\org-openide-util-lookup_ja.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\org-openide-util-lookup_pt_BR.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\org-openide-util-lookup_ru.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\org-openide-util-lookup_zh_CN.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\org-openide-util-ui_ja.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\org-openide-util-ui_pt_BR.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\org-openide-util-ui_ru.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\org-openide-util-ui_zh_CN.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\org-openide-util_ja.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\org-openide-util_pt_BR.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\org-openide-util_ru.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\lib\locale\org-openide-util_zh_CN.jar;C:\Program Files\Java\jdk1.8.0_20\lib\dt.jar;C:\Program Files\Java\jdk1.8.0_20\lib\tools.jar
  Startup Classpath       = D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\asm-all-5.0.1.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\core-base.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\core.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\org-netbeans-libs-asm.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\org-openide-filesystems-compat8.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\org-openide-filesystems.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\core-base_ja.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\core-base_pt_BR.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\core-base_ru.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\core-base_zh_CN.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\core_ja.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\core_pt_BR.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\core_ru.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\core_zh_CN.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\org-netbeans-libs-asm_ja.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\org-netbeans-libs-asm_pt_BR.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\org-netbeans-libs-asm_ru.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\org-netbeans-libs-asm_zh_CN.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\org-openide-filesystems-compat8_ja.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\org-openide-filesystems-compat8_pt_BR.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\org-openide-filesystems-compat8_ru.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\org-openide-filesystems-compat8_zh_CN.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\org-openide-filesystems_ja.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\org-openide-filesystems_pt_BR.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\org-openide-filesystems_ru.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\platform\core\locale\org-openide-filesystems_zh_CN.jar;D:\cnc\ugsplatform-2.0.0-stable\ugsplatform\ugsplatform\core\locale\core_ugsplatform.jar
-------------------------------------------------------------------------------
INFO [com.willwinder.universalgcodesender.utils.SettingsFactory]: Log location: C:\Users\I5\.ugs\UniversalGcodeSender.json
INFO [com.willwinder.universalgcodesender.utils.SettingsFactory]: Loading settings.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Applying settings.
INFO [org.netbeans.core.startup.NbEvents]: Turning on modules:
	org.openide.util.lookup [8.32.1 201510222201]
	org.openide.util [9.5.1 201510222201]
	org.openide.util.ui [9.4.1 201510222201]
	org.openide.modules [7.47.1 201510222201]
	org.netbeans.api.annotations.common/1 [1.26.1 201510222201]
	org.openide.filesystems [9.8.1 201510222201]
	org.openide.awt [7.65.1 201510222201]
	org.netbeans.api.progress/1 [1.46.1 201510222201]
	org.netbeans.api.progress.nb [1.46.1 201510222201]
	org.openide.dialogs [7.41.1 201510222201]
	org.openide.nodes [7.42.1 201510222201]
	org.openide.windows [6.74.1 201510222201]
	org.netbeans.modules.editor.mimelookup/1 [1.39.1 201510222201]
	org.openide.text [6.66.1 201510222201]
	org.netbeans.swing.tabcontrol [1.54.1 201510222201]
	org.netbeans.swing.outline [1.32.1 201510222201]
	org.openide.explorer [6.61.1 201510222201]
	org.openide.actions [6.38.1 201510222201]
	org.netbeans.modules.queries/1 [1.42.1 201510222201]
	org.netbeans.api.templates [1.6.1 201510222201]
	org.openide.filesystems.nb [9.7.1 201510222201]
	org.openide.loaders [7.63.1 201510222201]
	org.netbeans.api.intent [1.1.1 201510222201]
	org.netbeans.api.io [1.2.1 201510222201]
	org.openide.io [1.48.1 201510222201]
	org.openide.filesystems.compat8 [9.7.1 201510222201]
	org.netbeans.swing.plaf [1.40.1 201510222201]
	org.netbeans.spi.quicksearch [1.26.1 201510222201]
	org.netbeans.modules.templates/1 [1.6.1 201510222201]
	org.netbeans.libs.asm [5.2.1 201510222201]
	org.netbeans.bootstrap/1 [2.74.1 201510222201]
	org.netbeans.core.startup.base [1.61.1.1 1 201510222201]
	org.netbeans.core.startup/1 [1.61.1.1 201510222201]
	org.netbeans.modules.settings/1 [1.48.1 201510222201]
	org.netbeans.modules.sendopts/2 [2.34.1 201510222201]
	org.netbeans.modules.sampler [1.13.1 201510222201]
	org.netbeans.modules.progress.ui [1.32.1 201510222201]
	org.netbeans.modules.print [7.25.1 201510222201]
	org.netbeans.modules.keyring [1.23.1 201510222201]
	org.netbeans.core/2 [3.49.1 201510222201]
	org.netbeans.modules.options.api/1 [1.44.1 201510222201]
	org.netbeans.modules.options.keymap [1.36.1 201510222201]
	org.netbeans.libs.jna/1 [1.41.1 201510222201]
	org.netbeans.modules.masterfs/2 [2.54.1.2 2 201510222201]
	org.netbeans.modules.masterfs.windows [1.15.1 201510222201]
	org.netbeans.modules.masterfs.ui [2.2.1.2 201510222201]
	org.netbeans.modules.masterfs.nio2 [1.14.1 201510222201]
	org.netbeans.modules.editor.util/1 [1.61.1 201510222201]
	org.netbeans.modules.lexer/2 [1.62.1.1 1 201510222201]
	org.netbeans.modules.keyring.fallback [1.7.1 201510222201]
	org.netbeans.modules.keyring.impl [1.23.1 201510222201]
	org.netbeans.modules.favorites/1 [1.45.1 201510222201]
	org.netbeans.modules.editor.settings.lib [1.50.1.1 1 201510222201]
	org.netbeans.modules.editor.settings/1 [1.55.1 201510222201]
	org.netbeans.modules.editor.settings.storage/1 [1.50.1.1 201510222201]
	org.netbeans.modules.editor.fold/1 [1.43.1 201510222201]
	org.netbeans.modules.editor.document [1.5.1.1 1 201510222201]
	org.netbeans.modules.editor.lib2/1 [2.4.1.44.1 44 201510222201]
	org.netbeans.modules.editor.indent/2 [1.42.1 201510222201]
	org.netbeans.modules.editor.guards/1 [1.31.1 201510222201]
	org.netbeans.modules.editor.lib/3 [4.3.1.22.1.44 22 201510222201]
	org.netbeans.modules.editor.plain.lib/1 [1.32.1 201510222201]
	org.netbeans.modules.editor.fold.nbui [1.11.1.44 201510222201]
	org.netbeans.modules.editor/3 [1.84.1.5.1.22.44 5 201510222201]
	org.netbeans.modules.editor.plain/2 [1.34.1 201510222201]
	org.netbeans.modules.editor.mimelookup.impl/1 [1.31.1 201510222201]
	org.netbeans.modules.editor.actions/1 [1.29.1.44 201510222201]
	org.netbeans.modules.autoupdate.services [1.51.1 201510222201]
	org.netbeans.modules.autoupdate.cli [1.12.1 201510222201]
	org.netbeans.core.windows/2 [2.80.1 201510222201]
	org.netbeans.core.ui/1 [1.44.1 201510222201]
	org.netbeans.libs.osgi [1.20.1 201510222201]
	org.netbeans.libs.felix [2.14.1 201510222201]
	org.netbeans.modules.autoupdate.ui [1.44.1 201510222201]
	org.netbeans.modules.core.kit [1.29.1 201510222201]
	org.netbeans.libs.jna.platform/1 [1.10.1 201510222201]
	org.netbeans.core.output2/1 [1.40.1 201510222201]
	org.netbeans.core.network [1.9.1 201510222201]
	org.netbeans.core.netigso [1.30.1 201510222201]
	org.netbeans.core.nativeaccess/1 [1.30.1 201510222201]
	org.netbeans.core.multiview/1 [1.43.1 201510222201]
	org.netbeans.core.multitabs/1 [1.11.1.1 1 201510222201]
	org.netbeans.core.io.ui/1 [1.29.1 201510222201]
	com.willwinder.ugs.platform.ugslib [2.0 2.0-20170723 201707230409]
	com.willwinder.ugs.platform.visualizer [2.0 2.0-20170723 201707230409]
	com.willwinder.ugs.platform.ugscore [2.0 2.0-20170723 201707230410]
	com.willwinder.ugs.platform.surfacescanner [2.0 2.0-20170723 201707230410]
	com.willwinder.ugs.platform.plugin.workflow [2.0 2.0-20170723 201707230410]
	com.willwinder.ugs.platform.gcode.editor [2.0 2.0-20170723 201707230410]
	com.willwinder.ugs.platform.branding [2.0 2.0-20170723 201707230409]
java.lang.IllegalStateException: no splash screen available
	at java.awt.SplashScreen.checkVisible(SplashScreen.java:197)
	at java.awt.SplashScreen.update(SplashScreen.java:307)
	at org.netbeans.core.startup.Splash$SplashPainter.repaint(Splash.java:401)
	at org.netbeans.core.startup.Splash$SplashPainter$2.run(Splash.java:516)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
	at com.willwinder.universalgcodesender.utils.NarrowOptionPane.showNarrowDialog(NarrowOptionPane.java:39)
	at com.willwinder.universalgcodesender.utils.GUIHelpers.lambda$displayErrorDialog$0(GUIHelpers.java:45)
	at com.willwinder.universalgcodesender.utils.GUIHelpers$$Lambda$14/1989596405.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding control state listener.
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy resolver: Windows
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy reloading succeeded.
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy - mode: direct
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy: fell to default (correct if direct mode went before)
WARNING [org.openide.filesystems.Ordering]: Not all children in Menu/ marked with the position attribute: [Machine], but some are: [File, Tools, Window, Help]
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding control state listener.
java.lang.IllegalStateException: no splash screen available
	at java.awt.SplashScreen.checkVisible(SplashScreen.java:197)
	at java.awt.SplashScreen.update(SplashScreen.java:307)
	at org.netbeans.core.startup.Splash$SplashPainter.repaint(Splash.java:401)
	at org.netbeans.core.startup.Splash$SplashPainter$2.run(Splash.java:516)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
	at com.willwinder.universalgcodesender.utils.NarrowOptionPane.showNarrowDialog(NarrowOptionPane.java:39)
	at com.willwinder.universalgcodesender.utils.GUIHelpers.lambda$displayErrorDialog$0(GUIHelpers.java:45)
	at com.willwinder.universalgcodesender.utils.GUIHelpers$$Lambda$14/1989596405.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding control state listener.
INFO [null]: Last record repeated 6 more times.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Getting gcode file.
INFO [org.netbeans.ui.metrics.laf]: USG_LOOK_AND_FEEL
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding control state listener.
INFO [null]: Last record repeated again.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding controller listener.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Getting processed gcode file.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding control state listener.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding controller listener.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding control state listener.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding controller listener.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Getting processed gcode file.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding control state listener.
INFO [null]: Last record repeated again.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding controller listener.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding control state listener.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding controller listener.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding control state listener.
INFO [null]: Last record repeated 2 more times.

**Comment by winder** [comment]
This is probably the issue, but I'm not sure exactly what it means:
```
java.lang.IllegalStateException: no splash screen available
```

2 things to try:
1. Re-download UGS. Occasionally a corrupt download will cause strange issues.
2. Delete the properties directory which you found here: `C:\Users\I5\AppData\Roaming.ugsplatform`

**Comment by andreb70** [comment]
Oke, i wil try.

Option 2. did not work on the windows 7 Pc i have the same problem but there is a screen at the back that says.

Universal Gcode Sender is not fully localized for this language.
Please visit
http://winder.github.io/ugs_website/contrib/translation/ 
to see how you can help.

But if i go there i get a 404 File not found

Going to test option 1. now.

**Comment by andreb70** [comment]
Option 2. didnt work same problem.

**Comment by winder** [comment]
The current file built at 10:27: https://winder.ci.cloudbees.com/job/UGS/

Has the following MD5:
```
$ md5 ugsplatform.zip
MD5 (ugsplatform.zip) = 5f3faa74557ad474dbc53dc3115138a0
```

**Comment by winder** [comment]
It seems pretty unlikely that it is a corrupt download though. Are you using a non-english locale? Maybe try launching with the classic GUI and setting the language back to english, then try the platform again.

**Comment by andreb70** [comment]
I downloaded the file from https://winder.ci.cloudbees.com/job/UGS/
This gives me the same problem. Start as admin is the same. Changed locale to 4 difrent countrys stays the same.  It looks like there is some problem in the program but if thats the case others my have that same problem but thats not so.

**Comment by breiler** [comment]
Is this still a problem?

**Comment by andreb70** [comment]
No its no problem anymore... thanks
