### ISSUE TITLE
UGS Platform Doesn't Load Properly

### ISSUE THREAD

**Issue by BusbyGT** [winder/Universal-G-Code-Sender#1123]
## Problem description 
Downloaded a nightly build on 9/6 and ran the 64-bit EXE in Windows 10. Got the attached error message. Downloaded a nightly build on 9/12 (tonight) and got the same exact behavior.

I want to say the last nightly build before these two was from late August but I have those files deleted.

![capture](https://user-images.githubusercontent.com/26131866/45463176-14ec7780-b6d9-11e8-9282-48a02cbd5430.PNG)

There is a button to Disable modules and continue and when you do that, the screen goes to this:

![capture2](https://user-images.githubusercontent.com/26131866/45463297-8b897500-b6d9-11e8-8662-f9af7007dbef.PNG)

I've attached the messages.log file

[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/2377469/messages.log)

If I rename the .ugsplatform folder from C:\Users\<user>\AppData\Roaming, it loads up without a problem but I believe my window settings and macros are lost?

I can always redo my window layout but obviously something else is going wrong.

**Comment by AbySet** [comment]
There is some files need to be deleted from that folder to clean the program data cash but i dont remembers whitch ones are they, this issue happend to me one day and i fixed it by deleting those files, your windows is just fine dont reinstall it.

**Comment by AbySet** [comment]
I was kind of sleepy yesterday, just delete .ugdplatform folder from C:\Users<user>\AppData\Roaming this will clean everything but after that you have to redo software settings and **pay attention on probe settings** if you are using it.

**Comment by breiler** [comment]
Closing as the requester hasn't returned with any progress after suggested solution.
