### ISSUE TITLE
Ongoing Probe Module Problems

### ISSUE THREAD

**Issue by groberts22** [winder/Universal-G-Code-Sender#1141]
The probe module appears to have a bug that causes it to incorrectly calculate distances in at least some cases.  In the example provided below, I set the probe retract distance (amount) to 0.25 in, but the module instead retracts the probe 1 in, causing it to fail during the slow re-measurement phase. My settings and console output are provided below.
 
Settings
![image](https://user-images.githubusercontent.com/25800167/47456874-a6a0d780-d7a3-11e8-88f0-08538ae5bd12.png)
 
Z
 
![image](https://user-images.githubusercontent.com/25800167/47456902-b6b8b700-d7a3-11e8-9000-9ba6d54b06d2.png)

Console
>>> G21 G91 G49
ok
>>> G38.2 Z-12.7 F127
[PRB:-20.5000,-13.5000,-2.8388:1]
ok
>>> G90 G21
ok
>>> G91 G20 G0 **Z1.0**
ok
>>> G90 G21
ok
>>> G21 G91 G49
ok
>>> G38.2 Z-12.7 F25.4
An error was detected while sending 'G38.2 Z-12.7 F25.4': (ALARM:5) Probe fail. Probe did not contact the workpiece within the programmed travel for G38.2 and G38.4. Streaming has been paused.
>>> G90 G21
[PRB:-20.5000,-13.5000,-2.8388:0]
ok
>>> G10 L20 P2 Z0.7
An error was detected while sending 'G10 L20 P2 Z0.7': (error:9) G-code commands are locked out during alarm or jog state. Streaming has been paused.
**** The communicator has been paused ****
An unexpected error was detected: (error:9) G-code commands are locked out during alarm or jog state.
**** The communicator has been paused ****
>>> G91 G21
An error was detected while sending 'G91 G21': (error:9) G-code commands are locked out during alarm or jog state. Streaming has been paused.

**Comment by AbySet** [comment]
I tested it using both mm and inches units converting the exact mesurments to mm units.
- In mm units the prob is working just fine.
- In inches units the prob retract too much.
This must be an issue to fix.

**Comment by groberts22** [comment]
There are also problems when attempting to use the module to set the XY coordinates.  After recording the current XY position, the module attempts to move in absolute coordinate space, causing a soft alarm error.  I think this may also be related to the choice of inches as the unit of measure.  My settings and console output are again provided below.
Settings
 
![image](https://user-images.githubusercontent.com/25800167/47500977-46a54200-d832-11e8-9b29-1399d24ddd15.png)

XY
 
![image](https://user-images.githubusercontent.com/25800167/47500995-502eaa00-d832-11e8-8bdd-79cfbd314657.png)

Console
>>> G10 L20 P2 X0.0Y0.0
ok
>>> G91 G20
ok
>>> G90 G20 G0 X0.5
An error was detected while sending 'G90 G20 G0 X0.5': (ALARM:2) Soft limit alarm. G-code motion target exceeds machine travel. Machine position retained. Alarm may be safely unlocked. Streaming has been paused.

**Comment by stanhowe** [comment]
touch probe in Z axis was working with earlier version, now I have new version and installed limits, using homing as well as soft limits. the Z probe will not initiate it gives an error that the there is not enough space to the soft limit. I have more than enough room to soft limit and reduced the prove distance to only.-.1 and 
<img width="414" alt="screen shot 2018-12-31 at 11 13 19 pm" src="https://user-images.githubusercontent.com/46290702/50570266-b6afd700-0d51-11e9-924a-d62de89a0e12.png">
same error.

**Comment by breiler** [comment]
I am closing this as there has been plenty of bug fixes for the probe functions, please try again. If you still find problems please reopen this issue.

The fixes are available in the latest nightly build.
