### ISSUE TITLE
TinyG jog not working

### ISSUE THREAD

**Issue by CodeZone8** [winder/Universal-G-Code-Sender#1142]
The jog panel is not enabled after connection to the controller. 
Everything else works fine.

 UGS Platform 2.0 - Nightly Build Mar 23, 2018
 Windows 10
 TinyG

No way no jog machine other than a right click on the visualizer and Jog To x,y

**Comment by winder** [comment]
Try the latest nightly build, there have been a lot of TinyG improvements this year.

**Comment by CodeZone8** [comment]
> Try the latest nightly build, there have been a lot of TinyG improvements this year.

I did used the latest build at that time. Still no go. A quick check shows there is nothing new since my last post so I guess I am out of luck using this software until there is a fix for this.

**Comment by norru** [comment]
Why was this bug closed?

**Comment by norru** [comment]
Opened https://github.com/winder/Universal-G-Code-Sender/issues/1265
