### ISSUE TITLE
The new JOG controller SUCKS!

### ISSUE THREAD

**Issue by poplawa** [winder/Universal-G-Code-Sender#1146]
## Problem description 
I pressed "Z-" button ONCE (step was set to 0.5 mm) and it kept on going waaay further than I expected... This has happened to me already few times but never in such a way.

#### Version
UGS Platform 2.0 - Nightly Build Mar 23, 2018

#### Operating system
  Windows 10 PRO

#### Platform
  GRBL 1.1f

#### VIDEO
[https://photos.app.goo.gl/xE8ZPUVchZXvazqH7](https://photos.app.goo.gl/xE8ZPUVchZXvazqH7)

**Comment by poplawa** [comment]
Now It got to me that I must have pressed it with right mouse button. If that's a feature then please remove it.

**Comment by AbySet** [comment]
I don't know about mar 23 version but i'm using october 21 version and jogging is just fine to me.
You may also update java and do no hold mouse button on jog button to avoid this issue.
Some poeple want to use the feature that allow you by holding the mouse for about 2 secs make the machine move in the loop and then they have to do quick click on the same jog direction to stop it.
So if you don't wana use that feature just click on the mouse without holding it.

**Comment by poplawa** [comment]
Holding LEFT mouse button is fine. I like it. But pressing RIGHT mouse button and moving that axis forever? That's a VERY bad idea, especially if someone presses it by accident.

**Comment by AbySet** [comment]
Agreed and i think this needs to be fixed (removed).

**Comment by jahnj0584** [comment]
this was an issue earlier this year. It'd take one "jog" command to refresh the increment size, so if you went from 600 to 1, then clicked a jog it'd read 1, but still send 600. Just download the latest version.
