### ISSUE TITLE
"GRBL has not finished booting."

### ISSUE THREAD

**Issue by DavidLQuick** [winder/Universal-G-Code-Sender#116]
I am able to start the application, connect to my Mega 2560 running the 2560 Port of GRBL .08c. I can send command line commands, direction buttons, send gcodes to the 2560 and I can read responses from the firmware. The issue I am running into is that the file stream is reporting "GRBL has not finished booting." 

Any suggestion would be welcome. I am a proficient Java programmer and can implement necessary changes.

**Comment by abhilashkumar911** [comment]
david sir,

**Comment by abhilashkumar911** [comment]
i have same problum. what i do
its say( GRBL has not finished booting
so please help me

**Comment by abhilashkumar911** [comment]
i am using ATmaga 328

**Comment by winder** [comment]
Are you using the wrong baud rate?

**Comment by DavidLQuick** [comment]
Will, this post is very old. I resolved the issue over a year ago.

**Comment by abhilashkumar911** [comment]
thank you

please give me a detail of arduino THC ( torch height control)
how i build

**Comment by abhilashkumar911** [comment]
sir plz

**Comment by mahid1** [comment]
is there a way for changing the startup line? grbl and version?

**Comment by winder** [comment]
@mahid1 It isn't configurable, but in the code it's done here: https://github.com/winder/Universal-G-Code-Sender/blob/717da06f8d7c724b7212daa4b6a42a365c89ebc9/ugs-core/src/com/willwinder/universalgcodesender/GrblUtils.java#L88

**Comment by mahid1** [comment]
thanks winder,ill have a look.

**Comment by mahid1** [comment]
just checked it, so that is in UGS not grbl firmware. Any guidelines?.

**Comment by winder** [comment]
@mahid1 could you create a new ticket and describe what you're trying to accomplish? I'm really not sure how to answer your question as is.

**Comment by ben-crowhurst** [comment]
FYI: We managed to solve this issue by altering the baud rate.

**Comment by Shanki070** [comment]
I fixed this issue by uploading grbl in the Ardunio. 

In Ardunio IDE go to File ->  Examples -> grbl ->grblUpload. Flash this sample in the Ardunio and then run "Universal-G-Code-Sender".

**Comment by kiranshashiny** [comment]
Changing the port to 9600 helped in my case.

**Comment by hariharan382** [comment]
above solution doesn't seem to solve my problem

**Comment by breiler** [comment]
@hariharan382 please open a new issue and specify at least which version of GRBL, UGS and operating system you are using.

**Comment by hariharan382** [comment]
I am using  version 2.0 (nightly)/july 23 2017 -Universal g code sender
windows 10 -OS
g rbl master from this link https://github.com/gnea/grbl

**Comment by hariharan382** [comment]
please any one reply I am running out of time

**Comment by breiler** [comment]
The UGS version is pretty old, please try and upgrade to the latest version.

**Comment by hariharan382** [comment]
windows 10
version 2.0 nightly ju

**Comment by hariharan382** [comment]
sir can you send me the link

**Comment by hariharan382** [comment]
sir tried with classic 2019 beta version 2.0 
same result

**Comment by hariharan382** [comment]
sir tried it says "error while starting file stream"

**Comment by hariharan382** [comment]
please anyone

**Comment by hariharan382** [comment]
![error](https://user-images.githubusercontent.com/47359638/68223279-817bb180-0012-11ea-90f7-2b10149a5b6d.PNG)

**Comment by hariharan382** [comment]
> The UGS version is pretty old, please try and upgrade to the latest version.

sir i tried new version it says"error while starting file stream"

**Comment by breiler** [comment]
@hariharan382, please stop...

I'm guessing that your firmware didn't upload properly. I suggest that you start by verifying this by connecting to the GRBL-controller using Arduino IDE:s serial console:
https://github.com/gnea/grbl/wiki/Using-Grbl#getting-started-for-new-users

If that doesn't work I suggest that you take a look on how to upload a prebuilt image from:
https://github.com/gnea/grbl/releases

These can by uploaded using XLoader:
https://github.com/gnea/grbl/wiki/Flashing-Grbl-to-an-Arduino#for-windows

What type of Arduino are you using?  (Arduino Uno, Arduino Nano, other)
Is it a cheap China variant or a more expensive genuine variant?

**Comment by winder** [comment]
One last link before locking this issue which keeps getting resurrected.
http://winder.github.io/ugs_website/guide/troubleshooting/#grbl-has-not-finished-booting

If you're from the future and are seeing "GRBL has not finished booting", check out these links and create a new issue if you're still having a problem.
