### ISSUE TITLE
Ugs Platform not loading

### ISSUE THREAD

**Issue by Woodmonger** [winder/Universal-G-Code-Sender#1167]
Ok still pretty new to the ugs but do have a pretty good hang of things. 

UGS opened normally about 4 days ago and ran perfectly. I now open it and the splash screen shows up then disappears and nothing happens after that. I have downloaded the latest build and still the same thing happens.

Any help would be appreciated.

**Comment by AbySet** [comment]
Can you please use the template for issues so we can know what exactly you have installed, we don't even know on what OS you are working ! The template will provide us with needed infos so we will be able to help you, like OS, Java version, and  so on.
Thank you.

**Comment by carneeki** [comment]
Also checkout the troubleshooting page on GitHub and Will Winder's site,
the answer may be there too.

**Comment by breiler** [comment]
Closing as there isn't enough information to investigate.
