### ISSUE TITLE
port busy

### ISSUE THREAD

**Issue by mgorman0178** [winder/Universal-G-Code-Sender#1176]
### Steps to Reproduce the Problem

  1.
  1.
  1.

**Comment by mgorman0178** [comment]
Hi my machine stopped halfway thought what i was doing! I checked my software and an error message come up saying Error opening connection (jssc.serialportexception): Port name- COM3; Method name-openport(); Exception type- port busy!? I turned it of and on but still same message! What do i do? Oh and the visualize don't work aswell???

**Comment by breiler** [comment]
Closing this as no additional information was provided.

**Comment by PauCatala** [comment]
Hi, I have the same problem, and I cannot fix it. I have nothing connected to my PC except for UGS. I have my Arduino connected to COM8, and even if I connect it to other ports the same error appears. Is there anything I can do?

**Comment by breiler** [comment]
@PauCatala please create a new issue.
