### ISSUE TITLE
When send my gcode file an error was detected while sending '0S30' error

### ISSUE THREAD

**Issue by jashwant1234** [winder/Universal-G-Code-Sender#1181]
![img_20190124_125925](https://user-images.githubusercontent.com/46989904/51662120-d779ee00-1fd8-11e9-8d98-10c4a8138783.jpg)

### Steps to Reproduce the Problem

  1.
  1.
  1.

**Comment by winder** [comment]
Looks like you have a typo in your gcode, try removing that line

**Comment by jashwant1234** [comment]
Plzz help me to make gcode in from of .nc

**Comment by winder** [comment]
The screenshot tells you what line didn't work. Try opening the text file and removing that line. If you still have issues you'll need to configure your CAM software for GRBL.

**Comment by jashwant1234** [comment]
How i configure i don't know

**Comment by AbySet** [comment]
Tell us where did you get that file from so we can help, if that file is generated by some software you are using, we need to know what is it, if not then just delete that line.

**Comment by AbySet** [comment]
Hey;
I forget to mention: In your case the job is just paused not canceled, just press RUN button again and the machine will skip that command and continu. But if the file has many of those commands, they will be disturbing and you better delete them before you run the job.

**Comment by breiler** [comment]
There were no follow ups from user, closing issue.
