### ISSUE TITLE
Gcode edit

### ISSUE THREAD

**Issue by Psychokiller1888** [winder/Universal-G-Code-Sender#1186]
## Problem description 
After using Gcode edit, the edited code, even after saving (closing the edit tab) is not taking into consideration

### Expected Behavior
The gcode to be reloaded

### Actual Behavior
Old gcode is ran, resulting in badness.....

### Steps to Reproduce the Problem
- Open a gcode file
- File->Edit gcode
- Change some lines. I changed my pcb drill pointing depth that was wrong, from z-1.7 to z-0.3
- Close the tab, accept the popup asking for saving
- Run gcode

#### Version
  UGS Platform 2.0 - Nightly Build Dec 18, 2018

#### Operating system
Windows 10

#### Platform
GRBL 1.1f

**Comment by khturnings** [comment]
This would be a good idea

**Comment by revtmyers** [comment]
Need to reload the Gcode manually.
