### ISSUE TITLE
hepl

### ISSUE THREAD

**Issue by davidhalik123** [winder/Universal-G-Code-Sender#1189]
startup problem

startup ugsplatform write: cannot be run from folder that contains non-ascii characters in path

C:\Users\Já\Desktop\Nová složka (18)\bin
platform 2.0 (beta)
windows 10

**Comment by Psychokiller1888** [comment]
The error says it all... Try installing under c: directly

**Comment by davidhalik123** [comment]
C:\ugsplatform\bin

write: cennot find java 1.8 or higher

**Comment by davidhalik123** [comment]
YES 
installation java startup problem solved

Thank you so much Psychokiller1888
