### ISSUE TITLE
Additional shortcuts

### ISSUE THREAD

**Issue by jheyman** [winder/Universal-G-Code-Sender#1191]
## Feature request
Could we please get shortcuts for:
- [x] "Initiate Probe" action
- [x] the four diagonal jogging arrows
That would be neat to complete my keypad setup

Cheers,
Julien

**Comment by breiler** [comment]
#1226 fixes diagonal jogging

**Comment by roelze** [comment]
I would very much appreciate seeing the touch plate initiate added to the keyboard shortcut so it could be used my the wireless keypad/game controller.
Thanks,
Rick

**Comment by breiler** [comment]
Please try with version 2.0.19, make sure to double check your settings after upgrading:
https://github.com/winder/Universal-G-Code-Sender/releases/tag/v2.0.19
