### ISSUE TITLE
I/O error

### ISSUE THREAD

**Issue by Mgilbride** [winder/Universal-G-Code-Sender#122]
Had following error today.

Job interrupted with "IOException while sending status command: Input/Output error in writeByte". This error came up in the UGS console. Sounds like a loss of USB connectivity? That sound right to you or is something else going on?

**Comment by smooker** [comment]
I got around this by tweaking nice-ness of the process by:
/usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 cnc.ugcs
