### ISSUE TITLE
Recovery utility / functionality

### ISSUE THREAD

**Issue by Mgilbride** [winder/Universal-G-Code-Sender#123]
How hard would it be to add a little bit of recovery functionality to UGS? AM thinking that UGS does a line count of the G-code file. UGS has the visualizer. Lets assume your job craters for whatever reason (false limit, you stop it, etc.) and you want to save the job. Lets also assume you have a way to re-zero your machine even if you have lost 0 in the preceding mishap. If you could tell UGS to start sending from a certain line (a text box, spinner, whatever) and then look at the visualizer to see where the Job will be resumed (change line resume as needed and revisualize) and then hit send. I think you mentioned this somewhere. Seems easy to implement. Pick tool up and touch down at resume point and off you go. 

Probably more complicated than that, I know.

**Comment by jahnj0584** [comment]
Could we add something as simple as "line" in the console beside whats being sent? Similar to what Notepad++ has for its text files!

**Comment by winder** [comment]
There's a little more to it, since previous commands could have updated the internal state that state needs to be saved and reapplied.

So the steps would be something like:
1) figure out what the gcode state was at `<line>`
2) move machine to location right before `<line>`
3) reapply gcode state
4) resume programe with `<line>`

**Comment by jahnj0584** [comment]
With my gcodes, each tool path is called like (2D contour1) and reflects as
such in the "last sent" row, but a line number would work.

My codes are also all g91 so as long as you keep work 0 you can restart at
any toolpath

**Comment by winder** [comment]
Implemented with #1388 and #1394
