### ISSUE TITLE
Stuck on a blank dialog box after launching. Unable to close or continue

### ISSUE THREAD

**Issue by moonface1977** [winder/Universal-G-Code-Sender#1237]
## Problem description 
Once launched, it shows the window with the message title "nightly build" but no contents or buttons. I can select the X  to close it but it doesn't close or launchs the UGS. Only way to stop it is from task manager

### Expected Behavior
Launch UGS

### Steps to Reproduce the Problem
1-  open the folder BIN
2- right click and run ugsplatform64

#### Version
<!-- 
  What versions of the application does the issue exist in.  You find the version 
  in the title bar of the application. Example:
  
  UGS Platform 2.0 - Nightly Build April 233, 2019

#### Operating system
Windows 10 Home, 64 bit
Java 1.80_211-b12

#### Platform
GRBL 1.1

Steps done to try to correct:
*Uninstalled and installed again
*Downloaded again
*Deleted the files under user and roaming
*Upgraded video card drivers
*Run in compatibility mode (different options)

*Run from command line:
    The launcher has determined that the parent process has a console and will reuse it for its 
    own console output.
    Closing the console will result in termination of the running program.
    Use '--console suppress' to suppress console output.
    Use '--console new' to create a separate console window.
(it stops here and stays there.)

*Tried different versions
* completely unistalled java and reinstalled
[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/3195633/messages.log)

**Comment by AbySet** [comment]
Please provide us with more informations like your OS, also take a look at UGS files date so we know whitch version of UGS you are using.
Thank you.

**Comment by JacksCrafts** [comment]
You might try uninstalling and then reinstalling Java.

**Comment by moonface1977** [comment]
Im very sorry. I had a very detailed comment. For some reason it didn't go through.
Looks like it gets stuck on the first warning and I'm unable to do anything.
Here is the info:

Windows 10 Home 64
java Version 8 update 211
UGS nightly April 23, 2019 (also tried other versions)

Steps I took to fix:
*Unistalled UGS completely, deleted the files under Appdata (including roaming). Restarted PC
*Installed UGS again. Restarted PC
*Uninstalled Java completely and installed again. Restarted PC
*run UGS from command line, same results. Please see attached as it looks like stops after the second 
  message and stays there. (I've see other screenshots and it doesn't get that far)
*Run UGS in compatibility mode
*Updated Video drivers.


[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/3195707/messages.log)

**Comment by moonface1977** [comment]
Here are the screenshots.

![Capture](https://user-images.githubusercontent.com/50780621/57989305-c1e87280-7a66-11e9-86fc-f18a89546126.PNG)
![CMD](https://user-images.githubusercontent.com/50780621/57989308-c4e36300-7a66-11e9-9cd3-86b97494727c.PNG)

**Comment by AbySet** [comment]
Did you deleted a folder called ".ugs" under \users\username\ ?
complete path: c:\users\username\.ugs

Also you may try a classic version just to see if it's the interface or something else causing the issue and can help to go to the source of the problem.
I do use win10 x64 and same version of ugs but everyting is working fine to me.

Some antivirus can hold the execution of programs when they are newly installed for about 15 seconds before they let them run (avast do that).

**Comment by moonface1977** [comment]
It was the antivirus (Comodo). Even with all the features disabled it was creating an issue. I attempted to create an exception with no results. Completely uninstalled it and Voila!
THANK YOU SO MUCH FOR YOUR PROMPT HELP!
Once i figure how to create the proper exception I will post it here for future reference

**Comment by breiler** [comment]
If you got the time we'd appreciate if you could write a couple of lines about your findings here:
https://github.com/winder/Universal-G-Code-Sender/wiki/Troubleshooting-Overview#antivirus-software

Thanks!
