### ISSUE TITLE
new jog controller wont accept X axis shortcuts 

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#1238]
alt up/down ant alt pg up/down work for the Y and Z axis.

alt left/right do not effect the X axis.

yes the keybinds are set to what i want it to do. worked in the april version. now trying the 5/19 platform with the diagnal jog options

**Comment by breiler** [comment]
I don't have a Windows machine to try this out. But I experience similar problems on Mac OSX where the operating system already have stuff mapped or won't let me assign certain key combinations.

I've just tried different combinations and finally found combinations working...

It's weird though that shortcuts stopped working, did you perhaps upgrade Windows or installed other software that may interrupt certain key combinations?

**Comment by jahnj0584** [comment]
Nothing changed. If I use the old version it still works.

**Comment by breiler** [comment]
Thanks, I'll try to look into it!

**Comment by breiler** [comment]
I can't reproduce this, but I found an issue where some input boxes (still) steal focus making the shortcuts inactive... This could be what you are experiencing.

I'm working on a potential fix/workaround for this

**Comment by breiler** [comment]
Once this has been built you can try the new button and see if it helps, otherwise we'll open this again.
