### ISSUE TITLE
UGS Platform fails to open after Java license update (Apr 16, 2019)

### ISSUE THREAD

**Issue by landbrad** [winder/Universal-G-Code-Sender#1241]
I've been using UGS Platform2.0 nightly build for over a year with java 8 on Win 7 / 64bit.  I allowed Java to update to build 1.8.0_211-b12 and now UGS will not open. Opening dialog box advances to the point where it reads "Opening Modules" then disappears.  I've tried deleting the UGS log files and DLing new UGS zip files to no avail.....
Any suggestions? Anyone else having a similar issue?

  What hardware are you using. Example:
  GRBL 1.1
  
[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/3244458/messages.log)

**Comment by AbySet** [comment]
I had this issue a year ago, try these two steps:
- Update UGS Platform as well.
- Delete this folder to have a clean installation (Your UGS settings will be deleted):
   c:\users\<username>\ .ugs       
   c:\users\<username>\AppData\Roaming\ .ugsplatform
   - _(Without spaces after \ in both lines, i had to add them)._

You can also check here for Troubleshooting overview:
https://github.com/winder/Universal-G-Code-Sender/wiki/Troubleshooting-Overview#antivirus-software

**Comment by landbrad** [comment]
Thanks AbySet but I tried that.
I'm almost certain this is related to the recent Java update on April 16, 2019...

**Comment by AbySet** [comment]
I am using it and i have no problems at all.
Maybe @winder or @breiler can take a look and help you, they have much more knowlege than me, just be patient, i'm sure they will take a look at your post.
Wish you good luck.

**Comment by breiler** [comment]
Sorry, I don't have a Windows machine to try reproducing the problem on. 

But from the log messages. it really looks like the settings file is corrupt. Would you mind attaching your settings file located in c:\users\username\ .ugs?

**Comment by landbrad** [comment]
> Sorry, I don't have a Windows machine to try reproducing the problem on.
> 
> But from the log messages. it really looks like the settings file is corrupt. Would you mind attaching your settings file located in c:\users\username\ .ugs?

The .json file ?

**Comment by landbrad** [comment]
Hmmmm
The only files in the .ugs folder are .json files which aren't supported here for uploading.

**Comment by JacksCrafts** [comment]
You might try uninstalling java and then go download it again.

**Comment by landbrad** [comment]
Reinstalled Windows and started from scratch. Back in business now...
