### ISSUE TITLE
Confirmation of "Reset Zero"

### ISSUE THREAD

**Issue by AngeloQABR** [winder/Universal-G-Code-Sender#1249]
Hi!
"Reset Zero" button is just near "Return Zero" button... I know, is my problem but I clicked "Reset Zero" button for two times when I wanted return to zero.
Is it possible create a message for confirmation in "Reset Zero" button? It would have saved me on the two jobs I lost.
Thanks!

**Comment by AbySet** [comment]
This happend to me too, but since it is not a bug i did not post it.
I should say i totaly agree with you @AngeloQABR , any improuvement will be welcome or at least colored text in red or orange but confirmation is better.
Thanks to you and to everyone working on this project.

**Comment by jahnj0584** [comment]
Quickest solution is to make these commands as a seperate macro, which you can easily re-order and seperate from each other

**Comment by TekMason** [comment]
+1 for this feature built-in.

**Comment by breiler** [comment]
It is now possible to reorder the buttons in the toolbox window:
https://github.com/winder/Universal-G-Code-Sender/wiki/Usage#toolbox
