### ISSUE TITLE
Setting work positions

### ISSUE THREAD

**Issue by Klaufmann** [winder/Universal-G-Code-Sender#125]
Hi
I'm not very satisfied with the "Reset Zero"-button. It just resets the position buffer with "G92 X0 Y0 Z0" and when you restart, everything is lost again...

My way to overcome this, I used the command "G10 L2 P1 X***\* Y***\* Z***_", where ***_ are the actual coords of the tool to save this position as origin for G54 (I need no more than this one work system). I have grbl 0.8c and works perfectly fine

What about turning this into an additional button or replace the old reset button completely?
Also, I could imagine resetting every axis on its own, should be very practical when seeking the work edges.

Edit: I have now seen, that for grbl 0.9 G10 is used, but with P0. Isn't P0 the register for the machine coordinates? I don't know if that's such a good idea...don't mind, if I'm wrong here...

**Comment by breiler** [comment]
@winder I think that we can close this?

We are using G10 for setting work offsets since GRBL 0.9 which I think is good enough.
