### ISSUE TITLE
Streaming , Feed Hold, Canceling

### ISSUE THREAD

**Issue by Mgilbride** [winder/Universal-G-Code-Sender#127]
Am curious how the pause and cancel functionality of file streaming works. If I pause streaming the machine stops almost instantly / gracefully. I see "Hold" in the verbose console output but no indication that a "!" has been sent. And likewise, when I resume I see the run status but see no indication of a "~" being sent. 

When I cancel I do not see a graceful stop. The CNC continues on it's way for some time. You can even see this behavior just watching the visualizer on an arduino that is not hooked up to an actual machine. 

Pausing brings machine to a stop in about a second or two. Canceling leaves machine running for 10 seconds or more. Am wondering if it is not possible to pause / feed hold for a controlled stop and then issue cancel commands. Currently, when you are using file streaming you have no access to the command line. Both the command line and the machine control pages are modal. So, if you pause by issuing a feed hold and stopping streaming you can not issue a soft reset (Ctrl-X) via the machine control panel or the command line. You're in a pickle if you do not have those functions hard wired on your control box. I think a soft reset should be available on the file mode page. This follows GRBL recommendations for gracefully exiting a program in a non-emergency.

**Comment by winder** [comment]
This is implemented now.

@Anachronicman GRBL v1.1 now has this feature built in, see "[laser mode](https://github.com/gnea/grbl/blob/edge/doc/markdown/settings.md#32---laser-mode-boolean)"
