### ISSUE TITLE
File fails to visualize correctly

### ISSUE THREAD

**Issue by khturnings** [winder/Universal-G-Code-Sender#1270]
## Problem description 
File generated in Fusion 360 fails to visualize correctly in UGS.

### Expected Behavior
Should show image in attached file. This image was taken from LaserGrbl which shows the data correctly.

### Actual Behavior
File shows parts of the data correctly but other parts is wrong

### Steps to Reproduce the Problem
Load attached NC (BirdparkKeyring.txt) file into NGS Platform

#### Version
  Product Version: Universal Gcode Platform 20190423
Java: 1.8.0_222; OpenJDK Client VM 25.222-b10
Runtime: OpenJDK Runtime Environment 1.8.0_222-8u222-b10-1~deb9u1-b10
System: Linux version 4.19.66-v7+ running on arm; UTF-8; en_US (ugsplatform)
User directory: /root/.ugsplatform/2.0-SNAPSHOT/dev
Cache directory: /root/.ugsplatform/2.0-SNAPSHOT/dev/var/cache

#### Operating system
  Raspbian Buster on RaspberryPI

#### Platform
  GRBL 1.1f

#### Other

[BirdParkKeyring.txt](https://github.com/winder/Universal-G-Code-Sender/files/3613025/BirdParkKeyring.txt)
![image](https://user-images.githubusercontent.com/30479350/64912324-73519900-d725-11e9-8208-bcd49c1205d5.png)
![image](https://user-images.githubusercontent.com/30479350/64912329-7e0c2e00-d725-11e9-8213-8548fdc094d6.png)

**Comment by DanielWeigl** [comment]
Can you try a more recent version, http://winder.github.io/ugs_website/download/#nightly-builds

This was most likely fixed here https://github.com/winder/Universal-G-Code-Sender/pull/1220

**Comment by khturnings** [comment]
Tried with nightly build - August 27 2019 with same result.
![image](https://user-images.githubusercontent.com/30479350/64921875-13f49700-d7c0-11e9-8831-a9663c851051.png)

**Comment by khturnings** [comment]
I reprocessed the file in Fusion 360 and got the correct output this time.

Please put this down to human error. 

I will close this issue. Thank for your help

**Comment by DanielWeigl** [comment]
It also looks strange in ncviewer.com:
![grafik](https://user-images.githubusercontent.com/1370302/65046864-af713d80-d961-11e9-9b9a-cd88e96f7c31.png)

Seems you have used a wrong postprocessor in fusion360, ive sofar not seen "inline" comments, like this:
```
G03 ( Circular CCW ) X0002.0550 Y0010.0000 I-0001.2500 J0000.0000 S90 ( Set laser power )
G03 ( Circular CCW ) X0004.5550 Y0010.0000 I0001.2500 J0000.0000 S90 ( Set laser power )
```

(the ` ( Circular CCW )`)
