### ISSUE TITLE
This G-Code works with bCNC but halts with UGS

### ISSUE THREAD

**Issue by CliveMcCarthy** [winder/Universal-G-Code-Sender#1272]
I ran this test code on the same rig, same GRBL, same computer with bCNC. UGS halts after about 45 minutes. There is no error message.

[hello_image.zip](https://github.com/winder/Universal-G-Code-Sender/files/3627388/hello_image.zip)

**Comment by breiler** [comment]
Classic or Platform edition?
Which version of UGS are you running?
What operating system are you using?

**Comment by CliveMcCarthy** [comment]
UGS
        Platform    20190814
        Java                   1.8.0_222
        Linux                  4.15.0-62
      
    On 9/18/19 9:31 AM, Joacim Breiler
      wrote:
    
    
      
      Classic or Platform edition?
        Which version of UGS are you running?
        What operating system are you using?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/winder/Universal-G-Code-Sender/issues/1272?email_source=notifications\u0026email_token=ACPQYUPDEWBF4QLTL6JUMWDQKJJXDA5CNFSM4IYA52FKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7AVIIY#issuecomment-532763683",
"url": "https://github.com/winder/Universal-G-Code-Sender/issues/1272?email_source=notifications\u0026email_token=ACPQYUPDEWBF4QLTL6JUMWDQKJJXDA5CNFSM4IYA52FKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7AVIIY#issuecomment-532763683",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by breiler** [comment]
Sorry for the late reply.

What processor architecture are you running?
`uname -a`

How much memory is available on the system?

I've just run the whole file without any problems.

**Comment by breiler** [comment]
I suspect that this is due to running jSerialComm driver on Linux, but without further answers from user it's hard to solve. Closing the issue.

**Comment by jes** [comment]
If the JSerialComm driver doesn't work properly on Linux, should we consider making JSSC the default?
