### ISSUE TITLE
help please how can i configure gbrl to have a pen up and down for my pen cnc

### ISSUE THREAD

**Issue by oraherb** [winder/Universal-G-Code-Sender#1279]
hi guys can someone help me how to configure this grbl (https://github.com/bdring/Grbl_Pen_Servo)  to work with my servo for up and down movement? im using windows 10 and  ugs 
my hardware is arduino nano   and i connect the orange wire or pulse  of the servo to  pin D11  on arduino    how can i make it work to have a pen type cnc
i follow all the instruction from here (https://www.instructables.com/id/How-to-Control-a-Servo-Using-GRBL/)but nothing work  my  question is what D pin should i use to make the servo up and down and how to rewrite the gcode to trigger the servo for up and down pleasese help i been figuring out this on my on and now im already giving up for my project please help

**Comment by svenhb** [comment]
I used https://github.com/cprezzi/grbl-servo
Just send Sx for spindle PWM to control a servo - x between 0 and 1000
Short description in german for an egg-bot with servo (but with link to google translator): http://svenhb.bplaced.net/?CNC___Eggbot___Eggbot_via_GRBL-Plotter

**Comment by oraherb** [comment]
@svenhb  bro so i have to change the gcode  to trigger the servo for pen up and down? what will i insert to the gcode?

**Comment by svenhb** [comment]
Yes, for example send "M3 S50" for pen down and "M3 S500" for pen up (or M4).
The correct values for S you need to figure out.
If the servo need some time for motion you may add the command "G4 P1" after pen down/up command for 1 second delay

**Comment by oraherb** [comment]
@svenh  bro thanks but how can i figure out the correct value for my S?? and it gives me an error so whats wrong i follow the instruction in your website please help me bro

**Comment by oraherb** [comment]
![Screenshot (6)_1](https://user-images.githubusercontent.com/56026346/66270370-2eabb000-e842-11e9-911e-dc5095d19df6.jpg)
heres my error   bro  @svenhb

**Comment by svenhb** [comment]
You send M17 and M18, this commands are not known by grbl, and also not known for other CNC - check known M-Codes here: http://linuxcnc.org/docs/html/gcode/m-code.html

**Comment by svenhb** [comment]
How do you generate your GCode?

**Comment by oraherb** [comment]
@svenhb  in inkscape and it has an unicorn plugin bro

**Comment by svenhb** [comment]
You may save your inkscape path and open it in GRBL-Plotter... 
But here we are in the Universal-G-Code-Sender area...

**Comment by oraherb** [comment]
@sve
![Screenshot (8)_1](https://user-images.githubusercontent.com/56026346/66270587-ec37a280-e844-11e9-8390-80c41c710d1d.jpg)   how can i generate gcode for my pen plotter bro? 
nhb

**Comment by svenhb** [comment]
Drag your SVG and drop it on the 2D view
In Setup section you define what to do at pen up/down action

**Comment by oraherb** [comment]
@svenhb  ok i will try it thanks hope it works just a sec...

**Comment by oraherb** [comment]
@svenhb bro your awesome  but  i have a problem  where should i define the pen up and down action i cannot find  it where to write the  code for  pen example (m3 s50
![Screenshot (10)](https://user-images.githubusercontent.com/56026346/66271176-8c43fa80-e84a-11e9-834d-c188c0cd408b.png)
)

**Comment by oraherb** [comment]
@svenhb  bro it means a lot to me when i make this project works im a new to this still learning

**Comment by svenhb** [comment]
In setup - graphics import - GCode generation, on the far right, enable Servo control.
Via Main GUI "Control/Jogging" you need to switch off / on the spindel with different speed, to find your S-Values for up and down.
![image](https://user-images.githubusercontent.com/19973251/66271830-e2bd3300-e862-11e9-8e63-10735061b462.png)

**Comment by oraherb** [comment]
@svenhb bro i subscribe to your youtube  and you make a dvd plotter thats what im doing now  and thanks it works but the servo is traveling to far like 180degrees   can u give me the exact setting of your dvd mini plotter ?

**Comment by svenhb** [comment]
My dvd plotter uses stepper motor for Z, but the egg-bot I use a servo: 100 for pen up, 400 for pen down

**Comment by oraherb** [comment]
@svenhb bro it works but  how can i setup my mini pen plotter  its x and y axis travel too far my range is only 40mm   even i configure in grbl setting??   im using  DRV8825 step driver   do i have to connect the M0 M1 M2 to +5v  like a4988 to have a mircro stepping? if ot how can i make this mini cnc  draw  small image??
![CYMERA_20191007_014035_1](https://user-images.githubusercontent.com/56026346/66273177-0f704b00-e861-11e9-931b-e63b647f0ecf.jpg)

**Comment by svenhb** [comment]
If you move by 10 mm via virtual joystick, does it travel 10 mm? Then it's ok.
You can resize your drawing, depending on source a) SVG during conversion, b) via menu 'GCode transform. If you have an image you need to define the size on the tab 'image correction'.
Most probably your grbl settings are not correct. I set M0,1,2 al to +5V
GRBL-Settings:
$100=107.000
$101=107.000
$102=107.000
$110=10000.000
$111=10000.000
$112=10000.000
$120=500.000
$121=500.000
$122=500.000
See also http://svenhb.bplaced.net/?CNC___Mini_CNC_Plotter

**Comment by oraherb** [comment]
@svenhb bro can u give me idea how to make an gcode  that will fit in  my mini cnc from dvd i mean  i tried everything but the gcode i created always exceed  the limit of my mini cnc 30mm  my stepper x and y always running out of axis

**Comment by svenhb** [comment]
Does your x axis move by 5 mm if you send x5 ? Or if you click on '5' in virtual joystick?

**Comment by oraherb** [comment]
X-axis: Engine = 400 = steps / revolution = 1,111 steps / degree 
setting the Y parameters: 
$ 100 = 1,111; 
$ 110 = 10000 (max. Speed - tried); 
$ 120 = 500 (max. Acceleration -ausprobiert)
Y-axis: Engine = 400 = steps / revolution + reduction 1:50 = 20,000 steps / revolution = 55.555 steps / degree 
setting the X-parameters: 
$ 101 = 55,555; 
$ 111 = 800 (max. Speed - tried); 
$ 121 = 500 (max acceleration -. Tried)

**Comment by oraherb** [comment]
i tried those setting and it move 9mm

**Comment by oraherb** [comment]
when i tried this your setting theng press 5 in virtual joystick it move 1mm per jog


$100=107.000
$101=107.000
$102=107.000
$110=10000.000
$111=10000.000
$112=10000.000
$120=500.000
$121=500.000
$122=500.000

**Comment by svenhb** [comment]
Aha. You may change $100 to 1.111/9*5 = 0.617 and $101 to 30.86.... (or the other way arround *9/5)
Makes no sense to change any graphics scaling when your hardware reacts wrong!
BTW: did you uncheck "STOP Jogging on mouse up" - then on click causes one complete move for e.g. 5 mm.

**Comment by oraherb** [comment]
@svenhb hey bro  when ipress the Y axis it also move the X axis in virtual  joystick but when i press the X      it doesnt move the way what u think is an hardware?

**Comment by svenhb** [comment]
Check the COM window to what was sent to grbl. 
Are you using the hardware which is mentioned in your grbl-link  (https://github.com/bdring/Grbl_Pen_Servo) ? Perhaps some signal-wires are mixed up?

> Default setup.
> **The default setup is for a buildlog.net** Pen/Laser Bot Controller. If you are not using that, you need to make sure your schematic matches the pin defined in cpu_map.h

**Comment by oraherb** [comment]
yes bro im using that grbl

**Comment by svenhb** [comment]
If you move 5 mm in UGS, does your hardware move by 5 mm?
I think you need to play with your $100 / $101 setup.

**Comment by oraherb** [comment]
yes bro it accurately move 5mm if i move 5mm in ugs

**Comment by oraherb** [comment]
@svenhb hey bro help me with this how can i generate and gcode image that size is 10mm height and  10mm width  i dont know how i can resize this image to make it fit with my minimum axis ![Screenshot (10)_1](https://user-images.githubusercontent.com/56026346/66316372-16ea2f80-e907-11e9-9992-d9ebaee95aed.jpg)

**Comment by svenhb** [comment]
Go to the tab 'Image correction' and play with 'width' and 'height'

**Comment by oraherb** [comment]
ok bro thanks

**Comment by winder** [comment]
@oraherb I'm glad that you're getting help, but please move this discussion on the right project page -> https://github.com/svenhb/GRBL-Plotter

**Comment by svenhb** [comment]
@winder can you close the thread here?
@oraherb go on here: https://github.com/svenhb/GRBL-Plotter/issues/new/choose

**Comment by oraherb** [comment]
ok  guys thanks
