### ISSUE TITLE
Importing keymapping crashes stable version

### ISSUE THREAD

**Issue by falviani** [winder/Universal-G-Code-Sender#1296]
### Steps to Reproduce the Problem

  1.
  1.
  1.

**Comment by falviani** [comment]
I created a set of keymappings in the latest platform nightly and exported just them. I then  opened the latest platform stable and imported them. The app immediately crashed with no error messages being displayed.

**Comment by BallscrewBob** [comment]
Good to see this brought up again as that's the issue I had.
In between some of the crashes it did actually import my macros and such so I never came back to the issue.

**Comment by breiler** [comment]
The import/export function is unfortunately broken in earlier versions of UGS. This should have been fixed in #1156.

I'm closing this as there isn't much we can do with the old import files. =(
