### ISSUE TITLE
Support symlinks like /dev/ttyArduino e.g.

### ISSUE THREAD

**Issue by hungerpirat** [winder/Universal-G-Code-Sender#131]
If you have multiple devices connected they are represented as /dev/ttyACM0 , /dev/ttyACM1, /dev/ttyACM2, ... 
To assign every device a single point of access you can use udev rules. These are creating symlinks like /dev/ttyArduino -> /dev/ttyACM? when plugging in. 

I already did the required changes in my fork, see commit a14e9c1330c0e1ce73961fd650d90193b3fc7f06. Tell me if you would like to have a pull request. 

Finally, thank you for your great work on UGS.

**Comment by winder** [comment]
I changed the serial library used by UGS to something that hasn't been abandoned since 2009. It seems to handle symlinks with nothing special.

**Comment by winder** [comment]
Also I didn't notice you had provided changes a year ago, I would have pulled them into the main branch. Sorry about that.
