### ISSUE TITLE
[Error] An error was detected while sending '0S30': error: Expected command letter. Streaming has been paused. **** The communicator has been paused ****

### ISSUE THREAD

**Issue by raimis170** [winder/Universal-G-Code-Sender#1313]
i need help to fix this error in UGS I create g code in inkscape and i did try with other codes too but nothing
in different versions of ugs i get same error.

[Error] An error was detected while sending '0S30': error: Expected command letter. Streaming has been paused.
**** The communicator has been paused ****

**Comment by breiler** [comment]
I suspect that this is similar to: #603 

I'm guessing you are using a plugin in Inkscape that requires a modified version of GRBL that can handle a M300-command for lifting a pen with a servo.

To be able to help you we would need what software you are running:
* GRBL-version
* Arduino type (Due, Mega, other)
* Inkscape plugin
* UGS version

**Comment by raimis170** [comment]
Fixed my problem

**Comment by AVTG-1** [comment]
> I suspect that this is similar to: #603
> 
> I'm guessing you are using a plugin in Inkscape that requires a modified version of GRBL that can handle a M300-command for lifting a pen with a servo.
> 
> To be able to help you we would need what software you are running:
> 
> * GRBL-version
> * Arduino type (Due, Mega, other)
> * Inkscape plugin
> * UGS version

**Comment by DonVoid18** [comment]
@raimis170 disculpa, puedes compartir la solución

**Comment by moshe582** [comment]
[falla en  imprimir  con universal.zip](https://github.com/user-attachments/files/18428886/falla.en.imprimir.con.universal.zip)

**Comment by breiler** [comment]
@moshe582 read this: https://github.com/winder/Universal-G-Code-Sender/issues/603#issuecomment-383352765
