### ISSUE TITLE
Loading Gcode : 'Problem with Shortcut'

### ISSUE THREAD

**Issue by FloydHD** [winder/Universal-G-Code-Sender#1327]
## Problem description 
When clicking on the open Gcode file it shows me the warning 'Problem with Shortcut'.
After clicking OK, the Messagebox comes up 3 more times and then the File Explorer with the Desktop to select the Gcode File. After the File Explorer opened the Error comes up one more time.

### Expected Behavior
When I try to open a Gcode the File Explorer should show without an error.

### Actual Behavior
3x Error 'Problem with Shortcut'
File Explorer opening
1x Error 'Problem with Shortcut'
Edit : The error also shows again when changing directory. 

### Steps to Reproduce the Problem
Click 'Open Gcode File'

#### Version
UGS Platform (Version 2.0 [nightly] / Aug 20, 2019) 

Product Version: Universal Gcode Platform 20190820
Java: 1.8.0_201; Java HotSpot(TM) 64-Bit Server VM 25.201-b09
Runtime: Java(TM) SE Runtime Environment 1.8.0_201-b09
System: Windows 10 version 10.0 running on amd64; Cp1252; en_US (ugsplatform)
User directory: C:\Users\floyd\.ugsplatform\2.0-SNAPSHOT\dev
Cache directory: C:\Users\floyd\.ugsplatform\2.0-SNAPSHOT\dev\var\cache

#### Operating system
Windows 10

#### Other
I don't know if its a problem with Windows or with UGS but here is the Error:
![Screenshot_1](https://user-images.githubusercontent.com/29488767/71307689-2cdd9b80-23f2-11ea-8e17-ffbe11945462.png)

**Comment by breiler** [comment]
And you are sure you are opening the actual gcode file and not, as the error suggests, a shortcut-file?

**Comment by FloydHD** [comment]
The error occurs before I can even select a Gcode file. 
I've recorded a video : https://youtu.be/0fU1E568ASw

**Comment by winder** [comment]
Looks like this is a known issue in the Java runtime. You can fix the desktop shortcut or upgrade to the latest Java 12 version for a fix.

https://bugs.openjdk.java.net/browse/JDK-8213583

**Comment by FloydHD** [comment]
So I've currently got Java Version 8 build 1.8.0_231-b11
The Oracle Support for Java 12 has ended and there is only the 13.0.1 Version available. Should I install Version 13?

**Comment by FloydHD** [comment]
Ah nvmd. I found the Shortcut which is not working. Deleted it and now it's working perfectly 👍 
Thanks :)
