### ISSUE TITLE
Failed to build a part of the code on instalation

### ISSUE THREAD

**Issue by Kirbsterbbq** [winder/Universal-G-Code-Sender#1331]
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) on project ugs-pendant: Could not download Node.js: Got error code 404 from the server. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ugs-pendant
pi@raspberrypi:~/Universal-G-Code-Sender $

**Comment by breiler** [comment]
This is a known issue on raspberry pi. If you really need to build it yourself follow this guide:
https://github.com/winder/Universal-G-Code-Sender/wiki/Raspberry-Pi#building-on-raspberry-pi
