### ISSUE TITLE
Alarm:2 Soft limit alarm

### ISSUE THREAD

**Issue by Thulebug** [winder/Universal-G-Code-Sender#1335]
Hi,
I know my CNC works because it runs with Easel. When I try to use UGS and Vcarve Desktop it gives me the error in the picture. It doesn't matter where on the CNC I place my material. I've rebooted everything multiple times and recreated the g-code file multiple times.

![1](https://user-images.githubusercontent.com/59212111/71625051-9439df00-2b9a-11ea-912e-eb6c190e05b3.jpg)

Thank You

**Comment by JacksCrafts** [comment]
What are your firmware settings? Are they set to inches or mm? Bed size?

**Comment by Thulebug** [comment]
Hello, not sure about firmware. Set to inches and it's a Bob's E4 24x24 inch bed.

Sent from AT&T Yahoo Mail on Android 
 
  On Tue, Dec 31, 2019 at 7:06 AM, JacksCrafts<notifications@github.com> wrote:   
What are your firmware settings? Are they set to inches or mm? Bed size?

**Comment by breiler** [comment]
Can you post your settings from the command:
```$$```

**Comment by Thulebug** [comment]
Hello, I'm sorry but I don't understand what you want me to do.
    On Tuesday, December 31, 2019, 10:11:17 AM PST, Joacim Breiler <notifications@github.com> wrote:  
 
 
Can you post your settings from the command:
$$

**Comment by JacksCrafts** [comment]
When you connect you will see your settings.
$0 = 10    (Step pulse time, microseconds)
$1 = 255    (Step idle delay, milliseconds)
$2 = 0    (Step pulse invert, mask)
$3 = 0    (Step direction invert, mask)
$4 = 0    (Invert step enable pin, boolean)
$5 = 0    (Invert limit pins, boolean)
$6 = 0    (Invert probe pin, boolean)
$10 = 1    (Status report options, mask)
$11 = 0.010    (Junction deviation, millimeters)
$12 = 0.002    (Arc tolerance, millimeters)
$13 = 1    (Report in inches, boolean)
$20 = 0    (Soft limits enable, boolean)
$21 = 0    (Hard limits enable, boolean)

**Comment by JacksCrafts** [comment]
You can also see them when you are connected, by going up to the top menu next to File is Machine.
Toward the bottom of the dropdown is firmware settings.

**Comment by breiler** [comment]
@Thulebug did you find the output from your settings?

**Comment by Thulebug** [comment]
I will be able to look at it Saturday.
    On Friday, January 3, 2020, 05:21:46 AM PST, Joacim Breiler <notifications@github.com> wrote:  
 
 
@Thulebug did you find the output from your settings?

**Comment by breiler** [comment]
Closing as we didn't get any further response, please reopen again if you still have a problem
