### ISSUE TITLE
Unable to open UGSplatform on Windows 7 or Windows 10

### ISSUE THREAD

**Issue by artrun** [winder/Universal-G-Code-Sender#1337]
Hello,

When i launch UGS the application loads then gets stuck at the following screen:
![image](https://user-images.githubusercontent.com/52615152/71698834-dcf7c080-2d71-11ea-8ea7-256efeb460a4.png)

The application then freezes and I have to close via task manager.
At first, I thought it was an issue with java but I download UGS with a specific Java version preconfigured but the same issue happened.
https://ugs.jfrog.io/ugs/webapp/#/artifacts/browse/tree/General/UGS/nightly/ugs-platform-app-2.0-SNAPSHOT-win.zip

Here are the logs:
-------------------------------------------------------------------------------
>Log Session: Thursday, January 2, 2020 at 3:04:03 PM Pacific Standard Time
>System Info: 
  Product Version         = Universal Gcode Platform incubator-netbeans-release-404-on-20190319
  Operating System        = Windows 10 version 10.0 running on amd64
  Java; VM; Vendor        = 12.0.2; OpenJDK 64-Bit Server VM 12.0.2+10; AdoptOpenJDK
  Runtime                 = OpenJDK Runtime Environment 12.0.2+10
  Java Home               = C:\Users\aarzunyan\Downloads\ugsplatform-win\jdk\jdk-12.0.2+10-jre
  System Locale; Encoding = en_US (ugsplatform); Cp1252
  Home Directory          = C:\Users\aarzunyan
  Current Directory       = C:\Users\aarzunyan\Downloads\ugsplatform-win
  User Directory          = C:\Users\aarzunyan\.ugsplatform\2.0-SNAPSHOT\dev
  Cache Directory         = C:\Users\aarzunyan\.ugsplatform\2.0-SNAPSHOT\dev\var\cache
  Installation            = C:\Users\aarzunyan\Downloads\ugsplatform-win\etc
                            C:\Users\aarzunyan\Downloads\ugsplatform-win\ide
                            C:\Users\aarzunyan\Downloads\ugsplatform-win\bin
                            C:\Users\aarzunyan\Downloads\ugsplatform-win\ugsplatform
                            C:\Users\aarzunyan\Downloads\ugsplatform-win\extra
                            C:\Users\aarzunyan\Downloads\ugsplatform-win\java
                            C:\Users\aarzunyan\Downloads\ugsplatform-win\platform
                            C:\Users\aarzunyan\Downloads\ugsplatform-win\platform
  Boot & Ext. Classpath   = 
  Application Classpath   = C:\Users\aarzunyan\Downloads\ugsplatform-win\platform\lib\boot.jar;C:\Users\aarzunyan\Downloads\ugsplatform-win\platform\lib\org-openide-modules.jar;C:\Users\aarzunyan\Downloads\ugsplatform-win\platform\lib\org-openide-util-lookup.jar;C:\Users\aarzunyan\Downloads\ugsplatform-win\platform\lib\org-openide-util-ui.jar;C:\Users\aarzunyan\Downloads\ugsplatform-win\platform\lib\org-openide-util.jar
  Startup Classpath       = C:\Users\aarzunyan\Downloads\ugsplatform-win\platform\core\asm-all-5.0.1.jar;C:\Users\aarzunyan\Downloads\ugsplatform-win\platform\core\core-base.jar;C:\Users\aarzunyan\Downloads\ugsplatform-win\platform\core\core.jar;C:\Users\aarzunyan\Downloads\ugsplatform-win\platform\core\org-netbeans-libs-asm.jar;C:\Users\aarzunyan\Downloads\ugsplatform-win\platform\core\org-openide-filesystems-compat8.jar;C:\Users\aarzunyan\Downloads\ugsplatform-win\platform\core\org-openide-filesystems.jar;C:\Users\aarzunyan\Downloads\ugsplatform-win\ugsplatform\core\locale\core_ugsplatform.jar
-------------------------------------------------------------------------------
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Applying settings.
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading LocalizingService...
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading JogService...
INFO [org.netbeans.core.startup.NbEvents]: Turning on modules:
	org.openide.util.lookup [8.37.1 incubator-netbeans-release-404-on-20190319]
	org.openide.util [9.11.1 incubator-netbeans-release-404-on-20190319]
	org.openide.util.ui [9.12.1 incubator-netbeans-release-404-on-20190319]
	org.openide.modules [7.52.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.api.annotations.common/1 [1.31.1 incubator-netbeans-release-404-on-20190319]
	org.openide.filesystems [9.14.1 incubator-netbeans-release-404-on-20190319]
	org.openide.awt [7.72.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.api.progress/1 [1.51.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.api.progress.nb [1.51.1 incubator-netbeans-release-404-on-20190319]
	org.openide.dialogs [7.46.1 incubator-netbeans-release-404-on-20190319]
	org.openide.nodes [7.49.1 incubator-netbeans-release-404-on-20190319]
	org.openide.windows [6.80.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.mimelookup/1 [1.44.1 incubator-netbeans-release-404-on-20190319]
	org.openide.text [6.71.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.api.scripting [1.0.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.swing.tabcontrol [1.60.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.swing.outline [1.38.1 incubator-netbeans-release-404-on-20190319]
	org.openide.explorer [6.66.1 incubator-netbeans-release-404-on-20190319]
	org.openide.actions [6.43.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.queries/1 [1.47.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.api.templates [1.12.1 incubator-netbeans-release-404-on-20190319]
	org.openide.filesystems.nb [9.14.1 incubator-netbeans-release-404-on-20190319]
	org.openide.loaders [7.71.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.api.intent [1.6.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.api.io [1.7.1 incubator-netbeans-release-404-on-20190319]
	org.openide.io [1.53.1 incubator-netbeans-release-404-on-20190319]
	org.openide.filesystems.compat8 [9.13.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.swing.plaf [1.45.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.spi.tasklist/1 [1.39.1.1 1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.spi.quicksearch [1.31.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.spi.navigator/1 [1.42.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.settings/1 [1.61.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.util/1 [1.69.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.document [1.13.1.3 3 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.lexer/2 [1.67.1.1 1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.lib2/1 [2.22.1.55.3 55 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.settings.lib [1.55.1.1 1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.fold/1 [1.49.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.indent/2 [1.47.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.guards/1 [1.37.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.lib/3 [4.11.1.23.3.55 23 incubator-netbeans-release-404-on-20190319]
	org.netbeans.spi.editor.hints/0 [1.46.1.7.55 7 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.templates/1 [1.11.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.libs.asm [5.7.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.bootstrap/1 [2.82.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.core.startup.base [1.66.1.1 1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.core.startup/1 [1.66.1.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.settings/1 [1.53.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.sendopts/2 [2.40.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.sampler [1.18.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.keyring [1.28.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.core/2 [3.55.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.options.api/1 [1.49.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.options.keymap [1.41.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.settings.storage/1 [1.55.1.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.fold.nbui [1.16.1.55 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor/3 [1.91.1.6.3.23.55 6 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.options.editor/1 [1.64.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.errorstripe.api/1 [2.36.1.1 1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.errorstripe/2 [2.38.1.1.1 1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.projectapi/1 [1.71.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.diff/1 [1.55.1.42.1 42 incubator-netbeans-release-404-on-20190319]
	org.netbeans.api.java.classpath/1 [1.58.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.libs.lucene/3 [3.23.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.masterfs/2 [2.59.1.2 2 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.parsing.lucene/2 [2.39.1.1 1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.parsing.api/1 [9.11.1.8 8 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.projectuiapi.base/1 [1.89.1.9 9 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.project.indexingbridge [1.21.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.parsing.indexing [9.12.1.1.3.8 1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.refactoring.api [1.51.1.1 1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.projectapi.nb [1.7.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.progress.ui [1.37.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.print [7.30.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.parsing.nb [1.7.1.8.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.libs.jna/1 [1.51.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.masterfs.windows [1.20.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.masterfs.ui [2.7.1.2 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.masterfs.nio2 [1.19.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.keyring.fallback [1.12.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.keyring.impl [1.28.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.core.ui/1 [1.49.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.api.search [1.25.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.jumpto/1 [1.58.1.1 1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.favorites/1 [1.50.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.plain.lib/1 [1.37.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.plain/2 [1.39.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.mimelookup.impl/1 [1.36.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.completion/1 [1.48.1.2 2 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.codetemplates/1 [1.47.1.1 1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.breadcrumbs/0 [1.21.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.editor.actions/1 [1.35.1.55 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.csl.types/1 [1.4.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.core.multiview/1 [1.48.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.csl.api/2 [2.58.1.2.1.1.8.1 2 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.autoupdate.services [1.57.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.autoupdate.cli [1.17.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.core.windows/2 [2.87.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.libs.osgi [1.26.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.libs.felix [2.19.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.autoupdate.ui [1.49.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.modules.core.kit [1.34.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.libs.jna.platform/1 [1.19.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.core.output2/1 [1.46.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.core.network [1.15.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.core.netigso [1.35.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.core.nativeaccess/1 [1.35.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.core.multitabs/1 [1.16.1.1 1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.core.io.ui/1 [1.34.1 incubator-netbeans-release-404-on-20190319]
	org.netbeans.api.progress.compat8 [1.51.1 incubator-netbeans-release-404-on-20190319]
	com.willwinder.ugs.platform.ugslib [2.0.0.2019.12.30.17.55 2.0-20191230 201912301758]
	com.willwinder.ugs.platform.visualizer [2.0.0.2019.12.30.17.55 2.0-20191230 201912301758]
	com.willwinder.ugs.platform.welcome.page [2.0.0.2019.12.30.17.55 2.0-20191230 201912301759]
	com.willwinder.ugs.platform.ugscore [2.0.0.2019.12.30.17.55 2.0-20191230 201912301758]
	com.willwinder.ugs.platform.surfacescanner [2.0.0.2019.12.30.17.55 2.0-20191230 201912301758]
	com.willwinder.ugs.platform.plugin.workflow [2.0.0.2019.12.30.17.55 2.0-20191230 201912301758]
	com.willwinder.ugs.platform.plugin.setup.wizard [2.0.0.2019.12.30.17.55 2.0-20191230 201912301759]
	com.willwinder.ugs.platform.plugin.jog [2.0.0.2019.12.30.17.55 2.0-20191230 201912301758]
	com.willwinder.ugs.platform.gcode.editor [2.0.0.2019.12.30.17.55 2.0-20191230 201912301758]
	com.willwinder.ugs.platform.branding [2.0.0.2019.12.30.17.55 2.0-20191230 201912301757]
	com.willwinder.ProbeModule [2.0.0.2019.12.30.17.55 2.0-20191230 201912301758]
	com.willwinder.GcodeTools [2.0.0.2019.12.30.17.55 2.0-20191230 201912301758]
	com.willwinder.DowelModule [2.0.0.2019.12.30.17.55 2.0-20191230 201912301758]
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading OverrideActionService...
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading MacroService...
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading SendStatusLineService...
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading SettingsChangedNotificationService...
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: SettingsChangedNotificationService$$Lambda$227/0x0000000801125c40
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading WindowTitleUpdaterService...
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: WindowTitleUpdaterService$$Lambda$228/0x0000000801126840
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading PendantService...
INFO [com.willwinder.ugs.nbp.core.services.PendantService]: Starting pendant service
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading ConsoleNotificationService...
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Services loaded!
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Setting UGP version title.
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy resolver: Windows
INFO [org.netbeans.core.network.proxy.windows.WindowsNetworkProxy]: Windows system proxy resolver: auto detect
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy reloading succeeded.
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy - mode: direct
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy: fell to default (correct if direct mode went before)
WARNING [org.openide.filesystems.Ordering]: Not all children in Menu/ marked with the position attribute: [Machine, Visualizer], but some are: [File, Tools, Window, Help]
WARNING [org.openide.filesystems.Ordering]: Found same position 100 for both Toolbars/File and Toolbars/StartPauseStop
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: ConnectDisconnectAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: FirmwareAction
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: Initializing firmware... ...
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config/g2core.json
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config/test_1.json
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config/test_2.json
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config/tinyg.json
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config/grbl.json
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config/smoothieboard.json
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: PortAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: BaudRateAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: StartAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: StopAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: PauseAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: HomingAction
INFO [org.netbeans.ui.metrics.laf]: USG_LOOK_AND_FEEL
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: LoadedFileStatusLineService$$Lambda$263/0x00000008012b2c40
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: JogStatusLine
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: SendStatusLine
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding controller listener: SendStatusLine
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Getting processed gcode file.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: SendStatusPanel
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding controller listener: SendStatusPanel
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Getting processed gcode file.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: MacroActionPanel
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: UseSeparateStepSizeAction$$Lambda$271/0x00000008012ca040
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: JogTopComponent
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding controller listener: ContinuousJogHandler
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: ActionButtonPanel
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: StateTopComponent
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: MachineStatusPanel
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding controller state listener: MachineStatusPanel
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: CommandPanel
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: CommandTextArea

**Comment by breiler** [comment]
Thanks for the detailed report!

The latest version of UGS is using a newer version of both the netbeans platform which UGS is built upon and Java version. I'd appreciate if you could give it a try.

The log file content that you posted, was it the complete file? I was expecting some kind of error at the end, but there is no clues... =/

**Comment by breiler** [comment]
Similar issue was reported here #1347 caused by the antivirus software.

**Comment by artrun** [comment]
thank you. it was the antivirus

**Comment by breiler** [comment]
What antivirus software are you using?
