### ISSUE TITLE
Pendant ntroller z step size < 1 is broken

### ISSUE THREAD

**Issue by arneboe** [winder/Universal-G-Code-Sender#1345]
### Problem
Unable to enter values < 1 for z step size in web pendant.

### Expected Behavior
I am able to enter 0.1 into the field for z step size.

### Actual Behavior
The "." is removed and the value turns into 1 instead of 0.1.

### Steps to Reproduce the Problem
1. open ugs
2. open the web pendant
3. go to the jog controller
4. try to enter a value < 1 into z step size.

#### Version
  UGS Platform 2.0 - Nightly Build Aug 14 2019 (this is named stable on the download page).
#### Operating system
  Windows 10

**Comment by breiler** [comment]
This could be caused by the language specific settings of the web browser. What happens if you write a comma: 0,1?

**Comment by arneboe** [comment]
Doesn't work either. The comma is removed immediately

**Comment by arneboe** [comment]
I am accessing the pendant using firefox on android if that is relevant
