### ISSUE TITLE
how to solve  null point error in universal gcode sender

### ISSUE THREAD

**Issue by Pawankumar4UPK** [winder/Universal-G-Code-Sender#1349]
### 
  1.
  1.
  1.

### Specification 
i am using t and migrbl

**Comment by breiler** [comment]
There is no way to be able to help you with this little information.

* Which version of UGS did you download?
* What file are you trying to run, could you attach it?
* What GRBL-version are you running, provide the link where you downloaded it (migrbl sounds like it's fork a from https://github.com/gnea/grbl/)

It would be really helpful if you attached the logs, the locations of the log files are described here:
http://winder.github.io/ugs_website/guide/troubleshooting/#property-files
