### ISSUE TITLE
MVN Errors

### ISSUE THREAD

**Issue by ws-mkulas** [winder/Universal-G-Code-Sender#1354]
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.808 s <<< FAILURE! - in com.willwinder.ApplicationTest
[ERROR] com.willwinder.ApplicationTest.testApplication  Time elapsed: 0.019 s  <<< FAILURE!
junit.framework.AssertionFailedError:
**NbModuleSuite has been started with failOnMessage(WARNING) and failOnException(INFO). The following failures have been captured:
[com.willwinder.universalgcodesender.utils.Version] THREAD: On Start/Stop MSG: Couldn't convert the lut 02, 2020 from date format "MMM dd, yyyy" to format "yyyyMMdd"**

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR] com.willwinder.ApplicationTest.testApplication
[INFO]   Run 1: PASS
[ERROR]   Run 2: ApplicationTest.testApplication NbModuleSuite has been started with failOnMessage(WARNING) and failOnException(INFO). The following failures have been captured:
[com.willwinder.universalgcodesender.utils.Version] THREAD: On Start/Stop MSG: Couldn't convert the lut 02, 2020 from date format "MMM dd, yyyy" to format "yyyyMMdd"

[INFO]
[INFO]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.611 s
[INFO] Finished at: 2020-02-02T23:37:29+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project ugs-platform-app: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/mkulas/Downloads/Universal-G-Code-Sender-master/ugs-platform/application/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by breiler** [comment]
What language is your system set to?

**Comment by breiler** [comment]
Closing as there was no more information from the user.
