### ISSUE TITLE
Tiny UI elements on high resolution windows laptop.

### ISSUE THREAD

**Issue by kthornbloom** [winder/Universal-G-Code-Sender#1370]
## Problem description 
On a high resolution device, (Lenovo Yoga 900 Laptop) some UI elements are too small.

### Expected Behavior
Normal UI sizing

### Actual Behavior
Tiny UI

#### Version
Platform Version 2.0 nightly / Mar 20,2020

#### Operating system
Windows 10

#### Platform
  GRBL 1.1

#### Other

![Annotation 2020-03-21 205736](https://user-images.githubusercontent.com/3322795/77239988-290b1200-6bb7-11ea-9d5c-55cc5c31c1fe.png)

**Comment by kthornbloom** [comment]
FYI, I was able to fix this:

1. Right click ugsplatform.exe
2. Properties
3. Click compatibility tab
4. Use the following settings:
![Annotation 2020-03-22 112454](https://user-images.githubusercontent.com/3322795/77253376-12ed6800-6c30-11ea-9e3e-a36440ee95e1.png)

I'll leave it up to someone else if that's good enough to close this :)

**Comment by abdset** [comment]
Good to know how you fixed it, this may help others.
Thanks a lot.

**Comment by breiler** [comment]
Closing this issue as there is a workaround. But Netbeans Platform have been updated with a lot of fixes for hdpi-issues that might fix this natively.
