### ISSUE TITLE
UGSplatform wont start under Ubuntu 20.04

### ISSUE THREAD

**Issue by ouinouin** [winder/Universal-G-Code-Sender#1391]
## Problem description 
While launching UGS platform under ubtuntu 20.04, i get the following : 
![Capture d’écran de 2020-04-16 10-35-06](https://user-images.githubusercontent.com/6713759/79434243-5daf9500-7fce-11ea-858d-43891a900fb8.png)
the screen locks at this step, and goes no further.
`OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.ProxyURLStreamHandlerFactory (file:/home/ouinouin/soft/installers_et_sources/usinage/ugs-platform-app-2.0-SNAPSHOT-linux/ugsplatform-linux/platform/lib/boot.jar) to field java.net.URL.handler
WARNING: Please consider reporting this to the maintainers of org.netbeans.ProxyURLStreamHandlerFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`
it looks like the same issue  than : https://github.com/winder/Universal-G-Code-Sender/issues/1228
but since this bug report was closed as working ...
### Expected Behavior
The UGS platform shall not lock at startup.

### Actual Behavior
UGS doesnt finish the startup and hangs at splash screen

### Steps to Reproduce the Problem
 1. Open the program

**Comment by breiler** [comment]
Which version of UGS are you running?

Did you install Java yourself or are you using the version that comes bundled with Java from here?
https://github.com/winder/Universal-G-Code-Sender#downloads

**Comment by ouinouin** [comment]
Hi, yes i took the bundled version and tried both the latest version and the stable version... I put the version numbers in my first message but apparently was eaten by github ....
so the error is the same with https://ugs.jfrog.io/ugs/UGS/nightly/ugs-platform-app-2.0-SNAPSHOT-linux.tar.gz
and with : http://bit.ly/2Z3DIVC (the 2.0 platform beta in the stable list of downloads.)

**Comment by breiler** [comment]
Can you upload your log file:
https://github.com/winder/Universal-G-Code-Sender/wiki/Configuration#log-files

**Comment by ouinouin** [comment]
hi, here is the latest log

`>Log Session: Sunday, April 19, 2020 at 8:31:23 PM Central European Summer Time
>System Info: 
  Product Version         = Universal Gcode Platform 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54
  Operating System        = Linux version 5.4.0-21-generic running on amd64
  Java; VM; Vendor        = 13.0.1; OpenJDK 64-Bit Server VM 13.0.1+9; AdoptOpenJDK
  Runtime                 = OpenJDK Runtime Environment 13.0.1+9
  Java Home               = /home/ouinouin/ugsplatform-linux/jdk/jdk-13.0.1+9-jre
  System Locale; Encoding = fr_FR (ugsplatform); UTF-8
  Home Directory          = /home/ouinouin
  Current Directory       = /home/ouinouin/ugsplatform-linux/bin
  User Directory          = /home/ouinouin/.ugsplatform/2.0-SNAPSHOT/dev
  Cache Directory         = /home/ouinouin/.ugsplatform/2.0-SNAPSHOT/dev/var/cache
  Installation            = /home/ouinouin/ugsplatform-linux/etc
                            /home/ouinouin/ugsplatform-linux/ide
                            /home/ouinouin/ugsplatform-linux/bin
                            /home/ouinouin/ugsplatform-linux/ugsplatform
                            /home/ouinouin/ugsplatform-linux/extra
                            /home/ouinouin/ugsplatform-linux/java
                            /home/ouinouin/ugsplatform-linux/platform
                            /home/ouinouin/ugsplatform-linux/platform
  Boot & Ext. Classpath   = 
  Application Classpath   = /home/ouinouin/ugsplatform-linux/platform/lib/boot.jar:/home/ouinouin/ugsplatform-linux/platform/lib/org-openide-modules.jar:/home/ouinouin/ugsplatform-linux/platform/lib/org-openide-util.jar:/home/ouinouin/ugsplatform-linux/platform/lib/org-openide-util-lookup.jar:/home/ouinouin/ugsplatform-linux/platform/lib/org-openide-util-ui.jar
  Startup Classpath       = /home/ouinouin/ugsplatform-linux/platform/core/org-openide-filesystems-compat8.jar:/home/ouinouin/ugsplatform-linux/platform/core/asm-all-5.0.1.jar:/home/ouinouin/ugsplatform-linux/platform/core/org-netbeans-libs-asm.jar:/home/ouinouin/ugsplatform-linux/platform/core/org-openide-filesystems.jar:/home/ouinouin/ugsplatform-linux/platform/core/core-base.jar:/home/ouinouin/ugsplatform-linux/platform/core/core.jar:/home/ouinouin/ugsplatform-linux/ugsplatform/core/locale/core_ugsplatform.jar
-------------------------------------------------------------------------------
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading LocalizingService...
INFO [com.willwinder.universalgcodesender.utils.SettingsFactory]: Log location: /home/ouinouin/.ugs/UniversalGcodeSender.json
INFO [com.willwinder.universalgcodesender.utils.SettingsFactory]: Loading settings.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Applying settings.
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading JogService...
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding controller listener: ContinuousJogWorker
WARNING [org.netbeans.modules.autoupdate.ui.actions.AutoupdateSettings]: The property "netbeans.default_userdir_root" was not set!
INFO [org.netbeans.core.startup.NbEvents]: Turning on modules:
	org.openide.util.lookup [8.39 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.openide.util [9.13 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.openide.util.ui [9.14 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.openide.modules [7.54 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.api.annotations.common/1 [1.33 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.openide.filesystems [9.16 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.openide.awt [7.74 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.api.progress/1 [1.53 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.api.progress.nb [1.53 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.openide.dialogs [7.48 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.openide.nodes [7.51 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.openide.windows [6.83 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.mimelookup/1 [1.46 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.openide.text [6.73 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.api.scripting [1.3 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.swing.tabcontrol [1.62 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.swing.outline [1.40 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.openide.explorer [6.68 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.openide.actions [6.45 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.queries/1 [1.49 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.api.templates [1.14 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.openide.filesystems.nb [9.16 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.openide.loaders [7.73 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.api.intent [1.8 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.api.io [1.9 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.openide.io [1.55 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.openide.filesystems.compat8 [9.15 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.swing.plaf [1.47 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.spi.tasklist/1 [1.41.0.1 1 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.spi.quicksearch [1.33 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.spi.navigator/1 [1.44 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.settings/1 [1.63 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.util/1 [1.71 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.document [1.15.0.3 3 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.lexer/2 [1.69.0.1 1 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.lib2/1 [2.26.0.55.3 55 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.settings.lib [1.57.0.1 1 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.fold/1 [1.51 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.indent/2 [1.49 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.guards/1 [1.39 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.lib/3 [4.13.0.23.3.55 23 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.spi.editor.hints/0 [1.48.0.7.55 7 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.templates/1 [1.13 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.libs.asm [5.9 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.bootstrap/1 [2.84 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.core.startup.base [1.68.0.1 1 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.core.startup/1 [1.68.0.1 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.settings/1 [1.55 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.sendopts/2 [2.42 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.sampler [1.20 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.keyring [1.30 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.core/2 [3.57 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.options.api/1 [1.51 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.options.keymap [1.43 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.settings.storage/1 [1.57.0.1 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.fold.nbui [1.18.0.55 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor/3 [1.93.0.6.3.23.55 6 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.options.editor/1 [1.66 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.errorstripe.api/1 [2.38.0.1 1 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.errorstripe/2 [2.40.0.1.1 1 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.projectapi/1 [1.73 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.diff/1 [1.57.0.42.1 42 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.api.java.classpath/1 [1.60 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.libs.lucene/3 [3.25 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.masterfs/2 [2.61.0.2 2 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.parsing.lucene/2 [2.41.0.1 1 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.parsing.api/1 [9.13.0.8 8 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.projectuiapi.base/1 [1.91.0.9 9 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.project.indexingbridge [1.23 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.parsing.indexing [9.14.0.1.3.8 1 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.refactoring.api [1.53.0.1 1 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.projectapi.nb [1.9 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.progress.ui [1.39 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.print [7.32 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.parsing.nb [1.9.0.8.1 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.masterfs.ui [2.9.0.2 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.masterfs.nio2 [1.21 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.libs.jna/2 [2.1 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.masterfs.linux [1.19 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.keyring.fallback [1.14 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.keyring.impl [1.30 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.core.ui/1 [1.51 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.api.search [1.27 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.jumpto/1 [1.60.0.1 1 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.favorites/1 [1.52 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.plain.lib/1 [1.39 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.plain/2 [1.41 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.mimelookup.impl/1 [1.38 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.completion/1 [1.50.0.2 2 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.codetemplates/1 [1.49.0.1 1 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.breadcrumbs/0 [1.23 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.editor.actions/1 [1.37.0.55 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.csl.types/1 [1.6 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.core.multiview/1 [1.50 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.csl.api/2 [2.60.0.2.1.1.8.1 2 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.autoupdate.services [1.59 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.autoupdate.cli [1.19 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.core.windows/2 [2.89 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.libs.osgi [1.28 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.libs.felix [2.21 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.autoupdate.ui [1.51 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.modules.core.kit [1.36 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.libs.jna.platform/2 [2.1 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.core.output2/1 [1.48 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.core.network [1.18 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.core.netigso [1.37 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.core.nativeaccess/1 [1.37 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.core.multitabs/1 [1.18.0.1 1 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.core.io.ui/1 [1.36 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	org.netbeans.api.progress.compat8 [1.53 11.2-d04fb24027334c4b6fd8397b5d0cdd33187a8f54]
	com.willwinder.ugs.platform.ugslib [2.0.0.2020.4.15.19.4 2.0-20200415 202004151906]
	com.willwinder.ugs.platform.ugscore [2.0.0.2020.4.15.19.4 2.0-20200415 202004151906]
	com.willwinder.ugs.platform.visualizer [2.0.0.2020.4.15.19.4 2.0-20200415 202004151906]
	com.willwinder.ugs.platform.welcome.page [2.0.0.2020.4.15.19.4 2.0-20200415 202004151907]
	com.willwinder.ugs.platform.surfacescanner [2.0.0.2020.4.15.19.4 2.0-20200415 202004151906]
	com.willwinder.ugs.platform.plugin.workflow [2.0.0.2020.4.15.19.4 2.0-20200415 202004151906]
	com.willwinder.ugs.platform.plugin.setup.wizard [2.0.0.2020.4.15.19.4 2.0-20200415 202004151906]
	com.willwinder.ugs.platform.plugin.joystick [2.0.0.2020.4.15.19.4 2.0-20200415 202004151907]
	com.willwinder.ugs.platform.plugin.jog [2.0.0.2020.4.15.19.4 2.0-20200415 202004151906]
	com.willwinder.ugs.platform.plugin.cloud.storage [2.0.0.2020.4.15.19.4 2.0-20200415 202004151907]
	com.willwinder.ugs.platform.gcode.editor [2.0.0.2020.4.15.19.4 2.0-20200415 202004151906]
	com.willwinder.ugs.platform.branding [2.0.0.2020.4.15.19.4 2.0-20200415 202004151905]
	com.willwinder.ProbeModule [2.0.0.2020.4.15.19.4 2.0-20200415 202004151906]
	com.willwinder.GcodeTools [2.0.0.2020.4.15.19.4 2.0-20200415 202004151906]
	com.willwinder.DowelModule [2.0.0.2020.4.15.19.4 2.0-20200415 202004151906]
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading OverrideActionService...
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading MacroService...
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading SendStatusLineService...
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading SettingsChangedNotificationService...
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: SettingsChangedNotificationService$$Lambda$208/0x0000000800c4bc40
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading WindowTitleUpdaterService...
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: WindowTitleUpdaterService$$Lambda$209/0x0000000800c80840
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading PendantService...
INFO [com.willwinder.ugs.nbp.core.services.PendantService]: Starting pendant service
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading ConsoleNotificationService...
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Services loaded!
INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Setting UGP version title.
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy resolver: Gnome
INFO [org.netbeans.core.network.proxy.gnome.GsettingsNetworkProxy]: GSettings system proxy resolver: direct connection
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy reloading succeeded.
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy - mode: direct
INFO [org.netbeans.core.network.proxy.NetworkProxyReloader]: System network proxy: fell to default (correct if direct mode went before)
WARNING [org.openide.filesystems.Ordering]: Not all children in Menu/ marked with the position attribute: [Machine, Visualizer], but some are: [File, Tools, Window, Help]
WARNING [org.openide.filesystems.Ordering]: Found same position 100 for both Toolbars/File and Toolbars/StartPauseStop
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: ConnectDisconnectAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: FirmwareAction
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: Initializing firmware... ...
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config/g2core.json
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config/test_1.json
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config/test_2.json
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config/tinyg.json
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config/grbl.json
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config/smoothieboard.json`

i tried to clear the .usgplatform in my home folder with no success.
ill try with a fresh ubuntu 20.04 install in a VM if I have time

**Comment by winder** [comment]
Try removing the `.ugs` directory as well

**Comment by tbfunk** [comment]
I havent been able to get UGS to run without using sudo.
"./ugsplatform"   always hangs at modules
"sudo ./ugsplatform" works but I have random connection/disconnection errors occasionally

**Comment by bianchifan** [comment]
While UGSPlatform's nightly from Febr.27 was runnin' fine in Ubuntu 19.10 it shows only a weired screen on 20.04

![Bildschirmfoto von 2020-05-16 13-21-50](https://user-images.githubusercontent.com/17491743/82118820-e5c5bd80-9779-11ea-80c2-af11e9ac2a1c.png)
The actual nitely stucks on splash as shown above..:((
Here is the latest log:
[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/4638275/messages.log)

**Comment by ngocminhdao88** [comment]
I am using a nighty build with bundled java on Ubuntu 20.04. By removing .ugs and .ugsplatform at ~, i can run the program.

**Comment by erichVK5** [comment]
I was successfully running a maven built UGS on this netbook with ubuntu 16LTS, but after upgrading to 20.04 I am getting similar errors to others:

OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.ProxyURLStreamHandlerFactory (file:/home/tonia/Source/ugsplatform-linux/platform/lib/boot.jar) to field java.net.URL.handler
WARNING: Please consider reporting this to the maintainers of org.netbeans.ProxyURLStreamHandlerFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

This is happening with the 2.0 platform snapshot, as well as with the August 14, 2019 stable release.

The August 14 release did launch, but it exits with the above error on trying to launch the visualiser screen.

The 2.0 platform release hangs while displaying the launch screen and "loading modules" while trying to start up.

I have tried modifying the ugsplatform.conf file in the 2.0 platform snapshot as described in the mac os security error issue, but this did not work despite trying various combinations for the following local default java directories:

$ ls /usr/lib/jvm/
default-java java-1.11.0-openjdk-amd64 java-11-openjdk-amd64 openjdk-11

Similar issues appear to be afflicting java apps built with certain Java3d versions, i.e. see

http://forum.jogamp.org/JAVA-11-quot-illegal-reflective-access-quot-warning-td4039322.html
https://forum.image.sc/t/java3d-1-6-0-and-the-near-future/19471/2

and some more gory details here:

https://www.docjava.com/pub/document/reports/joglAndJava3d.pdf

Any advice would be appreciated.

Erich.

**Comment by larsskj** [comment]
I'm hit by the same trying to make UGS run on Ubuntu 20.04.2 LTS. I've tested the latest snapshot in both versions - with and without embedded Java. I won't run at all using my own Java - OpenJDK 11.0.10, but it does run using the embedded Java. I tested 2.0.7-SNAPSHOT.

My last attempt looked like this:

![ugs-screenshot](https://user-images.githubusercontent.com/7857959/107498677-65ab7780-6b94-11eb-97c1-4c76d1357616.png)

It ran for a while, then crashed with this message:

```
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.ProxyURLStreamHandlerFactory (file:/opt/ugsplatform-linux-2.0.7-SNAPSHOT/platform/lib/boot.jar) to field java.net.URL.handler
WARNING: Please consider reporting this to the maintainers of org.netbeans.ProxyURLStreamHandlerFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f81af4b152d, pid=125242, tid=125306
#
# JRE version: OpenJDK Runtime Environment (13.0.1+9) (build 13.0.1+9)
# Java VM: OpenJDK 64-Bit Server VM (13.0.1+9, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [iris_dri.so+0xc0d52d]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/lars/core.125242)
#
# An error report file with more information is saved as:
# /home/lars/hs_err_pid125242.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-build/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
/opt/ugsplatform-linux/bin/../platform/lib/nbexec: line 425: 125242 Aborted                 (core dumped) "/opt/ugsplatform-linux/jdk/jdk-13.0.1+9-jre/bin/java" -Djdk.home="/opt/ugsplatform-linux/jdk/jdk-13.0.1+9-jre" -classpath "/opt/ugsplatform-linux/platform/lib/boot.jar:/opt/ugsplatform-linux/platform/lib/org-openide-modules.jar:/opt/ugsplatform-linux/platform/lib/org-openide-util.jar:/opt/ugsplatform-linux/platform/lib/org-openide-util-lookup.jar:/opt/ugsplatform-linux/platform/lib/org-openide-util-ui.jar" -Dnetbeans.running.environment=gnome -Dnetbeans.dirs="/opt/ugsplatform-linux/etc:/opt/ugsplatform-linux/ide:/opt/ugsplatform-linux/bin:/opt/ugsplatform-linux/ugsplatform:/opt/ugsplatform-linux/extra:/opt/ugsplatform-linux/java:/opt/ugsplatform-linux/platform:" -Dnetbeans.home="/opt/ugsplatform-linux/platform" '-Xms64m' '-Xverify:none' '-Dsun.java2d.noddraw=true' '-Dsun.awt.noerasebackground=true' '-Dnetbeans.indexing.noFileRefresh=true' -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="/home/lars/.ugsplatform/2.0.7-SNAPSHOT/dev/var/log/heapdump.hprof" org.netbeans.Main --cachedir "/home/lars/.ugsplatform/2.0.7-SNAPSHOT/dev/var/cache" --userdir "/home/lars/.ugsplatform/2.0.7-SNAPSHOT/dev" "--branding" "ugsplatform" 0<&0
```
Deleting `~/.ugs` and `~/.ugsplatform` solves the problem for a while - but also deletes all my settings.

**Comment by breiler** [comment]
Please try the latest nightly build, I have upgraded to the latest OpenGL library (or version 2.0.13 when it get released)
