### ISSUE TITLE
joystick doesn't work if reconnected

### ISSUE THREAD

**Issue by jon-daemon** [winder/Universal-G-Code-Sender#1396]
## Problem description 
I tried the nightly build and it works fine with a gamepad joystick. The porblem occurs if I disconnect the joystick or start UGS before connecting it. The joystick is working only if its connected before starting UGS. Is this normal?

### Steps to Reproduce the Problem
1. Connect the joystick
2. Open UGS (joystick is working fine)
3. remove joystick and reconnect. It stops working
or
1. Open UGS
2. Connect the joystick. Joystick is not working

#### Version
UGS Platform 2.0 - Nightly Build Apr 19, 2020

#### Operating system
Linux Mint

#### Platform
GRBL 1.1f

**Comment by abdset** [comment]
Sounds like a bug that needs to be fixed.

**Comment by mmosimann** [comment]
I'm facing the same problem using a xBox wireless joystick.

**Comment by breiler** [comment]
@mmosimann does this problem still exist in version 2.0.12?

**Comment by breiler** [comment]
Closing as this was fixed in #1927
