### ISSUE TITLE
UGS sending G-code to the machine in inch but the CAD project done in mm

### ISSUE THREAD

**Issue by midosayed0** [winder/Universal-G-Code-Sender#1402]
Problem description 
UGS sending G-code to the machine in inch but the CAD project done in mm

**Comment by breiler** [comment]
UGS will send the gcode as is and will not change units. Check your CAD/CAM settings. In the beginning of your gcode file you can check for G20 (inches) or G21 (mm).

If I am going to be able to help further I need the version of UGS, version of controller and a sample of the Gcode program (just like we asked for in the issue template when you created the issue).

**Comment by whitetd** [comment]
the inch /metric setting is more for jog control, and correct
visualization, not to convert your gcode..
