### ISSUE TITLE
UGS 2.0 doesn't launch (Fedora 32)

### ISSUE THREAD

**Issue by DynamiteStick** [winder/Universal-G-Code-Sender#1405]
## Problem description 
UGS 2.0 Doesn't launch on my fedora 32 machine. I'm fairly new to Linux so it could be I'm just inexperienced

### Steps
1. change directory to ugsplatform/bin
2. run the command ugspaltform

### Expected Behavior
UGS launches

### Actual Behavior
Nothing happens

#### Version

UGS Platform 2.0

#### Operating system

Linux Fedora 32

#### Platform

GRBL 1.1

**Comment by breiler** [comment]
Are you using the latest nightly build with bundled Java from here?
https://github.com/winder/Universal-G-Code-Sender#downloads

Could you post the log file:
https://github.com/winder/Universal-G-Code-Sender/wiki/Configuration#log-files

**Comment by cornnatron** [comment]
Its your run command lol
It should be ugsplatform not ugspaltform hihi

**Comment by breiler** [comment]
Closing as the user hasn't responded
