### ISSUE TITLE
Freezing when starting ugsplatform

### ISSUE THREAD

**Issue by IliaNoz** [winder/Universal-G-Code-Sender#1407]
When I'm trying to launch ugsplatform its freezes on "Loading module services.." 
![image](https://user-images.githubusercontent.com/17799522/84590074-76a8bb00-ae44-11ea-8a40-4df26e370ec6.png)
I'm using PopOs(ubuntu based) 
openjdk version "1.8.0_252"

messages.log file looks like this

> INFO [com.willwinder.ugs.nbp.core.lifecycle.startup]: Loading LocalizingService...
INFO [com.willwinder.universalgcodesender.utils.SettingsFactory]: Log location: /home/ilianoz/.ugs/UniversalGcodeSender.json
INFO [com.willwinder.universalgcodesender.utils.SettingsFactory]: Loading settings.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Applying settings.
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: PortAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: ConfigureFirmwareAction$$Lambda$197/0x00000008402be440
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: ResetZCoordinateToZeroAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: ConnectDisconnectAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: CheckModeAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: RunFromAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: BaudRateAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: ResetXCoordinateToZeroAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: ResetCoordinatesToZeroAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: PauseAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: OutlineAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: UnlockAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: SoftResetAction
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Adding UGSEvent listener: FirmwareAction
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: Initializing firmware... ...
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config/g2core.json
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config/test_1.json
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config/test_2.json
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config/tinyg.json
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config/grbl.json
INFO [com.willwinder.universalgcodesender.utils.FirmwareUtils]: /resources/firmware_config/smoothieboard.json

**Comment by breiler** [comment]
Duplicated by #1391
