### ISSUE TITLE
Slow on Raspberry Pi 3 with bundled JDK

### ISSUE THREAD

**Issue by avarakin** [winder/Universal-G-Code-Sender#1411]
## Problem description 

I installed the latest nightly RPI installer with bundled Java 13 and it seems to be much slower than Java 8, which comes with Linux. Also, it seems that it consumes more memory.

#### Version
Latest nightly build

#### Operating system
  Ubuntu 20.04 32 bit on RaspberryPI 3 with Gnome DE

#### Platform
  GRBL 1.1

**Comment by breiler** [comment]
Do you have any numbers and methods that made you come to this conclusion?

**Comment by avarakin** [comment]
I am seeing startup time of about 30s for  Java 8 of Ubuntu 20.04 and about 55s for bundled Java 13. 
It was measured after starting/stopping 3 times in a row.

**Comment by Utkarsh-vishnoi** [comment]
It would help if you tell us which model of PI are you using?
I use raspbian which is quite good on Raspberry Pi 3 Model B.
There can be a number of reasons for slow response time.

1. Your PI doesn't have enough empty memory.

**Comment by breiler** [comment]
Downgraded to jdk8 by default in the rpi-package.
