### ISSUE TITLE
Bluetooth Port (/dev/rfcomm0) not showing up in the ports list

### ISSUE THREAD

**Issue by Utkarsh-vishnoi** [winder/Universal-G-Code-Sender#1423]
## Problem description 
The application can only detect the wired serial communication port but not the bluetooth serial communication port.
In my case it's /dev/rfcomm0. I have modified my CNC setup to work over bluetooth which is working like a charm from arduino serial console. but with the UGS the rfcomm0 port isn't showing up. 

### Expected Behavior
When I try to refresh the ports list, it doesn't show the bluetooth serial port (/dev/rfcomm0) but the port is visible in the arduino serial console. Also when I send `$$` in arduino IDE's serial console, I get the expected output. It will be really helpful to just communicate over the bluetooth serial port as well from the application.

### Actual Behavior
The bluetooth serial port is not detected by the application

#### Version
UGS Platform 2.0 - Nightly Build Aug 14, 2019

#### Operating system
Raspbian on the Raspberry PI

#### Platform

GRBL 1.1f on Arduino Uno (Works completely fine on wired serial communication)

**Comment by breiler** [comment]
Did you get it working?

**Comment by Utkarsh-vishnoi** [comment]
Yes, I was always using dropdown for the ports. If I enter the port name manually, I was able to get it to work.
