### ISSUE TITLE
Raspberry Pi Install Instructions need updating

### ISSUE THREAD

**Issue by MonkeyManGuy** [winder/Universal-G-Code-Sender#1433]
## Problem description 
While following the Rasp Pi instructions step 3 includes options that do not appear on Raspberry Pi. We are looking for "7 Advanced Options"->"A7 GL Driver"->"G3 GL" (in my case)

The reality of the current OS for Pi is that A8 Is for the GL Driver, however when on this page "G3 GL" is not an option. Please see the picture attached:

### Expected Behavior
Progress through step 3 of install instructions and locate all categories and options described as nessacary in the instructions.

### Actual Behavior
Step 3 contains a category level deveation from the current operating system release, on the subsequent page the needed option is not listed.

### Steps to Reproduce the Problem
<!-- Example:
Attempt an install while using the instructions found here: https://github.com/winder/Universal-G-Code-Sender/wiki/Raspberry-Pi

#### Version
Unfortunately this bug prevents install of UGS entirely

#### Operating system
Raspbian GNU/Linus 10 (buster)

#### Platform
Raspberry Pi, without being able to install UGS the machine type is not yet relevant as they have not been connected to each other.

![117092280_287325749037500_3559039650682862260_n](https://user-images.githubusercontent.com/56900581/89474140-c1fb8d80-d752-11ea-99af-8ed6ab45c25e.jpg)
![117080589_792895034784972_4599216761039160083_n](https://user-images.githubusercontent.com/56900581/89474143-c32cba80-d752-11ea-80ac-5a9d9cee1998.jpg)

**Comment by MonkeyManGuy** [comment]
![117092280_287325749037500_3559039650682862260_n](https://user-images.githubusercontent.com/56900581/89474158-ca53c880-d752-11ea-9b91-a925e1c6d709.jpg)
![117080589_792895034784972_4599216761039160083_n](https://user-images.githubusercontent.com/56900581/89474160-cb84f580-d752-11ea-87bb-b64b8f190431.jpg)

**Comment by zoominbc** [comment]
I believe that the G3 option is supported for a Pi 3 but not for a Pi 4. The G2 option Fake KMS does work.

**Comment by MonkeyManGuy** [comment]
> I believe that the G3 option is supported for a Pi 3 but not for a Pi 4. The G2 option Fake KMS does work.

So this means Pi 4 users must choose the G1 option?

**Comment by sepiroth887** [comment]
use nightly as of [d432d5e](https://github.com/winder/Universal-G-Code-Sender/commit/d432d5ec3891f8347a457e1ce13c0b4a244a9c37)  which should not require any changes in Pi 4 gpu drivers. (tried with software and FakeKMS)

**Comment by breiler** [comment]
I have updated the install instructions. Though only for 32-bit systems as that was the only one I could get to work reliably.
