### ISSUE TITLE
User interface broken

### ISSUE THREAD

**Issue by itsharrie** [winder/Universal-G-Code-Sender#1436]
## Problem description 
The user interface does not initiate properly when starting up ugsplatform. 

![Screenshot from 2020-08-17 15-47-45](https://user-images.githubusercontent.com/17196784/90403809-c6ed0500-e0a1-11ea-84f7-b146208b2b27.png)

### Expected Behavior
Properly show the window.

### Actual Behavior
UI elements are seemingly randomly refreshed when clicking anywhere on the window.

### Steps to Reproduce the Problem
Install openjdk-8-jre and openjdk-8-jre-headless, remove all other java runtimes.
Open ugsplatform 
 
#### Version
Stable version 2019-08-14 or nightly version 2020-08-10 (same problem)

#### Operating system
Linux Mint 20

#### Platform
n/a

**Comment by breiler** [comment]
Did you try the version with bundled java from here:
https://github.com/winder/Universal-G-Code-Sender#downloads

**Comment by breiler** [comment]
Closing as there was no response from user.
