### ISSUE TITLE
Software limit switch, and spindle ON/OFF

### ISSUE THREAD

**Issue by angel6700** [winder/Universal-G-Code-Sender#144]
Hello,

I think It could be helpful to have some limits defined in software.
So, hard limits are important for the cnc machine, but software limits can be useful for the working piece, and can be different from every day.

Also, could be possible to add a spindle ON /OFF (M3/M5) button in the machine control tab? 

I hope someone else could find these ideas interesting and they are not very hard to implement.

Regards.

**Comment by jahnj0584** [comment]
are soft limits not already added? Can this be closed?

**Comment by jahnj0584** [comment]
I guess not :P

**Comment by breiler** [comment]
Closing this as it's available in the hardware (GRBL 1.1) and is visualized in UGS Platform when active.
