### ISSUE TITLE
UGS platform wont open in windows 7 with java 8

### ISSUE THREAD

**Issue by ptcruiserx3** [winder/Universal-G-Code-Sender#1440]
i can open classic 1.09 but not platform version

anyone know why?

**Comment by breiler** [comment]
It depends what error you get and which version of UGS platform you are trying. 

Did you download the latest platform from here?
https://github.com/winder/Universal-G-Code-Sender#downloads

**Comment by ptcruiserx3** [comment]
No error
Just wont open

**Comment by ptcruiserx3** [comment]
Yes i downloaded latest platform version

**Comment by breiler** [comment]
Can you post the log file:
https://github.com/winder/Universal-G-Code-Sender/wiki/Configuration#log-files

**Comment by ptcruiserx3** [comment]
i have windows 7 32bit and when i try to run the exe file in the bin
folder for platform it proceeds to try to install but when its done it
gives me a prompt saying this version is not compatible with my OS
please check if 32bit or 64bit

the file is 32bit that i opened and my pc is 32 bit

i dont know how to do a log file

**Comment by ptcruiserx3** [comment]
well i downlaoded 3 diff times and ran each file and on the 3rd time
it actually worked

question where dioes it install the pogram or do i have to run the
downloaded exe file every time which takes a long long time to load?

**Comment by ptcruiserx3** [comment]
Hi one more issue
When i open ugs platform ..or ugs 2.0"it opens fine but,when i try to
connect it closes

Any ideas why?

**Comment by ptcruiserx3** [comment]
Which version ugs has least issues?
Having problems

1. When i have it in inches and move .100 step..it moves like .020
If i close ugs and reopen it then works ok...this happens every time i open
ugs....u have to close and reopen every time

2. When toolpath is over on about 90% of the time ugs still thinks profram
is running and mach control is greyed out...i have to close and reopen to
control cnc

**Comment by breiler** [comment]
For your first question there are so many ways this problem can originate from and it's impossible to answer without knowing exactly which version and variant of UGS you are using (is shown in the application title) or controller (GRBL 1.1h?).

So I assume you are running the latest UGS Platform and GRBL controller, start with:
1. Check your step settings in GRBL and make sure settings $100, $101 and $102 are given in "steps/mm" (https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#100-101-and-102--xyz-stepsmm)
2. Make sure your maximum feed rate settings doesn't exceed the machine limits: $110, $111, $112 (https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#110-111-and-112--xyz-max-rate-mmmin)

Your second question, also dependent on which version of UGS and GRBL, but at least some stuff you could check:
1. It could mean that you have an unstable connection to the Arduino. Make sure you have a properly shielded USB cable to the arduino.
2. If I recall correctly this problems could occur with older versions of GRBL, make sure you are running the latest version.

**Comment by ptcruiserx3** [comment]
I use grbl 1.1

Also the .100 step issue is not grbl issue...its ugs issue

It happens every time i open ugs...i have to close and reopen ugs to move
proper step

**Comment by ptcruiserx3** [comment]
And yes connection / ugs communication could be issue...90% of the time ugs
will not connect to my machine

**Comment by ptcruiserx3** [comment]
I use ugs 1.09 ... suppose to be most stable version

**Comment by ptcruiserx3** [comment]
one other question

using the same exact gcode file

why would UGS 1.09 run a gcode file and UGS 2.0 would not ?

i made a simple gcode toolpath using a fanuc post processor and in UGS
it shows fine in visual screen in ugs but when i run same toolpath in
ugs 2.0 it wont even visualize..it says doesnt recognize commands

is ugs 1.09 more lenient in running generic post priocessors?

**Comment by breiler** [comment]
May we have the gcode file so that we can have a look?

The gcode parser / visualizer in UGS 2.0 has added a lot more features and is a bit more sensitive to not correctly formatted gcode. 

Again, it would help a lot if you could locate the log file and attach it here in a post:
https://github.com/winder/Universal-G-Code-Sender/wiki/Configuration#log-files

**Comment by ptcruiserx3** [comment]
Thanks
I cant attach file ..its on a diff pc

So if the visualizer in 1.09  shows toolpath ok with no errors...it
should run ok on my cnc?

Whereas ...in 2.0 the toolpath wont run since there are errors?

**Comment by breiler** [comment]
This is impossible to answer without either logs or example gcode file.

**Comment by ptcruiserx3** [comment]
Ok so apparently just because ugs visualizer shows ok does not mean it will
actually run toolpath

Correct?

**Comment by breiler** [comment]
Without logs, sample files, the error message or even an exact version (build date) of the program there are simply too many ways things can go wrong for me to just guess. We can't help you if you don't give us something to work with.

**Comment by ptcruiserx3** [comment]
run these in UGS 1.09 and 2.0 and you will see what happens

**Comment by breiler** [comment]
Nothing was attached, I think that you need to add it as an attachment via github.

**Comment by ptcruiserx3** [comment]
dont know how and dont have time for that sorry

i attached it in email..if you want to include and email i can send it
to that would be good

i try attach again

**Comment by breiler** [comment]
Send it to joacim.breiler@gmail.com

**Comment by breiler** [comment]
The Gcode you've generated seems to not be GRBL compatible. I'm testing with **UGS Platform 2.0.6**

When I open the file it says:
![image](https://user-images.githubusercontent.com/8962024/95224697-49b95300-07fb-11eb-8e31-487e6123689a.png)

If you open the file and then use the editor (File -> Edit Gcode File...) you will get some more hints on what could be wrong:
![Screen Shot 2020-10-06 at 17 33 40](https://user-images.githubusercontent.com/8962024/95223783-4376a700-07fa-11eb-8475-a74839070a5e.png)

* The slashes in the beginning of the line N104, N106 and N108 must be removed.
* The G0 and G80 needs to be on separate lines

Now it renders ok:
![Screen Shot 2020-10-06 at 17 45 05](https://user-images.githubusercontent.com/8962024/95225127-baf90600-07fb-11eb-9229-ef9588ede84f.png)


But even after fixing those problems GRBL will respond with an error:
```
[Error] An error was detected while sending 'N104G91G28Z0.': (error:31) Axis words found in block when no command or current modal state uses them. Streaming has been paused.
[Error] Error while processing response <An error was detected while sending 'N104G91G28Z0.': (error:31) Axis words found in block when no command or current modal state uses them. Streaming has been paused.>
```

Check your settings in your CAM software and make sure it can generate GCode for GRBL.

**Comment by ptcruiserx3** [comment]
open it in UGS 1.09

it runs fine there

**Comment by ptcruiserx3** [comment]
hi again
i installed ugs platform on one of my computers and i have to say it
takes literally 5 minues to load every time and also where the heck
are  the jog menus/options

i cant find a way to jog my machine with that version

v 1.09 has jog....does platform not have jog interface?

**Comment by ptcruiserx3** [comment]
i think i found the job menu..for some reeason it wasnt there

i uninstalled and reinstalled platform and now i see it

**Comment by paullahaye** [comment]
![UGS v2 0 7 32bit Install Error - Java 281](https://user-images.githubusercontent.com/70071558/108103603-2bd8e600-7058-11eb-9932-f137ce93c0fd.png)
Hi. I'm having the same issue trying to install v2.0.7 on a 32bit system.
I downloaded the zip several times, tried rebooting, update java8 from 271 to 281 to no avail.
UGS v2.0 nightly aug 14, 2019 runs fine
Any help?

**Comment by breiler** [comment]
@paullahaye this was resolved quite recently in #1506. It is only available in the latest nightly build so far and will also become available in the next version 2.0.8.

**Comment by paullahaye** [comment]
wow. talk about a quick answer. Thank you very much for doing so

**Comment by ptcruiserx3** [comment]
hi
the current UGS does not work with Vista? why not?

also i am using an older UGS on my win7 laptop i think 1.09 and every
time my gcode program ends and project is done the controller greys
out so i can not jog machine

i have to always close and restart ugs to enable the jog controller

this is very annioying

can you fix?

**Comment by breiler** [comment]
@ptcruiserx3 the UGS 1.0.9 version is from 11 Nov 2015, there has been ~2200 commits since then. The problem is most likely fixed.

Microsoft stopped supporting Vista in 2017, a bit hard to test. I don't see any reason why it shouldn't work. I suspect that the problem you are experiencing has been fixed as previously mentioned in #1506 which is available in the nightly build and in the next version of UGS (2.0.8). But as you don't specify what happens when you try to open UGS there is no way to know...

**Comment by ptcruiserx3** [comment]
i dont see nightly builds anymore

can you send me link to nightly builds?

**Comment by breiler** [comment]
https://github.com/winder/Universal-G-Code-Sender#downloads

**Comment by ptcruiserx3** [comment]
here is what it shows when i opn the exe file for ugs current version
in windows vista 32bit

**Comment by ptcruiserx3** [comment]
thanks
ill try the nightly builds
