### ISSUE TITLE
Visualizer is pixellated when running on windows with OpenJDK

### ISSUE THREAD

**Issue by NickBeeuwsaert** [winder/Universal-G-Code-Sender#1442]
## Problem description 
When running on Windows 10 with OpenJDK, the visualizer is very pixellated. When run with JRE installed, the visualizer looks fine.

OpenJDK downloaded from here: https://jdk.java.net/15/
JRE downloaded from here: https://www.java.com/en/download/windows-64bit.jsp

### Expected Behavior
The visualizer doesn't look pixellated

### Actual Behavior
The visualizer is pixellated when running with OpenJDK

### Steps to Reproduce the Problem
1. Use Windows 10
2. Download and extract OpenJDK from https://jdk.java.net/15/
3. Update etc/ugsplatform.conf to point to the extracted JDK
4. Run UGS, and open the visualizer tab

#### Version
UGS Platform 2.0 - Nightly Build September 19, 2020
UGS Platform 2.0 - August 14, 2020

#### Operating system
Windows 10, Resolution 1920x1080, display scaling at 150%

#### Other
Running with the JRE:
<img width="563" alt="jre" src="https://user-images.githubusercontent.com/491083/93716114-3f2c6780-fb33-11ea-8d03-c65c7f7db687.png">
Running with OpenJDK and setting sun.java2d.uiScale=0.5
<img width="659" alt="OpenJDK uiscale" src="https://user-images.githubusercontent.com/491083/93716115-3fc4fe00-fb33-11ea-932a-dfc2a1e299ad.png">
Running with just OpenJDK
<img width="550" alt="openjdk" src="https://user-images.githubusercontent.com/491083/93716116-3fc4fe00-fb33-11ea-8137-6fdbd38e68cb.png">

**Comment by breiler** [comment]
Won't fix, we bundle a specific version of Java which is tested on each platform.
