### ISSUE TITLE
Updating the "About"-information of the project.

### ISSUE THREAD

**Issue by breiler** [winder/Universal-G-Code-Sender#1444]
I would like to se the about-information updated to make it more search friendly (don't have access doing this myself).

The description should say something like "A cross-platform G-Code sender for GRBL, Smoothieware, TinyG and G2core"

Additional tags should be added:
* tinyg 
* g2core 
* smoothieware
* gcode-sender
* gcode-visualizer

**Comment by winder** [comment]
Good idea, updated.
