### ISSUE TITLE
When I open UGS(with GRBL) and click "connect" the console begins downloading but it never stops. It seems as if it is just loading the same thing repeatedly and I can never move on because the console isn't finished "loading."

### ISSUE THREAD

**Issue by kaeleighgray** [winder/Universal-G-Code-Sender#1446]
## Problem description 
 Upon opening the UGS platform and connecting to CNC machine (with GRBL), the console lists the same codes repeatedly and in return no other tasks can be completed since the console is still "loading."

### Expected Behavior

  1.
  1.
  1.

**Comment by breiler** [comment]
What version of GRBL, UGS and operating system are you using. Could you give a sample of the log messages that are being sent.
