### ISSUE TITLE
Open Recent Files option (Feature Request)

### ISSUE THREAD

**Issue by khturnings** [winder/Universal-G-Code-Sender#1463]
Feature request
Can you add a item to the file drop down menu to show a list of recently opened files.

Problem description 
When working on a batch of jobs over a few days each time I need to open a file I need to scroll through all my Gcode files in the directory they are stored in.

Expected Behaviour
Use File -> Open Recent -> List last xx number of jobs opened.

Actual Behaviour
Currently not available

**Comment by winder** [comment]
The start page has a recently opened files tab.

**Comment by khturnings** [comment]
So it does - I have never really used the tabs on the start page.
Will close this as you have plenty of other more important issues to resolve.
