### ISSUE TITLE
Bug in Setup Wizard

### ISSUE THREAD

**Issue by henfri** [winder/Universal-G-Code-Sender#1467]
## Problem description 
Using the latest nightly (2.0.6) there seems to be a Bug in the setup wizard.

### Expected Behavior

1. Drive X 1mm
2. Enter actual distance
3. Steps/mm are calculated
4. Steps/mm are entered and updated
5. Drive X nine times 1mm (for a total of 10)
6. Check Distance and Go to 2 if needed

### Actual Behavior
1. Drive X 1mm
2. Enter actual distance
3. Steps/mm are calculated
4. Steps/mm are entered and updated
**Now the actual X jumps from 1mm to e.g. -6.7mm. Why?**
Better would be to set keep the current position (1mm) or to set the current position to the new "0mm".

### Steps to Reproduce the Problem
see above

#### Version
  UGS Platform 2.0 - Nightly Build Nov 6th 2020.

#### Operating system
  Windows 10

#### Platform
  GRBL 1.1f

**Comment by breiler** [comment]
I've noticed this on occasions when developing and didn't find a reliable way to reproduce it or to fix the problem. 

I am just guessing here, this could happen if the internal state in GRBL is keeping track of the number of steps it has taken and not the actual position. If the step size configuration changes the number of steps would be recalculated to a new position.

This is duplicated by #1424, so I'm closing it.
