### ISSUE TITLE
Misure non corrispondono....

### ISSUE THREAD

**Issue by Duval13** [winder/Universal-G-Code-Sender#1478]
Buongiorno a tutti, ho questo problema, dopo che ho creato dei G-Code (es. Aspire) salvo il lavoro e lo apro con UGS trovo il G-Code con le misure errate ossia molto più piccolo, potete Aiutarmi dove sbaglio,Grazie

Armando

**Comment by breiler** [comment]
Could you post the Gcode file that is wrong?

I'm suspecting you are missing G20 (inch) or G21 (mm) in the beginning of the file.
