### ISSUE TITLE
Small size drawed

### ISSUE THREAD

**Issue by ladyfirst2010** [winder/Universal-G-Code-Sender#1479]
Hi,

I export .gcode from inkscape then run with UGS but it's very small image drawed.

Any suggestion for me to fix it please ?

**Comment by ladyfirst2010** [comment]
Example gcode :

M3
G90
G21
G1 F1000
G1  X2.1335 Y29.4418
M5 S90
G4 P0.5
G1 F500.000000
G1  X56.7502 Y29.4418
G1  X56.7502 Y2.7735
G1  X2.1335 Y2.7735
G1  X2.1335 Y29.4418
M3
G4 P0.5
G1 F1000
G1 X0 Y0

**Comment by breiler** [comment]
I'm not sure what you are expecting, but the gcode is a rectangle that is approximately 56x30mm. 
What was the expected size?

**Comment by ladyfirst2010** [comment]
Hi.

Thanks for your reply. I expect it much bigger because I draw it in A4
size.
Dont know what cause the problem, Inkscape or the MI extension.

Vào Th 3, 24 thg 11, 2020 lúc 23:55 Joacim Breiler <notifications@github.com>
đã viết:

**Comment by breiler** [comment]
My guess is it's in the MI extension, you will need to check its manual.
I'm closing this issue as it is a bit beyond the scope of UGS. 

Good luck!

**Comment by ladyfirst2010** [comment]
Thank a lot for your help

Vào Th 4, 25 thg 11, 2020 lúc 13:35 Joacim Breiler <notifications@github.com>
đã viết:
