### ISSUE TITLE
"Jog Here" Command not working - UGS - BobsCNC Evo4

### ISSUE THREAD

**Issue by bdrayer21** [winder/Universal-G-Code-Sender#1500]
**Describe the bug**
When I right mouse click in the visualizer and go to "coordinates" and then select "jog here" I get an error message.

Error Message: 
An error was detected while sending '$J=G20G90G1X______Y______': (error:16) Jog command has no '=' or contains prohibited g-code. Streaming has been paused.

**To reproduce**
1. Go to "visualizer"
2. Right mouse click location you would like to view coordinates
3. Scroll down to "coordinates X=xx.xxxx Y=xx.xxxx
4. Click "jog to here" from other pop-up window.
5. Get error

**Expected behavior**
I'd expect that when I select "jog to here" the machine would go to those coordinates. This would assist in setting my z when setting up a project to cut. 

**Screenshots**
![image](https://user-images.githubusercontent.com/76694574/103230930-97c68a00-4904-11eb-94f6-9b2374ef644b.png)
![image](https://user-images.githubusercontent.com/76694574/103231186-38b54500-4905-11eb-882b-305acd6a7302.png)

**Version**
Product Version: Universal Gcode Platform 20190814

**Hardware**
Bobs CNC Arduino Board - GRBL 

**Operating system (please complete the following information):**
 System: Windows 10 version 10.0 running on amd64; Cp1252; en_US (ugsplatform)

**Additional context**
Java: 1.8.0_261; Java HotSpot(TM) 64-Bit Server VM 25.261-b12
Runtime: Java(TM) SE Runtime Environment 1.8.0_261-b12

If I missed any info, please let me know. 

Thanks,
bdrayer21

**Comment by breiler** [comment]
Never seen that error. You are running an old version of UGS, could you try if the problem still exists in the latest version 2.0.7

**Comment by bdrayer21** [comment]
@breiler - Thanks, I wasn't aware that I didn't have the most up to date version (had tried to "update" from the version of UGS I had, but it said it was all up to date. Just installed 2.0.7 version and the Jog Here command seems to work. Thank you!
