### ISSUE TITLE
I can´t run the *.exe file

### ISSUE THREAD

**Issue by Laufmischel** [winder/Universal-G-Code-Sender#1510]
Hi, I would like to run the software 2.0.7. "ugsplatform64.exe" and got the message
"cannot be run from folder that contains non-ASCII characters in path"

OS: WIN10

can you help me?

**Comment by breiler** [comment]
What is the current directory path?

**Comment by Laufmischel** [comment]
D:\WISAMIC Fräsmaschine\Software\UGS Platform\Neuer Ordner (2)\ugsplatform\bin

**Comment by breiler** [comment]
I expect it to work with both `ä`, `(` and `)`-characters in your folder names, but those are the only ones that could cause this error. Try removing the parentheses first otherwise try removing the `ä`.

**Comment by Laufmischel** [comment]
heureka, appr. 10h are now finished, grrrrrrrr :-)

the software is running!!!!  1000 Thanks 👍
