### ISSUE TITLE
an error was detected while sending '0s30':

### ISSUE THREAD

**Issue by Jeeva2000** [winder/Universal-G-Code-Sender#1512]
While uploading gcode file to the UGS it shows this error 
![cnc error](https://user-images.githubusercontent.com/60503222/104408066-2edc4480-5589-11eb-99e0-abd5a640d683.png)

**Comment by breiler** [comment]
What software (and plugin) are you using for generate the gcode? (Inkscape + MI)
What controller and firmware version are you using? (GRBL 1.1h?)

The `0S30.00` is not a valid GRBL gcode so the controller does not know how to handle it. Not much we can do in UGS.

This error has been mentioned before #1313, #1181, #705, #603
Have a look at this post and see if it helps you: https://github.com/winder/Universal-G-Code-Sender/issues/603#issuecomment-383352765
