### ISSUE TITLE
Update Install/Run Instructions for Pi/Linux

### ISSUE THREAD

**Issue by Miniclubbin** [winder/Universal-G-Code-Sender#1514]
I was unable to get UGS to run on my Pi without installing the bundled version. Please add lines in the how to guide for install on pi/linux:

Open terminal and run the following commands:
```
sudo usermod -a -G dialout pi
mkdir ugs
cd ugs
#use command below with link address from downloads page for your platform
wget https://ugs.jfrog.io/ugs/UGS/v2.0.7/ugs-platform-app-pi.tar.gz   
#use command below to unzip the file downloaded above
tar zxvf ugs-platform-app-pi.tar.gz
```
Navigate in file explorer to: /home/pi/ugs/ugsplatform-pi/bin/ugsplatform and run 'ugsplatform'. 
Create a desktop shortcut by selecting the file and clicking 'create link' from the edit menu.

**Comment by breiler** [comment]
Done, thanks
