### ISSUE TITLE
Notice of units mismatch bug in UGS probing Module

### ISSUE THREAD

**Issue by SienciLabs** [winder/Universal-G-Code-Sender#1518]
Hi guys, Chris here. There has been a longstanding issue that we've heard of from LongMillers with using the touchplate module in UGS where, after probing, the bit will crash into the spoil board after clicking "Return to zero". Finally we think we've located the source of this problem down to how unit mismatch is being handled in UGS. This problems seems to span all UGS versions that we've tested so far.

To replicate the issue, set jogging units to 'inches' and probing units to 'mm' and then probe as normal (usually we use the XYZ probe function). Upon successful probe completion, you should notice that bit offsets on the DRO look correct for mm, but in actuality they've been set in inches, and when you click to return to zero the bit will plunge far down.

For reference, to use our touchplates you start the bit at a circle relatively aligned with the final cutting origin that's engraved into the top of a square with a milled L-shaped hardstop on the underside (https://sienci.com/product/touch-plate/). Starting the bit about 5mm off the top of a 15mm thick block means that the end result is the machine trying to plunge about 20 inches into the material rather than returning to zero which is 20mm below.

Looking at the console there seems to be a hiccup in how the code is executing:
![image](https://user-images.githubusercontent.com/22357995/105089201-cef30b80-5a6a-11eb-8b68-d527be818726.png)

Every probe command is being followed up by a revert to **G91** and **G20** in case the probing were to fail, but since the line "**G10 L20 P1 X-2.035Y-0.215Z21.12**" doesn't contain a G21 where the line previous is "**G91 G20**", the WCS offset is being set in inches rather than mm.

If there is any other context needed to test or solve this issue, then I'll be sure to reply promptly. If there is an issue in how the code is being handled on our end then also let me know, as we've been able to replicate on multiple machines ourselves as well as across many of our user group.

**Comment by breiler** [comment]
Thanks for the report, sorry for taking so long to fix it...

We are now using the same units as throughout the application so it should no longer mix up the units.
