### ISSUE TITLE
Outline doen't update when model orientation changes

### ISSUE THREAD

**Issue by federicort** [winder/Universal-G-Code-Sender#1524]
I import a model, if I use straight away the outline function it works perfectly, but if I decide to rotate the model in any direction, when I press outline, it will do it with the original orientation of the model.
I don't know if is meant to work that way, but the logical thing for me is that if I change the orientation of the model when outlining it should do it with the updated orientation.

Im using:
*Windows 10 version 10.0 running on amd64; Cp1252; en_US (ugsplatform)
*Universal Gcode Platform 20201202
*OpenJDK Runtime Environment 13.0.1+9

**Comment by breiler** [comment]
Ah, thanks. No it isn't supposed to work that way and needs to be fixed.
