### ISSUE TITLE
Support for Inventables "gCarvin" GRBL fork

### ISSUE THREAD

**Issue by jaikdean** [winder/Universal-G-Code-Sender#1529]
**Is your feature request related to a problem? Please describe.**
The Inventables Carvey runs on a custom version of GRBL called gCarvin. Because this string isn't recognised, UGS things GRBL hasn't finished booting.

**Describe the solution you'd like**
UGS accept `gCarvin` as a GRBL version string prefix, alongside `Grbl`, `CarbideMotion` and `GrblHAL`.

**Describe alternatives you've considered**
None.

**Additional context**
<img width="588" alt="Screenshot 2021-02-03 at 14 39 46" src="https://user-images.githubusercontent.com/348408/106762425-ba4b7180-662d-11eb-9f7e-54f44ebb14d5.png">

**Comment by breiler** [comment]
I tried loading gcarvin on my Mega and made the changes in UGS. It looks like it is working, but I am not able to test all features so use with care. I am just waiting for the build server to complete.
