### ISSUE TITLE
Decrease the Joystick step size limit to 0.001 for inch mode

### ISSUE THREAD

**Issue by htrantx** [winder/Universal-G-Code-Sender#1537]
when using joystick feature the step size for the machine is limited to 0.01, which is fine for mm but not for inch mode.

Changing the step size with Machine/Jog/Stepsize has no effect on the joystick action

Please change the joystick limit to 0.001 for inch mode

**Comment by breiler** [comment]
This is most likley caused by this error:
https://groups.google.com/g/universal-gcode-sender/c/q5wdEQSZZTU

There is a possible fix on its way:
https://github.com/winder/Universal-G-Code-Sender/pull/1538

**Comment by breiler** [comment]
Try the latest nightly build, I think that I have solved the problem with the dynamic actions that does not load properly on some platforms.

It should look something like this:
![image](https://user-images.githubusercontent.com/8962024/108036034-fde3a980-7037-11eb-8805-97590829b121.png)

**Comment by htrantx** [comment]
Thanks Joecim,

It's fixed!
