### ISSUE TITLE
Errors sending early commands in script - buffering or something ?

### ISSUE THREAD

**Issue by dmb0058** [winder/Universal-G-Code-Sender#1549]
[I'm finding that early commands in my script are generating this errir:

Error] An error was detected while sending 'G0x0y0': (error:1) G-code words consist of a letter and a value. Letter was not found. Streaming has been paused.
[Error] Error while processing response <An error was detected while sending 'G0x0y0': (error:1) G-code words consist of a letter and a value. Letter was not found. Streaming has been paused.>
**** The communicator has been paused ****

If I comment the offending command the error moves down the script.

Any ideas if this is a known issue ?

David

**Comment by breiler** [comment]
Could you post your gcode file?

**Comment by dmb0058** [comment]
I don't know what was causing this, but I think nit may have been interference between my stepper cables and my end stop cables that was ultimately affecting the arduino. I had re-set the arduino a couple of times without effect but once I separated these cables the problem went away immediately and hasn't recurred, so this case can be put down to pilot error :)
