### ISSUE TITLE
Latest nightly built hanged-up at start-- this is the same as #1536

### ISSUE THREAD

**Issue by htrantx** [winder/Universal-G-Code-Sender#1550]
**Describe the bug**
The latest nightly built hanged after connect

**To reproduce**
standard connect procedure

**Expected behavior**
should list  all Grbl parameters after connect, but hang up after listing $13 or $20 parameter

**Version**
UGS Platform 2.0.7 Feb/16/2021

**Hardware**
GRBL 1.1f on UNO

**Operating system (please complete the following information):**
 Windows 10 64 bit and
 Windows 10 32 bit

**Additional context**
UGS classic or UGS platform  2.0.7 stable release works fine

![ugshangup](https://user-images.githubusercontent.com/16945934/110043097-70c57380-7d0c-11eb-9f35-99ffa24f65f6.jpg)

**Comment by breiler** [comment]
Could you post your log file:
https://github.com/winder/Universal-G-Code-Sender/wiki/Configuration#log-files

**Comment by htrantx** [comment]
Joacin, here it is:

[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/6090750/messages.log)

**Comment by htrantx** [comment]
I noticed this issue is the same as #1536, please close this or merge to #1536

**Comment by rlwoodjr** [comment]
Try setting $20=0.  This worked for me.

**Comment by dvsingletary** [comment]
I'm not sure this is the same bug as #1536.  This bug looks like the IO to the machine hangs after the initial connect when the firmware settings are being retrieved, and hangs after receiving $21.
I tried turning off soft limits with $20=0 as suggested above, and this worked.  So, I think a bug has been introduced somewhere in UGS when it's processing the firmware settings that are requested on initial connect, and if $20=1, then it hangs.  @breiler I can reproduce this consistently, so let me know if I can grab any additional debug info for you.  I'm running on the latest nightly build Mar 20210322.

**Comment by alecarvalhof** [comment]
> Try setting $20=0. This worked for me.

https://github.com/winder/Universal-G-Code-Sender/issues/1726
I had the same problem and posted it today!
It really did!
Thanks.
By the way, is Autoleveler working 100% or with errors?

**Comment by Mrbaddaddy75** [comment]
Hello. So I'm past nube stage with the UGS software. I use the 2.0.7 nightly version and I recently been having the same problem or something similar.  I get  a ( T1m6 error 20 ) code at start up along with Java null error code.. I also downloaded the 2.0.8 version and I'm having issues with that.  I can connect and I can send my machine back home but I have no other functionality. I have all my parameters set as they should be, at least I think so. Am I missing something?
