### ISSUE TITLE
UGS stop moving machine and don't move at all

### ISSUE THREAD

**Issue by GasperStef** [winder/Universal-G-Code-Sender#1560]
Hello to all,

Yesterday I was trying to cut one of my project. I have GRBL and UGS Platform.

I noticed, that during cutting program comes to one point where it just stop and doesn't move. It seems like that is waiting something.  Work clock (duration of job) is still going. 

I checked the code several times ( not easy due to 15k of lines) but it seems to be OK.
The g-code was created with Fiusion 360.

I made tool change in 360, but I have erase it in code so I think that this is nt the problem. My code doesen't include any of Tx and M6 code.

This happens every time if I want to run program. And always on same position.

Do you have maybe some ideas for this issue?

Thank you in advance.

**Comment by breiler** [comment]
Could you add the gcode program? Also what operating system are you using?

**Comment by GasperStef** [comment]
I am using win 10 64x.
When I will come home from work I will paste the gcode.

Thank you.

**Comment by GasperStef** [comment]
Ok. Ass promised I'm adding my Gcode file.

Tnx in advance.
[ZAN_ZNAK_REZANJE_4MM_FI6mm.txt](https://github.com/winder/Universal-G-Code-Sender/files/6165121/ZAN_ZNAK_REZANJE_4MM_FI6mm.txt)

**Comment by breiler** [comment]
The file ran fine here which I believe rules out any errors on the gcode file.

I suspect that you have an unstable connection to your controller:
* Check that you have JSerialComm connection driver selected in UGS ![Connection driver](https://user-images.githubusercontent.com/8962024/40659348-4a279b84-634e-11e8-91f6-19bcc6f0e16e.png)
* Try running the program without the motors and spindle activated (this would rule out any EMI-problems from your hardware)

**Comment by breiler** [comment]
Closing as we didn't get any response from user.
