### ISSUE TITLE
mvn install fails

### ISSUE THREAD

**Issue by mron** [winder/Universal-G-Code-Sender#1563]
running mvn install produces many errors. Here's the first:

ERROR]   Run 2: ApplicationTest.testApplication NbModuleSuite has been started with failOnMessage(WARNING) and failOnException(INFO). The following failures have been captured:
[org.netbeans.ProxyClassLoader] THREAD: main MSG: Will not load class com.willwinder.universalgcodesender.model.UnitUtils$Units arbitrarily from one of ModuleCL@0[com.willwinder.ugs.platform.ugslib] and ModuleCL@1[com.willwinder.ugs.platform.plugin.joystick] starting from SystemClassLoader[134 modules]; see http://wiki.netbeans.org/DevFaqModuleCCE
[org.openide.filesystems] THREAD: main MSG: null
...
  java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:423)
  org.openide.filesystems.XMLMapAttr$Attr.decodeValue(XMLMapAttr.java:861)
  ... 
52 more
....
[org.openide.filesystems] THREAD: main MSG: null
java.io.IOException
  org.openide.filesystems.XMLMapAttr$Attr.decodeValue(XMLMapAttr.java:865)
  org.openide.filesystems.XMLMapAttr$Attr.getObject(XMLMapAttr.java:944)
....
  java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2244)
  java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2082)
  java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1586)
  java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:423)
  org.openide.filesystems.XMLMapAttr$Attr.decodeValue(XMLMapAttr.java:861)
  ... 52 more

I'm on os x 10.14. I'm using VSC IDE. This may be related to my running MainWindow.cpp from inside VSC for debugging.

**Comment by whitetd** [comment]
All this to try and run a firmware transformed to 3d printing to run a cnc?
Its a fork from grbl, and grbl has been constantly updated for cnc.
Personal choice.
