### ISSUE TITLE
ESP32 will not boot with ESP32 selected unless the EN button is pressed.  It will boot with grbl selected

### ISSUE THREAD

**Issue by rlwoodjr** [winder/Universal-G-Code-Sender#1569]
I am running a ESP32 with the nightly build and it will not load unless I press the EN button on the ESP32 if the firmware selected is ESP32.  

If I connect the ESP32 with the GRBL firmware selected I do not need to push the EN button.  The ESP32 loads.

**Comment by breiler** [comment]
Grbl_ESP32 is no longer maintained, switch to [FluidNC](https://github.com/bdring/FluidNC). 
FluidNC will be available as a connection alternative in UGS 2.0.12.
