### ISSUE TITLE
File open dialog delay

### ISSUE THREAD

**Issue by Mgilbride** [winder/Universal-G-Code-Sender#1575]
**Describe the bug**
the file open dialog takes a minute or more to open.

**To reproduce**
1. Click on the file open icon.
2. Go get a cup of coffee

**Expected behavior**
Immediate opening of select file to open dialog.

**Version**
Latest build.

**Hardware**
Windows 10 on Dell laptop. G2 on Arduino Due

**Operating system (please complete the following information):**
 Windows 10

**Comment by breiler** [comment]
This could be related to a Java bug described here:
https://github.com/winder/Universal-G-Code-Sender/issues/1415#issuecomment-652001419

The bugs should have been fixed as of Java 7 (we are using Java 8 and 13) but the user tried moving the zip files which seemed to help and you might want to give that a try.

**Comment by breiler** [comment]
Closing as we didn't get any response from the user.
