### ISSUE TITLE
G92 offset visualization

### ISSUE THREAD

**Issue by Mgilbride** [winder/Universal-G-Code-Sender#158]
When you enter in an offset with the G92 command you see the tool move. However, it does not seem to move the acual cutting pattern along with it to reflect a change in where the part will be actually cut. 

Also, I sometimes bring in an extra path to show the work area. Would be very helpful to add a representation of work area to interface and visualizer

And it seems like there is some limit on how much you can zoom out in the visualizer.

**Comment by jahnj0584** [comment]
I think this issue was solved thanks to the platform.

**Comment by breiler** [comment]
The G92 looks right to me, it changes the workspace offset as expected.
When activating Homing + Soft limits you'll get a machine bounding box in the visualizer.
I'm closing this.
