### ISSUE TITLE
Z axis issues

### ISSUE THREAD

**Issue by nonpds** [winder/Universal-G-Code-Sender#1585]
When starting a job the Z axis moves up to and limits out. My safe, start and clearance are all set to 2 mm. Return to Zero works correctly.

When I hit Start the Z goes up to the limit and when I restart at a position it does the same. I do not understand why it doesn't use the 2mm safe height.

When I hit start this is the command shown, [GC:G0 G54 G17 G21 G90 G94 M5 M9 T0 F0 S0]

**Comment by breiler** [comment]
Do you mind sharing your gcode file?

**Comment by breiler** [comment]
Closing as we didn't get any response from user.
