### ISSUE TITLE
an error has occured,error while processing response < <hold>>

### ISSUE THREAD

**Issue by arjunds45** [winder/Universal-G-Code-Sender#1599]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Version**
[e.g. UGS Platform 2.0.6, UGS Classic 1.0.9]

**Hardware**
[e.g. GRBL 1.1f, TinyG,  SmoothieBoard]

**Operating system (please complete the following information):**
 [e.g. Windows 10, MacOSX, Ubuntu 20.04 ]

**Additional context**

**Comment by arjunds45** [comment]
How to correct it sir

**Comment by breiler** [comment]
It is impossible to help you without any details about your setup and a clear description of the problem.
 * What controller firmware and version you are running (ie: GRBL 1.1f)
 * Which version of UGS you are running (ie: UGS Platform 2.0.7)

**Comment by arjunds45** [comment]
please find the solution  to resolve the issue ,please find the atched file
eariles mail

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by breiler** [comment]
Github does not allow attachments from emails, you would need to attach them to the issue from the webpage.
