### ISSUE TITLE
ugsplatform version 2.7 not connecting to GRBL device

### ISSUE THREAD

**Issue by FrankC1981** [winder/Universal-G-Code-Sender#1608]
Hello,

I'm new to this forum and this is my first issue I have with UGS.
In the past I had (and still have) an ok working GRBL0.9 machine which I connected to Windows10 with UGSplatform.

Recently I used a different laptop with a fresh UBUNTU 18.04 installation. Here I also installed the latest UGSplatform version 2.7. I installed CH340 as USB driver. DMESG is showing that the USB cable is connected. Now I have the problem that I can't connect via UGS with my machine. First I had no USB ports found, but after changing to JSerialCom I could find the correct port. But still not connection possible (Status is not changing to IDLE).

I used minicom to check if my port is ok, and with 115200,8N1 I could easily connect to my machine and send commands.
So I make the carefull conclusion that the problem should be in UGS.. But I don't know how to continue to solve this issue.

Do you have any ideas how to debug/solve this?

If any information is still needed, please ask and I will provide.

Many thanks.

BR,
Frank

**Comment by FrankC1981** [comment]
Dear all,

Just to inform you all: I solved my issue by myself. I need to start UGSplatform with sudo to get permission to access USB port.
I'm happy to continue my milling again! :)

BR,
Frank

**Comment by waterwin** [comment]
sudo ./ugsplatform

**Comment by breiler** [comment]
@waterwin you should not run UGS as root. If your user don't have the proper user rights to access the controller serial device you should add it. This depends a bit on the flavour of Linux. Usually the device is accessible with group permissions `dialout`. 

This can usually be added through:
`sudo usermod -a -G dialout $USER`
