### ISSUE TITLE
Error while starting file to stream

### ISSUE THREAD

**Issue by BSaage** [winder/Universal-G-Code-Sender#162]
Hi,
I'm pretty new to CNC so please excuse if it's a newbie question.
When starting a job via "Send" I get the error "Error while starting file to stream: Command #12311 too long: (53>50)" followed by a G-code line. What's wrong with this line of code?
G3 X132.5932 Y159.6612 Z-0.1000 I-2034.6790 J-205.3555 F100

Thanks!!

![fehlermeldung](https://cloud.githubusercontent.com/assets/5887321/3011571/9c7fed28-df2c-11e3-8fe7-8569a316ca6f.jpg)

**Comment by laus785** [comment]
Hello
Bonjour à tous 
Voila moi j'ai un  message d’erreurs de ce type.
Error while starting file stream:command#3 too long:(86>50)'(using default header. to add your own header create file "header" in the output dir.)'
Je comprend pas vraiment la fin de se message ?
Es ce que quelqu'un pourrais me venir en aide s'il vous plais. :)

**Comment by winder** [comment]
@laus785 

Un ordinateur a traduit ceci. Je ne parle pas français.

Le message d'erreur est dans votre fichier gcode, la ligne est trop longue. C'est un commentaire que UGS aurait dû supprimer.

Quelle version utilisez-vous? Je pense que c'est un bug que j'ai fixé dans la "construction nocturne". Télécharger ici: http://winder.github.io/ugs_website/download/

**Comment by laus785** [comment]
Hello
Thank you for your answer.
I use version 1.0.7
The file and creates with Inkscape 64-bit, Windows 7.
Thank you

**Comment by winder** [comment]
@laus785 
La mise à niveau vers 1.0.9 ou 2.0 devrait corriger le problème, il ya beaucoup de corrections sinec 1.0.7 a été libéré.

**Comment by laus785** [comment]
Hello
Thank you, No more problems with this version 1.0.9 😉


2017-02-22 14:58 GMT+01:00 Will Winder <notifications@github.com>:

**Comment by sole99** [comment]
![g code](https://user-images.githubusercontent.com/35136670/34607334-6307defe-f213-11e7-9f4c-8c72c6b01d73.png)
 Do you can to help me? @BSaage

**Comment by winder** [comment]
@sole99 you're using a very old version of UGS. This has been fixed for a long time.

**Comment by sole99** [comment]
Thanks, Which version can I use?
Thanks.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#m_-2036351750686899146_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by sole99** [comment]
![ugs 2 0](https://user-images.githubusercontent.com/35136670/34644478-c73853e8-f337-11e7-96cb-c7af5f79c6a8.png)
 I have a problem, please, help me. What should I do?
Thanks

**Comment by dastultz** [comment]
First, go to the Google Group and start a discussion: https://groups.google.com/forum/#!forum/universal-gcode-sender
Once it has been determined there is a bug or work to do in UGS, create an issue. The Google Group is for questions, help, discussion, etc.

Second: get on the latest version of UGS, whatever problem you are having might be fixed already.

Third: paste the first 10 lines of your G-code since it appears line 7 is failing. Screenshots can't be searched, text descriptions of problems are better.

It looks like your G-code isn't proper. Can you run it with some other utility than UGS? If not, the problem is in your code, not UGS.
