### ISSUE TITLE
UGS Unexpected Exception error

### ISSUE THREAD

**Issue by bryangr93** [winder/Universal-G-Code-Sender#1624]
**Describe the bug**
Please help.
I used to work normaly but suddenly the UGS started to show an error without apparently cause while g-code is being sent.
I restarted the G-code sending but after some minutes the alarm appears again and again after some minutes of g-code sending.

**Screenshots**
![image](https://user-images.githubusercontent.com/86680311/123841153-d5689780-d8d4-11eb-8b9f-1561dc3ca0c1.png)

**Version**
 UGS Platform 2.0.7-SNAPSHOT/ Dec 02, 2020

**Hardware**
 GRBL 1.1g

**Operating system (please complete the following information):**
Windows 10

messages.log  file: 
[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/6735396/messages.log)

**Comment by breiler** [comment]
Your machine has gone into an alarm state due to triggered limit switches. If they weren't physically triggered they might got triggered due to electro magnetical interference (EMI). What kind of machine do you have?
