### ISSUE TITLE
ninguna de las versiones me funciona, todas me traen un error diferente 

### ISSUE THREAD

**Issue by rockbull1** [winder/Universal-G-Code-Sender#1625]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Version**
[e.g. UGS Platform 2.0.6, UGS Classic 1.0.9]

**Hardware**
[e.g. GRBL 1.1f, TinyG,  SmoothieBoard]

**Operating system (please complete the following information):**
 [e.g. Windows 10, MacOSX, Ubuntu 20.04 ]

**Additional context**

**Comment by breiler** [comment]
There is not enough information to be able to help you. 
* Which versions did you try? 
* Classic or Platform edition? 
* What operating system are you running? 
* What error message did you get?
