### ISSUE TITLE
job stops in middle of cut, just freezes spindle doesnt stop no alarm

### ISSUE THREAD

**Issue by engine3061** [winder/Universal-G-Code-Sender#1630]
i am in the middle of a 6 hour cut UGS has stopped 5 times, at line 7730, line 73000, line 83000 and line 88000 , i keep getting error code but no alarm, just stopped again as im writing this and the status just goes to idle. only change since ive been running UGS is the new windows10 update and i updated JAVA already. the spindle keeps running just the movement stops. my friend had the same exact problem yesterday running his machine it popped up same error and stopped, i have run UGS with no issues until the windows 10 update. and have never had the machine stop like this in the middle of a job

i have windows 10

![ugs error](https://user-images.githubusercontent.com/22730078/125357428-a4a54b00-e335-11eb-8d84-1d365ff4d5ec.png)
![ugs error 2](https://user-images.githubusercontent.com/22730078/125357443-a838d200-e335-11eb-9c58-3b5f156ebe4e.png)

**Comment by breiler** [comment]
If you look at the last text received from the controller there is a bunch of garbage text. This is likely caused by interference in the USB cable.

Make sure that the USB cable is a properly shielded one and that it is far away from the spindle power cable as that produces the most EMI.
