### ISSUE TITLE
Menu Multiply XY Step Size by 10 not working

### ISSUE THREAD

**Issue by AndyCXL** [winder/Universal-G-Code-Sender#1645]
**Describe the bug**
Select Menu Multiply XY Step Size by 10, performs no action.
Not noticed any other such menu function omissions.

**Expected behaviour**
Expecting XY Step Size to x10. Divide by does work.

**Version**
UGS Platform 2.0.8-SNAPSHOT of 26-Jul-2021, 16:00 GMT+1

**Hardware**
GRBL 1.1t Mega 5X

**Operating system (please complete the following information):**
MacOSX

**Additional context**

**Comment by testanley3** [comment]
This bug also present in Windows 10 edition of the same version.  Glad it's not just my imagination.

**Comment by AndyCXL** [comment]
I have found the typo in the source that is causing this, and shortly will submit a pull request with the very simple fix.

**Comment by testanley3** [comment]
Thank you for this fix.  Forgive my ignorance, but how do I update my copy of the program to implement this change?

**Comment by AndyCXL** [comment]
Several ways;
1. Best is that my Pull Request is merged and this becomes part of the nightly builds
2. You fork my copy (Menu_Multiply from GitHub AndyCXL) compile and use that until 1. happens

**Comment by AndyCXL** [comment]
@testanley3 if you can PM me, I can send the ZIP file I have compiled of either Menu_Multiply or Replacer branches. It's not ideal as you are then wholly dependent on me, but if you can't compile from my repository it may a practical 'fix'.

**Comment by AndyCXL** [comment]
@testanley3 Note that this proposed fix (Menu Multiply XY Step Size by 10) has been accepted and merged into the nightly builds, so you can download a 'fixed' version of UGS

**Comment by testanley3** [comment]
Thanks to everyone!

**Comment by testanley3** [comment]
Hello. I have tried to load a nightly build that incorporates this Multiply
XY by 10 patch, but the latest I can find is dated 07/24/21 and this does
not seem to contain the correction. What am I doing wrong?

**Comment by testanley3** [comment]
Sorry to be a nuisance, but I must not know how to download nightly builds.  I am navigating to https://ugs.jfrog.io/ui/native/UGS/nightly and other than a .zip file for a Raspberry Pi version dated 08/02/21, the latest that I see for other platforms are dated 07/24/21.  These do not seem to include the patch for the above discussed error of XY Jog Size Multiply.  Where can I find a more recent nightly build for the Windows OS?  Is it possible that July 24 WAS the last nightly build for this version?  Please help.  Thank you!

**Comment by AndyCXL** [comment]
@testanley3 you are right, the nightly builds haven’t run since. Are you able to build the source yourself into the executable? That’s what I do. If not, it is down to the owners/administrators to run a nightly build so you can access it

**Comment by testanley3** [comment]
Well, I would like to be able to build it myself, but it's been a long time
since I did any code compilation, most recently websites using Visual
Studio using ASP.NET.  I wouldn't expect you to shepherd me through the
whole setup process, but if there are resources from which I could draw to
learn, I would be grateful to be pointed to them.  You have been very
generous with your time.  Thanks.

**Comment by AndyCXL** [comment]
If you are able to PM me, I could send you a ZIP of the compiled files. It is circa 150MB all-in, so we'll have to find a way to transfer it (OneDrive or something)

**Comment by testanley3** [comment]
This is so kind of you!  Looks like there is no longer a PM function within
github, so I'm not sure what to do other than to share my personal email,
which is ***@***.***  I have a Google Drive account and can share
a folder in that to whatever address you specify. I really appreciate your
help!

**Comment by AndyCXL** [comment]
PM me at AndyCXL@corteen.org and we can set something up
