### ISSUE TITLE
UGS Platform 2.0.8. does not connect to GRBL

### ISSUE THREAD

**Issue by pagabee** [winder/Universal-G-Code-Sender#1650]
**Describe the bug**
UGS Platform 2.0.8. Windows version does not connect to GRBL

**Expected behavior**
After clicking on connection, the icon changes to connected but the status remains offline. Some buttons of the Toolbox will be active, the others stay inactive.
The baud change or the serial connection driver chage does not help. 

**Screenshots**
![UGS Platform 2 0 8 Win10](https://user-images.githubusercontent.com/82469736/128064002-d3890c7e-597f-4f46-93dc-17042423f53c.jpg)
![UGS_2 0 8 Win 7 32 bit](https://user-images.githubusercontent.com/82469736/128064040-14f3d88f-61eb-486c-87bb-ee89f47de279.png)

**Version**
UGS Platform 2.0.8. Windows version

**Hardware**
GRBL 1.1f: gnea/grbl (Arduino) and stm32 grbl (robomechs)

**Operating system (please complete the following information):**
Windows 10 64 bit and Windows 7 32 bit

**Comment by breiler** [comment]
Could you post the log file from the Win10 machine: 
https://github.com/winder/Universal-G-Code-Sender/wiki/Configuration#log-files

**Comment by pagabee** [comment]
I attched the log from arduino and stm32 based GRBL.
[messages_arduino.log](https://github.com/winder/Universal-G-Code-Sender/files/6932563/messages_arduino.log)
[messages_STM32.log](https://github.com/winder/Universal-G-Code-Sender/files/6932564/messages_STM32.log)

**Comment by breiler** [comment]
The Arduino log didn't give any clues, but the STM32 showed an error with visualising machine boundaries which was fixed a couple of days ago. Please try the nightly build and see if that helps:
https://github.com/winder/Universal-G-Code-Sender#downloads

**Comment by pagabee** [comment]
The nightly build version works with stm32 grbl but not with arduino grbl.
[messages_arduino_2.log](https://github.com/winder/Universal-G-Code-Sender/files/6933282/messages_arduino_2.log)
[messages_STM32_2.log](https://github.com/winder/Universal-G-Code-Sender/files/6933283/messages_STM32_2.log)

**Comment by pagabee** [comment]
There was something wrong with the Arduino, with a new one it works fine.
Thanks for your support!

**Comment by breiler** [comment]
Excellent, have fun! =)

**Comment by KryptoMyner** [comment]
@breiler I'm having the same issue with 2.0.8.  I just upgraded from 2.0.7, which worked fine.  I'm using GRBL 1.1h.

![image](https://user-images.githubusercontent.com/4517085/132273358-30440ce3-36ff-4902-b3f8-055f43909082.png)
[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/7118435/messages.log)
