### ISSUE TITLE
Simulator

### ISSUE THREAD

**Issue by Mgilbride** [winder/Universal-G-Code-Sender#167]
I have mentioned some version of this before. Testing grbl can get a bit hard on your machine. Would be very useful to visualize machine jogging and homing moves. Ability to very simply represent your particular machine's bed size, depth,  x, y, and z axes, hard limits  and soft limits. Plug in an arduino with grbl and you have a great testing environment. Not all easy to do.

**Comment by winder** [comment]
Better late than never... is this something that @jgeisler's grbl-sim project would help with?

**Comment by Mgilbride** [comment]
Close but not exactly the same thing / goal. Was aiming at real time
hardware / firmware testing by running a grbl loaded aduino- and reading
outputs back into simulator environment rather than plugging it into
hardware. Obviously not critical. Thanks for following up.

**Comment by winder** [comment]
I don't see myself implementing this. In the UGS Platform project there is a plugin system which might make sense for things like this in the future.
