### ISSUE TITLE
joystick deadzones?

### ISSUE THREAD

**Issue by doctorpartlow** [winder/Universal-G-Code-Sender#1693]
I have an xbox controller that when connected to ugs platform shows some drift making the cnc drift around which isn't good. is there any deadzone settings for the joystick for it to ignore the lets say first n percent of the input and the last n percent of the input? if it doesn't exist, if there is already, I can't seem to find it. let me know if possible. thanks.

**Comment by breiler** [comment]
There is such a setting under the configuration called  `Zero threshold`

Read more about it here:
https://github.com/winder/Universal-G-Code-Sender/wiki/Usage#analog-controls
