### ISSUE TITLE
Display of limit switch and door alarm states

### ISSUE THREAD

**Issue by cdo1955** [winder/Universal-G-Code-Sender#1695]
In the attached photo from the web site there are limit switch outputs displayed clearly under the DRO. But in the version I just downloaded they don't exist. Can you tell me where to find them or re-add them as a feature. They are a valuable resource for troubleshooting.

![Limit switch](https://user-images.githubusercontent.com/86383897/135336634-9069396c-f430-468e-ac98-84af2822df29.PNG)

**Comment by breiler** [comment]
They are still there but hidden until they are triggered. Here is a screen shot of how it looks if the limit pins are triggered
![Screen Shot 2021-09-29 at 21 54 59](https://user-images.githubusercontent.com/8962024/135339369-91ce9b80-23a2-4c49-ac64-f1298847ee48.png)

**Comment by cdo1955** [comment]
Thanks for your responce,
Does it show each axes individually or just as "Alarm XYZ" no matter which goes off?  I kept have issues with limit switches but I didn't know which one was triggered. It would be helpful if it showed which one is on.

**Comment by breiler** [comment]
Yes, it will only show those pins that are triggered.
