### ISSUE TITLE
UGS se cierra automaticamente

### ISSUE THREAD

**Issue by manuel82-241** [winder/Universal-G-Code-Sender#1703]
Estaba usando la version de 2019 y esta mañana me descargué la ultima version la cual tuve abierta salvo que no la probé. Esta tarde he intentado abrir la nueva version y no se me abre y es más intento abrir la del 2019 y tampoco puedo, he actualizado java. He ejecutado como administrador el ugs tanto en version de 32 y 64 ya que la antigua había que ejecutar la de 32bits y solo consigo que aparezcan los mensajes de cargando modulos y ya está, a partir de ahí se cierra y no consigo abrirlo. Alguien me puede ayudar? Uso windows 10 

**To reproduce**
1. ugsplattform

**Expected behavior**

**Screenshots**

**Version**
[e.g. UGS Platform 2.0.6, UGS Classic 1.0.9]

**Hardware**
[e.g. GRBL 1.1f, TinyG,  SmoothieBoard]

windows 10
**Additional context**

**Comment by breiler** [comment]
Sorry for the late response...

Your settings have probably gotten corrupt. Please delete everything under:
`C:/users/[your username>]/.ugsplatform` and `C:/Users/[your username>]/AppData/Roaming/ugsplatform`
 
Then start UGS.

I am closing this issue as it is very old, please reopen if it still remains a problem.
