### ISSUE TITLE
Openjdk 13 menu font missing russian characters

### ISSUE THREAD

**Issue by xor2003** [winder/Universal-G-Code-Sender#1706]
**Describe the bug**
On Ubuntu when I switch to russian I get question marks instead of russian symbols.
Some one said he could resolve it on windows by using Sender without embedded java.

**To reproduce**
Enable russian language using menu

**Expected behavior**
Russian symbols instead question marks.

**Screenshots**

**Version**
UGS Platform 2.0.8

**Hardware**
--
**Operating system (please complete the following information):**
 Ubuntu 21.04

**Additional context**
No system java

**Comment by breiler** [comment]
Fixed in #2192
