### ISSUE TITLE
Visualisation of spirals shiftet by z-difference

### ISSUE THREAD

**Issue by AnHardt** [winder/Universal-G-Code-Sender#174]
When you look at:

G21 (Units in millimeters) 
G90 (Absolute programming) 
G17 (XY plane) 
F900

G3 X0 Y0 I20 J0
G3 X0 Y0 z -20 I20 J0
G3 X0 Y0 I20 J0

G1 Z0
G2 X0 Y0 I-20 J0
G2 X0 Y0 z 20 I-20 J0
G2 X0 Y0 I-20 J0
G1 Z0
M2 (Program end)

you should see:
a circle
a spiral down
and a circle at the new z-depth

you acually see:
a circle
a circle at the new z-depth
and a spiral below of that

For G2 and upwards the spiral shows above the new z-depth.

Tested with 1.07 and 1.08.

**Comment by droidmunkey** [comment]
Thanks!  Great find!
