### ISSUE TITLE
specify initial position for cli

### ISSUE THREAD

**Issue by thomasphys** [winder/Universal-G-Code-Sender#1741]
Suppose I have a g-code script that sets my tool position using a probe. I then want to remove the probe and, without manually adding lines to my job file, run the job. This requires me to tell ugs the position that my probe script set the tool. 

Can you add a simple -set-tool-position # # #  ?

**Comment by breiler** [comment]
I don't understand. What should `-set-tool-position # # #`should do? 
Set the work offset? 
Jog the machine?

**Comment by breiler** [comment]
Closing as we did not get any response from the user.
