### ISSUE TITLE
Can't run cloned repository

### ISSUE THREAD

**Issue by AndreaLombardo** [winder/Universal-G-Code-Sender#1750]
**Describe the bug**
Cloned repository from branch Master. Tryed to execute mvn install and mvc exec as in run_classic.sh but project won't start.

**To reproduce**
1. Clone git repo
2. run mvn install -DskipTest (because ugs-platform-plugin-cloud-storage test fails)
3. run mvn exec:java -Dexec.mainClass="com.willwinder.universalgcodesender.MainWindow" -pl ugs-core
4. Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project ugs-core: An exception occured while executing the Java class. com.willwinder.universalgcodesender.MainWindow

The class com.willwinder.universalgcodesender.MainWindow exists in the project. But when i try to open in Netbeans design tab an error occure. See screenshot below.

**Expected behavior**
A starting program.

**Screenshots**
![MainWindow designer error](https://gcdn.pbrd.co/images/NHOWmDg3hkSh.png)

![MainWindow](https://gcdn.pbrd.co/images/j5LhFThkhCHH.png)

**Logs**
[mvn install log](https://controlc.com/2a98a9eb)

[mvn install without tests log](https://controlc.com/86fb4699)

[mvn exec log](https://controlc.com/9da9648c)

**Version**
Branch Master Release 2.0.9

**Hardware**
Not yet important

**Operating system (please complete the following information):**
Edition Windows 10 Pro N
Version 21H2
Build OS	19044.1415
Experience Windows Feature Experience Pack 120.2212.3920.0

**Additional context**
Maven:
Maven home: D:\apache-maven-3.8.4
Java version: 1.8.0_322-beta, vendor: Temurin, runtime: C:\Users\Andrea\AppData\Local\Java\OpenJDK8U-jdk_x86-32_windows_hotspot_2021-12-02-11-02\jdk8u322-b04\jre
Default locale: it_IT, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "x86", family: "windows"

Java:
openjdk version "1.8.0_322-ea"
OpenJDK Runtime Environment (build 1.8.0_322-ea-b05)
OpenJDK 64-Bit Server VM (build 25.322-b05, mixed mode)

**Comment by breiler** [comment]
Sorry for the late reply. The module path has changed, use this command instead:
`mvn exec:java -Dexec.mainClass="com.willwinder.universalgcodesender.MainWindow" -pl ugs-classic`

I'm not sure why the test is failing, it works on my MacBook and the build server.

I don't know why GcodeTable-component isn't showing in the designer, I think you will need to use the source instead. =(
