### ISSUE TITLE
Zero reset

### ISSUE THREAD

**Issue by brad1983** [winder/Universal-G-Code-Sender#1751]
When in a program and pressing the stop button the XYZ axis reset to zero.
How can I disable this?

**Comment by breiler** [comment]
What firmware and version are you using? (GRBL 0.9?)
Which version of UGS are you running?

**Comment by brad1983** [comment]
UGS 2.0.9 for windows.
I’m not sure what firmware I have.

**Comment by breiler** [comment]
Closing as we didn't get enough information from the user.
