### ISSUE TITLE
Cant start miling g-code imported from flatCAM i think it is M6 error

### ISSUE THREAD

**Issue by oliskcz** [winder/Universal-G-Code-Sender#1758]
Heres the g-code. Thanks in advance
[g-code.txt](https://github.com/winder/Universal-G-Code-Sender/files/7781434/g-code.txt)

**Comment by breiler** [comment]
UGS does not support the M6-command (manual tool change) so it needs to be removed from the gcode.

**Comment by oliskcz** [comment]
How to remove it i dont want to mess up the gcode.

**Comment by khturnings** [comment]
I found this useful regarding this issue - although it does not say how to remove M6 from gcode.

I think it depends on how you generate your gcode - I use Fusion 360 to generate my gcode and you can get it to suppress Tool change (not a good idea going by this article https://www.3dtek.xyz/2020/01/29/grbl-m6-errors/ )
![image](https://user-images.githubusercontent.com/30479350/147572702-2a4bc5d9-f71d-4b22-b486-cf4d7f6b9855.png)

Else use NotePad++ or something similar and use find and replace - and then do test air cut.
