### ISSUE TITLE
Figure out how settings should be stored between different versions

### ISSUE THREAD

**Issue by breiler** [winder/Universal-G-Code-Sender#1781]
### Version

Other

### Hardware / Firmware

Other (add details about it below)

### What happened

When upgrading from one UGS version to another, how should the settings be transferred?
See discussion here: https://github.com/winder/Universal-G-Code-Sender/discussions/1755

**Comment by marshr32** [comment]
The latest nightly seems to do a great job at picking up my settings.
I guess that could be because I set up a nightly previously and it's looking at the same config file?

**Comment by breiler** [comment]
Yes, it uses the same settings directory between all nightly builds. We could do the same for the stable builds but this requires some testing.

**Comment by breiler** [comment]
Now uses the same settings directory. Fixed with #2038
