### ISSUE TITLE
Add options to the visualizer

### ISSUE THREAD

**Issue by OslayViera** [winder/Universal-G-Code-Sender#1808]
### Description

I have a CNC to make pyrography with nichrome. UGS works perfectly for me to send my .nc code to the machine, the problem is that when viewing the work, as my machine does not use the z axis, everything is seen in the same color and the work cannot be distinguished, only the position of the machine and of course the lines in classic blue. My proposal is that there are some options to activate or deactivate in the display a color scale proportional to the speed of movement and that it goes from minimum to maximum speed in the work in question.

**Comment by breiler** [comment]
Great suggestion, similar could be used for spindle speed when using a laser engraver.
