### ISSUE TITLE
Ability to test probe circuit before initiating probe macro

### ISSUE THREAD

**Issue by bryonmadge** [winder/Universal-G-Code-Sender#1816]
### Description

I would like to see an "Led" indicator on screen to test the continuity of my test probe each time before committing to initiating the probe routine. 
I use Mach3 on another machine and I've gotten used touching my probe wires together to quickly test for continuity before running. Mach3 has and on-screen indicator for this.
Thanks

**Comment by chrisla23** [comment]
All alarms including the probe will show up in red when activated. This happens at the bottom of the DRO pane. Depending on your window size you may need to scroll down some to see them. 

I do this same test you are suggesting each time I use the probe. 

Thanks,

-Chris

**Comment by bryonmadge** [comment]
It was hiding and I see it now. Thanks.
