### ISSUE TITLE
Run macros with keyboard shortcuts

### ISSUE THREAD

**Issue by bryonmadge** [winder/Universal-G-Code-Sender#1817]
### Description

I use a USB number pad to do jogging etc. I would like to be able to run macros from the pad by utilizing a custom keyboard shortcut.
Thanks

**Comment by daxliniere** [comment]
Yes, that would be awesome.

**Comment by daxliniere** [comment]
Hi @bryonmadge, you can already do this. Just go to Tools>Options>Keymap and scroll down until you see Macro on the third column. :)

![image](https://user-images.githubusercontent.com/8109020/159143781-20a5c977-ffac-4250-b12c-9d6785b9fe39.png)
