### ISSUE TITLE
Function to draw Visualizer based on program line number

### ISSUE THREAD

**Issue by daxliniere** [winder/Universal-G-Code-Sender#1831]
### Description

I just woke up this morning an idea. It would be amazing if the Visualizer could display the block you are up to based on which line is selected in the program source window (the Editor).

Especially for people like me who are starting out, it would be invaluable to be able to see exactly how each command relates to a movement.

A button in the toolbar would be an easy way to toggle this function.

All the best,
Dax.

**Comment by breiler** [comment]
This feature does exist (if I understood your request) and has been improved quite recently and is a part of the latest nightly build. There is a screen shot of these changes here: https://github.com/winder/Universal-G-Code-Sender/pull/1764

**Comment by daxliniere** [comment]
Yep, you've got it!

Would be nice to have an option (with toolbar button) to enable the behaviour I suggested above, though.
I think that when I used the word 'selected', it was in error. A better description would be whatever line the text cursor is on.
