### ISSUE TITLE
Outline mode needs a warning dialogbox (2.0.11)

### ISSUE THREAD

**Issue by daxliniere** [winder/Universal-G-Code-Sender#1838]
### Version

2.0.11

### Hardware / Firmware

GRBL 1.1

### What happened

I clicked the Outline button (since there was no tooltip explaining what it did), and my CNC launched into chopping up my workpiece. :/

Could you please add a) dialogbox asking the user if they wish to continue and b) a tooltip?

Cheers!
Dax.

### Anything else

By the way, Joacim, can you add UGS version 2.0.11 to the dropdown menu of this issue report feature, please? 2.0.10 
ais the latest you can choose.

**Comment by breiler** [comment]
Added a tool tip which will hopefully make it easier for the user to understand what will happen.
