### ISSUE TITLE
NC Editor pane missing

### ISSUE THREAD

**Issue by daxliniere** [winder/Universal-G-Code-Sender#1839]
### Version

Other

### Hardware / Firmware

GRBL 1.1

### What happened

I'm not exactly sure what happened, but I now no longer have the Editor pane, nor can I find how to open it from any of the menus. This is affecting both 2.0.9 and 2.0.11
When I load an NC program, I see a brief flash on the GUI, but the Editor pane doesn't appear.

I have rearranged my panes quite a bit.
![image](https://user-images.githubusercontent.com/8109020/159305267-173f47bf-731a-4a45-b7ba-4995828e482f.png)

### Operating System

Win10x64 Pro N

**Comment by breiler** [comment]
I would like to see if this is a general problem, can you attach your log file (described here how to find it):
https://github.com/winder/Universal-G-Code-Sender/wiki/Configuration#log-files

To fix this problem you could try and reset the Windows:
https://github.com/winder/Universal-G-Code-Sender/wiki/Troubleshooting-Overview#ugs-is-not-showing-all-windows

**Comment by daxliniere** [comment]
Cheers, Joacim.
Actually found it at **C:\Users\dax\.ugsplatform\2.0.11\dev\var\log** (help page needs an update)

[log 2011.zip](https://github.com/winder/Universal-G-Code-Sender/files/8318080/log.2011.zip)
[log 209.zip](https://github.com/winder/Universal-G-Code-Sender/files/8318086/log.209.zip)

**Comment by breiler** [comment]
I'm not sure but I know that on Windows things in the Java-world can be a bit sensitive to "special" characters such parenthesis in directory names.

Try renaming this directory:
`C:\Program Files\DEV\Universal G-Code Sender (Platform edition) 2-0-11\`

**Comment by daxliniere** [comment]
By the way, this is what I see when I open an NC file:
![UGS_EditorMissing](https://user-images.githubusercontent.com/8109020/159336613-35aa0bd7-2205-4e79-97f2-d6d0a787c8a6.gif)

**Comment by breiler** [comment]
So the program no longer resides in a directory path with parenthesis which I saw in the log file?

```
WARNING [org.netbeans.modules.openide.loaders.FileEntityResolver]
java.nio.file.NoSuchFileException: C:\Program Files\DEV\Universal G-Code Sender (Platform edition)\platform\modules\org-netbeans-core-ui.jar
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
	at java.base/java.nio.file.Files.readAttributes(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
	at java.
```

Then the settings may have become corrupt and you probably need to remove the settings dir: `C:\Users\dax\.ugsplatform`

**Comment by daxliniere** [comment]
Ahh, I didn't realise we counted parentheses as special. 😆

I was having a lot of trouble so I wiped the settings folders, but I did back them up first. Would you like me to restore them and test something?

**Comment by breiler** [comment]
If it is working for you now when you renamed the program folder I am happy, no need to further investigate.
You could probably restore the settings and they would probably work.

**Comment by daxliniere** [comment]
It also seems that this window won't remember where I want it to appear and I wonder if that is related to this problem I had.

Upon opening UGS, there is no NC file loaded. Once it's loaded, the source window appears at the top of the second column of panes. I can move it to where I want (third column, top), but once I close and re-open UGS then load NC file, the pane is back at top of second column.
