### ISSUE TITLE
Options->Filter results don't include Available Actions in UGS->Toolbox

### ISSUE THREAD

**Issue by daxliniere** [winder/Universal-G-Code-Sender#1847]
### Description

Title says it all. :)

**Comment by breiler** [comment]
One scenario that does not work is that it should show the sub tabs such as the following.
This should be possible to implement given the existing API:s in the Netbeans platform we are using.
![image](https://user-images.githubusercontent.com/8962024/160781546-851b491d-e707-41b2-95fb-743f8cced02b.png)

---

But if I interpret the title you want to be able to filter for the action that is assigned like this?
![image](https://user-images.githubusercontent.com/8962024/160781965-39efee35-214b-4a68-8364-9e11c2ce8344.png)

This is as far as I know not possible with the API:s in Netbeans. =(

**Comment by daxliniere** [comment]
Ahh okay, no worries, Joacim. Thanks for the reply. :)
