### ISSUE TITLE
TAB-Less GUI?

### ISSUE THREAD

**Issue by rugbymauri** [winder/Universal-G-Code-Sender#186]
Hello 

what you think about a TAB-Less GUI?

![ugs-tabless](https://cloud.githubusercontent.com/assets/5549264/3980377/576624cc-2861-11e4-8128-0507cc84e220.png)

**Comment by jahnj0584** [comment]
I much prefer the first version, but make a longer command line on top of the window.

**Comment by winder** [comment]
@jahnj0584 check out the UGSPlatform build, you can configure it however you like

**Comment by jahnj0584** [comment]
I got it now..just rar files and XML stuff. Means nothing to me? where do I start?

**Comment by winder** [comment]
@jahnj0584 sorry, I really need to write up something about running this. There's a "bin" directory, you can use the .exe (windows) or startup script (mac/linux) to run. Eventually there will probably be an installer.
