### ISSUE TITLE
Rotary axis rendering issues

### ISSUE THREAD

**Issue by reality-boy** [winder/Universal-G-Code-Sender#1864]
### Version

2.0.11

### Hardware / Firmware

GRBL 1.1

### What happened

I have a rotary 'A' axis on a GRBL-Mega-5x board.  When I load a gcode file that rotates the A axis over 90 degrees and back UGS renders the motion as a straight line rather than as an arc.  If I subdivide the rotation into smaller 10 degree steps then it approximates an arc as it should.  This causes larger projects to render completely distorted if the rotary axis moves more than a few degrees.  I don't think this has any impact on the actual running of the machine.

You can read a more detailed writeup on this at the following link.
https://hackaday.io/project/176110-multibot-cnc-v2/log/205303-round-and-round

And can download the example files from here.
https://drive.google.com/file/d/1IUrQ_qz4XGioOrLAUFKjmXXwvQFeCgeQ/view?usp=sharing

### How to reproduce

Open the file rotate_90deg.nc linked above, you will see a rectangle rendered rather than a quarter of a cylinder.

### Operating System

Windows 10

### Anything else

Always happens.

**Comment by breiler** [comment]
Thanks for the bug report, I have noticed this as well.
