### ISSUE TITLE
visualizer show chaotic lines

### ISSUE THREAD

**Issue by elsolo5000-2** [winder/Universal-G-Code-Sender#1868]
### Version

2.0.11

### Hardware / Firmware

GRBL 1.1

### What happened

when i load a gcode file (correct file),, the visualizer show chaotic lines,
but when i select some line it highlight correctrly them
i made some updates on windows, 
someone know what happened?

### How to reproduce

install ugs (tested on 2.0.11 and 2.0.9)
make some updates on fresh windows 7 system
return on ugs and load a file

### Operating System

windows 7

### Anything else

it is impossible to download bundle from offiicial source, the link ends on a never ending refresh "jfrog" pag
[New Compressed (zipped) Folder.zip](https://github.com/winder/Universal-G-Code-Sender/files/8564425/New.Compressed.zipped.Folder.zip)
[New Compressed (zipped) Folder.zip](https://github.com/winder/Universal-G-Code-Sender/files/8564431/New.Compressed.zipped.Folder.zip)
e

**Comment by khturnings** [comment]
This is how it looks on my PC - Running Windows 10 Home and Universal Gcode Platform 20220214

![Screenshot 2022-04-26 173928](https://user-images.githubusercontent.com/30479350/165350179-95a437dc-726b-4b8d-9ae0-3ff9e485a74b.png)

**Comment by elsolo5000-2** [comment]
i reverted back my display drivers and problem solved. happened with last "intel graphics express family 4" on an "acer 7715"
