### ISSUE TITLE
3D probe feature

### ISSUE THREAD

**Issue by kweilim98** [winder/Universal-G-Code-Sender#1900]
### Description

does the ugs platform support the 3D touch probe feature? because I have a 3D touch probe as the figure show and I m don know where can I set it from the ugs platform. 
![S2f2e3d9806a2472883c5c2a40d32c2d5C](https://user-images.githubusercontent.com/66898187/171803271-14421fdc-7b2e-4121-91a2-5c7ec6ea99f2.jpg)
![S9e9dd1a147f246bc9acdf7b57b3b78213](https://user-images.githubusercontent.com/66898187/171803278-006d09cb-2539-41aa-bd59-9e005f980652.jpg)

**Comment by breiler** [comment]
UGS will not interface with probes directly, so you need to check if your controller supports it.
Just google "UGS probing" to get tutorials on how to get started.
