### ISSUE TITLE
Macros starting with "->" cause disk path error

### ISSUE THREAD

**Issue by daxliniere** [winder/Universal-G-Code-Sender#1901]
### Version

2.0.11

### Hardware / Firmware

FluidNC

### What happened

To aid in visual reference, I changed my macro names from "**Go to X0,Y0**" to "**-> X0,Y0**" and in doing so, caused UGS to show an error for each macro.

**Comment by daxliniere** [comment]
I can confirm that starting it with the ">" character also has problems.

**Comment by breiler** [comment]
When creating a Macro it will also create an action in the Netbeans platform which are stored as files. On Windows the file name is limited to characters described here: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file
```
The following reserved characters:
< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)
```

We have to look at how the action name is stored. There might be a possibility to override it in the .nbattrs-file. This could also solve the problem with keyboard shortcut mapping when a macro is renamed.

**Comment by daxliniere** [comment]
Thanks Joacim. I would have suggested this was a pretty low priority, but know that it might be connecged to the macro rename issue, it seems more pressing. Especially considering how it affects Toolbox buttons. (https://github.com/winder/Universal-G-Code-Sender/issues/1862#issuecomment-1148965409)
