### ISSUE TITLE
Visualizer machine boundries in unexpected place

### ISSUE THREAD

**Issue by wohali** [winder/Universal-G-Code-Sender#1915]
### Version

2.0.11

### Hardware / Firmware

GRBL 1.1

### What happened

I've configured UGS and GRBL 1.1h.20190830 with the following:

```
$20=1 (Soft limits enable)
$21=1 (Hard limits enable)
$22=1 (Homing cycle enable)
$23=3 (Homing direction invert - home is at top left front on this machine)
$130=110.900 (X-axis maximum travel)
$131=65.000 (Y-axis maximum travel)
$132=53.000 (Z-axis maximum travel)
```

After loading some GCode, homing the machine, and then a Reset Zero (`G10 P0 L20 X0 Y0 Z0`), I have coordinates as expected via `$#`:

```
[G54:-107.900,-62.000,-3.000]
```

But the build volume in the visualizer is still way off:

![2022-07-05-193938_670x707_scrot](https://user-images.githubusercontent.com/112292/177434163-738995c6-1958-498a-a894-988f90d64668.png)

I can adjust the work position to place the design within the bounding box, but the machine head is then outside of the volume - and all motion is disabled because of soft limits. For example, moving the work to the very edge of the volume results in this (note the `$#` output for G54): 

![2022-07-05-194530_1716x905_scrot](https://user-images.githubusercontent.com/112292/177434564-c2fa33cd-5f1f-48b7-9fe6-a532d89d3c34.png)

I looked at #1287 for history on this issue, but no help. Something seems amiss in the positioning of the build volume for negative offsets.

### How to reproduce

Can be reproduced using the data given above for a machine and any g-code file.

### Operating System

Debian linux bullseye x86_64

**Comment by breiler** [comment]
Thanks for the issue report, it got inverted in #1287 which might not be correct (it currently doesn't work on my machine either). I am not sure, but I think @rlwoodjr uses `HOMING_FORCE_ORIGIN` to make the machine work in positive space.

So to fix this we would need a manual setting in the visualiser to invert the bounding box and I just haven't gotten around to it yet.

**Comment by wohali** [comment]
Thanks for the info. I never considered `HOMING_FORCE_ORIGIN` since that'd make this mill different from every other mill I've used 😉 Makes sense, though.
