### ISSUE TITLE
Clicking DRO position to change has incorrect units populated in setting pop-up window

### ISSUE THREAD

**Issue by bertieconfundo** [winder/Universal-G-Code-Sender#1928]
### Version

Other

### Hardware / Firmware

GRBL 1.1

### What happened

See title and steps to reproduce

### How to reproduce

Open UGS, connect to GRBL. Set Jog controller units to inches (DRO now displays position in inches also).  Move the machine so it's not at 0.000 on one of the axes, and then click the DRO position readout for that axis in order to change it. The setting window pops up and shows the current position in the wrong units.  Setting a value here works (it applies the value set in whatever the DRO units are) so this is just an issue with the current value populated into the box before you change it.

### Anything else

I will take a look at the code and submit a fix for this.

**Comment by breiler** [comment]
Thanks for the fix @bertieconfundo
