### ISSUE TITLE
Pendant Exception - java.io.FileNotFoundException

### ISSUE THREAD

**Issue by Mgilbride** [winder/Universal-G-Code-Sender#193]
Maybe it's the nightly builds. But I have tried a couple different versions of 1.0.8 on several different machines. None of them spit out an IP address in the console.

**Comment by mustang967** [comment]
The exact same issue when working on a mac. I had tried everything to make the pendant work, finally I put the java file directly in the root or home folder ran it from there and it works like a charm.

**Comment by bummster** [comment]
Interesting tidbit. I am running the Feb 2nd nightly via Win7 64bit. 

I just couldn't get the IP address to pop up in the universal gcode sender console tab within the UI. Placing it in the root directory didn't help either. I had been starting the jar file by simply double clicking it and letting windows send it on to the java.exe via file type association. I gave the start-windows.bat a try after adding a the java.exe directory to the win7 path environment variable. And while the IP address and port still didn't pop in the UI, it did pop in the cmd.exe window. A cheerful "Listening on: http://192.168.1.140:8080" appeared.

This is probably all moot, but the default port is 8080. Just grab the ip address of your machine and use that ip address:8080 on your tablet/phone.

**Comment by DasWookie** [comment]
I'm seeing the exact same problem. If I put the JAR file in a directory of:
c:\Program Files\Universal gCode Sender\1.08\
Then the pendant server fails to produce the UI and displays the error:
2015-03-30 17:56:47.029:WARN:oejsh.DefaultHandler:
java.io.FileNotFoundException: C:\Program%20Files\UniversalGcodeSender\1.0.8\UniversalGcodeSender.jar (The system cannot
 find the path specified)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
{etc etc etc}

But, if run directly out of the root of the c: for c:\UniversalGcodeSender.jar it works.
