### ISSUE TITLE
interface and font scaling

### ISSUE THREAD

**Issue by chrwei** [winder/Universal-G-Code-Sender#194]
Using on a high DPI screen, like that of the Lenovo Yogi 2 Pro laptop, the fonts are all way to small to read.  many apps are using some sort of scaling, possibly a windows graphics layer setting.  I've only had the laptop 2 days so if I learn more about what needs done I'll post here.

I have so far only had the issue with programs built with java, but it seems inconstant. for instance the arduino IDE the menus and prefs screens are fine, but the toolbar is not.  with USG it's all too small, so maybe peak at how the arduino IDE is doing its prefs screens.

**Comment by BennettBenson** [comment]
This page was the first hit when google'ing unversal gcode sender font. I'm having the same issue. Just wondering if there is a fix for this. I'll keep looking.
Thanks,
Bennett

**Comment by chrwei** [comment]
I had so many issues so far widespread that I gave up and set the display to 1920x1080.

**Comment by winder** [comment]
I took a quick look and it seems like supporting this would require overhauling the GUI. Searching for "Swing high dpi" has a lot of results. Something like [this](http://stackoverflow.com/questions/26877517/java-swing-on-high-dpi-screen) might be a possible workaround.

**Comment by winder** [comment]
I think the platform version works with high dpi displays. The classic version might have to wait until Java9 fixes this issue at the library level.
