### ISSUE TITLE
Does not work on Raspberry PI 4 - Bullseyes

### ISSUE THREAD

**Issue by mathojojo** [winder/Universal-G-Code-Sender#1956]
### Version

2.0.11

### Hardware / Firmware

Grbl_ESP32

### What happened

I extracted the tar.gz and launched the ./bin/ugsplatform binary as should be done, but I get this error : 

`./bin/../platform/lib/nbexec: ligne 430: /home/pi/ugsplatform-pi/jdk/jdk8u275-b01-jre/bin/java: Aucun fichier ou dossier de ce type`

nbexec seems to not find the java binary in the /home/pi/ugsplatform-pi/jdk/jdk8u275-b01-jre/bin/ folder.

But its really strange, because the java binary is there like you can see in the following screenshot.
![ugs_error_ls](https://user-images.githubusercontent.com/16633360/184014683-83f6e019-11c0-44e7-9e08-500eef8c5b9d.png)

Any idea?

### How to reproduce

- Download v2.0.12 for RPi
- Extract the ugs-platform-app-pi.tar.gz file
- Launch ./bin/ugsplatform

### Operating System

Bullseye on RPI4

**Comment by sepiroth887** [comment]
works fine on pi4 with latest build, does require universal app zip file tho or build from source
