### ISSUE TITLE
fluidnc z probe module not working

### ISSUE THREAD

**Issue by dmbbender** [winder/Universal-G-Code-Sender#1962]
### Version

Other

### Hardware / Firmware

FluidNC

### What happened

I have a probe connected to my board that works with ugs 2.012 if I choose grbl but I am running fluidnc,  when I connect as fluidnc everything works great except the z probe?? 

### How to reproduce

connect a fluidnc board with a probe attached an try to use the probe module for z

**Comment by breiler** [comment]
The probe function is not yet implemented. I could add the same code as with the GRBL controller but I have no way of testing it.

**Comment by dmbbender** [comment]
I can test it if you would like. I have Fluidnc ver 3.4.4  if I connect as a grbl control and use the probe feature it works properly so I would expect it should work. I set up a macro for now!

**Comment by breiler** [comment]
It should be available in the latest nightly build, please report back if it is working properly.

**Comment by dmbbender** [comment]
It is not working correctly, sorry.  I am just going to use the macro G38.2 G91 F80 Z-20 P20; G00 Z10 M00  Thank you!

**Comment by daxliniere** [comment]
@dmbbender, by the way, in latest FNC, you can use G53 in your z-probe macro. Do a search on the FNC Discord server for details.

**Comment by nickmayer** [comment]
This was probably fixed by https://github.com/winder/Universal-G-Code-Sender/pull/2058. Let me know if that isn't the case.

**Comment by breiler** [comment]
I have verified that it is working on my test rig with UGS 2.1.4 and FluidNC v3.7.11
