### ISSUE TITLE
main screen freezes if I do not close 'task is done' message in time

### ISSUE THREAD

**Issue by dvdnhm** [winder/Universal-G-Code-Sender#197]
I usually clean the board when the job is done and I forgot to click to 'done' message.

In that case the main screen freezes and does not come back. I have to terminate it from task manager and start over.

**Comment by midow** [comment]
I am running 1.0.8[nightly] 2015-01-10 00:02:30 EST and get the same thing - after a file run, Gcode Sender sometimes (>50% time) freezes upon port close, and I have to kill the command window and restart it. So far it only does this when I try to close the port. Sometimes the port closes normally, but the majority of the time it freezes.
I had a number of problems, but all except that one went away when I moved the jar file to the root of my windows XP laptop.

**Comment by winder** [comment]
I changed the serial library used by UGS and that may help with this problem. Are you still experiencing it  >50% of the time? Could you try the nightly build tomorrow and see if it alleviates the problem?

**Comment by dvdnhm** [comment]
I am working on something else these days but I will try to spare some time to test it.

Thanks.
