### ISSUE TITLE
JAVA major.minor version error with 1.07 and JAVA 7

### ISSUE THREAD

**Issue by dan9thsense** [winder/Universal-G-Code-Sender#199]
I tried to update to version 1.07 (1.06 works fine) but get a Java unsupported major.minor version 51.0 error.  I tried re-installing Java 7 (full JDK which includes the RTE) and a reboot to no avail.  I am running Java 1.0.7_67 from Oracle on a win 7 machine.

Solved:  Java 6 remained installed even though the installer said it removed all other versions.  Manually uninstalling Java 6 fixed the problem and UGC 1.07 is working fine.

**Comment by DamnedHippie** [comment]
I know this problem is very old but how did you do to uninstall java 6? I don't know much about linux and I don't get how to see which different versions are installed.
