### ISSUE TITLE
Clicking "Run From..." from the editor should ensure the controller has the current program

### ISSUE THREAD

**Issue by BenFrantzDale** [winder/Universal-G-Code-Sender#1992]
### Version

2.0.12

### Hardware / Firmware

GRBL 1.1

### What happened

I spent tens of minutes trying to figure out why "Run From..." didn't work. Neither did "Send". Turns out, I hadn't saved the file. In an IDE if I say "build & run" it asks if I want to save everything first, with a checkbox to always save. That seems like much less cryptic behavior.

### How to reproduce

Open a blank file, add some lines of gcode, connect, say "Run From..." or "Send". Note that nothing happens. Save the file and try again. IT works.

### Operating System

macOS

**Comment by breiler** [comment]
A very valid request, thanks for the feedback and sorry for head banging.
