### ISSUE TITLE
When I Jog x y the status seem to remain green Jogging

### ISSUE THREAD

**Issue by cpapplefamily** [winder/Universal-G-Code-Sender#1997]
### Version

2.0.11

### Hardware / Firmware

GRBL 1.1

### What happened

When I Jog x y the status seem to remain green Jogging
![image](https://user-images.githubusercontent.com/16618289/193346450-93fb203e-5b52-4051-abed-0811a2448e96.png)

### Operating System

Win 10

### Anything else

Every time I jog x or y the system jogs and does follow the next jog request but the UI seems to lock up

**Comment by breiler** [comment]
Can we have your log file from here: `C:/Users/[your username>]/.ugsplatform/2.X/dev/var/log/messages.log`

**Comment by cpapplefamily** [comment]
[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/9690349/messages.log)

**Comment by breiler** [comment]
The log says it is out of memory. Please try the 64-bit Windows variant, version 2.0.12.

**Comment by breiler** [comment]
Closing as we did not get any response up from the user. If anyone else has this problem, make sure you have downloaded the 64-bit edition of UGS from here: https://github.com/winder/Universal-G-Code-Sender#downloads
