### ISSUE TITLE
No USB/Serial port option on OSX

### ISSUE THREAD

**Issue by ArketypeDesign** [winder/Universal-G-Code-Sender#1999]
### Version

2.0.12

### Hardware / Firmware

GRBL 1.1

### What happened

I have been running UGS successfully  on a Raspberry Pi3, but performance left a little to be desired, and I had access to a "retired" 2011 MacMini which is much snappier.

![Screen Shot 2022-10-02 at 6 17 06 PM](https://user-images.githubusercontent.com/53065162/193482092-800568db-41c6-4e9d-800a-07439cdcd6c3.png)

I cannot select a USB/ Serial port from UGS on the Mac, I only see "bluetooth" options.
I have opened the Sender options and set JSerialComm.

I am not running any other versions of Java.

i have tried both 2.012 and 2.09 versions of UGS with similar results.
Any help would be appreciated.

[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/9693836/messages.log)

### Operating System

OSX 10.13.6 High Sierra

**Comment by breiler** [comment]
Depending on what controller you are using you need drivers for it to be identified by the OS. But you need to know which USB chip it is using. In my case I have a couple of cheap chinese boards that uses CH340.

**Comment by breiler** [comment]
Closing as we didn't get any response from the user. This is also related to the hardware and its driver rather than UGS so there is not much we can do about it.

**Comment by ArketypeDesign** [comment]
Installed driver, and it is working! Thanks!
