### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by niteshkadyan** [winder/Universal-G-Code-Sender#2007]
### Version

2.0.12

### Hardware / Firmware

GRBL 1.1

### What happened

Unable to download. https://ugs.jfrog.io/ugs/UGS/v2.0.12/ugs-platform-app-linux.tar.gz redirects to https://ugs.jfrog.io/ui/login/ for login

### How to reproduce

Click on the download link

### Operating System

Linux

**Comment by breiler** [comment]
There is something wrong with jfrog again, please use the download links on the bottom part of this page:
https://github.com/winder/Universal-G-Code-Sender/releases/tag/v2.0.12

**Comment by Witawat** [comment]
> มีบางอย่างผิดปกติกับ jfrog อีกครั้งโปรดใช้ลิงค์ดาวน์โหลดที่ส่วนล่างของหน้านี้: https://github.com/winder/Universal-G-Code-Sender/releases/tag/v2.0.12

can't download file

**Comment by breiler** [comment]
@Witawat on the bottom part of that page, under the section assets.

**Comment by peterfalm** [comment]
Thank you so much, I have been really struggling to install UGS and now at last I have managed it thanks to you.
I don't know what's going on with that Frog site but it's a waste of time and so much time wasted trying to get that to work. 😀

**Comment by Tjhcncuser** [comment]
I'm also having trouble.
Which file at the end do I download?
After extracting which file do I select to install?
Thx

**Comment by breiler** [comment]
I have now updated all download links to use github instead of JFrog:
https://github.com/winder/Universal-G-Code-Sender#downloads
