### ISSUE TITLE
Window Controls not working on MacOS Ventura beta

### ISSUE THREAD

**Issue by sricks1** [winder/Universal-G-Code-Sender#2009]
### Version

2.0.12

### Hardware / Firmware

GRBL 1.1

### What happened

Launching UGS platform on Mac OS Ventura Beta, the main window draws, and you can click on a menu, it highlights, but nothing else.  Same with dropdown menus in the main window. Hitting the Port Sync button displays 1 item in the list, but drop-down does nothing.  Same with Baud.

### How to reproduce

Just open in MacOS Ventura Beta.

### Operating System

MacOS 13.0 Beta (22A5373b)

### Anything else

Occurs every time.  After a while nothing happens and window freezes.  Under Force Quit the app still show as running.  But the only way to quit is to Force Quit.

**Comment by fehguy** [comment]
Try the nightly. `20221222` works for me on 13.0.1

**Comment by breiler** [comment]
According to #2036 it should be working better with the 2.0.13 version
