### ISSUE TITLE
Can't open file .nc from fusion360 ?

### ISSUE THREAD

**Issue by Witawat** [winder/Universal-G-Code-Sender#2011]
### Version

2.0.12

### Hardware / Firmware

GRBL 1.1

### What happened

![image](https://user-images.githubusercontent.com/4926369/196685854-13fd5d08-8953-4e51-974d-98ee5582e8e9.png)

### Operating System

windows 10 64bit

**Comment by breiler** [comment]
That is an old problem that has been fixed, are you sure you are running version 2.0.12 of UGS?

**Comment by Witawat** [comment]
> That is an old problem that has been fixed, are you sure you are running version 2.0.12 of UGS?
yes 2.0.12

![image](https://user-images.githubusercontent.com/4926369/196703348-50b78f61-9dd0-4d07-b1fc-acb4ea4dd2ed.png)
![image](https://user-images.githubusercontent.com/4926369/196703460-fb916585-5928-4a8a-a059-ea6dce85c5c4.png)

**Comment by breiler** [comment]
Can you post your log files from `C:/Users/[your username>]/.ugsplatform/2.X/dev/var/log/messages.log`

**Comment by Witawat** [comment]
> Can you post your log files from `C:/Users/[your username>]/.ugsplatform/2.X/dev/var/log/messages.log`

[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/9820881/messages.log)
[messages.log.1.txt](https://github.com/winder/Universal-G-Code-Sender/files/9820886/messages.log.1.txt)
[messages.log.2.txt](https://github.com/winder/Universal-G-Code-Sender/files/9820887/messages.log.2.txt)

**Comment by breiler** [comment]
Can you send me a gcode-file that you have problems opening

**Comment by Witawat** [comment]
> 

[Uploading test.zip…]()

**Comment by breiler** [comment]
It is not possible do download.

**Comment by Witawat** [comment]
[test.zip](https://github.com/winder/Universal-G-Code-Sender/files/9820958/test.zip)
reupload

**Comment by breiler** [comment]
The file opened fine for me. 

Have you unpacked different versions of UGS on top of each other?
Because the code that generates this line `(test3)????1??test3` is old.

Try deleting the directory `D:\XSoFTz\Download\Compressed\ugs-platform-app-win64\ugsplatform-win\platform` and unzip it again.

**Comment by breiler** [comment]
Have you tried removing the old folder and tried unzipping the package again?

**Comment by Witawat** [comment]
> Have you tried removing the old folder and tried unzipping the package again?
yes i delete all file all version and delete 
C:\Users\XSoFTz-PC\.ugsplatform\
and download new file unzip and run
[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/9821304/messages.log)

**Comment by Witawat** [comment]
this step new run
![err1](https://user-images.githubusercontent.com/4926369/196720453-3a43f4e2-70d3-4cf0-bee9-60dd59d39f85.gif)

**Comment by breiler** [comment]
Very strange. By deleting the `C:\Users\XSoFTz-PC\.ugsplatform` folder you have also cleared any library caches, which would have been my next suggestion.

I have no idea what is going on...

**Comment by Witawat** [comment]
this error message  in visual mode ? , if not open visual moad no error ?
in version 2.0.11 have error , but old version can't download

**Comment by breiler** [comment]
Yes, and that is an indication that it is somehow running some old code. And I don't know how that is possible as you've deleted both the application folder and cache-directory.

We changed the separator from `?` to `¶¶` in #1897 to mitigate other problems. So the `(top)????1??top` should actually be `(top)¶¶¶¶¶¶¶¶1¶¶¶¶top` now.

**Comment by Witawat** [comment]
i download file on github now dowload on jfos.io is ok ?

**Comment by breiler** [comment]
Fixed in #2078

This is available now in the latest nightly build.
It will be available in the next release 2.0.13.
