### ISSUE TITLE
The rendering of the UI under Linux is faulty 

### ISSUE THREAD

**Issue by dasarne** [winder/Universal-G-Code-Sender#2049]
### Version

2.0.12

### Hardware / Firmware

GRBL 1.1

### What happened

When starting UGS under Linux, parts of the UI are not rendered. If you send an event to these elements (mouse over), they will be rendered. However, the objects do not remain up to date after that.
Resizing the window is blocking the UI.
![Screenshot_20221114_110304](https://user-images.githubusercontent.com/8106470/201633989-d89589cb-cda4-47fb-9553-22808832ac37.png)
![Screenshot_20221114_110420](https://user-images.githubusercontent.com/8106470/201634001-51d804a0-9118-409a-b2e6-570b5f768749.png)
![Screenshot_20221114_110607](https://user-images.githubusercontent.com/8106470/201634006-ff99a48e-a831-4715-b320-dccad1267438.png)
![Screenshot_20221114_110937](https://user-images.githubusercontent.com/8106470/201634010-f246cee0-2e97-4324-80db-94b418fdd403.png)

### How to reproduce

- Download Version 2.0.12
- `rm -rf ~/.ugs ~/.ugsplatform `
- Extract and start UGS
- The presentation of the UI is incorrect
- Resize the window
- The UI is unreachable

### Operating System

Kernel: 5.15.76-1-MANJARO arch: x86_64 bits: 64 Desktop: KDE Plasma     v: 5.26.2 Distro: Manjaro Linux

### Anything else

These warnings can be seen:
```
egrep: warning: egrep is obsolescent; using grep -E
egrep: warning: egrep is obsolescent; using grep -E
egrep: warning: egrep is obsolescent; using grep -E
egrep: warning: egrep is obsolescent; using grep -E
egrep: warning: egrep is obsolescent; using grep -E
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.ProxyURLStreamHandlerFactory (file:/home/arne/Schreibtisch/ugsplatform-linux/platform/lib/boot.jar) to field java.net.URL.handler
WARNING: Please consider reporting this to the maintainers of org.netbeans.ProxyURLStreamHandlerFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
The following messages can be found:
- [messages-1.log](https://github.com/winder/Universal-G-Code-Sender/files/10002028/messages-1.log)
- [messages.log](https://github.com/winder/Universal-G-Code-Sender/files/10002015/messages.log)

I'm using xorg-server 21.1.4-1

**Comment by breiler** [comment]
Please try the latest nightly build. I updated the OpenGL libraries which should resolve this problem.

**Comment by dasarne** [comment]
Thank you Joacim. 
Everything works perfectly! 

![Screenshot_20221114_131813](https://user-images.githubusercontent.com/8106470/201676858-c07913ed-7855-4517-a80f-387e978f1183.png)
