### ISSUE TITLE
Bug?? Toolbox missing from snapshot 2022-11-04

### ISSUE THREAD

**Issue by daxliniere** [winder/Universal-G-Code-Sender#2050]
### Version

Other

### Hardware / Firmware

Other (add details about it below)

### What happened

![image](https://user-images.githubusercontent.com/8109020/201787164-a5baf3f7-d810-490f-8907-172129dfcfaa.png)

### Operating System

Win 10 Pro N x64

**Comment by breiler** [comment]
Can you post your log file?

**Comment by breiler** [comment]
As you seem to have got it working in #2052 I assume that this is a settings-related problem. The settings problems will hopefully eventually get better as of version `2.0.13` as they will now share config directory between versions.

**Comment by daxliniere** [comment]
Unfortunately not, if you check the screenshots you can see 2022-11-04

**Comment by daxliniere** [comment]
Resolved in 2022-11-29 build.
