### ISSUE TITLE
Importing SVG on design sheet with wrong coordinates 

### ISSUE THREAD

**Issue by dasarne** [winder/Universal-G-Code-Sender#2055]
### Version

2.0.12

### Hardware / Firmware

GRBL 1.1

### What happened

The svg file "[Test.svg](https://user-images.githubusercontent.com/8106470/202260360-b0b6993d-41ea-4992-b2ff-cbf55f10479e.svg)" contains a rectangle with dimensions 50x70 mm. The coordinate origin in this file is at the bottom left.
![Screenshot_20221116_191304](https://user-images.githubusercontent.com/8106470/202260276-31545f19-2127-49e6-93e9-5cf9fbbee229.png)
When you import this svg file into a design, it has dimensions of 270x190 mm. The origin of the coordinates is in the upper left corner.
![Screenshot_20221116_191346](https://user-images.githubusercontent.com/8106470/202260306-b9c2dc3c-0bc5-460f-9ee9-0f553ec63a82.png)

### How to reproduce

You create a new design.
Then open the file "[Test.svg](https://user-images.githubusercontent.com/8106470/202260360-b0b6993d-41ea-4992-b2ff-cbf55f10479e.svg)". The representation of the rectangle is not correct.

### Operating System

Kernel: 5.15.76-1-MANJARO arch: x86_64 bits: 64 Desktop: KDE Plasma     v: 5.26.2 Distro: Manjaro Linux

**Comment by breiler** [comment]
Thanks for the report. I found some problems with some affine transformations that doesn't calculate the size correctly. There is also a couple of problems with line objects where the properties is all zeroed out. So there is a bit to work with.

**Comment by dasarne** [comment]
I tried to give you an easy example file. If you are ready, give me a hint, and I'll test it again. ![Emo-Press Eye](https://user-images.githubusercontent.com/8106470/202293622-b5f1cbbd-5a82-4d22-8fc4-0102517d9e3c.png)
