### ISSUE TITLE
Joystick settings not transferred in Snapshot 2022-11-29

### ISSUE THREAD

**Issue by daxliniere** [winder/Universal-G-Code-Sender#2067]
### Version

Other

### Hardware / Firmware

GRBL 1.1

### What happened

Joystick settings are not transferred to new version even when all config files are manually copied.

I'm sure it's related to this: https://github.com/winder/Universal-G-Code-Sender/discussions/2052
No idea how much else is affected.

**Comment by breiler** [comment]
I am closing this as 'will not fix'. We had to change the locations of the config files as this caused problems on some systems. There is no way for us to migrate the setting unfortunately. =(
