### ISSUE TITLE
Settings not being saved

### ISSUE THREAD

**Issue by Anachronicman** [winder/Universal-G-Code-Sender#210]
I am having an unusual problem where the settings are not being saved. This is under Windows 7

Can anyone point me to where they are saved so I can check if everything is being created correctly.

thanks.

**Comment by Darbness** [comment]
I had the same problem. My work around was to manually change the value. Ie send $200=100 to the controller.

**Comment by winder** [comment]
Are these GRBL settings or UGS settings which aren't being saved?

**Comment by Anachronicman** [comment]
They were UGS settings.

**Comment by winder** [comment]
Replace RXTX with JSSC: bd9a4781e4f83ea21f4457fbced7ce5d723d58df 017bbbf5b5e8e3fa03a6ea770fd42eae67788dfb 6931115a20c943583974067c560e7632e0844d54 2a3b1a0c502e78ba2e6e041b0b52a6a5cd16b19a

**Comment by winder** [comment]
I believe this was fixed a while ago
