### ISSUE TITLE
Arrow keys no longer jog machine

### ISSUE THREAD

**Issue by ArcAIN6** [winder/Universal-G-Code-Sender#2105]
### Version

2.0.11

### Hardware / Firmware

GRBL 1.1

### What happened

Upgraded to 2.0.11 (2.12 simply wouldn't open at all) (would also like to note that nowhere in the software is 2.0.11 spelled out, as it's calling itself 2.0-Snapshot?) luckily the zip had the version

Everything works fine, for the exception of using arrow keys to jog, looked in every setting screen i could find, and no "check mark" to enable jogging via KB, so headed into the key mapping section, and manually mapped them to the arrows.. .still no joy.. Tried to reverse the changes, but selecting "reset to default" doesn't actually do anything. 

Keyboard jogging is a massively under rated feature. as trying to use a mouse while looking at the machine tends to lead to drifting mouse position, and miss-clicks

### How to reproduce

1) Remove all files, and folders belonging to older version 
2) Remove associated files and folders from %appdata% of the older version
3) Unzip new version and run it
4) Click "keyboard" symbol in center of jog window
5) Click arrow key on keyboard
6) See that nothing happens
7) click arrows in jog window
8) watch machine move
9) repeat steps 4 & 5 to verify keyboard jogging is not working

### Operating System

Windows 10 64Bit

### Anything else

i can't really think of anything else... hope it's something simple, and doesn't take up too much time... nothing worse than yak shaving.

**Comment by ydeydier2** [comment]
On Universal Gcode Sender 20250108, I accidentally found that CTRL-UP, CTRL-DWN, CTRL-LEFT and CTRL-RIGHT allow you to move the carriage ! It's so convenient...

Hope this help...
