### ISSUE TITLE
Different streaming options for files

### ISSUE THREAD

**Issue by JaakkoFagerlund** [winder/Universal-G-Code-Sender#212]
I would like to see a couple of settings for streaming a file to a controller. At this point the UGS kind of presumes that there is grbl in the receiving end and seems to do serial buffer counting to send multiple lines beforehand and then sending more when the grbl sends 'ok' messages.

I would like to have options for how the file is sent, as I have some controllers that do not have the serial buffer size the same as grbl has and the UGS says to be 'universal'. So my suggestion would be an option to select if the file is sent one line at a time and waiting for 'ok' before sending the next one, this in addition to the current serial buffer counting method.

Also, an option for selecting the line ending would be nice. Like \r, \n, \r\n, \n\r to have some options for different controllers.

Or am I just blind and can't see these options anywhere is UGS?

**Comment by winder** [comment]
The main UGS profile is pretty tailored for GRBL at this point. The "universal" part of the name is mostly that the executable jar should work on just about any desktop computer. That said, it would be nice if the universal part also extended to other devices that accept gcode. I've coded the framework such that profiles for other types of controllers would be possible without too much trouble, but at this point those profiles don't really exist at this point.
