### ISSUE TITLE
How to open editor?

### ISSUE THREAD

**Issue by marshr32** [winder/Universal-G-Code-Sender#2120]
### Version

2.0.13

### Hardware / Firmware

GRBL 1.1

### What happened

Is there a way to get the editor on screen if I don't have it open when a new file is loaded?
I can't seem to find it in the menus

**Comment by breiler** [comment]
That feature is not available yet, but a reasonable suggestion.

**Comment by marshr32** [comment]
Awesome, cheers.
I tried adding the "editor" button to my toolbar but it doesn't seem to do anything?
