### ISSUE TITLE
UGS stops about every 10 minutes

### ISSUE THREAD

**Issue by bcnx** [winder/Universal-G-Code-Sender#2145]
### Version

2.0.11

### Hardware / Firmware

GRBL 0.8c

### What happened

So my job stops every 10 minutes (more or less) and I get the message "finished sending file in 00:09:33": I can resume by hitting the Play icon. Not sure what is going on. Wil test next with the classic version. 
Thanks for your insight. 

### Operating System

Linux Mint

**Comment by breiler** [comment]
Can you attach a sample gcode program. Is there a reason you are running GRBL 0.8, it is very old...

**Comment by bcnx** [comment]
Hi,
it's the version that came with the CNC board. It's my understanding that I cannot just flash it to a higher version as it requires changes in the hardware. Might consider a whole new board though. I don't think the problem is in the gcode (attached anyway), but in the USB port being put to sleep. I disabled power saving and even killed the power saving daemon, but still the same ...

Cheers!

[Uploading mc_fire_birds2_clean.txt…]()
BC

**Comment by breiler** [comment]
Something went wrong with your file upload, can you try and attach it again?

**Comment by breiler** [comment]
Closing we didn't get more information
