### ISSUE TITLE
Internal parser error: missing data

### ISSUE THREAD

**Issue by VovoNauta** [winder/Universal-G-Code-Sender#2155]
### Version

2.0.13

### Hardware / Firmware

GRBL 0.9

### What happened

When I try to apply to Gcode after load file, generate test data or Scan surface I get the error: Internal parser error: missing data.

### How to reproduce

[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/10706450/messages.log)

### Operating System

win10

### Anything else

When I try to apply to Gcode after load file, generate test data or Scan surface I get the error: Internal parser error: missing data.

**Comment by breiler** [comment]
Please try with version 2.0.19, make sure to double check your settings after upgrading:
https://github.com/winder/Universal-G-Code-Sender/releases/tag/v2.0.19

**Comment by breiler** [comment]
Closing as we got no further information
