### ISSUE TITLE
Seperate Step Size for X/Y and Z

### ISSUE THREAD

**Issue by shmorgan** [winder/Universal-G-Code-Sender#217]
Have different step sizes for X/Y and Z, On the shapeoko 2, this would help greatly to not drive the bit into the waste board.

**Comment by jahnj0584** [comment]
I agree. Kinda sucks moving Y/X by numerous 250mm jogs, then having to change it to 3 just to dodge a clamp or something.

**Comment by winder** [comment]
This is implemented in the classic and platform GUIs now.
