### ISSUE TITLE
UGS won't load

### ISSUE THREAD

**Issue by ebetts62** [winder/Universal-G-Code-Sender#2176]
### Version

Other

### Hardware / Firmware

GRBL 1.1

### What happened

program worked great... at first.  running on Liinux mint.  UGs version 2.0,12 on a Dell inspiron 10 laptop with intel core I3. now it doesnt completely load.
![Screenshot from 2023-03-14 16-32-02](https://user-images.githubusercontent.com/124218723/225129648-1df215fa-0553-43c3-9dac-b59f2d443ce4.jpg)
Tried reinstalling several times, but after one or two uses, it effectively freezes up at the point shown.  not sure what's causing it, but it seems to be after trying to use the visualizer.

### How to reproduce

Tried reinstalling several times, but after one or two uses, it effectively freezes up at the point shown. not sure what's causing it, but it seems to be after trying to use the visualizer.

### Operating System

linux mint

**Comment by breiler** [comment]
Please try UGS 2.0.14 or later.

**Comment by ebetts62** [comment]
> Please try UGS 2.0.14 or later.

found 2.0.13... didn't see .14.  seems to be working, so far...  thanks!
