### ISSUE TITLE
error while processing response <<alarm>>

### ISSUE THREAD

**Issue by Naoufeldiabi** [winder/Universal-G-Code-Sender#2185]
### Version

2.0.7

### Hardware / Firmware

GRBL 0.9

### What happened

when i just try to connect the machine with the icon above a notification shows below it says error while processing response <<alarm>>
i don;t exactly where the problem is ? whether in wiring the motors or the program 
please i need a help

**Comment by Naoufeldiabi** [comment]
![alarm](https://user-images.githubusercontent.com/129346154/228703626-9489573c-142e-432e-80b7-84b9b6259913.png)

**Comment by Naoufeldiabi** [comment]
![alarm2](https://user-images.githubusercontent.com/129346154/228703746-36e09990-ce1e-4cd4-916d-ff2c4b02f3db.png)

**Comment by breiler** [comment]
I found that the status string parser does not recognize the '<Alarm>' status message.

I think that I have fixed the problem and is available in the latest nightly build:
https://github.com/winder/Universal-G-Code-Sender#downloads

**Comment by breiler** [comment]
After private discussion with user the parser issue is now resolved (there was still a lot to be configured in GRBL but is not related to this bug report).

**Comment by Naoufeldiabi** [comment]
there is also a problem of moving right and left , up and down
how can i inverse that two icons mentioned

‫في الجمعة، 31 مارس 2023 في 6:58 ص تمت كتابة ما يلي بواسطة ‪Joacim
Breiler‬‏ ***@***.***‬‏>:‬

**Comment by breiler** [comment]
Read about the setting for inverting direction here:
https://github.com/grbl/grbl/wiki/Configuring-Grbl-v0.9#3--direction-port-invert-maskbinary

Or you can use the Setup Wizard in UGS:
https://github.com/winder/Universal-G-Code-Sender/wiki/Configuration#setup-wizard
