### ISSUE TITLE
Can't roll back from 2.0.16

### ISSUE THREAD

**Issue by daxliniere** [winder/Universal-G-Code-Sender#2203]
### Version

Other

### Hardware / Firmware

FluidNC

### What happened

After having 2.0.16 installed and experiencing problems, I tried to roll back to .13, .14 and .15 but all give this error message:

![image](https://user-images.githubusercontent.com/8109020/234011487-0676e03b-ab42-48b7-9ef4-11fb446e84d2.png)

### Operating System

Win10x64

**Comment by breiler** [comment]
The new processor for removing empty lines is not available in earlier version causing the configuration parser to crash. Removed it temporarily from the config and created a new version 2.0.17. Please upgrade to this version to be able to downgrade.
