### ISSUE TITLE
Visualizer does not show what i have designed in design editor

### ISSUE THREAD

**Issue by AbdelrahmanElayashy** [winder/Universal-G-Code-Sender#2211]
### Version

2.0.17

### Hardware / Firmware

GRBL 1.1

### What happened

Visualizer does not visualize what i have designed in design editor.

### Operating System

windows 10

**Comment by breiler** [comment]
It works for me, so I need a bit more information on how to reproduce this problem. 

If you are you importing DXF:s or SVG:s I want sample files. A log file might help as well which should be located at `C:/Users/[your username>]/AppData/Roaming/ugsplatform/var/log/messages.log`

**Comment by breiler** [comment]
Did not get response from user
