### ISSUE TITLE
Windows disapeared

### ISSUE THREAD

**Issue by Yonaskassa** [winder/Universal-G-Code-Sender#2214]
### Version

2.0.17

### Hardware / Firmware

GRBL 1.1

### What happened

Dears,
Why windows disapeared as per attached image and how to repair these issue.

![Screenshot_20230504_085215](https://user-images.githubusercontent.com/131940631/236530515-a6a0fce1-4b69-4506-aa96-c2c3bf0ce664.jpg)

**Comment by breiler** [comment]
Can you attach your log file located here:
C:/Users/[your username>]/AppData/Roaming/ugsplatform/var/log/messages.log

**Comment by Yonaskassa** [comment]
Here is attached.
I have two ugs versions on my laptop, Is it have a problem?
[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/11409072/messages.log)

**Comment by breiler** [comment]
It should be ok to have multiple versions, but only one can be open at a time.

I see a couple of errors in the log but those should not make the windows disappear. The settings may have been corrupt, try and delete all files under these directories:
```
C:\Users\Yonas.kassa\AppData\Local\ugsplatform\Cache\var\cache
C:\Users\Yonas.kassa\AppData\Roaming\ugsplatform
```

**Comment by Yonaskassa** [comment]
Dear,

Thanks now displayed.

Regards!
