### ISSUE TITLE
COM port connected but not active

### ISSUE THREAD

**Issue by Yonaskassa** [winder/Universal-G-Code-Sender#2222]
### Version

2.0.15

### Hardware / Firmware

GRBL 1.1

### What happened

Dear @breiler,

Why ugs connected but not active, I choose the right port and baud rate. I tried by Arduino IDE and its working properly I can Uploade the code without a communication problem, But When I use UGS some times connected and active. But most of the time it will not active. I am tired to get the exact problem Please support me. Is there any windows problem or setting to deactive the com port when I use UGS?

**Comment by breiler** [comment]
What hardware are you using, Arduino UNO or Arduino Mega?

Can you try and connect to the controller using the Arduino IDE:s serial monitor. After you connect you should get a welcome string. What does that say?

**Comment by Yonaskassa** [comment]
I am using Arduino Mega 2560,
Here is attached well come string after connecting arduino IDE.
But when am connecting to UGS its connected but not active.
![IMG_20230514_234124_981](https://github.com/winder/Universal-G-Code-Sender/assets/131940631/b4587991-18a9-451a-9201-971213222e12)

**Comment by Yonaskassa** [comment]
And here is attached what UGS saying.
Thank you for your usual support!

![IMG_20230515_000518_262](https://github.com/winder/Universal-G-Code-Sender/assets/131940631/7a81559b-7559-44cf-a7c2-e55f8b1fed12)
![IMG_20230515_000513_194](https://github.com/winder/Universal-G-Code-Sender/assets/131940631/04221ffb-7d0b-4a99-8139-d6becbfb7137)

**Comment by breiler** [comment]
This is not what I meant, I wanted you to use the Arduino IDE Serial Monitor to get the output from GRBL.

You now need to reflash GRBL to your controller, and since you are using an Arduino Mega you will have to make sure that you are using the GRBL suited for those controller board:
https://github.com/gnea/grbl-Mega or https://github.com/fra589/grbl-Mega-5X/

**Comment by breiler** [comment]
And you will need to use UGS 2.0.17 or later which contains a fix that is required to connect to Mega Controllers: https://github.com/winder/Universal-G-Code-Sender/releases/tag/v2.0.17

The nightly build also contains a fix for this that you requested previously:
https://github.com/winder/Universal-G-Code-Sender/issues/2209

The nightly version can be downloaded from here:
https://github.com/winder/Universal-G-Code-Sender#downloads

**Comment by Yonaskassa** [comment]
@breiler 
When I connect to Ugs the error displayed on Console which says '' An error was detected while sending '?': +CME ERROR: 100. Streaming has been paused. ''
And it disconnected by it self.

**Comment by breiler** [comment]
`+CME ERROR: 100` is nothing that comes from UGS or GRBL. Are you sure that you've connected to  your GRBL device and not a 3G/4G internet dongle?

**Comment by Yonaskassa** [comment]
@breiler 
Dear Sorry for my mistake, after many trial I got the problem by relating with other laptop working ugs.
I found the zip file didnot work downloaded on the recent 2023, and I took from other pc downloaded Ugs zip file on 2022 and its working smoothly, and know I do have 2 versions smoothly working v 2.0.14 and snapshot 2.0 03/09/2022. Thank You so much🙏
