### ISSUE TITLE
Homing sequence not working

### ISSUE THREAD

**Issue by VaibhavCreate** [winder/Universal-G-Code-Sender#2240]
### Version

2.0.17

### Hardware / Firmware

GRBL 1.1

### What happened

Hii, I have created my own 2 axis pen plotter, 
I used grbl 1.1.h firmware for it with cnc sheild v3 and an arduino UNO.
Then i attached two limit swtiches to x- and y- and choose IT AS Homing direction in setup wizard.
But now whenever i press on homing button the Controller state shows : HOME(green colour)
But nothing actually moves the axis becomes constant (i.e. I wasn't even able move it with hands).
And If I click unlock then Jog controller shows up It also doesn't respond,

If i restart everything also then it shows up ALARM in CONTROLLER STATE.

Any help is appriciated.

### Operating System

Windows 11

**Comment by breiler** [comment]
Normally the homing sequence includes the Z-axis which is the first axis to be homed. And since you are only using two axes this is probably what is failing.

Check your GRBL config: https://github.com/gnea/grbl/blob/master/grbl/config.h#L105

**Comment by VaibhavCreate** [comment]
Ohh yes but what should I do now???
Should I erase that part of code?

**Comment by VaibhavCreate** [comment]
> From the documentation it says that it will do `HOMING_CYCLE_0` then `HOMING_CYCLE_1`. The first homing cycle is required, the second optional. So you should be able to replace this:
> 
> ```
> #define HOMING_CYCLE_0 (1<<Z_AXIS)                // REQUIRED: First move Z to clear workspace.
> #define HOMING_CYCLE_1 ((1<<X_AXIS)|(1<<Y_AXIS))  // OPTIONAL: Then move X,Y at the same time.
> ```
> 
> with
> 
> ```
> #define HOMING_CYCLE_0 ((1<<X_AXIS)|(1<<Y_AXIS))
> ```

I have reuploaded the grbl with the changes you said,
But now also the machine is not responding to Jog ,homing or anything
When i tried jog with grbl controller Application,
It says " machine not idle"
Please tell what should I check next?

**Comment by VaibhavCreate** [comment]
![16880307088506960053611892554500](https://github.com/winder/Universal-G-Code-Sender/assets/102853578/9f20e127-df58-4874-9c15-2cc4d566b36d)
After using $X it shows idle , but when i click on Jog controller nothing changes or responds.

**Comment by breiler** [comment]
The Z position looks really off. 

Can you activate verbose logging in the console (right click and choose "Enable verbose logging") and paste a couple of lines of the output here.

**Comment by VaibhavCreate** [comment]
**** Connected to COM9 @ 115200 baud ****
>>> 0x18
Grbl 1.1h ['$' for help]
>>> $$
$0 = 10 (Step pulse time, microseconds)
$1 = 25 (Step idle delay, milliseconds)
$3 = 1 (Step direction invert, mask)
$2 = 0 (Step pulse invert, mask)
$4 = 0 (Invert step enable pin, boolean)
$5 = 0 (Invert limit pins, boolean)
$6 = 0 (Invert probe pin, boolean)
$10 = 2 (Status report options, mask)
$11 = 0.010 (Junction deviation, millimeters)
$12 = 0.002 (Arc tolerance, millimeters)
$13 = 0 (Report in inches, boolean)
$20 = 0 (Soft limits enable, boolean)
$21 = 1 (Hard limits enable, boolean)
$22 = 1 (Homing cycle enable, boolean)
$23 = 7 (Homing direction invert, mask)
$25 = 500.000 (Homing search seek rate, mm/min)
$26 = 250 (Homing switch debounce delay, milliseconds)
$27 = 1.000 (Homing switch pull-off distance, millimeters)
$24 = 25.000 (Homing locate feed rate, mm/min)
$30 = 1000 (Maximum spindle speed, RPM)
$31 = 0 (Minimum spindle speed, RPM)
$32 = 0 (Laser-mode enable, boolean)
$100 = 100.000 (X-axis travel resolution, step/mm)
$101 = 100.000 (Y-axis travel resolution, step/mm)
$102 = 0.000 (Z-axis travel resolution, step/mm)
$110 = 500.000 (X-axis maximum rate, mm/min)
$111 = 500.000 (Y-axis maximum rate, mm/min)
$112 = 500.000 (Z-axis maximum rate, mm/min)
$120 = 10.000 (X-axis acceleration, mm/sec^2)
$121 = 10.000 (Y-axis acceleration, mm/sec^2)
$122 = 10.000 (Z-axis acceleration, mm/sec^2)
$130 = 300.000 (X-axis maximum travel, millimeters)
$131 = 200.000 (Y-axis maximum travel, millimeters)
$132 = 0.000 (Z-axis maximum travel, millimeters)
>>> $G
ok
ok
GrblFeedbackMessage{message='[GC:G0 G54 G17 G21 G90 G94 M5 M9 T0 F0 S0]',
distanceMode='G90', units='G21'}
[GC:G0 G54 G17 G21 G90 G94 M5 M9 T0 F0 S0]
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0|WCO:0.000,0.000,2147483.648>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0|Ov:100,100,100>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0|WCO:0.000,0.000,2147483.648>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0|Ov:100,100,100>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0|WCO:0.000,0.000,2147483.648>
<Alarm|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0|Ov:100,100,100>

*I Hope this is what you asked for!

**Comment by breiler** [comment]
What does it say in the console when you press one of the jog buttons?

**Comment by VaibhavCreate** [comment]
<Idle|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Idle|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
>>> $J=G21G91X10F100
>>> $J=G21G91X10F100
>>> $J=G21G91X10F100
>>> $J=G21G91X10F100
>>> $J=G21G91X10F100
>>> $J=G21G91X10F100
>>> $J=G21G91Y-10F100

this is what I receive

**Comment by breiler** [comment]
You are not getting any OK-messages from the controller. Could either be some command buffer in UGS that has not been cleared or the controller is not well. 
Can you attach the log file from: `C:/Users/[your username>]/AppData/Roaming/ugsplatform/var/log/messages.log`


Have you tried restarting UGS?

**Comment by VaibhavCreate** [comment]
+
no, i just cropped ok message actually it was like this

OK
_<Idle|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Idle|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Idle|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Idle|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Idle|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0|WCO:0.000,0.000,2147483.648>
<Idle|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0|Ov:100,100,100>
<Idle|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>
<Idle|WPos:0.000,0.000,2147483.648|Bf:15,128|FS:0,0>_
>>> $J=G21G91X10F100
>>> $J=G21G91X10F100
>>> $J=G21G91X10F100
>>> $J=G21G91X10F100
>>> $J=G21G91X10F100
>>> $J=G21G91X10F100
>>> $J=G21G91Y-10F100

and i have restarted ugs 100 times , @breiler

**Comment by breiler** [comment]
Turn off verbose logging. Jog and show me the output from those commands.

**Comment by VaibhavCreate** [comment]
**** Connected to COM9 @ 115200 baud ****
Grbl 1.1h ['$' for help]
>>> $$
[MSG:'$H'|'$X' to unlock]
$0 = 10    (Step pulse time, microseconds)
$1 = 25    (Step idle delay, milliseconds)
$2 = 0    (Step pulse invert, mask)
$3 = 1    (Step direction invert, mask)
$4 = 0    (Invert step enable pin, boolean)
$5 = 0    (Invert limit pins, boolean)
$6 = 0    (Invert probe pin, boolean)
$10 = 2    (Status report options, mask)
$11 = 0.010    (Junction deviation, millimeters)
$12 = 0.002    (Arc tolerance, millimeters)
$13 = 0    (Report in inches, boolean)
$20 = 0    (Soft limits enable, boolean)
$21 = 1    (Hard limits enable, boolean)
$22 = 1    (Homing cycle enable, boolean)
$23 = 7    (Homing direction invert, mask)
$24 = 25.000    (Homing locate feed rate, mm/min)
$25 = 500.000    (Homing search seek rate, mm/min)
$26 = 250    (Homing switch debounce delay, milliseconds)
$27 = 1.000    (Homing switch pull-off distance, millimeters)
$30 = 1000    (Maximum spindle speed, RPM)
$31 = 0    (Minimum spindle speed, RPM)
$32 = 0    (Laser-mode enable, boolean)
$100 = 100.000    (X-axis travel resolution, step/mm)
$101 = 100.000    (Y-axis travel resolution, step/mm)
$102 = 0.000    (Z-axis travel resolution, step/mm)
$110 = 500.000    (X-axis maximum rate, mm/min)
$111 = 500.000    (Y-axis maximum rate, mm/min)
$112 = 500.000    (Z-axis maximum rate, mm/min)
$120 = 10.000    (X-axis acceleration, mm/sec^2)
$121 = 10.000    (Y-axis acceleration, mm/sec^2)
$122 = 10.000    (Z-axis acceleration, mm/sec^2)
$130 = 300.000    (X-axis maximum travel, millimeters)
$131 = 200.000    (Y-axis maximum travel, millimeters)
$132 = 0.000    (Z-axis maximum travel, millimeters)
>>> $G
ok
ok
[GC:G0 G54 G17 G21 G90 G94 M5 M9 T0 F0 S0]
>>> $X
[MSG:Caution: Unlocked]
ok
>>> $J=G21G91X10F100
>>> $J=G21G91Y10F100
>>> $J=G21G91X-10F100
>>> $J=G21G91Y-10F100
>>> $J=G21G91X10F100
>>> $J=G21G91X10F100
>>> $J=G21G91X10F100

AFTER turning off i received this
Please check @breiler

**Comment by breiler** [comment]
So you didn't receive OK:s after jog commands like you said, so either the communication is broken or your controller doesn't respond with ok:s.

Does your controller still report a Z-position with "2147483.648" after cold restarting it (replugging power and USB). Having a Z-position of 2Km seems unresonable and might break the position parsing.

**Comment by VaibhavCreate** [comment]
Yeah still it shows like this
![16880361717706863542630875143763](https://github.com/winder/Universal-G-Code-Sender/assets/102853578/01637d43-b5ef-4f1f-867c-681b97c801c4)

Work position : 0
Machine postion: 2147483.648

I don't know how i reached this no. But is there must be someway to reset it?

**Comment by breiler** [comment]
Might be som junk in eeprom?
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Commands#rst-rst-and-rst--restore-grbl-settings-and-data-to-defaults

Make sure to make a backup of all settings before running this.

**Comment by VaibhavCreate** [comment]
backup in what way and how? @breiler

**Comment by breiler** [comment]
By running this `$$`

**Comment by VaibhavCreate** [comment]
Ohh yesss! Thank you motors are working now
Should I now try to setup limit swtich,  soft limit and other stuff??? @breiler

**Comment by breiler** [comment]
Go for it!

**Comment by VaibhavCreate** [comment]
Thank you so much for time and guidance!
@breiler
