### ISSUE TITLE
Jog Contolller has greyed out commands after 2.0.18 update

### ISSUE THREAD

**Issue by gopifollower** [winder/Universal-G-Code-Sender#2245]
### Version

2.0.18

### Hardware / Firmware

GRBL 1.1

### What happened

I updated UGS Platform from 2.0.15 to 2.0.18. I use a Bluetooth connection to Arduino Uno with CNC Shield.
After the update and connection to the Bluetooth, the Jog Controller commands are grey. The Reset Zero is active only.
This problem exists on Windows 11 and OSX.

*** Connecting to jserialcomm://tty.BOTSYART-GR-Port:115200
>>> ?
ok
>>> $I
[VER:1.1h.20190830:]
[OPT:V,15,128]
ok
>>> $$
$0 = 5    (Step pulse time, microseconds)
$1 = 10    (Step idle delay, milliseconds)
$2 = 0    (Step pulse invert, mask)
$3 = 0    (Step direction invert, mask)
$4 = 0    (Invert step enable pin, boolean)
$5 = 0    (Invert limit pins, boolean)
$6 = 0    (Invert probe pin, boolean)
$10 = 3    (Status report options, mask)
$11 = 0.050    (Junction deviation, millimeters)
$12 = 0.050    (Arc tolerance, millimeters)
$13 = 1    (Report in inches, boolean)
$20 = 0    (Soft limits enable, boolean)
$21 = 0    (Hard limits enable, boolean)
$22 = 0    (Homing cycle enable, boolean)
$23 = 0    (Homing direction invert, mask)
$24 = 5000.000    (Homing locate feed rate, mm/min)
$25 = 500.000    (Homing search seek rate, mm/min)
$26 = 250    (Homing switch debounce delay, milliseconds)
$27 = 1.000    (Homing switch pull-off distance, millimeters)
$30 = 1000    (Maximum spindle speed, RPM)
$31 = 0    (Minimum spindle speed, RPM)
$32 = 0    (Laser-mode enable, boolean)
$100 = 160.400    (X-axis travel resolution, step/mm)
$101 = 160.684    (Y-axis travel resolution, step/mm)
$102 = 100.000    (Z-axis travel resolution, step/mm)
$110 = 12000.000    (X-axis maximum rate, mm/min)
$111 = 12000.000    (Y-axis maximum rate, mm/min)
$112 = 10000.000    (Z-axis maximum rate, mm/min)
$120 = 50.000    (X-axis acceleration, mm/sec^2)
$121 = 50.000    (Y-axis acceleration, mm/sec^2)
$122 = 1000.000    (Z-axis acceleration, mm/sec^2)
$130 = 2000.000    (X-axis maximum travel, millimeters)
$131 = 2000.000    (Y-axis maximum travel, millimeters)
$132 = 5.000    (Z-axis maximum travel, millimeters)
ok
>>> $G
[GC:G0 G54 G17 G21 G90 G94 M5 M9 T0 F0.0 S0]
ok

When I click on the Soft Reset button, the Jog Commands become active, not greyed out.
The Console window shows this response:

**Grbl 1.1h ['$' for help]**

### How to reproduce

UGS Platform v2.0.18. Arduino Uno with CNC Shield and GRBL 1.1h. Windows 11 or OSX. Establish a Bluetooth connection to the Arduino Uno.

### Operating System

Windows 11 Home Eddition, 64 or Max OSX Catalina, 10.15.7

### Anything else

This problem is permanent. 
Thank you in advance for help.

**Comment by breiler** [comment]
A lot has happened in UGS since version 2.0.18, please try again and reopen issue if the problem persists.
