### ISSUE TITLE
Incompatible with dxf2gcode exports

### ISSUE THREAD

**Issue by timint** [winder/Universal-G-Code-Sender#2258]
### Version

2.0.18

### Hardware / Firmware

GRBL 1.1

### What happened

Loaded a gcode file from dxf2gcode. UGS says coordinates are invalid because of whitespace after the axis letter.

### How to reproduce

Produce a GCode file containing whitespace in coordinates after the axis letter. E.g. "X   10.00"

### Operating System

Windows 11

**Comment by breiler** [comment]
I just tried it with a sample file found online somewhere and the only place that I get errors are in the editor. Was this what you meant?

![Screen Shot 2023-07-17 at 06 40 27](https://github.com/winder/Universal-G-Code-Sender/assets/8962024/20f56699-9711-4391-843a-e465c58d671a)

**Comment by timint** [comment]
Yes. Thank you for providing a screen shot. I was on mobile.

**Comment by breiler** [comment]
When using GRBL it will strip white spaces by default before sending it, so your regexp example should work just fine for viewing the gcode.

I'll make the adjustments to the parser, but that will take a couple of days since I am out of town.

Thanks for the bug report

**Comment by timint** [comment]
No rush, I'm just happy to bring bones to the table. :)

**Comment by breiler** [comment]
It should now be available in the latest nightly build here:
https://github.com/winder/Universal-G-Code-Sender#downloads
