### ISSUE TITLE
Better visualizer

### ISSUE THREAD

**Issue by winder** [winder/Universal-G-Code-Sender#226]
The replacing the yellow rectangle with a cone like chilipeppr would be nice.

The way [this page](http://nraynaud.github.io/webgcode/) has the orientation box and mini zero plane would also be nice.

**Comment by winder** [comment]
Other suggestions:

Add scales along each axis.
Create buttons to go to each of the three plane views.
Add measurement feature - "how deep is the cut at this point?"
Add mm or inches to Dimensions statement.

**Comment by winder** [comment]
Looks a lot nicer!

<img width="917" alt="visualizer" src="https://cloud.githubusercontent.com/assets/125509/13542000/e8df6bb6-e22d-11e5-8f2c-93c82399369f.png">

**Comment by shmorgan** [comment]
Do you have a downloadable version of the .jar file with this?

**Comment by shmorgan** [comment]
Look GREAT!!

**Comment by winder** [comment]
@shmorgan It is in the nightly UGS platform build: http://bit.ly/1DkClRW

**Comment by jahnj0584** [comment]
Can I assume this shows the job 0 VS where the spindle currently is? Is there a Jog To feature? I like it for making sure my material is in the right spot, when it comes to things with little spare and air cutting is boring.
