### ISSUE TITLE
universal gcode sender doesn't know how to setup this type of controller CNC

### ISSUE THREAD

**Issue by CalvinCaUK** [winder/Universal-G-Code-Sender#2274]
### Version

2.0.14

### Hardware / Firmware

GRBL 1.1

### What happened

I am trying to run the setup wizard but the message is that UGS doesnt recognize this type of controller
CNC Expansion Board, Akozon CNC Shield Expansion Board + 4Pcs A4988.
![image](https://github.com/winder/Universal-G-Code-Sender/assets/108428240/c277ad8f-c507-4b7c-8f39-2e3fa8f50967)
Arduino seems to communicate with it but UGS doesnt recognise it

### How to reproduce

I am setting up the CNC card for the first time and ran setup wizard

### Operating System

Windows 10

**Comment by breiler** [comment]
Please try the latest version 2.0.18 of UGS:
https://github.com/winder/Universal-G-Code-Sender#downloads

If you still have problems with the latest version I would like to know the output from the `$I` command.

**Comment by CalvinCaUK** [comment]
From $1 I get error 3 returned

**Comment by breiler** [comment]
Not `$1`, it should be `$I` as in `Info`.

**Comment by CalvinCaUK** [comment]
[VER:1.1h.20190830:]
[OPT:V,15,128]

**Comment by breiler** [comment]
No error messages in the console or anything?

Did you close the Arduino IDE's serial monitor?
