### ISSUE TITLE
FR: FluidNC protocol - error reporting

### ISSUE THREAD

**Issue by daxliniere** [winder/Universal-G-Code-Sender#2289]
### Description

Since the entire list of all alarms/statuses is sent from FNC during bootup. (enable verbose), it would be great that if, instead of displaying "ALARM:8" it would show "ALARM:8 - Command requires idle state".

**Comment by breiler** [comment]
This should be fixed in v2.0.21

**Comment by daxliniere** [comment]
Thanks so much, Joacim!
