### ISSUE TITLE
Separate GUI from model

### ISSUE THREAD

**Issue by winder** [winder/Universal-G-Code-Sender#230]
Use an [MVP](http://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93presenter) style GUI pattern to allow more flexible GUI experimentation. This is the first step towards a GUI refresh and could allow some neat features like multiple front-ends, better PendantUI's and hopefully an easy way to implement keyboard shortcuts.

**Comment by rugbymauri** [comment]
I like it!
