### ISSUE TITLE
autolevel bug position

### ISSUE THREAD

**Issue by lidershinobi** [winder/Universal-G-Code-Sender#2313]
### Version

2.0.20

### Hardware / Firmware

GRBL 1.1

### What happened

When the autolevel is opened, the min, max, and resolution positions work fine, but when closing the autolevel and reopening it and modifying the min, max, and resolution values, they are not updated in the viewer view. It does not matter when you open and close the autolevel when changing the values it does not update them in the display, so you have to close and open the program again. Another thing is that my printer is 350x350x160 in size and only half of it appears in the display. Add that the display accepts user sizes and it can be seen better in the display.

### How to reproduce

open the autolevel and edit the values and the values can be seen in the viewer, close the autolevel and open it again and repeat the same step to see if the values are modified in the viewer

### Operating System

windows 10 64bit

**Comment by breiler** [comment]
Thanks, I never noticed that before.

Regarding the view size, it will currently only adjust the view to the size of the model and not actual size of the machine. It should be possible to make the view size customizable. We have an issue with machines that is working in positive space that I think needs to be fixed first.
