### ISSUE TITLE
Support for grbl mega 5x

### ISSUE THREAD

**Issue by siboj** [winder/Universal-G-Code-Sender#2327]
### Description

Hi,

As i see UGS can work with grbl mega 5x, but problem is when you homing axis its only do for 3 axis. It would be nice to add full support for grbl mega 5x. I didn't test to much grbl mega 5x on UGS so i don't know what else is missing.

**Comment by breiler** [comment]
The homing is configured in the firmware. To add more axes you need to change the controller config, recompile and upload.
 
Have a look here: https://github.com/fra589/grbl-Mega-5X/blob/edge/grbl/config.h#L241

**Comment by siboj** [comment]
> The homing is configured in the firmware. To add more axes you need to change the controller config, recompile and upload.
> 
> Have a look here: https://github.com/fra589/grbl-Mega-5X/blob/edge/grbl/config.h#L241

What exactly to change?
My output is 
![image](https://github.com/winder/Universal-G-Code-Sender/assets/94691807/68637ae6-14f8-445d-8ddd-1ff9f95cd675)

**Comment by breiler** [comment]
That is not the output from homing. You are pressing "Return to zero", which moves the machine to the current work position zero. I do not want to extend this button to move additional axes, you will have to create your own macro button for that.
