### ISSUE TITLE
Visualizer not operational with v2.0.20

### ISSUE THREAD

**Issue by billyxmoto** [winder/Universal-G-Code-Sender#2328]
### Version

2.0.20

### Hardware / Firmware

GRBL 1.1

### What happened

gcode visualization not showing with v2.0.20, seems OKI with v 2.0.18

### How to reproduce

loaded usgplatform64.exe from version 2.0.20.  opened gcode file, no visualization
loaded usgplatform64.exe from version 2.0.18.  opened same gcode file,  visualization seems OK
see screen shots 

![v2 0 20](https://github.com/winder/Universal-G-Code-Sender/assets/61522556/720e4451-abe4-4598-8329-a5898aced19d)
![v2 0 18](https://github.com/winder/Universal-G-Code-Sender/assets/61522556/8656923b-4029-476a-a5cb-b9a50f9f6dcc)

### Operating System

WIN 10Pro 22H2 Thinkpad-T410 Intel(R) Core(TM) i5 CPU   

### Anything else

Consistent

**Comment by breiler** [comment]
Start the 2.0.20 version and then exit it. After that attach the messages.log file from:
`C:/Users/[your username>]/AppData/Roaming/ugsplatform/var/log/messages.log`

**Comment by breiler** [comment]
Closing as we didn't get a response
