### ISSUE TITLE
error on connection

### ISSUE THREAD

**Issue by dvdnhm** [winder/Universal-G-Code-Sender#234]
I am getting the error below when I hit "Open" button and the app terminates.

java.lang.NullPointerException at com.willwinder.universalgcodesender.JSSCConnection.serialEvent(JSSCConnection.java:122) 
at jssc.SerialPort$EventThread.run(SerialPort.java:1112) com.willwinder.universalgcodesender.GUIBackend setControlState
INFO: Sending control state change.

**Comment by dvdnhm** [comment]
this is all it shows, I ran it through command line the output ends with last info line

**Comment by winder** [comment]
Thanks for the report, this should hopefully be fixed in the next nightly build.

**Comment by dvdnhm** [comment]
I will test it once its available, thanks 

-----Original Message-----

**Comment by dvdnhm** [comment]
it works now.

PS: I think I havent thanked for the great app you created yet, great job. thanks
