### ISSUE TITLE
UGS stops sending and becomes unresponsive after javax.swing.text.StateInvariantError: document lock failure

### ISSUE THREAD

**Issue by treyd3** [winder/Universal-G-Code-Sender#2347]
### Version

2.0.21

### Hardware / Firmware

GRBL 1.1

### What happened

Loaded and started gcode file prepared with Kiri Moto. Job starts fine, no issues. After some minutes UGS becomes unresponsive and toolhead stops moving but spindle stays on (status remains "RUN" and action buttons are not responsive), presumably because controller stops receiving instructions. At this point the toolhead must be moved manually away from the stock and the controller restarted

### How to reproduce

I have attached the .ugsplatform directory and the gcode program zipped. I couldn't find this issue reported even though I experienced it in 2.0.15 as well. Hopefully it's some issue with my settings/env and easily remedied. 
[UGSconfigs_and_gcode.zip](https://github.com/winder/Universal-G-Code-Sender/files/13044815/UGSconfigs_and_gcode.zip)

### Operating System

Linux 5.15.76-v7l+ #1597 SMP Fri Nov 4 12:14:58 GMT 2022 armv7l GNU/Linux
Running on rPi 400 with 4GB ram and 64GB SD

### Anything else

This has happened a few times now including the last 2 times I tried to run the included gcode. It doesn't happen at the same point in the gcode program so I don't think that's the issue - especially since UGS throws an exception.
That said, when running the attached program, the issue occurred during the 1st Trace routine, once in the middle and once it made it to the M0 at the end where I change tools.

**Comment by breiler** [comment]
Thanks for the detailed report!

Never seen this error so I can't event guess what the problem may be.
I have made a new packaging with a newer Java which would be interesting if it would work better.

You can find it under nightly builds here (Linux ARM):
https://github.com/winder/Universal-G-Code-Sender#downloads

**Comment by cah-98** [comment]
I think i might be having the same issue. I never get an error however. Whenever i try to run a job it gets a few minutes in, different every time and then it just stops and keeps the spindle on. Still it reports the "Run" state while continuing to count the time in the Send Status counter. All controls are disabled and i have to restart the controller and reconnect to it to get it started again. For me this happens with all jobs i have tried so far. I have tried both in the nightly and 2.0.21 with GRBL 1.1f.

**Comment by cah-98** [comment]
I am running windows and it connects to a Genmitsu 3020-pro max. 

Here is my log file:
[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/13205997/messages.log)

**Comment by breiler** [comment]
Based on the log, it is not the same problem as described in this issue.
Please create a new discussion or a issue.

**Comment by breiler** [comment]
Closing as we got no further response from user
