### ISSUE TITLE
Shortcut keys for jog distance adjustment

### ISSUE THREAD

**Issue by goobering** [winder/Universal-G-Code-Sender#235]
When I'm fine tuning my starting point before hitting 'Reset zero' I generally start with the jog distance set to 1mm for coarse adjustment, then switch to 0.1mm for tweaks and nudges. I would like to see keyboard shortcuts which allowed me to quickly flick either straight to jog distances of 1mm and 0.1mm, or which divided/multiplied the jog distance by a factor of 10.

This might not make a tremendous amount of immediate sense for someone parked in front of a full keyboard. If, however, you combined this with the already-proposed customisable keyboard shortcuts then you can separate manual machine movement completely from the PC. Keyboard shortcuts are easy to send from Arduinos/external USB buttons/Raspberry Pis/whatever, opening up the possibility of having a small remote next to the workbed rather than schlepping back and forth to the GUI.

**Comment by winder** [comment]
Covered by #229
