### ISSUE TITLE
M30 Remover processor - not disabling

### ISSUE THREAD

**Issue by DushkaF** [winder/Universal-G-Code-Sender#2357]
### Version

2.1.0

### Hardware / Firmware

GRBL 1.1

### What happened

Hi! 
I make a GRBL fork and I want use M30 code. But UGS can't send it. I checked config files but I not find how fix it. Can you fix it?

### Operating System

Windows 11

![image](https://github.com/winder/Universal-G-Code-Sender/assets/55884192/f98f4a04-e624-43aa-9a4e-defa632e684a)

**Comment by breiler** [comment]
Open the firmware configuration file `c:/users/[your username]/.ugs/firmware_config/grbl.json` and change the value `optional` to `true` and `enabled` to `false`:
```
      {
        "name": "M30Processor",
        "enabled": false,
        "optional": true
      },
```

**Comment by DushkaF** [comment]
Thank you! This was the only negative when choosing your software; other not dead programs do not have convenient functionality, unlike UGS
