### ISSUE TITLE
Tool doesn't lift between pockets

### ISSUE THREAD

**Issue by Sofocletus** [winder/Universal-G-Code-Sender#2377]
### Version

2.1.2

### Hardware / Firmware

GRBL 1.1

### What happened

I'm having an issue where the tool path generated cuts through the material in between pockets, when the tool size is larger than a certain value. For example with a 1mm tool size there is a line connecting two pocket areas but with the toolpath set to 0.25 the tool lifts off the material correctly.
The design is from an imported SVG that looks OK in Inkscape, no open paths or broken nodes.
Any ideas on what may be going on?

![ToolpathBug1](https://github.com/winder/Universal-G-Code-Sender/assets/113308628/a5306bc1-6b9b-4398-9813-d24fb2631ea1)

![ToolpathBug2](https://github.com/winder/Universal-G-Code-Sender/assets/113308628/72c39bc2-1b38-470e-a5f7-30a3de3e4bf5)

**Comment by breiler** [comment]
What software are you using as a CAM?

**Comment by Sofocletus** [comment]
I generated the G-Code in UGS itself from an imported SVG design.
I replicated the issue in this file, it mostly happens when the tool diameter is relatively large.
[sample.zip](https://github.com/winder/Universal-G-Code-Sender/files/13575261/sample.zip)
![sample](https://github.com/winder/Universal-G-Code-Sender/assets/113308628/f904ec3f-8ddb-4df9-b8d1-ca26b84cb179)

**Comment by breiler** [comment]
I think that I got it working and is available in the latest nightly build.
