### ISSUE TITLE
smothieware on MKS Sbase don't work whith MAcOs

### ISSUE THREAD

**Issue by 303055** [winder/Universal-G-Code-Sender#2380]
### Version

2.1.2

### Hardware / Firmware

Smoothieware

### What happened

HI, smothieware on MKS Sbase don't work whith MAcOs , 
i try on Arduino IDE  /dev/c.usbmodem14401 and if I write G1 X10 the X axe move.

When I connect with UGS the terminal returns me this:

`Smoothie
Build version: edge-1a9c1b2, Build date: Oct 16 2018 17:28:56, MCU: LPC1768, System Clock: 100MHz
>>> version
**** Connected to tty.usbmodem14401 @ 250000 baud ****
Build version: edge-1a9c1b2, Build date: Oct 16 2018 17:28:56, MCU: LPC1768, System Clock: 100MHz
5 axis
>>> $G
[G0 G54 G17 G21 G90 G94 M0 M5 M9 T0 F20000.0000 S0.8000]`

When I try commands the motors do not move.
<img width="1170" alt="Capture d’écran 2023-12-07 à 18 10 01" src="https://github.com/winder/Universal-G-Code-Sender/assets/4411202/a8a3008a-fb9c-4fa8-a524-497173cc2a85">

is there specific firmware to put in the MKS sbase ? 

thank you 
Julien 

### Operating System

MacOS Monterey V12.7.1

**Comment by breiler** [comment]
I think that I am running a later version of Smoothieware (the CNC build) which seems to work ok

```
Smoothie
**** Connected to ttyACM1 @ 115200 baud ****
>>> version
Build version: edge-9fac8fc, Build date: Mar 21 2023 10:24:49, MCU: LPC1768, System Clock: 100MHz
  CNC Build 3 axis
NOTICE: This MCU is deprecated, and cannot guarantee proper function
Build version: edge-9fac8fc, Build date: Mar 21 2023 10:24:49, MCU: LPC1768, System Clock: 100MHz
>>> $G
[GC:G1 G54 G17 G21 G91 G94 M0 M5 M9 T0 F1000.0 S0.0000]
ok
```

**Comment by breiler** [comment]
Closing as we didn't get a response from the user.
