### ISSUE TITLE
Small text not generating g-code

### ISSUE THREAD

**Issue by garyemiller** [winder/Universal-G-Code-Sender#2416]
### Version

2.1.4

### Hardware / Firmware

GRBL 1.1

### What happened

Small fonts, like 4mm high, are not being rendered into g-code.

Sample:

[rellim-card.ugsd.txt](https://github.com/winder/Universal-G-Code-Sender/files/13814157/rellim-card.ugsd.txt)

### How to reproduce

Load the attached ugsd file.

### Operating System

Gentoo amd64 unstable

**Comment by breiler** [comment]
Your tool size of 0.5 mm is too thick to fit inside that tiny text to make pockets.
If you change the tool to a 0.2 mm endmill it would work better.
