### ISSUE TITLE
Program Persistence After Being Run

### ISSUE THREAD

**Issue by miguelmthomas** [winder/Universal-G-Code-Sender#242]
I posted this on the shapeoko forum a few days ago, you suggested that I post here. 

I was wishing for the ability to run the same program over and over, without the need to constantly reload. Not that its hugely difficult by any means, but it would be a nice option to have.

I am not much of a programmer, but I am more than happy to help, if there is something I can do to make this happen. 

Thank you for all of your hard work, it is greatly appreciated!

-Miguel

**Comment by winder** [comment]
I think this was addressed indirectly sometime in the past year. You can click send again after the job has finished to run the program over again.
