### ISSUE TITLE
Entering values in Inches sends measurements in mm.

### ISSUE THREAD

**Issue by sfmissionmark** [winder/Universal-G-Code-Sender#2429]
### Version

2.1.4

### Hardware / Firmware

GRBL 1.1

### What happened

Manually entering values via ui set buttons sends values as mm regardless of if you are in inch mode or mm mode.

### How to reproduce

Click value on X axis. Add value in inches. New value reflects mm.

### Operating System

ubuntu

**Comment by sfmissionmark** [comment]
I verified this behavior on todays nightly build.

**Comment by breiler** [comment]
Can you give me 
* Your settings from `$$`
* Your gcode parser state `$G`
* And your build version `$I`

**Comment by breiler** [comment]
Closing as I can't reproduce and did not get more information from user.
