### ISSUE TITLE
Platform file

### ISSUE THREAD

**Issue by omar-alzant** [winder/Universal-G-Code-Sender#2433]
### Version

2.1.4

### Hardware / Firmware

GRBL 1.1

### What happened

Cannot find platform file 

*****************************************************

![Screenshot 2024-01-21 170051](https://github.com/winder/Universal-G-Code-Sender/assets/70784310/1d3be32e-7c18-412c-8455-9b7de3796239)

### Operating System

Windows 10 - 64bit

**Comment by breiler** [comment]
Closing as we got no response from user.
