### ISSUE TITLE
More connection Issues ...

### ISSUE THREAD

**Issue by spock64** [winder/Universal-G-Code-Sender#2455]
### Version

2.1.5

### Hardware / Firmware

GRBL 1.1

### What happened

Trying to use UGS on a MacBook Pro / Ventura 12.7.3 with a CNC that works with cncjs ...

On connecting, I see a modal dialogue box stating: "There was a problem setting one or more controller features"

Here's a screenshot:

![image](https://github.com/winder/Universal-G-Code-Sender/assets/22578643/683ba1cd-0f06-4d13-b1c7-69b3e2e3cb2c)

There are no messages in the console window.

The message log shows something interesting - an exception is thrown after the fourth connection attempt:

```
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Connecting to GRBL on port tty.usbserial-1450
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Applying settings.
INFO [com.willwinder.universalgcodesender.utils.KeepAwakeUtils]: Moving the mouse location slightly to keep the computer awake.
INFO [com.willwinder.ugs.nbp.core.actions.ConnectDisconnectAction]: openclose button, connection open: false
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Connecting to GRBL on port tty.usbserial-1450
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Applying settings.
INFO [com.willwinder.universalgcodesender.utils.KeepAwakeUtils]: Moving the mouse location slightly to keep the computer awake.
INFO [com.willwinder.ugs.nbp.core.actions.ConnectDisconnectAction]: openclose button, connection open: false
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Connecting to GRBL on port tty.usbserial-1450
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Applying settings.
INFO [com.willwinder.ugs.nbp.core.actions.ConnectDisconnectAction]: openclose button, connection open: false
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Connecting to GRBL on port tty.usbserial-1450
INFO [com.willwinder.universalgcodesender.model.GUIBackend]: Applying settings.
com.willwinder.universalgcodesender.firmware.FirmwareSettingsException: Couldn't find setting with key: $22
	at com.willwinder.universalgcodesender.firmware.grbl.GrblFirmwareSettings.lambda$getValueAsBoolean$6(GrblFirmwareSettings.java:467)
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at com.willwinder.universalgcodesender.firmware.grbl.GrblFirmwareSettings.getValueAsBoolean(GrblFirmwareSettings.java:467)
```

Any ideas as to how to fix?

### How to reproduce

This happens each time a connection is made after loading UGS.

### Operating System

MACOS Ventura 12.7.3

**Comment by breiler** [comment]
I suspect that you have turned off status reporting which is causing this error message. I will probably remove that option in the future since status reporting is required for the communication to work nowdays.

![image](https://github.com/winder/Universal-G-Code-Sender/assets/8962024/6333f177-5ae8-41c0-9e01-9fced781b643)


Same issue as https://github.com/winder/Universal-G-Code-Sender/discussions/2453, fixed in https://github.com/winder/Universal-G-Code-Sender/pull/2454 which is available in the nightly build and in the next release 2.1.6.

**Comment by spock64** [comment]
Thanks - that was indeed the issue!
