### ISSUE TITLE
When you select two objects in UGS version 2.1.5, for instance, one with a depth of 5 cut type “On path,” and another with a depth of 1 Cut Type  “Pocket,” and then choose “Select All,” both objects transform Cut type   “Pocket” with a depth of 5.

### ISSUE THREAD

**Issue by garasimeria** [winder/Universal-G-Code-Sender#2477]
### Version

2.1.5

### Hardware / Firmware

GRBL 1.1

### What happened

When you select two objects in UGS version 2.1.5, for instance, one with a depth of 5 cut type “On path,” and another with a depth of 1 Cut Type  “Pocket,” and then choose “Select All,” both objects transform Cut type   “Pocket” with a depth of 5.

### Operating System

win 10

**Comment by breiler** [comment]
This should now have been fixed in #2525 and is available in the latest nightly build.
