### ISSUE TITLE
UGS Trace feature

### ISSUE THREAD

**Issue by cinci5** [winder/Universal-G-Code-Sender#2484]
### Version

2.1.6

### Hardware / Firmware

GRBL 1.1

### What happened

I went to check for clearance with endmill by jogging up on z then hit the model trace and it sets there and says calculating and never starts. Went back to 2.1.3 and it works fine.

### How to reproduce

Just try to trace the part (outline)

### Operating System

windows 10

### Anything else

all the time just stalls on calculating

**Comment by breiler** [comment]
Works fine for me, can you share your gcode file?

**Comment by breiler** [comment]
Closing as we didn't get any response from user
