### ISSUE TITLE
"Find" and "Replace" menu items grayed out

### ISSUE THREAD

**Issue by clydeshaffer** [winder/Universal-G-Code-Sender#2490]
### Version

2.1.5

### Hardware / Firmware

GRBL 1.1

### What happened

The "Find" and "Replace" options are grayed out under the "Edit" menu. I have a file loaded and wanted to search for certain strings but these appear to be disabled for some reason. If it's not because of a bug, it's at least unintuitive.

<img width="271" alt="image" src="https://github.com/winder/Universal-G-Code-Sender/assets/5910682/719cd703-13e6-4283-9e09-75f31e1c598b">

### How to reproduce

Opened a .nc file and opened the "Edit" drop down

### Operating System

Windows 11

**Comment by breiler** [comment]
Thanks for the report, I have tried activating those features previously without success. I guess that I will need to deep dive into Netbeans API:s again to figure this one out.

**Comment by breiler** [comment]
Available in the latest nightly build: https://github.com/winder/Universal-G-Code-Sender?tab=readme-ov-file#downloads
