### ISSUE TITLE
Designer Tool Settings are hard-coded - should be loaded from a config file

### ISSUE THREAD

**Issue by cybervegan** [winder/Universal-G-Code-Sender#2494]
### Description

When using the Design tool to compose a design, it doesn't remember your tool settings, so you have to make the same changes every time you use it, especially if you have a laser cutter or other type of machine with a fixed diameter tool. These settings seem to be hard-coded in the SettingsV1.java class file; It should be possible to either change them in Tools/Options,  simply have the settings remembered between sessions, or allow them to be edited by hand in a settings xml file.

**Comment by breiler** [comment]
I have moved the settings to the UGS global settings and is no longer stored in the design file #2527. I was also getting annoyed with having setting everything up for each design file.

Some settings could probably be moved back to the design file as a setting for each shape. For instance, you might want to use one shape as a roughing pass with a coarse stepover/feed/plunge/speed, and another shape with finer settings. But I am leaning towards keeping things really simple with less settings and options... We'll see how this feels.
