### ISSUE TITLE
Universal g-code sender doesn't want to open .gcode files and crashes when saving clipart

### ISSUE THREAD

**Issue by wmoscon1** [winder/Universal-G-Code-Sender#2513]
### Version

2.1.6

### Hardware / Firmware

GRBL 1.1

### What happened

Hello.. when trying to open .gcode or .ngc files, the program cannot load the files and closes the tab and does not load, in relation to the clipart, the moment I go to save it, it crashes the entire system, thanks.
Note: sorry for my English, I'm Brazilian

### How to reproduce

![image](https://github.com/winder/Universal-G-Code-Sender/assets/9651123/0d739bc0-6727-48d1-af15-e1019611a096)

### Operating System

Windowns 10

**Comment by breiler** [comment]
Can you share your log file? Go to the menu "Tools > Open log directory" and attach the ?` `messages.log` here.

**Comment by wmoscon1** [comment]
he follows..


[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/15228546/messages.log)

**Comment by wmoscon1** [comment]
If you want me to delete it and generate it again, just let me know.

Another thing... by chance it doesn't generate cash, maybe it would just be me cleaning it, because it worked on the other machine, but on the one I'm on it doesn't open. grateful

**Comment by wmoscon1** [comment]
![image](https://github.com/winder/Universal-G-Code-Sender/assets/9651123/b793df21-5766-4f4a-951c-80db99a0d41c)

**Comment by wmoscon1** [comment]
I managed to solve the problem, however, on the two machines I installed, the gcode clipart is not generated correctly.
grateful!!

**Comment by breiler** [comment]
What do you mean that the gcode clipart is not generated? Can you post a screenshot with the error?

**Comment by wmoscon1** [comment]
When I create clipart, for example, I place an ant, when I send it to the machine it asks to save what was done and then generates a gcode without positions.


![image](https://github.com/winder/Universal-G-Code-Sender/assets/9651123/2408839a-c26d-48c0-a1dc-e87d12b115b0)


![image](https://github.com/winder/Universal-G-Code-Sender/assets/9651123/a048004c-f5fe-4050-a71d-f2912b393aec)

Or of course, it could be me who doesn't have much experience with the application yet.

grateful

**Comment by breiler** [comment]
Ah, select the ant shape and set the cut type and the target depth. Then press save and you should see it in the 3D visualiser.

**Comment by wmoscon1** [comment]
Thank you very much, it worked!

**Comment by wmoscon1** [comment]
One more question, how do I increase the memory consumed by the application?
Why does the app crash a lot when manipulating it!

**Comment by breiler** [comment]
Can I have a fresh log file?

**Comment by wmoscon1** [comment]
Of course, follow..

[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/15253456/messages.log)

**Comment by breiler** [comment]
I don't think that memory is an issue, from the log I can see that it will use up to 8Gb which is more than enough to be able to run UGS. Next time it crashes, post the latest log file from the directory `C:\Users\wmosc\AppData\Roaming\ugsplatform\var\log\`

**Comment by wmoscon1** [comment]
I had to close it now through the task manager because it didn't respond, here's the most recent generated file...

[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/15253580/messages.log)

**Comment by wmoscon1** [comment]
The moment I resize the image it stops responding

**Comment by wmoscon1** [comment]
Here it got stuck right when the image was being resized, it was shrinking the image.

![image](https://github.com/winder/Universal-G-Code-Sender/assets/9651123/d4ade1b4-9e15-4414-a748-c448bbebca69)

**Comment by wmoscon1** [comment]
The application stops responding.

![image](https://github.com/winder/Universal-G-Code-Sender/assets/9651123/341fc07f-e083-4268-9380-16a0b99b249d)

**Comment by breiler** [comment]
Did you import a DXF or SVG file? May I have the source? It looks like it contains a lot of points which could explain this problem.

**Comment by wmoscon1** [comment]
I imported a png, an image, this would be the one below.

![monica-01](https://github.com/winder/Universal-G-Code-Sender/assets/9651123/6376314f-01b3-4599-8f9a-398ec7a33067)

**Comment by wmoscon1** [comment]
the site won't let me load the file that ugs saves.

**Comment by wmoscon1** [comment]
![image](https://github.com/winder/Universal-G-Code-Sender/assets/9651123/e9fb2254-293a-4532-ad27-507d71335c1e)

![image](https://github.com/winder/Universal-G-Code-Sender/assets/9651123/102ee6e3-a475-48e6-9ea6-dd9ab77177f9)

**Comment by breiler** [comment]
I understand, the settings you were using will create very many small tiny objects which UGS will have problems applying the scaling operation to. 

I think that if you wanted to carve this it will take a loooong time. So the key is to simplify. 

* Generally you want as few layers as possible, otherwise you will cut the same shape multiple times.
* Color quantization is how the colors will be grouped together.
* Smothing of lines, curves and filter noise will remove small imperfections in the image (such as compression artefacts on JPGS)
* Blur will further simplify the vector result.

With these settings I get somewhat more usable vector graphics:
![image](https://github.com/winder/Universal-G-Code-Sender/assets/8962024/fa769e31-1706-4e55-bc99-481a1f40745e)
![image](https://github.com/winder/Universal-G-Code-Sender/assets/8962024/c100820b-fa9f-4f12-959e-b419467d1d2f)

**Comment by wmoscon1** [comment]
Perfect... thank you very much for your help.

**Comment by wmoscon1** [comment]
![Uploading 17152862996377250552564382332662.jpg…]()

**Comment by wmoscon1** [comment]
For some reason it was unable to generate the design when passed to the machine, it was lost.




![IMG_20240509_173557](https://github.com/winder/Universal-G-Code-Sender/assets/9651123/c920d29c-9109-4f35-804e-02229db3ad72)

**Comment by wmoscon1** [comment]
![IMG_20240509_205210](https://github.com/winder/Universal-G-Code-Sender/assets/9651123/ff44809e-5bea-43bd-a572-6300ffbf0a26)

**Comment by breiler** [comment]
I am closing this as it seems that you are up and running.
