### ISSUE TITLE
Unable to load Gcode, visualizer partially updates.

### ISSUE THREAD

**Issue by alum22** [winder/Universal-G-Code-Sender#2519]
### Version

2.1.6

### Hardware / Firmware

GRBL 1.1

### What happened

UGS works fine except when loading gcode with an .nc file. The visualizer updates to show the outer dimensions of the program, but no paths are show. The status changes and an error shows up in the lower right status bar. When I click it, it shows an error (see attached screenshot).

![UCS_ERROR](https://github.com/winder/Universal-G-Code-Sender/assets/103654914/46a8489b-418a-452c-9959-8cefc64dd023)

### How to reproduce

With UGS on, I navigate to File>Open. I open any .nc file (I generate my gcode programs from Fusion 360).

The Visualizer flashes and the error appears. The visualizer dimensions change to that of the program, but no paths are shown 0 lines are loaded.

### Operating System

Windows 10 Pro, Version 22H2

### Anything else

Everytime. I am unable to load an .NC file

**Comment by breiler** [comment]
Can you share your log file. Open them menu "Tools > Open log folder" and attach the messages.log here.

Can you also share your gcode file.

**Comment by breiler** [comment]
Looks like the settings have become corrupt, try deleting the folder `C:\Users\User\AppData\Roaming\ugsplatform` and start UGS again.

**Comment by alum22** [comment]
Unfortunately, it is giving the same error.
![UCS_ERROR](https://github.com/winder/Universal-G-Code-Sender/assets/103654914/3467abd5-a23e-4ceb-a9ff-91bcb9aac8e5)

**Comment by breiler** [comment]
Can you post a new log file

**Comment by alum22** [comment]
Yes, of course
[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/15308497/messages.log)

**Comment by breiler** [comment]
Still looks like the settings are corrupted.

UGS is looking for some files under C:\Users\User\Downloads\win64-ugs-platform-app-2.1.6\ which I assume is the old location. You have now moved all files to "C:\Program Files\ugsplatform-win\".

Shut down UGS and delete the folders: `C:\Users\User\AppData\Roaming\ugsplatform` and possible `C:\Users\User\AppData\Local\ugsplatform\Cache\var\cache` again.

**Comment by alum22** [comment]
That did it!! Thank you so much!
