### ISSUE TITLE
Default unit and macros not saved

### ISSUE THREAD

**Issue by Jibeji** [winder/Universal-G-Code-Sender#253]
Hello,
I have an issue with the default units (with both 1.0.8 and 2.0 on Windows).
At first startup, a json file is created with:
"defaultUnits": "inch"

Clicking on the Millimeters radio button works on the GUI but the parameter is not saved in the json file.
Changing the json file to "defaultUnits": "mm" does not even work, it is ovewritten with "inch".

Plus, the macros are not saved.
The json file timestamp changes, it is not a write permission issue.

**Comment by winder** [comment]
I believe this is fixed in the nightly build.

**Comment by Jibeji** [comment]
It is!
Thank you.
