### ISSUE TITLE
Lines in File, Lines Sent/Remaining

### ISSUE THREAD

**Issue by JC-1959** [winder/Universal-G-Code-Sender#2530]
### Version

2.0.13

### Hardware / Firmware

GRBL 1.1

### What happened

Since v2.0.13 and all releases since, I cannot find one that give consistently accurate Line count for Lines in File, Sent & Remaining both in the Send Progress Window and on the bottom Status Line.

### Operating System

Win 10/11

### Anything else

Occurs every time file loaded
![image](https://github.com/winder/Universal-G-Code-Sender/assets/171044526/8aeb8b00-7409-45d9-8197-aefab3e0c0d8)
![image](https://github.com/winder/Universal-G-Code-Sender/assets/171044526/f0be63cd-d21f-4a5e-9487-1546f09372d7)
![image](https://github.com/winder/Universal-G-Code-Sender/assets/171044526/486aaa46-b491-4bd1-bf05-5af5658123f4)

**Comment by breiler** [comment]
Version 2.0.13 is ancient. I can't reproduce the problem in version 2.1.7
