### ISSUE TITLE
Falha na instalação

### ISSUE THREAD

**Issue by diogo-alves13** [winder/Universal-G-Code-Sender#2548]
### Version

2.1.7

### Hardware / Firmware

GRBL 1.1

### What happened

Tenho um notebook com windows 10 e quando tento instalar o UGR aparece uma mensagem com a seguinte informação "Não pode ser executado a partir de uma pasta que contém caracteres não ASCII no caminho"

### How to reproduce

Qual a incompatibilidade do instalador
![Screenshot_20240613-160750-905](https://github.com/winder/Universal-G-Code-Sender/assets/96754838/9ef8fce5-a452-4985-b105-b533f81b17b2)

### Operating System

Windows 10

**Comment by breiler** [comment]
You get this error if any directory in the path contains "special" characters such as áéåäö. Move it to another folder.

**Comment by diogo-alves13** [comment]
Em quais pastas devo procurar ?

**Comment by diogo-alves13** [comment]
Fiz o teste com o mesmo arquivo em outro notebook e funcionou

**Comment by breiler** [comment]
Any folder leading up to the folder that you placed UGS in. If you gave me the complete path I could point it out for you.

**Comment by diogo-alves13** [comment]
Consegui resolver, a pasta área de trabalho estava no caminho porque uso o onedrive. Restaurei o caminho para padrão e funcionou.

Muito obrigado.
