### ISSUE TITLE
Visualizer doesn't work if you open the visualizer after opening the gcode file.

### ISSUE THREAD

**Issue by lagnat** [winder/Universal-G-Code-Sender#2570]
### Version

Other

### Hardware / Firmware

FluidNC

### What happened

With version 2.1.8.  It's not one of the choices on the bug reporting screen.

- Launch UGS
- Close the visualizer
- Open gcode file
- Show the visualizer

The visualizer will resize and show coordinates however the tool path is not shown and the inch/mm button doesn't do anything.

### How to reproduce

See above

### Operating System

MacOS, Ubuntu

### Anything else

I can send you a screen recording of the problem if you would like to see it.  100% reproducible.

**Comment by breiler** [comment]
Thanks for the report, it was easy to reproduce so no need to add a screen recording.
