### ISSUE TITLE
Reset X/Y/Z Axis buttons can not be translated

### ISSUE THREAD

**Issue by Jibeji** [winder/Universal-G-Code-Sender#259]
Hi,
While working on the French translation, I noticed Reset X/Y/Z Axis captions can not be translated, the variable names are missing.

**Comment by Jibeji** [comment]
Plus,

mainWindow.swing.activeStateLabel
gcodeTable.command
gcodeTable.sent
gcodeTable.done
gcodeTable.response

are not taken into account.

**Comment by winder** [comment]
This is finally resolved, new parameters:

mainWindow.swing.resetX = Reset X Axis
mainWindow.swing.resetY = Reset Y Axis
mainWindow.swing.resetZ = Reset Z Axis

I'm also trying out a new service to help maintain the translations: https://poeditor.com/join/project/2J2hB5I41Z
