### ISSUE TITLE
"Return to zero" issue

### ISSUE THREAD

**Issue by Jibeji** [winder/Universal-G-Code-Sender#263]
Hi,
Tried the latest release," Return to Zero" goes on Machine's Zero position, not to the position defined by "Reset Zero".

**Comment by Jibeji** [comment]
I guess I should use "G90 G0 X0 Y0" instead of the "G90 G53 X0 Y0" which is sent when the button is clicked.
One more macro. ;)

**Comment by winder** [comment]
I'd like to improve this workflow in the future.
