### ISSUE TITLE
UGS Quit working  entirely

### ISSUE THREAD

**Issue by waynek** [winder/Universal-G-Code-Sender#264]
I have been using the UGS for sometime.  Was working this morning, now nothing comes up when I attempt to open .jar.
If I go to task manager it says its running but nothing appears on screen.. running win 8,1

**Comment by winder** [comment]
Your config file might have gotten corrupted. If you go to "%userprofile%" in a file brower and delete "UniversalGcodeSender.json" see if that fixes it.
