### ISSUE TITLE
Visualizer is not working

### ISSUE THREAD

**Issue by Kibris1977** [winder/Universal-G-Code-Sender#2642]
### Version

2.1.9

### Hardware / Firmware

GRBL 1.1

### What happened

I create a new design and put in the cutting requirements but the visualizer dose respond and i cant send to the machine. 

### How to reproduce

using the new design function create and design, input the cutting requirements.  The visualizer should show the model of the design but in the visualiser window there is nothing apart from the view cube.

### Operating System

windows 11

### Anything else

I have tried reinstalling but its still the same.

**Comment by breiler** [comment]
Can you attach the ugsd-file for your project?

**Comment by Franckapik** [comment]
I have also empty visualiser sometimes when i change my windows apparence...

**Comment by breiler** [comment]
Closing as we did not get any response from user
