### ISSUE TITLE
Keyboard Movement active in file open dialogue

### ISSUE THREAD

**Issue by typ-o** [winder/Universal-G-Code-Sender#266]
Hi!

If I'm going to load a new file, and try to navigate through the files shown in file open dialogue, any cursor usage will move the machine. This is dangerous. 

/UniversalGcodeSender-v1.0.8/UniversalGcodeSender.jar
Native lib Version = RXTX-2.1-7
Java lib Version   = RXTX-2.1-7

Thank you for Your work, I'm happy to use UGCS!

**Comment by jahnj0584** [comment]
Is this still an issue? I dont think it is.

**Comment by breiler** [comment]
Yes this is still an issue with the classic version when keyboard movement is active.

**Comment by breiler** [comment]
Duplicate of #124
