### ISSUE TITLE
Clear button for Table/Console

### ISSUE THREAD

**Issue by winder** [winder/Universal-G-Code-Sender#268]
Allow the Table/Console to be cleared.

**Comment by jahnj0584** [comment]
Can it be configurable? Like, #$101= so we always see the current $101 setting, and it doesn't display the constant y-100/y100 commands we send through when doing a calibration?

**Comment by winder** [comment]
Actually the console has a maximum size now and the table can be disabled so this issue is kind of resolved. It might be possible to hide jogging movements, but I'm not sure I'd want to hide active commands.
