### ISSUE TITLE
On the fly feed adjustments

### ISSUE THREAD

**Issue by winder** [winder/Universal-G-Code-Sender#269]
When streaming a file have a % override that will scale feed rates up/down while sending the file

**Comment by jahnj0584** [comment]
I was talking to my friend about this too. Sometimes I make a code, but switch wood types and know I can run it quicker, or I also want to just mill a slot at different rates to see what my machine will stop being accurate in the name of rapid waste removal. Maybe just a slide or % button to modify it? Its just a matter of editing the .nc's feed speed, right?
