### ISSUE TITLE
Gui enhancements

### ISSUE THREAD

**Issue by Crazydoub** [winder/Universal-G-Code-Sender#279]
Hi!
I've made some modifications to your code From 2.0 nightly.
Buttons for macro are on Machine Control panel.
They automatically activate/deactivate and change of name if they are set or not.
It would be great to add this feature to your future release and so have all commands on same panel.
You could also link keyboards keys to Macro buttons...
![gcode1](https://cloud.githubusercontent.com/assets/6761932/8674090/d9766378-2a3b-11e5-881c-a22d5e8da29d.png)
![gcode2](https://cloud.githubusercontent.com/assets/6761932/8674094/de2981f2-2a3b-11e5-9001-f919a3f4c0cd.png)

I can send you modifications :D

**Comment by Jibeji** [comment]
Bonjour,
Pretty good!
Just a suggestion, a caption for the button could be better than the Gcode.
As an example, one of my macro is:
G21;G91 G38.2 F20 Z-45; G92 Z+1.5; G91 G0 Z1.5 (Z-probe)
Not sure it will fit... ;)

**Comment by Crazydoub** [comment]
My scrit take the 18 first letters of the gcode ;) but caption would be great yes!

Envoyé par TypeMail



Sur 15 juil. 2015 11:49, à 11:49, Jibeji <notifications@github.com> a écrit:

**Comment by winder** [comment]
Great idea. There are utility functions in UGS to pull out just the comment, I think that would be perfect for the button text.

Do you have a public fork of UGS with these changes in it?

**Comment by Crazydoub** [comment]
I got modified source biy dont understand how to post it on github...

Envoyé par TypeMail



Sur 14 sept. 2015 17:43, à 17:43, Will Winder <notifications@github.com> a écrit:
