### ISSUE TITLE
Windows 10 can't open Serial Port

### ISSUE THREAD

**Issue by shining01** [winder/Universal-G-Code-Sender#286]
I have tested Universal G Code Sender 1.08 and 2.0 both can't open the serial port.
Nullpointer Exception. I have tested several Windows 10 Systems.

**Comment by winder** [comment]
Could you run from a terminal and copy the full stack trace into this issue? Unfortunately I don't have a Windows 10 machine available right now.

**Comment by shining01** [comment]
Sorry i was on holidays. Yes i can do. I send you the stack trace this week. Thanks a lot.

**Comment by clockfort** [comment]
fwiw, UGS 1 and 2.x trunk both work for me on Windows 10
