### ISSUE TITLE
Using UGS on old XP laptop

### ISSUE THREAD

**Issue by tapnair** [winder/Universal-G-Code-Sender#289]
I was trying to revive an old laptop to run UGS on and leave in the garage.  

It has WIndows XP SP3 , Java 7_79
When i run UGS either from the bat file or by double clicking the jar file it jsut completely freezes my system.  Even ctrl-alt-del won't wake it up.  Have to do a hard reset.

Any thoughts?

Update.  Tried both UGS 1.7 and 1.8 both freeze computer at same place.  When it displays:
INFO: loading settings
Stable library
/========================
Native lib version = RXTX-2.1-7
Java lib Version = RXTX-2.1-7

At that point system becomes non-responsive.

**Comment by winder** [comment]
Does 2.0 freeze also? Thats really strange, I haven't seen any startup freezes before. Maybe Java 8 is better on Windows XP.
