### ISSUE TITLE
mm settings not restored

### ISSUE THREAD

**Issue by nathanwosborn** [winder/Universal-G-Code-Sender#292]
1.0.8 on Ubuntu 14.04 LTS

mm settings (in machine control) are stored to the .json file (as "mm"), but not restored on next run.
Message printed at startup follow:
Boot] INFO:  myJarPath=file:/home/nathano/UniversalGcodeSender-v1.0.8/UniversalGcodeSender.jar
[JarClassLoader] INFO:  setProperties(com.simontuffs.onejar.JarClassLoader@2a8f5fc2)
[JarClassLoader] INFO:  oneJarPath=file:/home/nathano/UniversalGcodeSender-v1.0.8/UniversalGcodeSender.jar
[Boot] INFO:  using JarClassLoader: com.simontuffs.onejar.JarClassLoader
[JarClassLoader] INFO:  oneJarPath=file:/home/nathano/UniversalGcodeSender-v1.0.8/UniversalGcodeSender.jar
[JarClassLoader] INFO:  findResource(): unable to locate "resources/MessagesBundle_en.properties"
Sep 14, 2015 11:36:10 AM com.willwinder.universalgcodesender.SettingsFactory loadSettings
INFO: Loading settings.
Sep 14, 2015 11:36:10 AM com.willwinder.universalgcodesender.SettingsFactory loadSettings
INFO: Settings file location: /home/nathano/UniversalGcodeSender.json
Experimental:  JNI_OnLoad called.
Stable Library
=========================================
Native lib Version = RXTX-2.1-7
Java lib Version   = RXTX-2.1-7

**Comment by winder** [comment]
I think this is fixed in 2.0
