### ISSUE TITLE
buttons are in gray, can't do anything

### ISSUE THREAD

**Issue by JamesinWS** [winder/Universal-G-Code-Sender#294]
run universal G code sender v1.07 under windows 10. but very buttons are in gray. can't do anything.
![gray buttons](https://cloud.githubusercontent.com/assets/14367551/10011749/0b539cc2-60b4-11e5-98ab-51c2a7dea82c.JPG)

**Comment by winder** [comment]
You need to open the connection first

**Comment by JamesinWS** [comment]
Thanks. It's working now.

Sent from my HTC

----- Reply message -----
