### ISSUE TITLE
UGS Window Not Updating

### ISSUE THREAD

**Issue by barnold96** [winder/Universal-G-Code-Sender#300]
I ran a job this morning while I was doing some yard work.  When I went to check after it finished, this is what I saw:

![screenshot 2015-10-08 11 14 57](https://cloud.githubusercontent.com/assets/11699666/10373215/09a5043e-6dba-11e5-8a0d-5ad988b4f7be.png)

The cut had finished as expected but the UGS window didn't update properly.

**Comment by winder** [comment]
There were a handful of weird edge conditions that could cause things like this. Over the past few months I've been cleaning up a lot of code which greatly simplified things to the point where I think these cases should be resolved now. These changes are in the nightly build.

How did the t-rex turn out?

**Comment by barnold96** [comment]
Weird things?  Software?  Say it isn't so. lol

T-Rex is doing well, thinks!

--------------------------------------------
On Fri, 1/22/16, Will Winder <notifications@github.com> wrote:

 Subject: Re: [Universal-G-Code-Sender] UGS Window Not Updating (#300)
 To: "winder/Universal-G-Code-Sender" <Universal-G-Code-Sender@noreply.github.com>
 Cc: "barnold96" <bb31757@yahoo.com>
 Date: Friday, January 22, 2016, 10:44 AM
 
 There were a handful of weird
 edge conditions that could cause things like this. Over the
 past few months I've been cleaning up a lot of code
 which greatly simplified things to the point where I think
 these cases should be resolved now. These changes are in the
 nightly build.
 
 How did the t-rex turn out?
 
 —
 Reply to this email directly or view
 it on GitHub.
