### ISSUE TITLE
bad performance for large files

### ISSUE THREAD

**Issue by rpanier** [winder/Universal-G-Code-Sender#301]
Are there limitations for the size of the .nc files? Wanted to run a job which had more than 700000 command lines. Job performed really bad and kind of screwed up.

**Comment by winder** [comment]
Yes, UGS currently loads the whole file into memory several times:
1) Each line is stored in an object with some additional metadata (like GRBL response)
2) If the visualizer is in use each vertex is stored in memory.
3) The GUI even keeps its own copy as part of a Swing JTable component, with even more metadata!!
4) (sigh) The GUI console may also keep a copy of this data, which would continue to grow as the operation is executed causing the application performance to degrade even further.

So the limit is based on the memory available to your computer. Specifically the JVM heap size - which on my machine with Java 8 seems to default to 1/4 of the total ram.

Take a look at these comments for some options you can pass to Java which might help:
https://github.com/winder/Universal-G-Code-Sender/issues/244#issuecomment-88140911
