### ISSUE TITLE
Is the Jar file missing

### ISSUE THREAD

**Issue by rfgsoftware** [winder/Universal-G-Code-Sender#303]
Is the Jar file missing from the latest release?  I can see it in previous releases, but not in 1..0.9

**Comment by winder** [comment]
No, its in there. Click the link under Downloads.

**Comment by rfgsoftware** [comment]
Really sorry, but I can't find it in the release files.  Where should I look?

**Comment by winder** [comment]
Scroll down on the main github page, next to the screenshots

**Comment by markstock** [comment]
Wow, you *really* need to make it clear that users should look in the "Downloads" section and not in the "Releases" or "Download .zip" or "git clone" buttons/features. I could have saved over an hour of my life, and some time from yours as well. I had no idea that the links under "Downloads" were any different than the bundles that github automatically makes.

**Comment by winder** [comment]
@markstock I'm open to suggestions, I agree with you that there's a problem but I'm not sure how to improve the situation.

**Comment by markstock** [comment]
@winder I'd be happy to help where I can. Let me work on the README.md and then I'll send you a patch (or I could branch and do the "pull request" thing).

**Comment by winder** [comment]
@markstock Thanks Mark, whichever you prefer is fine by me. The only difference I can think of is that a pull request gets you listed as a project contributor which is important to some people.
