### ISSUE TITLE
Why UGS of machine status in windows 7 & 8.1 ,Z position is covered by half?

### ISSUE THREAD

**Issue by viewsat** [winder/Universal-G-Code-Sender#317]
![machinstate](https://cloud.githubusercontent.com/assets/15762267/11704106/b9f70954-9f1f-11e5-92b3-a4bcdd972cac.png)
Z position is covered by half

**Comment by viewsat** [comment]
![zaxis](https://cloud.githubusercontent.com/assets/15762267/13139461/a5c6362e-d667-11e5-9f4d-df6e088995be.png)

**Comment by philreindl** [comment]
I haven't been able to reproduce this.  Do you know of anything that affects this?  I adjusted the windows font zoom, which didn't do anything.  What version of java are you running?  Have you changed the windows theme from the default?

**Comment by jahnj0584** [comment]
I think your resolution is just too low. I know when I minimize it a bit I lose the Visualize/browse/save buttons.

**Comment by viewsat** [comment]
I'm from Taiwan, we are using the traditional Chinese version of windows operating system, whether to display characters will be affected?
