### ISSUE TITLE
No error in nativeavailable

### ISSUE THREAD

**Issue by ChadRat6458** [winder/Universal-G-Code-Sender#318]
![nativeavailable](https://cloud.githubusercontent.com/assets/16234493/11706307/035e1e9c-9ebd-11e5-90bf-efe02626ca42.png)

Do you have any idea what this error is? Is there anything I can do to fix it? Thanks.

**Comment by winder** [comment]
What version are you using? Try upgrading to 1.0.9 or 2.0.

**Comment by ChadRat6458** [comment]
I upgraded to 1.0.9 I no longer get the error. Thanks.
