### ISSUE TITLE
Memory leak in Ubuntu

### ISSUE THREAD

**Issue by bahboric** [winder/Universal-G-Code-Sender#321]
I recently picked up a new cheap Dell Inspiron laptop, installed Ubuntu and java 8 on it, and have been trying versions 1.7, 1.8, 1.9, and the nightly build, of Universal-G-Code-Sender.  It works fine for small projects, but on a larger file, the memory gradually increases, until after about 40 minutes the memory reaches over 90%, and eventually the machine will freeze up.  I had no problems running Universal-G-Code-Sender (1.7) on this file on a very old desktop running Debian, and wonder if there is a fixable reason for the memory usage problem I'm having.

**Comment by winder** [comment]
The data in the console window keeps growing as the application runs. I'm working on this, and other memory issues for #302 

You can check out the constant-memory branch to see progress on that.
