### ISSUE TITLE
UI Designer not matching what's actually built

### ISSUE THREAD

**Issue by philreindl** [winder/Universal-G-Code-Sender#335]
I'm trying to implement a couple of fairly simple ui changes.  
1. Get rid of the commands tab, and move the command entry to the bottom of the console tab.
2. Add a current parser modal state indicator to the machine status area so it's clear what units the machine is parsing commands in.

My trouble is that the UI in the designer does not match what is shown when the program is actually running.  Obviously, this makes laying things out extremely difficult.
UI designer:
![image](https://cloud.githubusercontent.com/assets/3010883/12538793/94fbca2a-c2a8-11e5-902e-4df30fde2926.png)

Actual:
![image](https://cloud.githubusercontent.com/assets/3010883/12538796/c2efdc00-c2a8-11e5-9772-5e8220bc21ba.png)

Any suggestions as to what I'm doing wrong?  I'm using netbeans 8.1, installed just for this.  I haven't messed with any of the settings.  I'm using IntelliJ for everything but the form design.

**Comment by winder** [comment]
The builder can be like this sometimes, it isn't always as WYSIWYG as it
should be.

Based on this: https://forums.netbeans.org/topic37380.html
And this: https://netbeans.org/kb/docs/java/gbcustomizer-basic.html

It looks like most of the issues can be resolved by choosing better layouts
(in the navigator window, right-click a JFrame and change in the `Set
Layout` section. Maybe a box layout would be simpler?

Also it looks like there is a new GridBagLayout builder that could help.

**Comment by philreindl** [comment]
Hrm.
