### ISSUE TITLE
How to build/deploy the platform from within an ide

### ISSUE THREAD

**Issue by philreindl** [winder/Universal-G-Code-Sender#337]
I see that the build is failing due to recent changes that broke the platform version of UGS.  From what I can tell, that guy depends on something from netbeans.  I haven't been able to figure out how to get it to run though (aside from downloading the artifacts.)  Is there any development docs I should be looking at to get started?

**Comment by winder** [comment]
I've been working on documentation recently, but haven't gotten this far
yet (http://winder.github.io/ugs_website/)

If you open up the .travis file you can see the commands you need to run.
Basically you need to cope the latest .jar to a specific location, then you
can open the UGSPlatform directory with Netbeans and everything should
build.

**Comment by philreindl** [comment]
Ah ok.  I was assuming there was something automatic happening there.

**Comment by winder** [comment]
@philreindl I put together some information about building:
http://winder.github.io/ugs_website/dev/getting_started/

**Comment by philreindl** [comment]
Thanks for the update.  Are you able to run the UGS Plaform from within your ide and attach a debugger?

**Comment by winder** [comment]
Yes, its a little weird opening the project because you have to open the UGS project first. But it should import to netbeans just fine.

**Comment by philreindl** [comment]
ok, I finally got it to go.  I didn't realize that maven was a separate install, so that was the first thing.  The second thing was the package job wasn't quite working for me.  Third, I didn't see that the jar file gets renamed in the copy command.
