### ISSUE TITLE
Job Complete Window Persistent

### ISSUE THREAD

**Issue by barnold96** [winder/Universal-G-Code-Sender#339]
After a job is complete, the window pops up as it should.  It also keeps popping up after other operations, such as running a macro, jogging the machine, etc.

![screenshot 2016-01-28 14 26 18](https://cloud.githubusercontent.com/assets/11699666/12656402/18561c9c-c5cc-11e5-916a-362e936fd7f6.png)

**Comment by winder** [comment]
Thanks for the bug report, this is all set now!
