### ISSUE TITLE
Grbl has not finished booting

### ISSUE THREAD

**Issue by Farrokh62yousefi** [winder/Universal-G-Code-Sender#345]
Dear Winder

I use universal gcode sender (version 2.0 nightly, Feb 14, 2016 ) to send my gcodes to arduino uno. it works only on 115200 baudrate. on smaller baudrate i got error "Grbl has not finished booting". please guide me.

thanks in advance.
Farrokh

**Comment by winder** [comment]
The baud rate needs to match what you have set for GRBL, for current versions of GRBL 115200 is correct and you should use that setting.
