### ISSUE TITLE
Connection will close while laser is homing (nightly build)

### ISSUE THREAD

**Issue by ShacharWeis** [winder/Universal-G-Code-Sender#346]
I have an Emblaser laser cutter/engraver from Darkly Labs.

I connect to the laser over the serial port. Then I home it and while it is homing (takes 4-5 seconds) UGC will close the connection. This doesn't happen with v1.0.9, just on the nightly builds.

**Comment by winder** [comment]
I think I found the problem, to verify could you try running from the command line "**java -jar UniversalGcodeSender.jar**" and see if ""No Response in ###ms" is in the output?

**Comment by winder** [comment]
I'm almost certain that should fix the problem, but let me know if it didn't.

**Comment by ShacharWeis** [comment]
Thanks. Will verify later tonight.
