### ISSUE TITLE
UGS used in the Raspberry pi [Error while stream starting file ....]

### ISSUE THREAD

**Issue by viewsat** [winder/Universal-G-Code-Sender#347]
I use the Raspberry pi 2B test UGS 2.0 Nightly (Feb 17,2016).
When I began to send the wrong message sometimes occurs [Error while stream starting file ....]
I have to do soft reset + $ x to return to normal send gcode.

![img_8116](https://cloud.githubusercontent.com/assets/15762267/13131544/1d163de6-d627-11e5-9ab3-00bcaba8645c.JPG)

**Comment by viewsat** [comment]
![img_8118](https://cloud.githubusercontent.com/assets/15762267/13131919/d5349aa6-d629-11e5-859f-72dc981e5986.JPG)

**Comment by winder** [comment]
Are you running any commands before pressing send?
How often do you see the problem?

**Comment by viewsat** [comment]
1. Sometimes doing other commands (keyboard movement), and sometimes do not.
2. After the completion of gcode send again send gcode sometimes there are error
3. I often this problem.

sorry! my English is not good.

**Comment by winder** [comment]
Could you try again with the latest build? I added a little more information to the error message.

**Comment by viewsat** [comment]
ok

**Comment by viewsat** [comment]
I try again with the latest build. The result was often error message occurred.

I opened this gcode test of 97 million lines to be tested.
http://www.picengrave.com/downloads/darklylabs/Roy%20Rogers%20Metric.zip

**Comment by winder** [comment]
I added more information to the error message, does it say what the active commands are?

**Comment by viewsat** [comment]
I tested the latest build error message occurs, you see the the video.

https://youtu.be/Q5wuohVWYvg

**Comment by winder** [comment]
Thanks @viewsat that's what I needed. I'll take another look soon.

**Comment by winder** [comment]
@viewsat this should be fixed now!
