### ISSUE TITLE
UGS send gcode end stop here

### ISSUE THREAD

**Issue by viewsat** [winder/Universal-G-Code-Sender#348]
Raspberry pi 2 B use UGS,send gcode end stop here.
See video >>  https://youtu.be/Xer7LnWyTIc

**Comment by viewsat** [comment]
My Raspberry pi 2 B use official supported operating system. 
RASPBIAN JESSIE
Full desktop image based on Debian Jessie
Version:February 2016
Release date:2016-02-09
Kernel version:4.1

**Comment by winder** [comment]
Duplicate of #340 I haven't been able to reproduce this one yet.
