### ISSUE TITLE
UGS 2.0 Nightly used in the Raspberry pi 

### ISSUE THREAD

**Issue by viewsat** [winder/Universal-G-Code-Sender#353]
UGS 2.0 Nightly used in the Raspberry pi 2 model B / RASPBIAN JESSIE(Version:February 2016) has been an error message appears, someone like me do?

**Comment by winder** [comment]
Whats the error?

**Comment by viewsat** [comment]
# 340 issues with the same error message, ugs2.0 you have the Raspberry pi 2 model B really been tested?

**Comment by winder** [comment]
What is the error?

**Comment by viewsat** [comment]
# 340 issues with the same error message,

**Comment by winder** [comment]
Thanks, I'm hoping to find a fix for this soon.

**Comment by viewsat** [comment]
Thanks you!

**Comment by maly-miller** [comment]
I have it working but the visualizer is not working at all on Raspberry Pi3
