### ISSUE TITLE
Z Probe: spindle moves wrong direction

### ISSUE THREAD

**Issue by Smlittlep** [winder/Universal-G-Code-Sender#354]
This has worked fine in V1.0.9 from November, but fails in the 2.0 Nightly builds I have tried.  When using the Z probe, and the following G code command, G38.2 Z-0.5 F1, the probing function moves in the wrong Z direction and does not abort after 0.5 inches of travel. If I change the code to move in the positive Z direction, I get an "Alarm: Soft Limit" error.  The spindle is not close to any limits, hard or soft when this error occurs.

**Comment by winder** [comment]
This is probably a side effect of UGS jog motions no longer leaving the machine in relative mode (it now leaves it in your default movement mode). Try sending G91 before that command.
