### ISSUE TITLE
Crash with latest EAP JRE when opening serial port

### ISSUE THREAD

**Issue by dgtlmoon** [winder/Universal-G-Code-Sender#369]
Hi

I'm using a JRE latest Early Access Program build so I can use the application on a 4K monitor. (Otherwise java has a problem where it cant scale the fonts properly and all the text is about 3mm high). 

This is on Windows 10 with all updates.

http://www.oracle.com/technetwork/articles/java/ea-jsp-142245.html

The program seems to crash as soon as I click 'open' on the serial port

I have attached two log outputs from Java

[hs_err_pid6628.txt](https://github.com/winder/Universal-G-Code-Sender/files/181246/hs_err_pid6628.txt)
[hs_err_pid7092.txt](https://github.com/winder/Universal-G-Code-Sender/files/181245/hs_err_pid7092.txt)

**Comment by winder** [comment]
What version of Java are you using? Run "java -version"

Unfortunately it looks like the rash is in native code or the JNI for the
serial library so there isn't a lot I can do. When you give me you're Java
version I can do a little more digging to see if anyone else has this
problem with JSSC.
