### ISSUE TITLE
New GUI to big for 1024*768 screen

### ISSUE THREAD

**Issue by rugbymauri** [winder/Universal-G-Code-Sender#374]
Hi the new GUI is to big

![universal gcode sender version 2 0 nightly - mar 24 2016 _233](https://cloud.githubusercontent.com/assets/5549264/14011424/a4da0cde-f19e-11e5-89be-d16cec4a7a7b.png)

 my proposal is to put to Connection oanel on the top and arrange the elements in the little Panles more in the width, like this

![universal gcode sender version 2 0 nightly - mar 24 2016 _233](https://cloud.githubusercontent.com/assets/5549264/14011492/62e6ddba-f19f-11e5-99c0-74a0882c45ab.png)

**Comment by philreindl** [comment]
Crud, you're right.  

My plan to tighten things up is to have the connection panel only show when the machine is disconnected.  When connected, it will be replaced by the machine status panel (which will get the close button.)  Having them both onscreen at the same time seems redundant to me.

I think we can get rid of a row of the buttons in the file section as well by being a bit clever.  Send/pause can be combined.  I still don't see what good Save is.  Cancel and browse can probably be combined.  Visualize can be a tab in the area on the right.

Enable keyboard movement should be a setting.  For that to work though, jog should be disabled whenever the cursor is in a text box.  (file dialog/ console/ macro edit)

**Comment by rugbymauri** [comment]
Visualize can be implemented as menu item -> view -> visualize

**Comment by rugbymauri** [comment]
You can put all connection options (port, baud rate....) in a tab. And leave just the connect button. Normally the connection options dont change.

**Comment by jahnj0584** [comment]
I realized this yesterday too. Turns out my monitor can go higher, but I find myself going back to the classic platform as the new one has issues, like none of the common command buttons being usable and a failed attempt at macro keys.

**Comment by winder** [comment]
@jahnj0584 please create tickets for any issue you see in the platform - it's under heavy development right now.

**Comment by rugbymauri** [comment]
I made a Mockup of possible changes to the Gui

- Connect Menu (no menu items), like a button (tricky to find the right event. MouseClick?)
- Visulize Menu (no Menu Items), like a button (tricky to find the right event. MouseClick?)
- moved Connection Pane in the Tabs. used only once to setup the connection,
- stripped some buttons as proposed by @philreindl 

now it should fit in small screens 

![universal gcode sender version 2 0 nightly - _236](https://cloud.githubusercontent.com/assets/5549264/14109627/2dc47ad4-f5c3-11e5-9371-175289419e28.png)

**Comment by philreindl** [comment]
I'm working on making the status panels on the left a bit more dynamic.  The idea will be to hide the current machine status panel when the machine is NOT connected, and hide the bulk of the connection panel when the machine IS connected (Still need the disconnect button).  I'd like to give similar treatment to the file window.

My hope is to:
A. Make things fit properly on a small screen 1024x768 for sure, I'm planning to get a small tablet to run this on eventually, which may be more in the 800x600 range. 
B. Reduce the amount of UI navigation for "normal" use.  Settings adjustment, macro editing, etc are not what I'd group with "normal" use.  So those functions would be buried a bit from the main screen.
C.  Make the overall flow of what needs to happen next more intuitive, especially for new users.  First, need to connect, Second need to home (if enabled), Third load a file, Fourth run the file, Fifth, see how much time you  have to eat snacks while it runs.

**Comment by philreindl** [comment]
@fautlylee mentioned using a PC at 1024x600

**Comment by winder** [comment]
@philreindl What do you think about "forking" MainWindow.java (copying/pasting it to a new class) so that the old UI is stable while your in experiment mode? The nightly build gets 50-100 downloads a day.

At one point I was trying to support 640x480 since thats what the original raspberry pi supported out of the box. I'm not sure how widely that configuration is used though.

**Comment by philreindl** [comment]
That's not a bad idea at all.  I had no idea nightlys had that much traffic.

**Comment by philreindl** [comment]
@winder Actually, rather than just adding another MainWindow to the codebase, what do you think of getting the edge branch up to date and having it generate nightly builds as well?  Getting it up to date with master should be easy since there's no unmerged commits there.  I'm not sure what's involved with hooking it up to the build system.

**Comment by faultylee** [comment]
Kudos to all of you for catering to edge use cases :+1:
