### ISSUE TITLE
Jumbled Display

### ISSUE THREAD

**Issue by barnold96** [winder/Universal-G-Code-Sender#380]
I downloaded the latest passing build a short while ago and this is what I see:

![screenshot 2016-04-02 14 06 15](https://cloud.githubusercontent.com/assets/11699666/14228348/1b531a48-f8e0-11e5-91bb-12bc637341ec.png)

Backed up to build 500 for a normal looking display.

**Comment by philreindl** [comment]
What resolution is that?  If you make the window wider does it look better?

**Comment by winder** [comment]
I think the minimum sizes just need to be tweaked to make sure you can't shrink the window too much.

**Comment by philreindl** [comment]
What is the "official" minimum supported window size?  We should probably set that as the minimum size on the window itself.

**Comment by winder** [comment]
VGA was the lowest I ever actively tried to support (640x480), but 1024×768 is probably reasonable.

**Comment by philreindl** [comment]
1024x768 is more or less what I figured. Going off topic a bit.. Have you thought much about incorporating any usage statistics reporting (Google Analytics)?  Would be really nice to have concrete data to back things like this up.

**Comment by winder** [comment]
I've considered it. I was planning to look at what was build into the netbeans platform, but maybe something more general would be useful.

For an estimate, I have google analytics hooked up to the new website. Here are the statistics for the download page (not filtering out mobile devices):

<img width="415" alt="resolutions" src="https://cloud.githubusercontent.com/assets/125509/14254899/c212608e-fa5f-11e5-8dda-1d1473f0ee5b.png">

**Comment by philreindl** [comment]
Thanks for sharing.  That's an interesting mix.  If you're already using Google Analytics, it might make sense to stick with that.  https://developers.google.com/api-client-library/java/apis/analytics/v3

**Comment by barnold96** [comment]
I'm back in my shop today and checked some of the different recent passing builds.  The layout that looks more balanced is 501.  I see what's happening with 514 and window size but the layout is clunky.  Sorry I didn't try resizing before.

**Comment by faultylee** [comment]
@winder I think GA might give false result, at least in my case. I run UGCS on a dedicated machine, so I would download using my laptop and then copy the file over, instead of having a browser installed on the machine running UGCS :)

Like @philreindl said, having some form of analytic on the software might be helpful, though if the machine running it is not connected to the internet, then there might be another issue. And there might be noise coming from those testing the nightly on a different machine.
