### ISSUE TITLE
GRBL has not finished booting.

### ISSUE THREAD

**Issue by koratjay** [winder/Universal-G-Code-Sender#382]
i am facing this error while loading code into arduino uno.so please help,

**Comment by winder** [comment]
This usually happens because you set the wrong baud rate for your version
of Grbl

**Comment by koratjay** [comment]
how can i find proper baud rate?
i am using arduino uno r3 and which two of following are appropriate
 grbl_v0_8c_atmega328p_16mhz_9600.hex,or
grbl_v0_9a_edge_328p_16mhz_9600_build20121210.hex,
UniversalGcodeSender-v1.0.5-all64 or UniversalGcodeSender-v1.0.9

**Comment by Shanki070** [comment]
I fixed this issue by uploading grbl in the Ardunio.

In Ardunio IDE go to File -> Examples -> grbl ->grblUpload. Flash this sample in the Ardunio and then run "Universal-G-Code-Sender".
