### ISSUE TITLE
Pendant File mode

### ISSUE THREAD

**Issue by seanwlk** [winder/Universal-G-Code-Sender#395]
Is there any way to send a file to the machine through the pendant? This way it can be controlled from a lab in LAN

**Comment by winder** [comment]
It would be possible to build something like this, but the current pendant only does basic control. If someone was interested in building a full web-ui UGS could be launched in a headless mode and used that way, but it doesn't exist currently.

One idea I had was to implement the serial port json server API so chilipeppr could be used to control UG: #227

None of this is very high on my TODO list though.
