### ISSUE TITLE
Fonts very very small in high resolution monitor

### ISSUE THREAD

**Issue by simonmtl** [winder/Universal-G-Code-Sender#400]
I'm using a windows 10 based laptop with QHD+ resolution (3,200 x 1,800). The fonts are so small they can barely be
[UGS 1.09 on QHD plus resolution.pdf](https://github.com/winder/Universal-G-Code-Sender/files/241409/UGS.1.09.on.QHD.plus.resolution.pdf)
 seen.  Microsoft says this is caused by the use of local fonts instead of the system ones.

**Comment by simonmtl** [comment]
I just discovered USG platform, which solves my problem. Case closed  for me.

**Comment by winder** [comment]
This is a known issue for Java Swing applications in general. Glad to hear the platform build works, I didn't realize it had high dpi handling. Java9 is supposed to have native handling for application scaling, but its still a ways out.
