### ISSUE TITLE
STOP button does not stop the job immediately

### ISSUE THREAD

**Issue by cgalvisardila** [winder/Universal-G-Code-Sender#401]
Hello! i love the new UGCS platform, but i have only one problem which is a security concern. Sometimes i make mistakes and once the job starts i might need to stop it right away.. the pause button works for this but does not cancel the job, and also doesn't allow me to move the machine to zero point, so i have to break the connection and restart it! this means i have to re zero the machine, and i might not get it right the next time. the STOP button doesn't stop the machine until it runs all the issued commands, THEN it stops and you can zero back, this can take a while!... is there a way to stop the job dead and cancel the job immediately, while keeping the zero point? if not i'd really like to see this... it would improve the program greatly. thanks for your help... cheers!

carlos

**Comment by winder** [comment]
It should be possible to issue a feed-hold + soft-reset to do this, with all the refactoring over the past few months I can finally add this feature. 

The main issue stems from GRBL having a bunch of commands buffered when the cancel happens. If your project has a lot of long straight movements it could be a while for the buffer to drain.
