### ISSUE TITLE
'No serial ports found.'  on Mac OSX10.10.5 Yosemite

### ISSUE THREAD

**Issue by hobbietime** [winder/Universal-G-Code-Sender#403]
Just downloaded the latest version 1.0.9
executed the .jar file... it loads perfectly except for the message
'No Serial Ports Found'

The ports are there... I use them all the time with Adruino IDE or CoolTerm...
however they do not appear with this software? ( no other comm software is running)

any ideas would be greatly appreciated.
Thanks in advance

**Comment by winder** [comment]
Are you using an Arduino clone? There is a bug in the serial library that prevents it from listing some clone devices. If thats the case, you can enter the port address manually.

**Comment by hobbietime** [comment]
using Arduino clone using wchusbserial1410 / 115200 8-N-1
How do I input the port address manually?   
I have tried to input    wchusbserial1410   directly and nothing happens

**Comment by hobbietime** [comment]
Error opening connection (jssc.SerialPortException): Port name -wchusbserial1410; Method name -openPort(); Exception type - Port not found.

**Comment by winder** [comment]
Try `/dev/tty.wchusbserial1410`

**Comment by hobbietime** [comment]
perfet... that did the trick.... thank you very much...  just document in the realm file...
cheers

**Comment by hobbietime** [comment]
sorry  the ReadMe   file

**Comment by VelhoLobo** [comment]
Bom dia Srs., tenho o mesmo problema, macOS Mojave, Versão 10.14.16
**"Error opening connection (jss.SerialPortException): Port name - /dev/cu.whcusbserial410; Method name - openPort(); Exception type - Port no foud."**
Desde já agradeço penhoradamenete, qualquer ajuda
Helcio Xavier
