### ISSUE TITLE
Issues with T5 M6 commands?

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#405]
Seems to be causing issues with the newer versions. Never was an issue before, just started now that I upgraded. Removing the line from each gcode is a bother with all the work and operations I do! Please fix, maybe just add an option to skip or auto delete these? 

Or, teach me to edit the post processor to stop adding these. Whatever is easiest. I use HSMworks.

**Comment by winder** [comment]
This is a feature actually. In current version of GRBL lines with an error on them are completely ignored. Not good if you have a command like "G21 G90 G64 G40" at the beginning of a file to set modes.

Previously UGS would silently ignore these errors.

A quick google search suggests that a GRBL post processor is available for HWMworks. I don't have any experience with that software though.

**Comment by weirdguy79** [comment]
I don't use solid works and have no idea about post processing

**Comment by winder** [comment]
@weirdguy79 For any CAM software you need to use the appropriate post processor, GRBL is widely supported at this point.

**Comment by jahnj0584** [comment]
yes, i know theres a processor, im wondering if theres a way to edit it to not include M and T commands in the code?

**Comment by winder** [comment]
@jahnj0584 I'll see if it's possible to allow the job to continue when it halts like this, maybe adding some sort of "at your own risk" warning.

**Comment by jahnj0584** [comment]
Please do. I'd appreciate it. I don't want to start new threads, but maybe add an option to "never show again" for the "report to github" splash when you start, and I occasionally get errors that say "error while processing response <ok>; null" when I do lots of jogging. Cheers
