### ISSUE TITLE
Platform has no way to actually send gcode

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#407]
Has a browse option, but nothing to send! Also suggestion: Make the file progress window only come up once a file has been sent, or loaded.

**Comment by winder** [comment]
The play icon in the toolbar sends the file. I want to make some menu
actions to do that too though.

I'll look into having the Windows be more contextual.

**Comment by jahnj0584** [comment]
Thanks winder. Not an important feature, but would make the software look more polished for sure. I like where this is all going!


OH! Another thing. Theres no keyboard jogging, it seems.

**Comment by winder** [comment]
There are real shortcuts for jogging now, you can change them to the arrow
keys or leave them as shift+arrow.
