### ISSUE TITLE
Feature Request: Display position in inches

### ISSUE THREAD

**Issue by adamsd5** [winder/Universal-G-Code-Sender#410]
I work in inches.  It is great that I can do machine control in inches.  It would be better if the current position display can be toggled between mm and inches.  (Apologies if there is already a way to do this... I've not found it in 1.9!)

**Comment by winder** [comment]
There's a GRBL flag to report inches, just set `$13=1`!

**Comment by winder** [comment]
You may need the nightly build of UGS for the different units to be handled properly in the visualizer.
