### ISSUE TITLE
Is it compatible with OSX EL Capitan? I see weird massages in a console. 

### ISSUE THREAD

**Issue by tema2121** [winder/Universal-G-Code-Sender#415]
Hi, 
that wired massages are interrupt work of Universal Gcode Sender always including during sending.
It looks like: MPos 00000,000 WPos. 0000.00000
I know exactly that it something between my laptop and Universal Gcode Sender 
I have OSX EL Capitan. on others computers it works.

Thanks a lot for your future help.
Artem
![screen shot 2016-05-14 at 2 18 31 pm](https://cloud.githubusercontent.com/assets/19315633/15268241/feeb4336-19e0-11e6-9a2c-019e68a01761.png)

**Comment by tema2121** [comment]
![screen shot 2016-05-14 at 2 45 27 pm](https://cloud.githubusercontent.com/assets/19315633/15268392/7f504748-19e5-11e6-87ca-4502c9f90a4d.png)
![Uploading Screen Shot 2016-05-14 at 2.49.04 PM.png…]()
![screen shot 2016-05-14 at 2 49 55 pm](https://cloud.githubusercontent.com/assets/19315633/15268391/7f500990-19e5-11e6-8e4f-3a3a4efb547a.png)

**Comment by tema2121** [comment]
On others computers there are no such feedback massages. They interrupt communication. 
Thanks 
Artem

**Comment by winder** [comment]
I moved those messages to the verbose console. It looks like something else might be going on with your installation though, because the MPos/WPos messages shouldn't have been picked up here.

Do things seem to be working other than all the extra messages in the console?

**Comment by tema2121** [comment]
After starting sending a file first such message in the console stopping motion. Can I sending that  MPos/WPos messages back to verbose by typing a command or making change in log files?

**Comment by winder** [comment]
The `show verbose output` checkbox above the console toggles whether these messages are displayed.

**Comment by tema2121** [comment]
it it some thing with EL capital of Java

**Comment by winder** [comment]
I've tested UGS with el capitan. I'm not sure whats causing this, that code hasn't been changed in several months.

**Comment by tema2121** [comment]
I found that article https://oliverdowling.com.au/2015/10/09/oracles-jdk-8-on-mac-os-x-el-capitan/
and repeat all - but still that bug
