### ISSUE TITLE
Keep the computer awake while a file is sending

### ISSUE THREAD

**Issue by winder** [winder/Universal-G-Code-Sender#419]
Every so often my laptop falls asleep in the middle of a job.

Prevent that by moving the mouse a little every few minutes if a job is running: http://stackoverflow.com/a/10280104/204023

**Comment by faultylee** [comment]
Can't we just configure the machine not to sleep?

**Comment by dshookowsky** [comment]
If you're using windows, there's a small app called caffeine that works perfectly for keeping a laptop alive during presentations, etc.  It allows you tell the machine to stay awake regardless of the sleep settings.  I believe it sends an F12 key press event once a minute.
