### ISSUE TITLE
Missing settings on $$ command

### ISSUE THREAD

**Issue by TheAHan** [winder/Universal-G-Code-Sender#422]
I have an issue where my list of available settings (on $$) is shorter than it should be, most notably for me it's misssing the x,y and z settings:
![aef11e36ad7b33a1db8e814e58a501bf9770ad32_1_526x500](https://cloud.githubusercontent.com/assets/7548782/15746052/dec76cc6-28a2-11e6-8c61-82c6eb67e49a.png)
Is this an issue with GRBL rather than UGCS, and does anybody know what the fix could be?

**Comment by winder** [comment]
If you enable `Show verbose output` are the other commands displayed?

**Comment by TheAHan** [comment]
I will have to check later tonight when I get home. I've been reading on the GRBL github here: https://github.com/grbl/grbl/wiki/Frequently-Asked-Questions that the settings list is stored in the Arduino EEPROM, and that sometimes settings and parameters are funky after flashing, so I'm going to try that tonight too.

Is this most likely a problem with GRBL though?

**Comment by TheAHan** [comment]
So yes, I sent a $$ command with verbose output enabled and the settings are there:
![screen shot 2016-06-02 at 17 06 05](https://cloud.githubusercontent.com/assets/7548782/15800189/985447ec-2a40-11e6-9d87-2bb09195b49d.png)
It turns out I can also edit them and they will save normally.
Why are they verbose?

**Comment by bobdewar** [comment]
I am also only seeing settings 0 to 26 even if I have select "show verbose output".  It works fin in Version 1.0.9.  I get the same result if I enter "$$" in the command window or view the options using Settings/Firmware Settings/GRBL.

Here is what I see;

>>> $$
$0=10 (step pulse, usec)
$1=255 (step idle delay, msec)
$2=0 (step port invert mask:00000000)
$3=0 (dir port invert mask:00000000)
$4=0 (step enable invert, bool)
$5=0 (limit pins invert, bool)
$6=0 (probe pin invert, bool)
$10=3 (status report mask:00000011)
$13=0 (report inches, bool)
$20=0 (soft limits, bool)
$21=0 (hard limits, bool)
$22=0 (homing cycle, bool)
$23=0 (homing dir invert mask:00000000)
$26=250 (homing debounce, msec)
ok

**Comment by barnold96** [comment]
All I get with "show verbose" on is the following.  There's a constant output of lines as below, then only 0-26 when I enter $$.

[verbose]<Idle,MPos:0.0000,0.0000,0.0000,WPos:0.0000,0.0000,0.9999>
[verbose]<Idle,MPos:0.0000,0.0000,0.0000,WPos:0.0000,0.0000,0.9999>
[verbose]<Idle,MPos:0.0000,0.0000,0.0000,WPos:0.0000,0.0000,0.9999>
[verbose]<Idle,MPos:0.0000,0.0000,0.0000,WPos:0.0000,0.0000,0.9999>
[verbose]<Idle,MPos:0.0000,0.0000,0.0000,WPos:0.0000,0.0000,0.9999>
>>> $$
$0=10 (step pulse, usec)
$1=255 (step idle delay, msec)
$2=0 (step port invert mask:00000000)
$3=3 (dir port invert mask:00000011)
$4=0 (step enable invert, bool)
$5=0 (limit pins invert, bool)
$6=0 (probe pin invert, bool)
$10=3 (status report mask:00000011)
$13=1 (report inches, bool)
$20=0 (soft limits, bool)
$21=0 (hard limits, bool)
$22=0 (homing cycle, bool)
$23=0 (homing dir invert mask:00000000)
$26=250 (homing debounce, msec)
ok

**Comment by CritterCJ** [comment]
I have the same issue. List of setting always ends $26. Last version of GRBL Gcode sender where it works is about 2.0 (nightly) / Mar 28, 2016. Newest versions always have this issue.

Settings are missing too. See attached image.

![61f1461c-503a-11e6-8c95-55669eddc7dd](https://cloud.githubusercontent.com/assets/20600937/17103951/096c7e46-5281-11e6-940f-4b1c85b51ef7.png)
