### ISSUE TITLE
Marlin firmware support?

### ISSUE THREAD

**Issue by hikernl** [winder/Universal-G-Code-Sender#423]
Does the master version has support for Marlin firmware?

**Comment by winder** [comment]
It isn't supported right now, some recent improvements to the GCode Parser in UGS make it so that Marlin (and Smoothieboard) support shouldn't be much trouble to add. I'm not planning to work on that for a while though.

**Comment by concifederico** [comment]
Any news on this topic?

**Comment by winder** [comment]
@concifederico nobody is working on Marlin support to my knowledge.

**Comment by Silas-Asamoah** [comment]
Any update on Marlin support?

**Comment by breiler** [comment]
I had the intention to start working on this (see #1080) but I'm currently busy with moving to a new city and a new job.

**Comment by Silas-Asamoah** [comment]
Yes please
