### ISSUE TITLE
UGCS and Android

### ISSUE THREAD

**Issue by OldSalt1945** [winder/Universal-G-Code-Sender#424]
Will, is there some way to run UGCS on an Android tablet?

It sure would be easier than using my laptop.

John

**Comment by winder** [comment]
This isn't possible. I'm using Java 8 and the UI code isn't compatible with
android.

**Comment by winder** [comment]
There are cheap Windows tablets that can run it though.

**Comment by OldSalt1945** [comment]
thanks for the info.  I suppose I could take a deep breath, hold my nose and buy a winders tablet.  Yech.

John
