### ISSUE TITLE
Incorrect scale in visualizer when "report inches" is enabled

### ISSUE THREAD

**Issue by nmeek** [winder/Universal-G-Code-Sender#425]
When "Display Inches" is enabled, the scale of the tool movements in the visualizer does not match that of the visualized path, making it appear that the tool is not following the path. Changing the display back to mm fixes the scale issue and the tool again appears to follow the path.

**Comment by winder** [comment]
What version of UGS are you using? I think this is fixed in the nightly build.

**Comment by nmeek** [comment]
I'm using 1.0.9.
I apologize, my quick search did not find the existing issue.
Thanks for the update.

**Comment by winder** [comment]
No problem, let me know if you find any other problems.
