### ISSUE TITLE
Loaded program is not displayed

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#429]
no file path/name present after a file is loaded and or running. See pic

![fdzgsdfgsdfg](https://cloud.githubusercontent.com/assets/17396492/16498282/72882e70-3ed1-11e6-91a0-7074c8713b50.PNG)

**Comment by winder** [comment]
Is this still happening for you? I wasn't able to reproduce the problem.

Do you click the browse button, select File->Open from the menu or use CMD-O?

**Comment by jahnj0584** [comment]
Haven't launched today's version but it's still there. Happens no matter
what method I use.

**Comment by jahnj0584** [comment]
Also fixed.
