### ISSUE TITLE
(suggestion) Numbers in visualizer are always normal-to the viewer

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#430]
sucks having to always rotate back to the flat views to see the dimensions. It'd be nice if the numbers DIDNT rotate with the viewer, and maybe even had an option to show them outside of the constraint lines? 

Add-On: allow clicking on a face of the XYZ cube to instant snap to that view. 
![cap jpg](https://cloud.githubusercontent.com/assets/17396492/16498484/7d114cae-3ed2-11e6-97d9-8ac9ae97a11d.PNG)

**Comment by winder** [comment]
After implementing this, I think that it looks pretty bad/confusing when enabled for the X/Y axes. Maybe I'll enable it just for the Z axis.

<img width="855" alt="screen shot 2016-09-07 at 6 06 28 pm" src="https://cloud.githubusercontent.com/assets/125509/18330328/f0b0cc00-7525-11e6-8dfa-f15c2a1b47f8.png">

<img width="853" alt="screen shot 2016-09-07 at 6 09 59 pm" src="https://cloud.githubusercontent.com/assets/125509/18330396/52b2db32-7526-11e6-8a08-2f7efa0a70cd.png">

**Comment by jahnj0584** [comment]
Works for me! The Z one was the one that got the messiest anyways.
