### ISSUE TITLE
Error opening connection (jssc.SerialPortException): Port name Com4; Method name - openPort(); Exception type - Port not found

### ISSUE THREAD

**Issue by thiagostopa** [winder/Universal-G-Code-Sender#436]
Working in other programs like grblControl... But not working in UGS any versions of UGS

Error opening connection (jssc.SerialPortException): Port name Com4; Method name - openPort(); Exception type - Port not found

**Comment by jahnj0584** [comment]
well, is it on the 4th com?

**Comment by winder** [comment]
@thiagostopa if you have more than one com port it could be any one of them.

**Comment by thiagostopa** [comment]
Hi guys... there was only the COM4 for the arduino... 

The port was working fine, it stopped working suddenly. I solved the problem by removing the port on device manager and reinstalling the Arduino software again.

Thanks
