### ISSUE TITLE
(suggestion) add shortcuts in zip to the platform/64 files

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#437]
Im sure some people dont know to look for through the bin folder, so maybe add a shortcut to make it easier to anyone new?

**Comment by jahnj0584** [comment]
Still think this is a good idea

**Comment by winder** [comment]
A side effect of #731 is that UGS will have a real installer which should add a shortcut to run UGS like a regular windows/linux/mac application. This is definitely a requirement for me.

**Comment by jahnj0584** [comment]
Cool. Will that improve program load times too? (the splash screen)
