### ISSUE TITLE
Probe not working

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#438]
My probe doesnt want to work in GRBL 0.9j! I have one pin to A5, and the other to GRD on the same row. One clip on a metal block, other on the end mill. I inverted the pin ($6) to make it actually work, and send g38.2 Z-10 F30 and it just drops the Z slowly. Even touching the wires together wont trigger it, so clearly something is wrong with my inputs. Any ideas?

**Comment by winder** [comment]
Looks like chamnit answered this on the grbl github issue.
