### ISSUE TITLE
Latest/Next update

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#439]
Will, when was or is the latest update being rolled out? Just curious. I wish I could use the version from a month ago as this one has some new silly bugs. 

Cheers

**Comment by winder** [comment]
I've been refactoring the gcode processor and integrating those changes, so my local code wasn't in a working state for a while. As of today the tests are finally passing again, so I'll be getting to the bugs you've found soon.

**Comment by jahnj0584** [comment]
Great. Looking forward to it. Can you let me know when you do upload the next one?
