### ISSUE TITLE
Support GRBL Simulator

### ISSUE THREAD

**Issue by winder** [winder/Universal-G-Code-Sender#44]
Utilize grbl simulator
https://github.com/grbl/grbl/pull/112

**Comment by philreindl** [comment]
Has there been any movement on this?  If not, how do you guys do dev work on UGS without being connected to a cnc?

**Comment by winder** [comment]
I've been able to use the current version of grbl-sim with UGS.

For development I usually use a spare arduino with grbl loaded on it.

**Comment by philreindl** [comment]
oh ok, based on this ticket I'd assumed it didn't work.  What are your thoughts on the addition of a "mock serial" controller?  It would simply eat all commands thrown at it and return 'ok.'  It obviously wouldn't be useful for every aspect of UGS, but it would allow for things like macro development.

**Comment by winder** [comment]
@philreindl Somehow I missed this comment. Having a mock serial object would be great, I had the same idea recently.
