### ISSUE TITLE
No "Firmwares"

### ISSUE THREAD

**Issue by barnold96** [winder/Universal-G-Code-Sender#440]
I downloaded the latest build, 595, this morning.  When I ran it, I got this window.  All is OK if I drop back to the previous version I've been using, June 19.

![screenshot 2016-07-19 10 32 38](https://cloud.githubusercontent.com/assets/11699666/16954018/48102474-4d9d-11e6-8bc2-cd1101bced92.png)

**Comment by winder** [comment]
What OS are you using? Are there any errors on the console?

I made some changes to how the different firmwares are configured, looks like the code to initialize those settings isn't working on your machine.

**Comment by barnold96** [comment]
Win 10.  Also fails to connect after clicking past the box.

--------------------------------------------
On Tue, 7/19/16, Will Winder <notifications@github.com> wrote:

 Subject: Re: [winder/Universal-G-Code-Sender] No "Firmwares" (#440)
 To: "winder/Universal-G-Code-Sender" <Universal-G-Code-Sender@noreply.github.com>
 Cc: "barnold96" <bb31757@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Tuesday, July 19, 2016, 12:49 PM
 
 What OS are you using? Are there
 any errors on the console?
 
 I made some changes to how the different firmwares are
 configured, looks like the code to initialize those settings
 isn't working on your machine.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by winder** [comment]
I found the issue last night but wasn't able to finish fixing it, hopefully tonight.
