### ISSUE TITLE
no port selection 

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#441]
![connect](https://cloud.githubusercontent.com/assets/17396492/16993890/a22c6f60-4e7b-11e6-891a-131b431c2bd7.PNG)
I had to add the connect button through the options

**Comment by winder** [comment]
I'm pretty sure this is a side effect of #440

**Comment by jahnj0584** [comment]
ah good point. Didnt think an issue in one would effect the other platform. Whens the fix, boss?

**Comment by winder** [comment]
Yeah, probably more than 90% of the code is shared between the 2 GUIs. If I run out of time tonight I'll definitely get it on the train tomorrow morning.

**Comment by jahnj0584** [comment]
![ugs issue](https://cloud.githubusercontent.com/assets/17396492/17407613/4c19b1fe-5a3e-11e6-8029-3b3d644283ab.PNG)
I think the issue is still there after the aug 1st update will

**Comment by winder** [comment]
If you right click in the toolbar area is there a `Connection` option? I think you might have just disabled it on accident.

**Comment by jahnj0584** [comment]
Nope. this is how it is with a fresh download, Macros' arent there from my old version either

![ugsss](https://cloud.githubusercontent.com/assets/17396492/17411023/c11d9430-5a4c-11e6-97bf-5e49a730e5df.PNG)

**Comment by winder** [comment]
@jahnj0584 I found the problem, it should be fixed now. This was a really strange issue that wasn't reproducible from my development environment so I never noticed it. Thanks for reporting the problem.
