### ISSUE TITLE
GRBL not responding UGS

### ISSUE THREAD

**Issue by AqsaAli** [winder/Universal-G-Code-Sender#443]
hey!!
I connect my CNC xPRO V2 Controller Stepper Driver with system and start a software. but it does not select the USB port. and if it selects the port then GRBL in the shield does not respond.
When I look at the command table , the sent column is checked in front of all commands. but the done and responce column remain unchecked showing no command is done. and there is not even a jerk in the stepper motors.
How can I resolve this problem

**Comment by winder** [comment]
You're probably using the wrong baud rate, try 115200.

**Comment by AqsaAli** [comment]
I tried this also.. but there is no responce

**Comment by winder** [comment]
AqsaAli, maybe contact the xPro team and see if the board isn't flashed or setup propertly. It sounds like you're using UGS correctly.
