### ISSUE TITLE
File Window

### ISSUE THREAD

**Issue by DOUG888** [winder/Universal-G-Code-Sender#451]
Nice to have
A window where the Current file path is displayed, if you run gray scale raster you can't see the picture at all, this would allow you to at least confirm the correct file before RUN....next to the Run/Stop/Pause buttons up top would fit.
This was meant to be Labelled Suggestion, but i couldn't find that option...Help please.

**Comment by winder** [comment]
I was thinking about putting the current file on the little status bar along the bottom of the window.

**Comment by jahnj0584** [comment]
Why not simply in the white box by the open file box?

**Comment by breiler** [comment]
Can we consider it fixed with #896?
