### ISSUE TITLE
Output Window

### ISSUE THREAD

**Issue by DOUG888** [winder/Universal-G-Code-Sender#452]
UGS Platform latest overnight
Bottom of the screen is the Console window, all good, next to that is the Output window, this is empty, is this for future development or a bug or have i stuffed up a setting.
it was the same on the previous version.
If so what should it display??
Thanks
Doug
Apologies if this has been asked before.

**Comment by winder** [comment]
The output window is built into the framework I'm using. I was going to try replacing the console window with that built in output window, but thats pretty low priority for me. For now you can close the output window, it isn't used currently.

**Comment by DOUG888** [comment]
Thanks for clearing that up
