### ISSUE TITLE
Macro Issues

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#454]
1) Macro names and functions dont update in their "box" after hitting apply or accept in the options menu. They DO update in the file > macro bar though

2) While editing macros, cursor will sometimes skip to the other box (without anything being pressed)

3) If you name a macro in the first box, and hit apply it sometimes gets renamed to 0 or 1, depending of course where it is in the list.

**Comment by DOUG888** [comment]
I have found the same thing..To help stabilize i disconnected the link to the Arduino, editing behaved better then. Once the editing was finished i closed Macro and then reopened it, all changes activated, then reconnected Arduino...Not a Fix but works until it is.
