### ISSUE TITLE
Does not launch in OS X El Capitan, latest build with latest Java 1.8 build 101 

### ISSUE THREAD

**Issue by papastanley** [winder/Universal-G-Code-Sender#464]
Hi guys,

I have two machines...

my old setup is Yosemite 10.10.5 with Java 1.8.0_45 and UGS v 2 nightly build from 2015-06-03. This works fine - I'm using a Darkly Labs Emblaser (basically an Arduino GRBL 2d laser)

My new setup is _trying_ running on El Capitan  with Java 1.8.0_101 and the most recent build as at 22 August 2016.

The "new" setup is stalling - seems like it's after the Loading Settings/Applying Settings stages as reported in Terminal on first launch. Just sits there spinning it's wheels. While I can't put my finger on it it feels like maybe sandbox is blocking the GUI from appearing in some fashion, or there's some window bug occurring with the draw to screen. Nothing obvious in Console, but I'm no stack tracer...

On your web page when you say "tested on Mac OS X" it would be good to have some system specifics, or at least some dates for that advice - I don't know if you regularly test on OS X with Java 1.7 and 1.8 and the last 3 OS X versions, or whether you did once ages ago and haven't done since cause you don't run it.

Please advise? **papastanley@me.com** and/or **papastanley** on github. 

Next step is to rebuild the system clean, but that's pretty drastic just to get an applet to run IMO ;-)

Cheers, love your work

.:S:.

**Comment by winder** [comment]
@papastanley I've been using 1.8.0_80 for a while, so I gave it a test with a OSX El Capitan 10.11.5 with 1.8.0_101 and 1.8.0_102. Both are launching fine.  I'm guessing there might be some sort of security setting preventing UGS from accessing the settings directory which might cause a hang.

Does 1.0.9 work for you?
If yes, from the command line does `ls ~/Library/Preferences/ugs` give you an error?

As far as testing - you're right I'm not super formal about it (and for the nightly build there is mainly just unit tests). Fortunately UGS has a lot of users and I take issue reports (like this one) seriously so I think we have pretty good coverage.
