### ISSUE TITLE
Single Step issue

### ISSUE THREAD

**Issue by duisenberg** [winder/Universal-G-Code-Sender#466]
In single step mode, the sender should send a command and then wait for answer. If ok, the next command can be sent, if error the sender should pause the transfer and issue the "skip this command in future" dialog box. 

As it is, the sender sends the next command before pausing the transfer:

![ugs-pauseonerrorfail](https://cloud.githubusercontent.com/assets/21085153/18026799/1d5a7a62-6c52-11e6-808e-8321e739fac3.jpg)

In the above case my firmware (emulating grbl) issues an error at M6 to force ugs to pause transmission, enter its toolchange mode where it moves the table into a position the tool can be changed and after change is done, the next M6 (manually entered or from file) would drive the table back into its last position.

Currently I work around this by sending M1 before an M6 what - since M1 produces an error too to force the transmission to pause - works. But it would be better, if UGS in single step mode acts as expected.

**Comment by winder** [comment]
Nice catch, I'll try to fix this soon.

**Comment by winder** [comment]
This should be resolved now, let me know if you see any other issues with single step mode.

**Comment by duisenberg** [comment]
Looks good, currently its purring like a kitten.  If other issues come up I'll keep u posted.
