### ISSUE TITLE
Translation problems

### ISSUE THREAD

**Issue by cmsteinBR** [winder/Universal-G-Code-Sender#468]
Dear,

Some strings are not being translated (remain in English in the program GUI):

mainWindow.swing.activeStateLabel
gcodeTable.command
gcodeTable.originalCommand
gcodeTable.sent
gcodeTable.done
gcodeTable.response
mainWindow.swing.showCommandTableCheckBox 

They are missing strings to translate the captions of the buttons in tab Machine Control:
Reset X Axis
Reset Y Axis
Reset Z axis

Thanks

Carlos Stein

**Comment by winder** [comment]
I fixed these:
mainWindow.swing.activeStateLabel
Reset X Axis
Reset Y Axis
Reset Z axis

The rest work for me.

**Comment by cmsteinBR** [comment]
ok. Please, see the figures.

Thanks
![capturar2](https://cloud.githubusercontent.com/assets/21204259/18030711/6f94f68c-6c97-11e6-88af-8a6f90eded09.PNG)
![capturar3](https://cloud.githubusercontent.com/assets/21204259/18030712/6fb508be-6c97-11e6-8046-d7d3f5d16272.PNG)
