### ISSUE TITLE
UGS not loading in Netbeans 

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#480]
I assume this PC is missing some sort of software to run this properly?

![ss 2016-09-03 at 07 56 28](https://cloud.githubusercontent.com/assets/17396492/18228048/a42c05b0-7210-11e6-9e00-5f06f88980b1.png)

**Comment by jahnj0584** [comment]
you can close this. JUST got the latest java update, and it removed an old Java7 patch that was on my system. It launches properly now on this computer. Maybe update the req's to include you need Java 8+? Cheers

**Comment by winder** [comment]
Good point. I have a [comment here](http://winder.github.io/ugs_website/download/) but not in the github readme.
