### ISSUE TITLE
SUGGESTION...Editor bug

### ISSUE THREAD

**Issue by DOUG888** [winder/Universal-G-Code-Sender#481]
I realize that at this stage the Editor on Platform is not completed but I have noticed that when I do a SAVE that the Visualizer does not update and neither does the "operating" code, that is until i reload the code then all is correct.
Correcting these 2 issues would make the Editor at least more friendly until the usual editor features are added at a later date.

**Comment by winder** [comment]
Yup, these are definitely on the list
