### ISSUE TITLE
COM port setting question

### ISSUE THREAD

**Issue by DOUG888** [winder/Universal-G-Code-Sender#483]
One thing I just noticed, i forgot to set my port to com5 on startup, which i operate on, so it was set to com1 default, but ran anyway. My guess is that this is a saved setting and it just shows com1 as a display but operates on the setting that i previously made. Am i correct????

If this is a bug, please don't loose focus on your current mission, i can wear it for a while. ;-)

**Comment by breiler** [comment]
Changed the default connection driver in #1198, let us know if this still is a provlem.
