### ISSUE TITLE
Cant control machine while job is sent

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#489]
So on jobs like spoilboard leveling, the file has finish sending before the machine has stopped moving (i have a 800x600mm bed) and that could cause issues. I suggest leaving the start/stop/pause buttons until a machine stops moving after a file has been sent. As it stands, they get greyed out once the last line of code is sent.

**Comment by winder** [comment]
Good point.

**Comment by breiler** [comment]
No longer an issue
