### ISSUE TITLE
IOException while sending status command:null 

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#492]
This message keeps coming up in my console. It started after i sent a $4=1 command to test some drivers (as told from the forums, about a week ago) and now it's basically a constant stream today (i accidently left it connected overnight but that shouldn't damage the arduino, right?)

Just wondering what it's from and if i need to buy a new Uno now to stop seeing it?

**Comment by winder** [comment]
I think this is resolved now, it was just a UI issue, couldn't have harmed your Arduino.
