### ISSUE TITLE
Is UGS Platform 2.0 considered as reliable as 2.0 Classic ?

### ISSUE THREAD

**Issue by splitn2** [winder/Universal-G-Code-Sender#497]
Hi, I'm just wondering whats your recommendation , is 2.0 Platform pretty reliable, I am building a machine with a mate a wee router. Should we be brave and use Platform or be conservative and use Classic 2.0 ? I know its really up to use to decide but your guidance on this is appreciated. Cheers and thanks for all your great work.

**Comment by jahnj0584** [comment]
Use the platform

**Comment by winder** [comment]
The differences are mainly cosmetic. The platform literally uses the UGS Classic as a library, so all the machine communication code is identical.

**Comment by splitn2** [comment]
thanks for the advice guys. I think I have a dud Mega it kind of locks up, now I have tried with with both USG platform and classic  and also bCNC I am getting similar problems. cheers

**Comment by jahnj0584** [comment]
Did you send $X?

**Comment by splitn2** [comment]
I'll have a closer look tonight..... thanks @jahnj0584
