### ISSUE TITLE
UGS platform error

### ISSUE THREAD

**Issue by Encarnacao** [winder/Universal-G-Code-Sender#499]
i dont know what i did but  now every time i send a file when i hit start tells me  
"An error was detected while sending 1Z:error: Expected command letter.STreaming has been paused.
Would you like to skip commands like this in future?"
if i say ignore then comes
"An error was detected while sending G X7.52 Y17.81 error: Bad number format.STreaming has been paused."
Would you like to skip commands like this in future?"

and so on

I never had this problem i  have delet app data ugs platform and  start program from fresh and still same poblem, i have tested in Grbl controler program and all is fine no errors with same file, any idea what could be wrong?

**Comment by Encarnacao** [comment]
ups i figuer out was on the list of ignore

**Comment by DIYF** [comment]
Wer can i find the list of ignore ?
