### ISSUE TITLE
File duration information 

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#500]
Would it be possible to add things such as: 

Run time for last time file was sent (as in saving it within the gcode or into the title)

Run time saved after file is sent (i charge for jobs but the timer resets itself sometimes before i can check it - leave time until new file is loaded, or a console message such as ***Finished sending testfile.nc in 10:36***)

Total run time: tally how long the machine was running today/this week/all time. Not necessary but would be a cool feature (some music players do this)

**Comment by winder** [comment]
All set, the finished sending message: `**** Finished sending file in 12:34:56 ****`

**Comment by jahnj0584** [comment]
I JUST opened the version from the last hour. Time to redownload :P thanks a bunch for the super fast turnaround
