### ISSUE TITLE
Potential GUI Idea

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#504]
Just messing around. Puts everything on one screen without tabs, but even bigger buttons then currently so should be easier to use on tablets or low res screens. Lemme know what you think, and if this is a possibility. 

My Ideas - left to right:
Feed rate could be a drop down menu to select rapids/spindle/feeds.
On/off quick toggle of over rides 
Units/mm would be what the machine is running at (could prevent situations like I just posted in #503 , since you'd tell when the machine is at its max software velocity)
Macros would be all customization, but included from the get go. The Prompt command would allow for the probe ones to be easily implemented?
Visualizer text moved further from the leaders, easier to read
Soft reset to the connection bar
Machine coords and reset are in one box, I stole the pic from Mach3 but it looks good. Home would return that one axis to its G92 or other offset.
Jog sizes that are "quick select" 
Larger sent/stop/pause buttons, useful for emergency situations/touch screens
G/C are by the files, for when they are actually used

![ugs ui](https://cloud.githubusercontent.com/assets/17396492/19373240/e880dce8-9198-11e6-9417-014c8705b67d.png)

**Comment by DOUG888** [comment]
I like the Idea, one screen with all the info displayed is better than jumping into tabs to find the info, luv the bigger buttons, can’t remember all the times I have clicked stop instead of pause, but don’t forget the Macros, there could be a lot of those dependant on the end user, I currently have 6 but most likely more will come as I learn more myself.

**Comment by winder** [comment]
One of the main drivers towards using a GUI framework like netbeans was to avoid the "one-size-fits-all" design. You can move the windows around however you like. Most of the tabs are designed to be standalone widgets that you can mix and match for this reason. It also makes it much easier to add new widgets, since they don't have to be permanently embedded into the existing UI.

In that spirit I'm curious specifically at the widget level, which ones should change or be combined? Seems like the new overrides UI could be improved (not surprising, I whipped that one up quickly).

**Comment by jahnj0584** [comment]
I kind of expected that answer. What works for me definitely won't work so well for someone who cuts differently. I really hate the mach3 UI as it's over crowded and has unnecessary parts.

 I think if anything, you should seperate every module and have it be an option to join them (say, jog controller with machine coords or macros+common actions) so they can be moved together. 


Here is the closest I was able to get (can't upload to github on mobile, and shop pc getting Internet today) 
http://imgur.com/qkjFLnN

The issue is some modules have a "min size" and therefore can't be more compressed. My suggestions for each module are marked already, but I can list them out if you'd like a task list to run through? Im starting to feel like I'm the only one complaining for new features in this forum :P (Don't worry, i will be donating soon enough)

**Comment by DOUG888** [comment]
Hi Guys..
After reading your posts I have found how to move , resize, float etc the individual windows....but, when i dock them they do not stay in the same place or size that i had set, what's the trick???   ;-)
Doug

**Comment by jahnj0584** [comment]
You drag the title bar, without popping them out. Like where it says
console, drag the actual word tab and the orange square shows where itll be

**Comment by DOUG888** [comment]
Will, your comment  
> In that spirit I'm curious specifically at the widget level, which ones should change or be combined? Seems like the new overrides UI could be improved (not surprising, I whipped that one up quickly).
  
In JOG, I think if you moved the XYZ buttons to the RH of the STEP Size box you would have the same minimum width as the OVERRIDE UI, then you could blend the two together vertically, then they could be compressed vertically to MIN height, this would create more space in that column for other UI, etc, etc.

**Comment by DOUG888** [comment]
OK, got that to work, thanks.

Have run out of vertical room in my LH column, even with all the UI pushed up to minimum, I hope Will modifies the JOG UI as suggested as it will give more vertical available space.

**Comment by jahnj0584** [comment]
You can also just use keyboard commands to jog, such as ctrl+arrow keys and
place it wherever. I have no issue with space

**Comment by DOUG888** [comment]
Yep, got the movement working, as you described but still out of space LH column,, I think I am trying to get too much in and am exceeding the available vertical space.

I have used the “SIZE GROUP” on each of the UI, if I understand this command correctly, it reduces the UI to its designated Minimum, in this case vertically, horizontal would be set by the “Speed Overrides” UI which is the widest. Screen resolution is at Max. if that makes a difference.

**Comment by DOUG888** [comment]
Preamble: I did a lot of programming in Visual Basic for many companies i worked for and became proficient in Maximizing available space without cluttering thinks up, so these are graphical, space optimizing suggestions, not criticisms, please take them as such.

Ok..have been experimenting with relocating the UI, here are some suggestions that may be useful:-

firstly the "Speed Overrides" UI appears to be the longest with dimensions of 309 x 112. With this in mind, take 309 as the Maximum UI design width for "Common Actions", "Jog Control", Send Progress", and DRO"
This does not mean that they can't be stretched further, just keep the buttons inside 309.

Now, In "Jog Controller", put Step Size, Inches and Millimeters on one line, if its tight, the step size box only needs 4 characters, this would still give 9999MM of step. Move the JOG buttons up. new area now approx 309 x 190.

Next. In "Send Progress", move "Rows", "Sent" and Remaining" to the LH side, abbreviate text to read "Rows", "Sent" and Remaining", now move "Est Time Remaining" and "Duration" up to the top RH side, Change "Estimated"to "Est." new UI size approx 309 x 75.

One other thing that could be done is to move the "Help" button to the RH side of the "Common Actions", new size for UI approx 309 x 160.

Results are that all the above mentioned UI now have the ability to combine into one column if required and will Graphically align as well.

As I said, these changes are not a criticism, luv the work so far, just my way of helping with what i can. 
 I have attached a pic, unmodified UI, but you get the idea.
Please note that I seem to be out of space at the bottom of the screen, can't seem to get this corrected, my guess is that i am trying to get too much into one column, these suggestions will eliminate that and give space to spare.
![picture 2016-10-16 11_31_46](https://cloud.githubusercontent.com/assets/20902894/19414678/64afdad6-93a0-11e6-8c7f-4870de3941bf.png)
Doug
Question: In Workflow Helper, what is Toolname and is it necessary, more space for Filename. I realize that i can adjust column widths.

**Comment by jahnj0584** [comment]
I also think the coord widget should be more like GRBLPanel/mach,with
machine being a smaller number. It's only used for setting offsets or jigs.

Step size could go in the center of the Y/X jog buttons! And the units
could be a selection under the Z buttons or hidden in settings. I don't
like mixing up my units and only run metric.

**Comment by DOUG888** [comment]
Yes, Unit selection in Controller Options makes good sense, typically it’s a set and forget,  Step Size tucked in the middle of XY jog could work, worth a try.

**Comment by DOUG888** [comment]
Will
Just loaded latest UGS platform...the width of the "Speed Override" has been reduced and reconfigured, but the other suggestions from Jahn and myself should still be Viable.

**Comment by breiler** [comment]
There is a lot of ideas in this issue that either has been fixed or needs to be seperated to their own issues. This is a bit too big to work with. 

If there is still stuff you want to have fixed create new issues.
