### ISSUE TITLE
UGS platform problem?

### ISSUE THREAD

**Issue by Encarnacao** [winder/Universal-G-Code-Sender#505]
hi when i put  command $ it doesnt show parameter and outputs this
>>> $
ok
Skipping command #4

when i go to controler options i dont see on ignore list nothing 

is there any problem with it or  iam missing something?

**Comment by winder** [comment]
I noticed this last night, something odd is happening that I haven't figured out yet.

**Comment by Encarnacao** [comment]
i have update my grbl for version 1.1 today but it has nothing to do with it,  cause i have notice this problem for awhile.

**Comment by winder** [comment]
Thanks, found two display problems while fixing this.
