### ISSUE TITLE
Translation to Russian problem

### ISSUE THREAD

**Issue by Werwolfx** [winder/Universal-G-Code-Sender#507]
When I switched on the Russian language, all menu items are gone and can not be switched back to English
Where are the Setup? I use Linux Mint x64

**Comment by Werwolfx** [comment]
I found MessagesBundle_ru_RU.properties contains many blank lines, I now understand why the menu is not displayed after the switch. I know Russian language, and I can help you to translate into Russian. You need this help?

**Comment by jahnj0584** [comment]
Yes he does. Will can link you to the webpage when he's on next

**Comment by winder** [comment]
@Werwolfx Localization is managed here: https://poeditor.com/join/project/2J2hB5I41Z

Someone started working on it fairly recently but never finished. Thanks for the offer!

**Comment by SadovovAlex** [comment]
HI

i translated to Russian lang 100%

https://poeditor.com/projects/po_edit?id_language=134&id=52743

Please see it

**Comment by winder** [comment]
@SadovovAlex Thanks! There were a couple terms I added recently and forgot to import to poeditor. Could you update those last terms? I'll get them into the project later this morning

**Comment by SadovovAlex** [comment]
@winder Sorry for the long absence...

I translated the remaining rows to russian language.
