### ISSUE TITLE
$$ Output cosmetics

### ISSUE THREAD

**Issue by Encarnacao** [winder/Universal-G-Code-Sender#510]
i dont know but seems that the way is set the output of the command $$ of the grbl settings is a litle to mutch on screen

$0=10 (microseconds, Step pulse time: Sets time length per step. Minimum 3usec.)

 like was before looks better, the information is great no daut but maybe you could set in help files the information detailed and leave on the output has was before

 on screen like was before looks better

$0=10 (step pulse, usec)

i think someone have also mention this before, i could find the post

just a tought  looks more fancy like it was before, just cosmetics p:

**Comment by winder** [comment]
I agree, switched it back.

<img width="379" alt="settings" src="https://cloud.githubusercontent.com/assets/125509/19616549/0124747a-97e4-11e6-8e79-5fa6b5a4f86d.png">

**Comment by jahnj0584** [comment]
Thanks
