### ISSUE TITLE
visualizer problem

### ISSUE THREAD

**Issue by ufraa** [winder/Universal-G-Code-Sender#511]
Hi all, 
i have a problem with visualizer. in the config menu all items in the list are disappeared and set to the same color, i can change them but when i press apply it resets to the previous color. if i change the last item color and press apply it sets the color for all the items
![cattura](https://cloud.githubusercontent.com/assets/6683704/19595978/b3d2d09c-978c-11e6-9784-e9d081feb723.PNG)
![cattura1](https://cloud.githubusercontent.com/assets/6683704/19595994/c2d65dd4-978c-11e6-8c14-52eedf474cee.PNG)

**Comment by Encarnacao** [comment]
no clue what could be did u try maybe delete temp files and reinstall to see if fixes?

**Comment by winder** [comment]
Very strange. My guess is that somehow the configuration files were corrupted and things are crashing when they try to load/use them.

In the about menu it tells you the location of the **Cache directory** and **User directory**. Try deleting those directories.

**Comment by winder** [comment]
@ufraa were you able to try removing the cache and user directories?

**Comment by ufraa** [comment]
Yes. The problem was one of the file and the italian localization
Thank you so much

Il 28 ott 2016 11:44 PM, "Will Winder" <notifications@github.com> ha
scritto:

**Comment by winder** [comment]
@ufraa this seems to have something to do with localization, I'm not quite sure why though.

For now if you would like to contribute Italian translations, that should prevent the issue from happening for now. You can join the localization team here: https://poeditor.com/join/project/2J2hB5I41Z
