### ISSUE TITLE
UGS Platform tabs organization

### ISSUE THREAD

**Issue by vMeph** [winder/Universal-G-Code-Sender#513]
would it be possible to add extra tabs to this area sense theres alot empty space there for a better organization, i wanted to  put there the browser files for exemple for better visualization  but it dont allows to do it

![pp](https://cloud.githubusercontent.com/assets/12812111/19612983/abae2538-97e1-11e6-97e9-72495d644556.png)

**Comment by winder** [comment]
Yes, the content of the top bar is totally customizable. Right now the contents are in two widgets but many more could be added. Also just like the panels these can be enabled/disabled and moved around.

**Comment by Encarnacao** [comment]
so for what i understand they are in seperate widgets so how can i move the  " file browser " to the top?
it dont let me , and i dont see where is enable or disable option

**Comment by winder** [comment]
When I said many more could be added I meant that I could create more of them. Right now there are just two.

**Comment by Encarnacao** [comment]
thanks :)

**Comment by jahnj0584** [comment]
yea, that whole tab/bar is "locked" for me.

**Comment by jahnj0584** [comment]
The send buttons also should be seperate and larger. I like the idea of
adding the open bar there

**Comment by winder** [comment]
Added the file browser:
<img width="1127" alt="screen shot 2016-11-06 at 8 56 11 am" src="https://cloud.githubusercontent.com/assets/125509/20038294/eb7cee50-a3fe-11e6-83be-b9ac0d9c0c5d.png">

**Comment by vMeph** [comment]
Not home ill test later, thanks alot Will😁

**Comment by vMeph** [comment]
@winder  #678 shows has failed
