### ISSUE TITLE
Java.lang.integer cannot be cast to java.lang.Double

### ISSUE THREAD

**Issue by jglazer63** [winder/Universal-G-Code-Sender#515]
I just installed 2.0, connected to my machine (opened the port) and hit "X+" and got the above error.  It happens on X+, X-, Y+, Y-, Z+, Z-.  Pretty much cannot jog the spindle at all.  How did this get past testing and to release?

**Comment by winder** [comment]
Thanks for the report. The nightly build is released automatically on every commit, sometimes small issue like this sneak through since the unit tests don't cover the UI and most manual testing is focused on the platform UI.

**Comment by jglazer63** [comment]
Thanks for the quick response.  I'll get the latest and try again later today.
