### ISSUE TITLE
Workflow Event Box opens on Jog

### ISSUE THREAD

**Issue by DOUG888** [winder/Universal-G-Code-Sender#517]
Now running GRBL 1.1 and latest working "Nightly Build" Platform.

When i move around with Jog I get the workflow event "finished sending last file" popup appearing at each jog, this could be annoying ,to say the least  :-)
particularly if you are doing small repeated jogs.

This same box also appears when any of the "Common Action" buttons are pressed and also the "Macro" buttons.

can this be removed please....or limited to only when the job is finished.

The Units button in Jog Controller resets itself from "mm" to " , when i press one of my macro buttons...all it contains is a "M8" command.

also I noticed that the Z step does not respond to the scrolling arrows in the box, even when typed in, feed rate and xy step are ok.

Thats all for now, will continue testing.

Thanks
Doug

**Comment by DOUG888** [comment]
Now running GRBL 1.1d and UGS platform #671....same issues as above.

**Comment by winder** [comment]
@DOUG888 this is on my radar. My test arduino blew up on monday and I'm still waiting on the replacement. You can see an explanation I posted on #522

**Comment by DOUG888** [comment]
Ouch!!!  All good Will..new you would get to it ...hope the replacement gets to you soon.
Also..while the test bed is down...I had 2 other issues up, one you asked me to put s a reminder to you..that was on the COM port auto reconnect..I think that is OK, you might want to delete it.
