### ISSUE TITLE
UGS platform #670 update

### ISSUE THREAD

**Issue by Encarnacao** [winder/Universal-G-Code-Sender#521]
![k](https://cloud.githubusercontent.com/assets/12812111/19804126/5087ed38-9d04-11e6-9b13-194dc4b56fcb.png)

where is the buttons to conect machine and port choise?

**Comment by winder** [comment]
Oops sorry about that. The little red circle in the bottom right has the error message, but I was able to reproduce the issue as well.

The worst part is that the feature I was adding didn't even work that well:
<img width="262" alt="screen shot 2016-10-28 at 8 29 06 am" src="https://cloud.githubusercontent.com/assets/125509/19806466/237dfd7a-9ce9-11e6-8a8b-7fa64426a0de.png">

Also new buttons you can add keyboard shortcuts to:
<img width="163" alt="screen shot 2016-10-28 at 8 29 16 am" src="https://cloud.githubusercontent.com/assets/125509/19806479/368f83de-9ce9-11e6-9c4f-64570bb113e3.png">

**Comment by Encarnacao** [comment]
thanks for the fast update, if you dont forget if would be possible to be possible to add the other widget panel to that widget on top like for exemple"files browser"
that would rox
