### ISSUE TITLE
Macros?

### ISSUE THREAD

**Issue by vMeph** [winder/Universal-G-Code-Sender#529]
on macros everytime you create a macro it will add a new line for a new  macro eavean if you dont need, maybe would be good to have a button to add new macro and a button to delete a macro other then to keep adding buttons?

**Comment by winder** [comment]
@vMeph You should no longer need to restart UGS to see the macro configurations now, also empty buttons are no longer displayed. Hopefully this is easier to use.

**Comment by vMeph** [comment]
awsome
thanks :)
