### ISSUE TITLE
Laser stays on with pause

### ISSUE THREAD

**Issue by DOUG888** [winder/Universal-G-Code-Sender#530]
Hi Guys
Running a laser program and the power board apparently was overheating (first time) pressed PAUSE to give it a chance to cool down but it stayed running at S1000...need an option to set S..... value to Zero while in PAUSE same would apply to a milling operation, for safety if no other reason.
Thanks
Doug

ps: I do have heat sinks on both laser and control board fan assisted

**Comment by jahnj0584** [comment]
Maybe for laser, but when milling you must leave the spindle on as there is acceleration time to restart the spindle on a resume

**Comment by DOUG888** [comment]
Yes…makes sense…mostly laser for me…so still request that this be added, thanks

**Comment by winder** [comment]
Laser mode in GRBL v1.1 might do this already.

**Comment by DOUG888** [comment]
OK…How do I activate “”Laser Mode”” or are there specific commands that are to be used???

Or does config.h need to be specific for Laser and then another config.h for mill??, Hope this is not the case.

Thanks

**Comment by winder** [comment]
It is the $32 setting. Details here:
https://github.com/gnea/grbl/blob/edge/doc/markdown/settings.md

I don't see anything specific about what happens during a pause. If it doesn't disable the laser that would be a good grbl feature request.

**Comment by DOUG888** [comment]
Thanks Will

Yep, can see the $32, but doesn’t specify the PAUSE question…have asked the question on the GRBL wiki, get back to you when I get an answer.

Thanks

Doug
