### ISSUE TITLE
Suggestion...Laser Mode with planned GRBL Tweeks

### ISSUE THREAD

**Issue by DOUG888** [winder/Universal-G-Code-Sender#534]
Hi All 
Please see the comments by Sonny on planned tweaks, I have some Safety suggestions to work with these as they become available.

> 
From Sonny
ALL: Here are a list of tweaks I'm working on implementing prior to v1.1 master release! Please comment on them, if you disagree, have concerns, or think it's not the right thing to do for ANY reason. I'm fairly new to laser cutters and need user help to figure out some of the details.

    The laser will be automatically disabled whenever the motion mode is not G1, G2, or G3. This includes G0, G38.x, and G80 gcode commands. This is for safety reasons. I just got into laser cutters and it's very evident that safety is a huge issue with these devices. Fires are very easy to start.

    @DOUG888: In response to your earlier query. grbl/grbl#1129 After much thought, I'm going to add laser disabling during a feed hold as the standard behavior.

    There will be two distinct laser cutting modes. Dynamic power and Constant power (rate adjusted). They will be controlled by an M3 and M4 command, respectively. You would normally use M3 Dynamic power mode, but in special cases, like focusing the laser, M4 Constant power mode can be used.
        NOTE: The spindle direction pin will still behave the same way with M3 and M4. So it can be used with an LED to indicate which mode is active.
<

When using the Laser( $32) active I had an error message pop up, this paused the code execution as you would expect, but it did NOT turn the laser power to Zero, fortunately I was on watch quick enough to avoid a major problem, however, it could have been worst. can this be looked at as a safety issue as the above Tweaks are implemented.

I use the Laser for most of my projects with occasional milling operations with a Mill attachment...Are there and detriments/benefits milling with the $32 enabled, or doesn't it matter???...variable velocities on arcs????  If it does make a difference, then a button to change Modes (enable/disable $32) and indicate which mode is enabled would be a benefit.
Sonny mentioned the use of an LED, but screen display would be good.

Thanks
Doug

**Comment by winder** [comment]
@DOUG888 Looks good, thanks for the update!
