### ISSUE TITLE
UGS platform $G - View gcode parser state

### ISSUE THREAD

**Issue by vMeph** [winder/Universal-G-Code-Sender#536]
@winder  are you aware that when you type $G -  to View gcode parser state nothing shows up?
it should show uo the state something like
[G0 G54 G17 G21 G90 G94 M0 M5 M9 T0 S0.0 F500.0]
but nothing shows other then
>>> $G
ok

**Comment by winder** [comment]
@vMeph You could have seen the response if you enable verbose console output. But that brings lots of other stuff to the console, so I added this back to the regular console as well.
