### ISSUE TITLE
Optional seperate Z axis

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#538]
well, i might be the only person who doesnt like the new optional jog Z settings! Can you PLEASE make this an optional thing? I broke a bit tonight because while using 0.1mm Z I expected XY to do the same but they were still on 10. I'd much rather the space be used for 0.1/1/10 selectable increments or not at all.

**Comment by aforww** [comment]
I absolutely agree with this. I use an xbox controller mapped to keyboard shortcuts to manage everything and now I canI because I have no way of mapping step adjustments to z. Please make this an optional change.

**Comment by aforww** [comment]
I see you closed the issue.  however, I'm new to this and don't know what to make of the changes.  I know I still can't adjust all three axis simultaneously.  Is there a setting for this now?

**Comment by jahnj0584** [comment]
it seems like you have an option in the settings window. You have to re-download the file or read #546

**Comment by aforww** [comment]
Thank you. I will try and figure it out.  Again,  new to this.  What do you mean download the file?  The nightly builds or something else?

**Comment by jahnj0584** [comment]
yep, just off the front page here in github! The zip for ugsplatform.

**Comment by winder** [comment]
@aforww this doesn't let you jog in multiple directions at the same time, it lets you use a single step size for XY and Z.

<img width="926" alt="optional-z-step-size" src="https://cloud.githubusercontent.com/assets/125509/20863100/5db37328-b98e-11e6-9e1c-527abf550f39.png">

**Comment by aforww** [comment]
By "adjust"  I meant change step size for all three.  But I found the settings about twenty minutes ago.  Thanks for the reply though,  I really appreciate it!
