### ISSUE TITLE
Move reset X/Y/Z buttons beside work 0

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#540]
I think it would make much more sense for them to be there, and not in the common actions window. Machine coords should also just be a subscript underneath as it's only used for reference if using jigs + homing. 

Ideally, it'd be great if EVERY button could be moved around as docked as we see fit, then locked into our own "windows" that we manage (ie jog controller, coords, file mananger, etc)

**Comment by winder** [comment]
Here's the new panel. I added the pin states tonight as well, the panel is getting pretty big though so I might make separate windows for the DRO and the state/comment/pin.

<img width="303" alt="screen shot 2016-11-20 at 12 55 55 am" src="https://cloud.githubusercontent.com/assets/125509/20460745/65b059d8-aebc-11e6-9154-255049af2019.png">

**Comment by jahnj0584** [comment]
What are the pin States for?

**Comment by jahnj0584** [comment]
But yes seperate would be good. I feel like I won't be using them

**Comment by winder** [comment]
They tell you when the various external switches GRBL supports are activated. Like the probe, or XYZ endstops.

**Comment by jahnj0584** [comment]
Does it just go by what's plugged in? I just ordered an E-stop but if it
would be programmed to just pause the program and spindle that'd be gravy

**Comment by winder** [comment]
Yes, it's just for reporting. Sonny is adding a feature to pause the spindle (laser) when laser mode is enabled. Maybe you could ask him to bring that feature to non-laser mode.
