### ISSUE TITLE
Return to 0 axis order

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#542]
Still having issues where it moves Z to work 0 first. Please just revert this to be XY then Z, OR raise it by a user configurable amount.

**Comment by winder** [comment]
Z should only go to zero first if it was < 0 before, otherwise it should behave the way you described.

**Comment by jahnj0584** [comment]
it didnt today, when I just re-downloaded it. I made sure to connect with the Z at the top to set a high Z0 too!

**Comment by DirkHeinke** [comment]
Probably the problem is in in GrblController: https://github.com/winder/Universal-G-Code-Sender/blob/master/ugs-core/src/com/willwinder/universalgcodesender/GrblController.java#L354

`this.machineLocation.z` is used, but in my opinion this should be `this.workLocation.z`?

**Comment by aforww** [comment]
I am having the same issue. It is not existent on my other machine running a different version. I have homing switches installed and home every time I turn the machine on. So, Home, jog to desired work coordinates, reset zero. From there, anytime I hit "return to zero" it drops Z-axis first onto the work piece then drags it to X and Y zero. The G90 G0 Z0 command being issues before G90 G0 X0 Y0 Z0 needs to be changed.

**Comment by DirkHeinke** [comment]
Do you see two G90 G0 Z0 commands?
```
G90 G0 Z0
G90 G0 X0 Y0
G90 G0 Z0
```
That is what I see at my maschine.

**Comment by aforww** [comment]
No,  just the one. I thought the one was off,  but having two.  That makes
no sense.

**Comment by winder** [comment]
@DirkHeinke I just noticed your comment from 6 days ago. I think you're right and I've updated the code accordingly. Let me know if this helps the situation.

**Comment by DirkHeinke** [comment]
Yes, I just downloaded the latest nightly build and tested it. First X/Y-axis, followed by Z. Perfect, thanks for the fix.
