### ISSUE TITLE
new jog issues

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#544]
since the new jogs, you can no longer send a continuous stream. It sends, locks, then unlocks the controller when the first command is finished sending. This is REALLY annoying and makes for a very cumbersome and jerky style of jogging. The old way was A LOT better, and if it means removing the feed command that has been added, then I accept the small sacrifice.

**Comment by winder** [comment]
I made some tweaks a couple nights ago to fix the weird GUI state changes, you should be able to queue up a bunch of jogs in a row now.

**Comment by jahnj0584** [comment]
I was using a fresh download from today

**Comment by vMeph** [comment]
i have new version and also same problem you cant send a continous move on jog

**Comment by winder** [comment]
@jahnj0584 @vMeph This should finally be fixed.
