### ISSUE TITLE
UGS platform Feedrate

### ISSUE THREAD

**Issue by vMeph** [winder/Universal-G-Code-Sender#545]
when you first connect machine the feedrate is set to 10 on jog controler and if you send command lets assume F1000  nothing changes, same  if i do a macro button with F1000 when machine first connect you got no acess to macro butttons, nothing changes unless you go to jog controller and change the feed rate, it didnt use to be like that, so everytime i start machine if i want to me arround im force to go to jog control to make changes when i could have a easy acess by making a macro button with F1000 and just click and star moving arround or just type a F1000 on command line

it makes sense that it should let you acess macro buttons when you first connect machine?
it makes sense that it should let you change feed rate by using a macro button or by  sending a command?

**Comment by jahnj0584** [comment]
Did you send $X first?

**Comment by vMeph** [comment]
i did do you have same problem or works fine?

**Comment by jahnj0584** [comment]
I didn't have this issue yesterday but I do think the feed rate option for
jogs should be removed or only set as 100/75/50 of your X/Y/Z rapid speed
set by the $ configuration

**Comment by winder** [comment]
@vMeph I found the feed rate issue, it wasn't being restored or updated properly. I don't follow the issue with macros though. They don't enable for you when the machine starts?

What version of GRBL are you using?

**Comment by vMeph** [comment]
yes what i mean is when i start machine they are enable, but sense i have switches i got to first remove alarm $X and then macros buttons become disable, they only be enable if i do a jog move after

**Comment by winder** [comment]
@vMeph this should be working, let me know if you're still seeing problems.
