### ISSUE TITLE
Smaller download size

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#546]
I understand this a small issue, but my Internet is below 1mb/s and a 30mb download sometimes takes me 5-30 minutes to do, if I don't lose connection. Any way to only download the latest change/commit? Or does that require recompliling on my end or something?

**Comment by winder** [comment]
1) Netbeans Platform has an "auto-update" feature which is really the only way to make the download size smaller. Using it ended up being much more complicated to implement than I was hoping, so I'm not sure if/when that is going to happen.

2) If you install git and a Java IDE like Netbeans or Eclipse you could recompile it yourself pulling down just the small commits each time. I have some information about getting started here: http://winder.github.io/ugs_website/dev/getting_started/

In a new directory you run `git clone https://github.com/winder/Universal-G-Code-Sender.git`, then just open that directory with an IDE and look for a green triangle.
