### ISSUE TITLE
Reset axis treated as job 

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#547]
You have to hit the stop button after resetting an axis to be able to reset the other or do anything else.

**Comment by winder** [comment]
Thanks, it looks like any commands which complete instantly are causing problems.

**Comment by breiler** [comment]
Can not reproduce this, it's has been fixed right?

**Comment by breiler** [comment]
Closing as I'm no longer able to reproduce the issue.
