### ISSUE TITLE
VISUALIZE

### ISSUE THREAD

**Issue by RWW549** [winder/Universal-G-Code-Sender#549]
I've used UGS without problems until I upgraded to Windows 10.  The visualizer always had thin precise lines that were easy to keep track of, but since the upgrade, all the lines in the visualizer are many pixels wide and not much better than a blur. the space between the lines is smaller than the lines are supposed to be. No other programs were effected, and I can't find any fix on the windows side. I downloaded a new copy of UGS with the same result. Any suggestions?
![image](https://cloud.githubusercontent.com/assets/24197810/20645288/2e2d52a0-b41f-11e6-9d9e-7990938fe36a.png)

**Comment by jahnj0584** [comment]
its time for you to use the platform anyways.

**Comment by winder** [comment]
@rww549 I'm not sure what causes this, but it's been a problem pretty much
since day 1 of the visualizer for some people on windows. The ugs platform
visualizer has been almost completely rewritten and seems to be more
consistent across different operating systems.

**Comment by RWW549** [comment]
Thanks for the quick reply. It's still worth a lot more than I paid for it, but if you happen to find a fix, let me know.    Thanks.
