### ISSUE TITLE
Machine or Working location

### ISSUE THREAD

**Issue by jpbbricole** [winder/Universal-G-Code-Sender#550]
Concern UGS 2.0
When I change the location mode, $10=1 or $10=2, Machine status changes!
Why?

**Comment by winder** [comment]
UGS uses GRBL status reports to display status information. You're changing the status reports so the UGS display changes.

**Comment by jpbbricole** [comment]
Hi winder
I'm using GRBL 1.1
When I swap between Mpos ($10=1) and Wpos ($10=2) the displayed positions, machine position or work position, in UGS interface must be the same.

If WPos: is given, use MPos = WPos + WCO.
If MPos: is given, use WPos = MPos - WCO.

Ref.: https://github.com/gnea/grbl/blob/edge/doc/markdown/interface.md

Best ragards
jpbbricole
