### ISSUE TITLE
Cannot jog less than 1mm

### ISSUE THREAD

**Issue by jglazer63** [winder/Universal-G-Code-Sender#553]
I appreciate fixing the keyboard jog but now I cannot go less than 1mm. Even though it says .001mm it still seems to go much more than that.  Nothing changes from 1-0mm.

**Comment by ganeby** [comment]
Hello

has no-one answered you yet?

Grant

**Comment by winder** [comment]
I haven't had time to look at this one yet

**Comment by jahnj0584** [comment]
It has to be his side or from the latest version I always use 0.1mm when
setting my zero

**Comment by ganeby** [comment]
Hello, I think it is grbl.


On 14 Dec 2016 8:38 pm, Julius <notifications@github.com> wrote:
It has to be his side or from the latest version I always use 0.1mm when
setting my zero

**Comment by chamnit** [comment]
The only reason Grbl would not move less than 1mm is if the steps/mm setting is >= 1. There isn't much else that would cause that type of behavior.

**Comment by winder** [comment]
@jglazer63 I can't reproduce this in the Classic or Platform versions. If you are typing in a number you might have to tab out of the text box in order for it to register. Let me know if you're still seeing issues.
