### ISSUE TITLE
Feature request: sending email/text when job is done

### ISSUE THREAD

**Issue by shayo** [winder/Universal-G-Code-Sender#555]
Would be nice to have a way to send an SMS or an email when jobs are done so I don't have to come and check the machine :)

**Comment by jahnj0584** [comment]
Can you not just enable sleep mode for GRBl and set a timer?

**Comment by winder** [comment]
It's an interesting suggestion, but I'm not sure I want to encourage people to leave their machines unattended.

**Comment by shayo** [comment]
I'm doing aluminum with Xcarve so I need to go very slow.... jobs can take
couple of hours. I'm not going to babysit my machine :)

Shay Ohayon
HHMI Postdoc Fellow of the Life Sciences Research Foundation
DiCarlo's lab, MIT, 46-6147
+1 617-324-3593

**Comment by aforww** [comment]
Invest in a web cam then.  Problem solved.

**Comment by shayo** [comment]
Workaround... My Form2 3D printer has no problem sending me emails when
jobs are done.

Shay Ohayon
HHMI Postdoc Fellow of the Life Sciences Research Foundation
DiCarlo's lab, MIT, 46-6147
+1 617-324-3593
