### ISSUE TITLE
Baudrate 230400 needed

### ISSUE THREAD

**Issue by tymop** [winder/Universal-G-Code-Sender#558]
The baudrate for arduino grbl is 230400 baud. I'm able to connect and send Gcode by hand on the serial port. But I can't connect with Universal-G-Code-Sender because the maximum baudrate is 115200.
I do not know how to add it.

Please add 230400 baud and maybe the others higher.

thank you!

**Comment by winder** [comment]
@tymop Added 230400. FYI that field is editable so you can workaround the issue if you are testing something with an even higher baudrate.

**Comment by tymop** [comment]
I can not see the new baudrate.
I downloaded the zip file, and replaced my old folder, but I can not see the 230400 baudrate.

You said I can edit it. But how ? It is impossible to modify the field.

**Comment by winder** [comment]
@tymop You can edit the field in the "platform" version. The nightly builds have this change in it.

**Comment by TamGit** [comment]
Good morning,
I'm also interested in modifying the baudrate at higher value than 230400 but I can't find where to edit it ?
It's about laser engraving where the segments are way smaller than when milling stuffs.
Thanks.

**Comment by winder** [comment]
@TamGit This option is in the nightly build version at the bottom of the page here: http://winder.github.io/ugs_website/download/

**Comment by TamGit** [comment]
Ok I got it. I thought it was about a file to modify but it's the baudrate field that is directly editable.
Perfect !
Thanks.

**Comment by awd86** [comment]
So I'm having a similar issue just trying to set 115200. Sorry to resurrect the thread, but can anyone help me find where to edit the baud rate in the files? 

I can't use the mouse to select any options below the boundary of the window. Also, i can't edit the baud rate field. I'm using Ubuntu on an old Optiplex 330

**Comment by vMeph** [comment]
@awd86  
GRBL by defaul comes with  115200 baudrate already
so most like you have to change in the UGS the baudrate to 115200 also, i think comes at 9600 baudrate by default

anyway if you want to confirm on GRBL files you can look on GRBL folder in libary, the config.h file 
on lines 40,41,42 you will see this

// Serial baud rate
// #define BAUD_RATE 230400
#define BAUD_RATE 115200

like you see is already set to 115200 baudrate by default

**Comment by winder** [comment]
@awd86 it sounds like you might be using an old version of UGS. Try v1.0.9 or the nightly build.

**Comment by DiegoChajtur** [comment]
Please add 250000 baud or add editable baudrate field please

**Comment by breiler** [comment]
@DiegoChajtur it is now available in the latest nightly build.
