### ISSUE TITLE
Unable to conduct soft reset after soft limits hit

### ISSUE THREAD

**Issue by Bosque00** [winder/Universal-G-Code-Sender#563]
Summary:
When soft limits are reached the UGSplatform disables all buttons in "Common Actions" not allowing a user to conduct a soft reset of Grbl. Currently disconnecting and reconnecting serial port to reset Grbl. This looses the current position.

Hardware:

Shapoko 3
Software:
Grbl 0.9g
Java: 1.8.0_51; Java HotSpot(TM) Client VM 25.51-b03 Runtime: Java(TM) SE Runtime Environment 1.8.0_51-b16
ugsplatform.exe 1/1/2017
System:
Windows 7 version 6.1 running on x86; Cp1252; en_US (serverlaunch)
Steps to create error:

Start Grbl
Start UGSplatform
Home system
Use jog controller to move any axis past a soft limit.
Attempt to issue a soft reset command
Workaround - Disconnect the serial port and reconnect it. Position is lost.

**Comment by jahnj0584** [comment]
Try only using UGS and the stop button or $X

**Comment by Bosque00** [comment]
This works using the UGS and $X.

**Comment by Bosque00** [comment]
This works using the UGS and $X.

**Comment by kardinal7** [comment]
The same happens to me in the platform. If limit switch is detected I need to disconnect the UGS platform and re-connect

**Comment by 71tr6** [comment]
> Start Grbl
Start UGSplatform
Home system
Use jog controller to move any axis past a soft limit.
Attempt to issue a soft reset command
Workaround - Disconnect the serial port and reconnect it. Position is lost.

Same thing here. You don't even have to physically move the axis, just give a g code command that exceeds the soft limit.

**Comment by aforww** [comment]
Was there ever a resolution to this?

**Comment by Bosque00** [comment]
I have not used UGSplatform since finding this issue as the feature works better in UGS. I will have to try the latest version.

**Comment by winder** [comment]
I haven't worked on this issue yet. I recently wire a button to my test arduino so at least I can finally simulate some of these homing/limit scenarios.

**Comment by aforww** [comment]
@winder it seems to be isolated to platform. Hopefully it gets worked out.

**Comment by cjbaar** [comment]
I am not sure if this is the best place to comment on this, but I am having a similar issue. After hitting a hard reset (running into a physical limit switch), I have to disconnect and reconnect the serial port in order to reset the arduino firmware. However, about 25% of time, the "Jog Controller" functions do not re-activate. Even after homing or issuing $X, they are still grayed-out, and I have to quit and re-launch. I am using the platform version on OSX.

**Comment by winder** [comment]
Thanks everyone for bearing with me. This issue is finally resolved.

<img width="848" alt="screen shot 2017-07-09 at 10 45 13 am" src="https://user-images.githubusercontent.com/125509/27995077-48208628-6496-11e7-9363-106061556b41.png">

**Comment by aforww** [comment]
You sir, are the man.
