### ISSUE TITLE
G02 ERROR

### ISSUE THREAD

**Issue by DOUG888** [winder/Universal-G-Code-Sender#564]
Just running the new setup, latest GRBL and Platform.
Repeating error at the same code location, have attached screen shot.

Ran the program twice, exactly the same spot, same error.

Also cannot see the XYZ symbols in the DRO next to reset buttons. see same screen shot.
EDIT...THIS APPEARS TO BE AS A RESULT OF THE THEME I AM USING, the the symbols are there but i think the symbol color is to light to see. Any chance of changing the XYZ character color to BLACK, more universal

Apart from that all seems OK..
Thanks for the hard work.
Doug
![picture](https://cloud.githubusercontent.com/assets/20902894/21873183/fc56e82e-d8c0-11e6-8ae0-03274448bf2c.png)

**Comment by jahnj0584** [comment]
Your column width is probably too narrow. I also had issues sometimes with
the long strings of commands, even they they fit under the settings.

**Comment by vMeph** [comment]
Off the topic what ugs skin you using? Where to download? How to install?
Thanks

**Comment by DOUG888** [comment]
Jahnj
Thanks for the feedback, but what exactly do you mean by column width??? Which column?

**Comment by DOUG888** [comment]
vMeph
This is a theme file called Darcula.jar , I have attached the file but i don't remember how to install it. There are other themes available ...go to  TOOLS/OPTIONS/APPEARANCE/LOOK AND FEEL....YOU WILL SEE THEM THERE.
[com.revivius.nb-darcula.zip](https://github.com/winder/Universal-G-Code-Sender/files/703053/com.revivius.nb-darcula.zip)

**Comment by winder** [comment]
I heard recently that this issue happens with fusion 360 when generating gcode in inches. The 33 error means that the arc was not specified accurately enough. If this is still a problem you could try posting it on the grbl github for more details.
