### ISSUE TITLE
ugs nightly deletes nc file

### ISSUE THREAD

**Issue by holla2040** [winder/Universal-G-Code-Sender#566]
I'm running the nightly build on ubuntu 16.04 with oracle java 1.8.0.11 and grbl 1.1. When I open /tmp/a.nc, the contents of a.nc are deleted and ugs displays 0 lines. Something is wrong here.

**Comment by winder** [comment]
@holla2040 I'm surprised you were the only person to report this over the years. I was putting the preprocessed gcode file in the system temp directory which was replacing the original. Finally resolved.

**Comment by holla2040** [comment]
glad you found it. Thanks for the fix.
