### ISSUE TITLE
Cant open File on OSX 10.11

### ISSUE THREAD

**Issue by f0m3** [winder/Universal-G-Code-Sender#569]
When i try to open a file in ugcs plattform i get a small Window with:
"Error while starting file stream: nulling"
This error doesn't always appear... I'm trying to figure out under what circumstances it happens...

**Comment by f0m3** [comment]
When i do not get this error messages after i browsed the file and opened it there are no "rows in file" mentioned in the "send" tab. The visualization doesnt show anything but the "basic grid". I double checked the file in ugcs classic.

**Comment by joacimb** [comment]
To be able to fix these kinds of problems it needs to be reproducible. Could you post the file you are trying to open?

**Comment by winder** [comment]
I think this is due to the same issue as #600 and should be fixed now.
