### ISSUE TITLE
toggle for speed over ride

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#571]
+/- 10% has its uses, but I'd much prefer optional toggle settings. Think 5/50/100% speeds like on Haas machines Just seems to make more sense to me, or offer both? 5% is more if you are unsure of whether or not youll hit a screw, but +/- percent is good for dialing in speed for cutting in various materials.

**Comment by breiler** [comment]
The commands available in GRBL is in 1% or 10% steps so I'm afraid that this is not possible from the hardware.

We could simulate this in UGS by getting the current override status and then send multiple commands to make up for the increment steps that you suggest. But I it seems a bit risky...
