### ISSUE TITLE
Pin Sensors

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#573]
Any way to incorporate sensors in the UI to show when pins are open/closed or active? Would help out a bunch when setting up limit switches and all that fun stuff. Maybe add a filter level to what counts as an actuation to compensate for electrical noise?

**Comment by vMeph** [comment]
Would be great to have that option,i actualy have it but by using another arduino that is reading the pin states from arduino of grbl with a lcd

**Comment by winder** [comment]
This is available in the ups platform. The DRO panel adds a bunch of
checkboxes to the bottom when you run GRBL 1.1.

**Comment by whitetd** [comment]
Just add leds to the lines, would work fine. I will draw up an example
tonight
