### ISSUE TITLE
universal gcode sender      adjust default settings grbl

### ISSUE THREAD

**Issue by rolfee** [winder/Universal-G-Code-Sender#575]
nightly build jan 22 2017
setup machine open settings grbl       
gui window is blank with no text at all

**Comment by winder** [comment]
What version of GRBL are you using?

**Comment by rolfee** [comment]
version 1.1


________________________________

**Comment by winder** [comment]
Could you share a screenshot of the blank window? I double checked and this window is working fine for me with grbl v1.1 and the nightly build.

**Comment by rolfee** [comment]
i have just replaced grbl with 1.1f  and ugs with a nightly build and all seems fine

**Comment by winder** [comment]
@rolfee thanks for the update
