### ISSUE TITLE
nightly builds fail

### ISSUE THREAD

**Issue by swarfer** [winder/Universal-G-Code-Sender#583]
Hi Will
Clicking on either of the nightly builds links on http://winder.github.io/ugs_website/download/ results in a web page saying that the account has been hibernated.

"This  DEV@cloud account is currently unavailable, 
System status
We're sorry, your Jenkins service is not accessible at the moment.
This account is currently hibernated. "

**Comment by winder** [comment]
Thanks for the heads up, should be working again.
