### ISSUE TITLE
Universal Gcode sender not support for G82 command

### ISSUE THREAD

**Issue by chamiljb** [winder/Universal-G-Code-Sender#585]
When try to implement G82 Gcode in UGS 1.0.8 it shows an error message as **Unsupported statement**.How to fix this error?

**Comment by winder** [comment]
GRBL doesn't support G82, take a look at the end of the page here for the list of supported codes:
https://github.com/gnea/grbl

**Comment by chamiljb** [comment]
Thanks for informing me about this.

Are there any grbl cnc control softwares which can support to G82 command?
