### ISSUE TITLE
Jog being done as individual commands instead of continuous. 

### ISSUE THREAD

**Issue by aforww** [winder/Universal-G-Code-Sender#586]
I'm pretty sure this has been addressed somewhere but I can't seem to find it or a resolution if there is one. When I'm jogging holding down an arrow key, for example, it's jogging as if I'm tapping the arrow instead of moving smoothly as I hold it down. Can someone point me in the right direction?

**Comment by jahnj0584** [comment]
Are you using the latest version? This issue was present a month or two ago
but has been fixed.
