### ISSUE TITLE
2.0 or Platform?

### ISSUE THREAD

**Issue by 71tr6** [winder/Universal-G-Code-Sender#587]
This isn't actually and issue but a question.  Please let me know if there is a more appropriate venue for this sort of query.

I've played with 1.0.9 and 2.0 and Platform.  I really like 2.0 best of the three but I'd like to know in what direction most of the development effort is headed.  To the casual observer, things seem to be headed toward Platform.  Or, are they being developed in parallel and will keep a roughly even level of maturity?

**Comment by winder** [comment]
All of the backend code is shared between the Classic and Platform versions, so any bug fixes or stability improvements benefit both versions. That said, most new features will only be supported in the Platform version.

For example the low-level GRBL v1.1 support (jogging, status updates, error message parsing) is a core feature shared by both versions of UGS. But the real-time feed/speed UI is only available in the Platform.
