### ISSUE TITLE
overrides feed

### ISSUE THREAD

**Issue by vMeph** [winder/Universal-G-Code-Sender#591]
is it possible to add keymaps for overrides feed ++ and feed --?

**Comment by winder** [comment]
Lots of new actions in the menu and keymap:
<img width="567" alt="screen shot 2017-03-31 at 12 03 55 am" src="https://cloud.githubusercontent.com/assets/125509/24536065/04711062-15a6-11e7-8127-a979e0e44aa2.png">

**Comment by vMeph** [comment]
Thanks alot awsome :)
