### ISSUE TITLE
Can not connect to cnc card "Grbl 0.9j ['$' for help] <Idle, WPos> gives an error.

### ISSUE THREAD

**Issue by Seyko5** [winder/Universal-G-Code-Sender#597]
Can not connect to cnc card "Grbl 0.9j ['$' for help]
<Idle, WPos> gives an error.

I want a solution

**Comment by Seyko5** [comment]
![adsiz](https://cloud.githubusercontent.com/assets/26200339/23627686/c2a878e6-02c2-11e7-854f-e913df524c29.jpg)

**Comment by rmisko11** [comment]
It shows that you ARE connected.

**Comment by Seyko5** [comment]
The stepper motors are not moving. Look at the picture

Android için Outlook<https://aka.ms/ghei36> uygulamasını edinin



On Mon, Mar 6, 2017 at 10:23 PM +0200, "rmisko11" <notifications@github.com<mailto:notifications@github.com>> wrote:

It shows that you ARE connected.

**Comment by Seyko5** [comment]
The stepper motors are not moving. Look at the picture

**Comment by winder** [comment]
@Seyko5 Are you resetting your GRBL board in your screenshot? You shouldn't see `Grbl 0.9j ['$' for help]` over and over again. Also the `<Idle, WPos` showing up is very unusual, it means the `>` is not being received from GRBL. What do you see if you select `Show verbose output`?

Are you using a GRBL clone? There are some known issues with CH340G based boards: https://github.com/grbl/grbl/wiki/Known-Bugs#usb-to-serial-transmission-errors

Also, thank you for the Turkish translation. I'll update UGS soon to include it in the nightly build.
