### ISSUE TITLE
UGS no serial ports found

### ISSUE THREAD

**Issue by isitcrunchy** [winder/Universal-G-Code-Sender#599]
I also have the gcode-sender Chrome app working on my macbook and it finds my serial port just fine:

<img width="597" alt="screen shot 2017-03-06 at 12 12 26 pm" src="https://cloud.githubusercontent.com/assets/26234958/23633127/976acf9e-0268-11e7-92a3-ac7479419ddf.png">

My macbook knows the serial port is there

<img width="337" alt="screen shot 2017-03-06 at 12 13 57 pm" src="https://cloud.githubusercontent.com/assets/26234958/23633175/c555fe4c-0268-11e7-95d6-d22e3468663a.png">

But UGS can't find it

<img width="656" alt="screen shot 2017-03-06 at 12 32 29 pm" src="https://cloud.githubusercontent.com/assets/26234958/23633235/ffd9a73a-0268-11e7-85ec-4e358e911701.png">

I have the Eleks mill from china
It has the chinese auridino that needed the patch from
/dev/tty.wchusbserial1420

I have tried turning everything on and off multiple ways

Any help would be appreciated

**Comment by winder** [comment]
You can paste that into the port text box to connect. There's a bug in the
serial library I'm using that causes this.

**Comment by isitcrunchy** [comment]
I must have tried pasting that in a dozen times. But now, this time, with your help it worked.

Thanks for waving whatever magic wand you have.

**Comment by vleroylr** [comment]
Hi, I'm having the same problem, what was it that you pasted and solved the problem? I have windows 10

**Comment by luiscabus** [comment]
I am having the same problem. Only pasting /dev/tty.wchusbserial1420 makes it work

**Comment by stevecooley** [comment]
I am also having this problem with a woodpecker 3.0.1 board, and GRBL 0.9
