### ISSUE TITLE
UGS customize themes?

### ISSUE THREAD

**Issue by vMeph** [winder/Universal-G-Code-Sender#614]
@winder  im not sure if this would be possible

Could UGS have like a area to customize theme, the same way you have for the visualization and console area that we can change colors and text styles?

if we could have a area that we could customize the tables,text,cells,buttons etc.. with option to change colors
i know there is out there themes that you can bring it into UGS, but if we could customize it, to our own style would be great

**Comment by winder** [comment]
@vMeph this isn't something I'm planning to work on, but there seem to be some options available.

You could try this plugin: http://plugins.netbeans.org/plugin/55618/ui-editor

There are also other themes available, but they're pretty difficult to find on the netbeans plugin portal:
https://jaxenter.com/netbeans/the-complete-guide-to-tuning-the-appearance-of-netbeans
