### ISSUE TITLE
Stable Release

### ISSUE THREAD

**Issue by DirkHeinke** [winder/Universal-G-Code-Sender#618]
Hello,

do you plan to release a new stable version? The last release is from 2015 and does not work with the new GRBL 1.x
I would love to do some beta testing if you need someone.

**Comment by jahnj0584** [comment]
2.0 has been stable and usable for all but one of the versions which was
only out for two days.

**Comment by winder** [comment]
@DirkHeinke the Nightly Build is very close to being ready, but I keep getting distracted from the last few items on my checklist. About 40% of UGS downloads are nightly builds, so they are getting a lot of testing. If you'd like to try it out and report any problems you find the download link is at the bottom of this page: http://winder.github.io/ugs_website/download/

I'll try to get a stable release of the 2.0 branch one of these days... I agree, it's been too long.

**Comment by DirkHeinke** [comment]
There are quite some bugs in our setup but they change every nightly build. Can you perhaps declare a release candidate, so that I/we/all other users can report bugs in relation to that release?

**Comment by greyltc** [comment]
Why was this issue closed?
I'm looking for a release here: https://github.com/winder/Universal-G-Code-Sender/releases
Is that the wrong place to look?

**Comment by JacksCrafts** [comment]
http://winder.github.io/ugs_website/download/
Try this one.
