### ISSUE TITLE
GUI Scaling for high DPI/4K screen?

### ISSUE THREAD

**Issue by walkinplaces** [winder/Universal-G-Code-Sender#623]
Are there any tricks to adjust the target resolution of the program? I have a 4k laptop monitor, and the interface comes in really, really small. I'd like to avoid changing to a lower resolution every time I need to use the program... is there workaround?

**Comment by winder** [comment]
@walkinplaces are you using the classic or platform version?

**Comment by walkinplaces** [comment]
@winder I am using the classic version.

**Comment by winder** [comment]
@walkinplaces you can try using a Java9 early release version, it is supposed to fix this. Alternatively, I've been told the Platform version has better support for HiDPI screens.

**Comment by winder** [comment]
Suggested on the Inventables forum: https://discuss.inventables.com/t/solved-ugs-window-too-small/40923/4
```
Windows 10 machine:

Find java.exe you installed.
Right click -> Properties
Go to Compatibility tab
Check Override high DPI scaling behavior.
Scaling performed by: choose System
```
