### ISSUE TITLE
LCD Using AtMega2650

### ISSUE THREAD

**Issue by mahid1** [winder/Universal-G-Code-Sender#633]
Is there any way we can add an LCD with grbl? We plan to use atmega2560 for this project.

**Comment by vMeph** [comment]
you can start by here
https://github.com/grbl/grbl/issues/1125

**Comment by mahid1** [comment]
thanks vMeph i had a look but found nothing specific to mega.

**Comment by winder** [comment]
There is also this project: https://github.com/xpix/XLCD

**Comment by mahid1** [comment]
hi winder. 
I was wondering if using arduino library for lcd display with arduino mega would effect the overall timing of the code.
