### ISSUE TITLE
Unable to use macros

### ISSUE THREAD

**Issue by cjbaar** [winder/Universal-G-Code-Sender#636]
In the absence of being able to customize the stock buttons (return to zero, $h, etc)... I am trying to create macros for precise control. However, I can't get them to work. I have created the information in the settings, as shown below, but clicking on the button in the "Macros" panel does not do anything, and no commands are sent. Is there something else I need to enable? Thanks.
<img width="693" alt="screen shot 2017-04-25 at 2 36 08 pm" src="https://cloud.githubusercontent.com/assets/1058385/25569926/7bcb9fc6-2ddc-11e7-9295-10b1cc14c0a1.png">

**Comment by cjbaar** [comment]
I see this issue was closed quickly, but I don't see any action taken it. The latest version of platform (downloaded last night) still does not have these fixed. I am unable to use any macros at all

**Comment by vMeph** [comment]
Macros works dont know what you trying to achive home is issue by comand $H if you have switches .
your home macro is G91 X259 Y50 ,it seems you work on positive space usualy on cnc you work on negative side.
You have machine position and work positions so lets say you are at home X0 Y0 Z0 and the piece you working on is at X-100 Y-50 Z-7, you jog to there and then you set your working position by using the command G10 P1 L20 X0 Y0 Z0,That will set your work coords to  X0 Y0 Z0 ,WCO on G54,so now you have your machine coords at X-100 Y-50 Z-7 and work coords at X0 Y0 Z0,so when you have a gcode file and you set there G54 and you at home ,when you start file it always will go to the G54 start point WCO X0 Y0 Z0

**Comment by cjbaar** [comment]
The content of the macros is not what is relevant here; I just entered random commands I was using at the time. The macros do nothing. Clicking on the button sends no commands. It doesn't matter what the commands are set to.

**Comment by winder** [comment]
@cjbaar there was a bug where the buttons in the macro settings weren't clickable.  It was fixed which is why the issue was closed. You can see the code change referenced right above your comment yesterday.

The most common way to use macros is from the macro window in the main application and this has always worked. If you closed this window you can re-open it from window menu. Both methods should now be working. Are you running a recent nightly build?

<img width="991" alt="screen shot 2017-05-14 at 9 20 58 am" src="https://cloud.githubusercontent.com/assets/125509/26034194/f711027a-3886-11e7-93bb-96d712a57625.png">

**Comment by cjbaar** [comment]
I am not trying to run the macros from the settings pane; I am clicking on them in the "Macros" panel of the main application window. I just re-downloaded yesterday, using the "UGS Platform" link under the "2.0 Nightly builds" on the main github page. Is there another link I should be using?

**Comment by cjbaar** [comment]
I feel like there is some confusion as to what my issue is. Here is how I am trying to use the macros functionality. I have created a macro in the settings.

<img width="701" alt="1" src="https://cloud.githubusercontent.com/assets/1058385/26036447/2ed4d060-389b-11e7-8fb2-1b8004e45637.png">


Then, I close the settings. The new macro button show up in the macros pane, in the upper-left corner of the GUI window.

<img width="357" alt="2" src="https://cloud.githubusercontent.com/assets/1058385/26036450/42c78c5c-389b-11e7-9e93-1b0a6e8e88e7.png">


Then, I click on this button. It is my understanding that clicking on the button should send whatever command was created in the preferences. However, I get nothing. No command is sent; no data is shown in the console output.

<img width="429" alt="3" src="https://cloud.githubusercontent.com/assets/1058385/26036457/5e0f7402-389b-11e7-9ccc-78cf820f63ac.png">
