### ISSUE TITLE
UGS multiplies all GCode feedrate by 2.6

### ISSUE THREAD

**Issue by jiarko** [winder/Universal-G-Code-Sender#640]
Hi,

I've noticed the UGS multiplies all feedrates by a factor of 2.6. This happens for both "classic GUI" and new "UGS Platform".
here n example:
my GCode -->G2 Y-233.072 Z2.5 J-0.4 F960

UGS table --> G2Y-233.072Z2.5J-0.4F2496

that weird thing is that in the command table I see my correct code in the second column and the "multiplied" one in the first column, so I guess it shouldn't be a parse issue.. this happens for ALL feedrate command

can someone help me?

**Comment by jahnj0584** [comment]
Sounds like you're missing units. A standard to metric would be a 2.54
ratio

**Comment by jiarko** [comment]
That's what I've thought... but than the dimensions would have been wrong not the feedrate... this is the beginning of my GCode...

(T1  D=4 CR=0 - ZMIN=-16 - flat end mill)
G90 G94
G17
G21
M9
T1 M6
S10000 M3
G54

**Comment by winder** [comment]
@jiarko it sounds like you accidentally enabled the feed rate override setting
<img width="751" alt="screen shot 2017-05-01 at 6 15 28 am" src="https://cloud.githubusercontent.com/assets/125509/25577642/b2918b16-2e35-11e7-92a6-fc54095f418a.png">

**Comment by jiarko** [comment]
you're right... I didn't know that there is this panel, so maybe some accidentally hit shortcut enabled this...

I could check this only because you send me the screenshot because in my version there is no labels beside the checkbox... as in the snapshot below

![image](https://cloud.githubusercontent.com/assets/24867746/25577700/b2931052-2e68-11e7-9e06-1985c40fbc91.png)


BTW, when I start the program I get an empty window with an error icon, do you know how to fix these issues?

![image](https://cloud.githubusercontent.com/assets/24867746/25577742/f4db5f3c-2e68-11e7-8fe3-33fedf07e9a8.png)


thanks again

**Comment by winder** [comment]
@jiarko Your language isn't fully localized. I thought those messages were supposed to fall back to english. If you'd like to help finish the localization UGS is using a service here: https://poeditor.com/join/project/2J2hB5I41Z

**Comment by jiarko** [comment]
do you think this is the cause of not having labels beside the "Controller options" window? cause I didn't choose any language setup, in fact all descriptions are in english...

thanx for your help

**Comment by winder** [comment]
The "sender options" tab in the screenshot above has a language selector at the bottom, what is it set to?

**Comment by jiarko** [comment]
your are (again) right. There was Italian as set language, when set English and restart application now I can see the labels.

thanx again!!!

**Comment by jahnj0584** [comment]
True. Check your CAM, and the feed over ride (but that mazes at 200% I
think)
