### ISSUE TITLE
UGS platform firmware settings

### ISSUE THREAD

**Issue by vMeph** [winder/Universal-G-Code-Sender#646]
firmware settings has some bug, when you change firmware settings by using "machine button firmware"
if you click the save button after you change settings, you get this dialog
![1](https://cloud.githubusercontent.com/assets/12812111/25643053/53dba2ee-2f95-11e7-9894-c0d14b4b7aec.png), 
the only way you can close is if you click the X button.

also if you try redo changes again then says
![2](https://cloud.githubusercontent.com/assets/12812111/25643058/5fa80f72-2f95-11e7-878d-692e420f4cd5.png)
the only way to redo changes is by disconect UGS and reconnect again

**Comment by breiler** [comment]
@vMeph we have made some changes with the settings panel that should resolve this. If you have the time I would really appreciate if you tested the latest nightly build and could verify that the issue is resolved.
