### ISSUE TITLE
Add way to alter feedrates and spindle speed during milling

### ISSUE THREAD

**Issue by Harvie** [winder/Universal-G-Code-Sender#648]
Hello,
i've run into the situation where i've improperly set feedrates in my g-code and it was too late to fix that when i noticed... I could have stoped everything, jog to zero, modify g-code and run it again, but it was too much hassle... i think it would be nice if there was option to tune the feedrates online during g-code execution.

So i can set feedrates to eg. 10% or 500% of original while running the g-code. Of course there has to be some safety confirmation feature that will let us review that we didn't entered some ridiculous extreme value.

It would also be handy to be able set spindle speed (separately of feedrates) and Z axis feedrates may be set separately too.

I think it happens to everyone. You are running g-code and your intuition tells you, that you should run code faster or slower just by watching/listening to milling process.

**Comment by vMeph** [comment]
Thats already implanted on UGS

**Comment by jahnj0584** [comment]
Update your software and flash GRBL 1.1

**Comment by winder** [comment]
I'm not planning to add this anytime soon now that it's supported natively in grbl v1.1.

**Comment by Harvie** [comment]
i have grbl v1.1e. it might have this feature. but there's no user friendly GUI for it in ugs-platform.

**Comment by Harvie** [comment]
oh sorry. it's already there, but it's hidden by default...
