### ISSUE TITLE
Co Ordinates - Distance to go

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#656]
Any way to display how much is left on the movement with a current line of command, like a Haas? Helps a lot with the first run of a program to make sure you can clear clamps or NOT dive right into a work piece.

**Comment by breiler** [comment]
This is probably not possible with the standard configuration of GRBL... Numerous commands are streamed and buffered in GRBL and there is no reporting back to UGS which command that's currently in progress.

However there is a way to turn on line reporting when compiling GRBL. Does anyone know if this is a common setting?

**Comment by breiler** [comment]
Closing because of limitations of the hardware
