### ISSUE TITLE
ISSUE #140131

### ISSUE THREAD

**Issue by gdc5414** [winder/Universal-G-Code-Sender#659]
Another issue Im having when attempting to send a file to the CNC...

![ugserror](https://cloud.githubusercontent.com/assets/27893487/26136997/26756878-3a74-11e7-814f-b44f27e5a2af.PNG)

**Comment by winder** [comment]
@gdc5414 G64 is not a supported command.

**Comment by gdc5414** [comment]
Ok, why is f-carve generating the code and how do I get rid of it?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by winder** [comment]
@gdc5414 I don't use f-engrave, but they have a blog post you can follow: http://www.scorchworks.com/Blog/using-f-engrave-with-grbl/
