### ISSUE TITLE
usgPlatform Default Firmware Setting (GRBL 1.1f)

### ISSUE THREAD

**Issue by CNCQuilter** [winder/Universal-G-Code-Sender#660]
While exploring usgplatform, I changed some of the firmware settings for grbl 1.1f.
Is there a list of default firmware settings for grbl 1.1f ?
Thanks

**Comment by winder** [comment]
There aren't really "default settings", it's going to depend on your machine. I'd suggest reviewing the grbl documentation, you can start here: https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration
