### ISSUE TITLE
Feture Request

### ISSUE THREAD

**Issue by hexmaster111** [winder/Universal-G-Code-Sender#663]
Would it be possible to add configurable keyboard shortcuts for every item in ugcs, even for jumping from text boxes.

**Comment by winder** [comment]
@hexmaster111 there are keyboard shortcuts for almost everything in the UGS platform build in the configuration menu. What do you mean by jumping from text boxes, is tab not working for that?

**Comment by hexmaster111** [comment]
I am thinking separate shortcuts to jump to spesfic boxes/the console. I am
thinking a button only interface/ no mouse. Thanks for the speedy response.

**Comment by winder** [comment]
Unfortunately, I doubt I'll ever add this. You can get close - there are shortcuts you can set to open a specific window which I believe sets their focus.
