### ISSUE TITLE
Can't get UGS Platform to launch on macOS Sierra

### ISSUE THREAD

**Issue by clarkdv** [winder/Universal-G-Code-Sender#666]
On my iMac running macOS Sierra 10.12.4, when I double-click the UGS Platform jar file I get the error message "The Java JAR file "core_ugsplatform.jar could not be launched."

I have JRE 8 installed and the most recent version of UGS Platform. When I run plain UGS I have to open the Terminal, cd to the UGS directory and then paste in java -jar -Xmx256m UniversalGcodeSender.jar and it runs.

When I try to launch UGS Platform in the same way, I get in Terminal "Failed to load Main-Class manifest attribute from core_ugsplatform.jar"

What do I need to do to get UGS Platform to run?

**Comment by winder** [comment]
@clarkdv the platform instructions are here, you run a script in the bin directory: http://winder.github.io/ugs_website/guide/platform/#how-to-run
