### ISSUE TITLE
Error while proccessing response

### ISSUE THREAD

**Issue by trbLeeciN** [winder/Universal-G-Code-Sender#667]
Hello, I am trying to use backend in my project. When I do some movements, "I get error dialog saying Error while processing response : An unexpected command was completed by the controller."
However after this error, I can use all ugs functions. How can I get rid of this error? all I want is hide that error dialog

**Comment by winder** [comment]
@trbLeeciN if you look in `GUIBackend.java` there are a few places calling `displayErrorDialog`. You can comment those out.
