### ISSUE TITLE
Machine status doesn't update

### ISSUE THREAD

**Issue by Bair22** [winder/Universal-G-Code-Sender#682]
I'm using UGS 1.09 and GRBL1.1 everything is working just fine 
but the machine status on the left doesn't change at all. There is no active state, work oder Machine Position. Only thing that changes is the latest command. 
I tryed all $10 versions I can imagen but no changes. 
Does anybody now whats the problem?

Thanks alot.

**Comment by winder** [comment]
GRBLs communication protocol changed with GRBL 1.1, you'll need to use the UGS nightly build.
