### ISSUE TITLE
sometimes homing not supported

### ISSUE THREAD

**Issue by peezal** [winder/Universal-G-Code-Sender#683]
I have been going nuts. New at this and built bobs E3. Works great. Using universal G code 2.0 nightly build. It connects to the cnc and more often than not it says homing not supported. Strange as a few times it has homed and I could move router. Now im back to not supported. any help would be appreciated,

**Comment by vMeph** [comment]
do you have homing enable in grbl sets?

**Comment by peezal** [comment]
When I try to check in fermware settings it wont allow me and states grbl has not finished booting. even 30 minutes later it says the same thing.

**Comment by peezal** [comment]
baud rate is set at 115200. grbl wont finish downloading.

**Comment by winder** [comment]
@peezal if grbl doesn't connect after a couple seconds it probably isn't going to.
1. Check the baud rate is 115200, or 9600 for very old versions of grbl.
2. Make sure you are connecting to the correct port (and have any required drivers installed).
3. Make sure GRBL is properly flashed on your controller board.

**Comment by peezal** [comment]
am at 115200 and correct comport. 
currently trying to flash grbl. Having a few issues with that, looking at many videos however nothing goes as smooth as the video.

**Comment by peezal** [comment]
By the way, I appreciate your help.
many thanks

**Comment by winder** [comment]
Happy to help.

If the video's aren't complete you can try the grbl wiki page which has a lot of detail for all operating systems: https://github.com/gnea/grbl/wiki/Flashing-Grbl-to-an-Arduino

**Comment by winder** [comment]
Feel free to keep asking questions if you have more problems. I've started a troubleshooting page so in the future it will be easier to answer these sorts of questions.

http://winder.github.io/ugs_website/guide/troubleshooting/

**Comment by peezal** [comment]
I had to set it aside for a few days. Just can not get it to work. very frustrated. currently trying to see if grbl is loaded on board but getting board not responding.

**Comment by vMeph** [comment]
did you  upload correctly the grbl to the arduino?
to upload correctly from ide arduino you cant have old grbl folders in the libaries

**Comment by peezal** [comment]
reflashed grbl and it works. CNC will home.

**Comment by vMeph** [comment]
Cool
