### ISSUE TITLE
Control state ?

### ISSUE THREAD

**Issue by vMeph** [winder/Universal-G-Code-Sender#686]
@winder 
i was messing arround and was wondering if anything like this style could be added in to have more info in

think something like this was asked before to show Wpos Mpos  to dont cause confusion and then be diferent if is $10=1  or $10=2
i made this quicly just to have a idea, no idea how it would look better but to have that info in added would be great

![d](https://user-images.githubusercontent.com/12812111/28044608-4810b8de-65d0-11e7-8881-c8cf97711e5c.jpg)

**Comment by jahnj0584** [comment]
I say just mimic the mach3 style of displaying both, or making it a toggle
since machine posit is only needed when recording work or fixture locations
on a table
