### ISSUE TITLE
cyclestart, feedhold, abort/reset

### ISSUE THREAD

**Issue by carvfx** [winder/Universal-G-Code-Sender#688]
i'm running running the nightly build of ugs platform and grbl 1.1f and the hardware abort/reset button just stops the machine turns the spindle off and locks. previous versions of said software raised the z and sent the machine home when i hit the abort/reset button.  am i missing something?

sorry if this is not the right forum

**Comment by winder** [comment]
There is a "return to zero" button for that, or you can create a macro with the exact routine you want. The "stop" button just stops sending gcode and issues a soft reset to grbl.
