### ISSUE TITLE
Fusion 360 post to ugs

### ISSUE THREAD

**Issue by allcustomz** [winder/Universal-G-Code-Sender#693]
![20170721_183718](https://user-images.githubusercontent.com/28508085/28485133-51654436-6e45-11e7-9d60-c7c390bab366.jpg)

**Comment by allcustomz** [comment]
Ware did i go wrong im trying to post from fusion 360 to ugs i get the add in and then it pops up what to post and ware. But i get this error any ideas?

**Comment by vMeph** [comment]
Hmm you dont post directly to ugs you post on brackets save the code in a file.  .nc and then open from ugs the file

**Comment by allcustomz** [comment]
i have saved file but ugs won't read it because the code is different is there anything else I could do or something I need to turn on or install I installed grlb and grlb plus then installed a post prossesser from  a guy at fusion for ugs but i get this error. Did i paste fine wrong when you add add_ins? Or how do you do it? Before all this ugs wouldnt read file? Thanks for the reply im stuck

**Comment by vMeph** [comment]
did you select on post processor the grbl.cps has the post process output?
pic of your post process settings?

**Comment by allcustomz** [comment]
@vmeph thanks i think i didnt need it just turn of g24 i think and send file it was great thanks it was overkill putting new post prossesser when i didnt need it thank you again for your help im cutting now with no problems thanks your a lifesaver

**Comment by vMeph** [comment]
You welcome mate, you can close post
