### ISSUE TITLE
DEV/TTY/AMA0 UGCS Platform Raspberry Pi issue

### ISSUE THREAD

**Issue by CNCXPROUK** [winder/Universal-G-Code-Sender#699]
So, although it connects to the port and its visible it just never loads.

I don't think its the Pi, SPJSON works with the port, as does GRBLWEB on the pi using the same port.

The CNCC ProV2 works with a Mac/Windows using UGCS Platform so its not the Arduino flash. The baud rate is set to 115200, UGCS is set to GRBL. It just sits there with the port open and does nothing. See image :)

I am using the 28th July stable nightly build.

![ugcs platform](https://user-images.githubusercontent.com/30697816/28929288-83a1a1b6-7867-11e7-91b0-97f3a94ce9b5.png)

Thanks :)

**Comment by winder** [comment]
Thanks for the thorough issue report.

Is it possible you haven't configured your user with access to the serial ports? You can test by running as root.

Could one of the other tools still be connected to this port?

This one is a long shot, but you could try restarting your board after opening the serial connection.
