### ISSUE TITLE
USC v2.x Loading gcode file - error while starting file stream: null

### ISSUE THREAD

**Issue by lanamor001** [winder/Universal-G-Code-Sender#702]
MeshCam v6 (post processor grbl)
grbl 1.1f
Win10
JRE 8u144
UGS v2.x

When sending a gcode file in UGS v2.x I get the error "error while starting file stream: null". This error happens immediatly after clicking send. I can send this gcode file with the Inventables Easel program just fine. I can also send this gcode file with UGS v1.0.9. 

Here's my test gcode file:
[test.nc.txt](https://github.com/winder/Universal-G-Code-Sender/files/1203300/test.nc.txt)

**Comment by winder** [comment]
The problem is most likely from accidentally misconfiguring the gcode parser and can be fixed like this: http://winder.github.io/ugs_website/guide/troubleshooting/#gcode-program-stopped-working
