### ISSUE TITLE
im making a cnc machine using cd drive stepper motor.

### ISSUE THREAD

**Issue by Hariyeaon** [winder/Universal-G-Code-Sender#705]
this is the thing shown when i send a gode file in universal g code sender.
 im using A4988 module, cd drive stepper motor, 12 v power supply 1.5 amp, arduino uno, cnc sheild.
kindly help me

Skipping command #1
Skipping command #2
Skipping command #13
Skipping command #55
Skipping command #80
Skipping command #101
Skipping command #117
Skipping command #154
Skipping command #185
Skipping command #204
Skipping command #214
Skipping command #224
Skipping command #245
Skipping command #260
Skipping command #287
Skipping command #298
>>> G90
>>> G21
>>> G90
>>> G92X0.00Y0.00Z0.00
ok
ok
>>> 0S30
>>> G4P150
>>> 0S50
>>> G4P150
>>> M18
>>> M01
>>> M17
ok
ok
>>> G1X0.56Y24.27F3500.00
>>> 0S30.00
>>> G4P150
>>> G1X1.59Y24.54F3500.00
>>> G1X1.96Y22.50F3500.00
error: Expected command letter

**Comment by winder** [comment]
What is `0S30` supposed to do? Is that in your original gcode file?
