### ISSUE TITLE
toll does not move

### ISSUE THREAD

**Issue by salimOfTizi** [winder/Universal-G-Code-Sender#707]
Hi every one. First, excuse me for my bad English.
i  have a problem with the visualize window of UGS : the tool does not move when i send the G-code file

**Comment by winder** [comment]
What version of GRBL and UGS are you using?

**Comment by salimOfTizi** [comment]
I'm using GRBL 0.9j   and  UGS  1.09 .
Ihave  a lenovo thinkpad with window7 64 bits installed.

**Comment by winder** [comment]
When you say the tool does not move, do you mean in UGS, or on your machine?

If it is in UGS you might need to fix the the `$10` setting to `$10=3` ([see document here](https://github.com/grbl/grbl/wiki/Configuring-Grbl-v0.9#10---status-report-maskbinary)).

If your machine doesn't move you might have it wired wrong, you can check that here: https://github.com/grbl/grbl/wiki/Connecting-Grbl

**Comment by salimOfTizi** [comment]
It works !!!.Thank you very very very.......very much .You are a genius!!!!
