### ISSUE TITLE
Blacklisted commands is not intuitive for new users  (regular expression pattern remover)

### ISSUE THREAD

**Issue by rlwoodjr** [winder/Universal-G-Code-Sender#708]
70% of my emails to help users with software with issues are related to the blacklisted commands.  Can we disable this feature as a default? (regular expression pattern remover).  It would appear folks are just clicking yes, 

For example, sometimes g20 gets on the list, Then UGS displays the g-code in the default mm units. 

Another option is to take them to the "controller option" screen so the operator can know when a command is being blacklisted and where it is.

**Comment by winder** [comment]
Disabling the feature until I am able to finish #680 is probably a good idea

**Comment by winder** [comment]
@rlwoodjr Finally got around to disabling this, sorry for the delay.
