### ISSUE TITLE
Issues with high feed rates 

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#710]
Testing my motors before I mount them. It seems that if I put the feed over 12500mm/min or so the red DRO value freezes, the stop command does nothing, and my motor shaft locks in place. The alarm light does NOT go off on my driver. 

200 steps/mm
15000 Max feed 
250mm/s2 acceleration 

Does this have something to do with the driver's 20kHz Max pulse rate or the arduinos computational power?

**Comment by pelrun** [comment]
12500/60 * 200 = 41kHz, so yes.

**Comment by jahnj0584** [comment]
Weird then that 12400 will send. Does it have anything to do with the pulse
time of 10 or is that my limit?

I guess it's a first world problem lol.

**Comment by winder** [comment]
@jahnj0584 when you say the red DRO value freezes does that mean the number is red and doesn't change? I'm trying to understand if there's a GUI bug in addition to trying to running the driver too fast.

**Comment by jahnj0584** [comment]
yes exactly, the DRO freezes at its value and stays red. It stays as such
even if you wait for the motor to come back. It requires me to force quit
UGS and restart it.

**Comment by MattyJ4** [comment]
I am experiencing the same issue. 

My steps/mm on $102=39500 (due to non adjustable micro stepping on my driver) 

When I try to increase my max on $112 everything stops and needs a hard reset.

**Comment by inFamousMcGrath** [comment]
GRBL really can do 25-30kHz max in ideal conditions. You must use 32bit platforms, like Smoothieboard, or ported GRBL version on STM32 microcontroller.
