### ISSUE TITLE
Z-axis goes straigt up when sending the g-code

### ISSUE THREAD

**Issue by Nube123** [winder/Universal-G-Code-Sender#712]
Having a issue when sending the g-code.
All axis are zeroed out and the g code is made in 360 fusion. 
When clicking _send_ the z-axis goes straight up until hitting hard limit.

**Comment by jahnj0584** [comment]
Is Z zero'd? Disable G28 in your post settings

**Comment by Nube123** [comment]
Don't i lose my homing function then? yes Z is zeroed
It seems that the work position is jumping to another value and then it returns to zero

**Comment by jahnj0584** [comment]
No. It just disables the useless movement at start of the program.

**Comment by Nube123** [comment]
Thanks!

**Comment by winder** [comment]
@Nube123 did this fix your problem?
