### ISSUE TITLE
The parser stops when it encounters a G38.2 probe command in a script

### ISSUE THREAD

**Issue by groberts22** [winder/Universal-G-Code-Sender#714]
Attempting to execute an auto zero script using the 7/23 nightly build of Platform V2. The script processes as expected until it encounters a g38.2 command.  The parser then reports ok several times and stops. The command works fine when entered directly from the command line.

**Comment by BusbyGT** [comment]
I'm seeing the same exact behavior. It worked on the 6/14 build. manually issuing the command worked as well.

**Comment by winder** [comment]
This should be fixed now, thanks for the report.

**Comment by groberts22** [comment]
Thank you!
