### ISSUE TITLE
UGS Bug on writeByte(); Exception type - Port not opened.  periodically

### ISSUE THREAD

**Issue by Sunnysky** [winder/Universal-G-Code-Sender#719]
**Update : unable to duplicate problem after restarting UGS Nightly**

Aug 26 Nightly gives new error code from GRBL 1.1f that was not present in previous nightly versions.
Error in Bold always occurs after 3rd verbose message after Idle ...> (Ov...) every 10  messages or so using 1000ms  rate or if verbose is Off every 20 seconds or so.

[verbose] <Idle|WPos:0.000,0.000,0.000|FS:0,0|WCO:0.000,0.000,0.000>
[verbose] <Idle|WPos:0.000,0.000,0.000|FS:0,0|Ov:100,100,100>
[verbose] <Idle|WPos:0.000,0.000,0.000|FS:0,0>
[verbose] <Idle|WPos:0.000,0.000,0.000|FS:0,0>
[verbose] <Idle|WPos:0.000,0.000,0.000|FS:0,0>
**IOException while sending status command.: Port name - COM5; Method name - writeByte(); Exception type - Port not opened.**
>>> $I
[VER:1.1f.20170801:ERIC@UMD,TONY@SSE]
[OPT:V,15,128]
ok

Product Version: Universal Gcode Platform 201609300101
Java: 1.8.0_144; Java HotSpot(TM) Client VM 25.144-b01
Runtime: Java(TM) SE Runtime Environment 1.8.0_144-b01
System: Windows 8 version 6.2 running on x86; Cp1252; en_US (ugsplatform)
User directory: C:\Users\Tony Stewart\AppData\Roaming\.ugsplatform\2.0-SNAPSHOT\dev
Cache directory: C:\Users\Tony Stewart\AppData\Roaming\.ugsplatform\2.0-SNAPSHOT\dev\var\cache

**Comment by winder** [comment]
@Sunnysky the only way I can imagine this happening is if the USB connection flakes out and disconnects unexpectedly. My guess is that this is an intermittent hardware issue, there isn't really anything I can do in UGS to handle it in a more graceful way.

There have been reports of issues with some Arduino clones: [details here](https://github.com/grbl/grbl/wiki/Known-Bugs#usb-to-serial-transmission-errors). It might also happen if you have a lot of electrical noise (i.e. refrigerator, air compressors, or even a router with worn out brushes).
