### ISSUE TITLE
unknown error "wait for ok failed"

### ISSUE THREAD

**Issue by alihamza96** [winder/Universal-G-Code-Sender#720]
my machine is not runing with a programmee and it is showing thistype of error, can any one help me
![23](https://user-images.githubusercontent.com/31143834/29753882-e2a8d37a-8b93-11e7-8044-9ea5c3f03587.jpeg)

![23](https://user-images.githubusercontent.com/31143834/29753879-d312439c-8b93-11e7-8608-01e02726bb0f.jpeg)

**Comment by vMeph** [comment]
you asking suport for Grbl Controler program and this is program universal g code sender suport
what grbl version you using?

**Comment by winder** [comment]
@alihamza96 My understanding is that the Grbl Controller project has been abandoned by the primary developer. If you want to try asking that community for support, this is where you would post the question: https://github.com/zapmaker/GrblHoming/issues

There are lots of active controller programs you could use. I can recommend UGS (of course), or you could explore [some of the many alternatives](https://github.com/gnea/grbl/wiki/Using-Grbl).
