### ISSUE TITLE
v1.0.9 doesn't see ports while v1.0.8 does

### ISSUE THREAD

**Issue by zjor** [winder/Universal-G-Code-Sender#722]
Env: Mac OS 10.12.5
version 1.0.9 complains immediately after start "No serial ports found" while 1.0.8 start without an error and shows list of ports.
It is still possible to enter manually port name e.g. /dev/cu.w... in version 1.0.9 and it will work but an error dialog during each start is confusing.

**Comment by winder** [comment]
This is a bug in the serial library I started using in v1.0.9, additional comments here: https://github.com/winder/Universal-G-Code-Sender/issues/704#issuecomment-322241643

I may fix this eventually but its pretty low on my priorities.
