### ISSUE TITLE
v.1.0.9 Spindle should stop when pausing or cancelling file mode

### ISSUE THREAD

**Issue by zjor** [winder/Universal-G-Code-Sender#724]
Please add functionality to manually control (turn on/off) spindle and stop spindle when cancelled or paused in file mode

**Comment by pelrun** [comment]
You should be able to define macros to do this already.

**Comment by vMeph** [comment]
Set up macros 
"Start Spindle" M3 S1000
"Stop Spindle" M5 S0

**Comment by winder** [comment]
This isn't possible with GRBL 0.9 and UGS 1.0.9

GRBL 1.1 + UGS 2.0 has support for this. I'm not sure if the spindle stops automatically though but you can turn it on/off during a pause. Documentation here: https://github.com/gnea/grbl/wiki/Grbl-v1.1-Commands#extended-ascii-realtime-command-descriptions
