### ISSUE TITLE
Spindle Dwell?

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#729]
Any chance we can add a user configurable spindle dwell time for when M3 commands are initiated? Very few, if any VFDs are able to get to speed immediately. It seems like Mach, UCCNC, and linuxCNC all have this feature already too.

**Comment by winder** [comment]
It should be possible to throw in a `G4 PXXX` after detecting an `M3`. I think GRBL might already do this though based on this comment: https://github.com/gnea/grbl/issues/28#issuecomment-257126519

**Comment by jahnj0584** [comment]
Who do I ask to get that added?

**Comment by winder** [comment]
I decided to build this feature as part of a [tutorial for creating a new gcode processor](http://winder.github.io/ugs_website/dev/gcode_processor/#tutorial-creating-a-new-commandprocessor).


![](http://winder.github.io/ugs_website/img/tutorials/gcode_processor_plugin/2.settings.png)

**Comment by jahnj0584** [comment]
coding is over my head, how about you just add it to UGS from the get go? :P

I had a friend edit my post for me, to insert G04 P0.5 after an M3

**Comment by winder** [comment]
There's no coding involved, it's a new option on the gcode parser config
page
