### ISSUE TITLE
Usability improvements: Connect button

### ISSUE THREAD

**Issue by winder** [winder/Universal-G-Code-Sender#734]
The red coloring of the connect button gives mild impression that it is a disconnect button, even though context would suggest otherwise (issue: cpu cycles are way cheaper than brain cycles). I think worse than that though, it implies that a connection may not be possible. As this is likely the first action button a new user will seek I would personally align with standard conventions. Green for "make go!", red for "make stop!". Also, generally speaking separating buttons from status indicators minimizes possible confusion.

**Comment by jahnj0584** [comment]
Just brought this up in the other post. 👍
