### ISSUE TITLE
Failure with Testing firmware 

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#749]
![20170906_180815](https://user-images.githubusercontent.com/17396492/30134746-8d831052-932e-11e7-9834-91caff70c086.jpg)

**Comment by winder** [comment]
What were you doing when this happened?
In the lower right of the GUI status bar, is there a red error marker?
Are all the error messages the same message?

**Comment by jahnj0584** [comment]
I was trying to simply connect to get my grbl settings without an arduino
plugged in, so I assumed that was the firmware I had to "connect" with

**Comment by jahnj0584** [comment]
Yes it's all the same error message

**Comment by winder** [comment]
I'm not exactly sure why this happened, but I it happened to me just now. There's a rare race condition somehow is my guess. It's easy to check for though so I should have a fix shortly, let me know if you see this again.
