### ISSUE TITLE
Jog button display issue - RaspberryPi

### ISSUE THREAD

**Issue by BusbyGT** [winder/Universal-G-Code-Sender#750]
![z_plus_button](https://user-images.githubusercontent.com/26131866/30142960-61de1fb4-9351-11e7-971e-b106933034e5.png)

On the Raspberry Pi, resolution set to 1600x1200 (VNC). Size of the UGS window doesn't matter. Size of the Jog window doesn't matter.

UGS Classic is good. UGS Platform on Windows is good.

**Comment by winder** [comment]
@BusbyGT I made these buttons 10px wider, please let me know if that resolves the issue
