### ISSUE TITLE
File load error Pop-up Suppression

### ISSUE THREAD

**Issue by BusbyGT** [winder/Universal-G-Code-Sender#751]
When opening this file with UGS Platform on Raspberry Pi, there is no error pop-up, the UI just sits idle. However, if I click the Connect/Disconnect button after it, the error (seen below from Classic) will continually popup on every click.

[Kodiak-129644.txt](https://github.com/winder/Universal-G-Code-Sender/files/1283321/Kodiak-129644.txt)

When loading this file on UGS Classic, this error pops up:

![g91-error](https://user-images.githubusercontent.com/26131866/30143863-e0cc9fb8-9355-11e7-9543-1b005a5a7b69.png)

UGS Platform on Windows pops up an error when loading the file.

**Comment by BusbyGT** [comment]
@winder This is not fixed as of the September 17, 2017 build.

Loading a file that throws a parsing error, no window pops up BUT if you click on "Connect" or "Disconnect", it'll pop up the error window.

**Comment by winder** [comment]
@BusbyGT thanks for the update. There are going to be a lot of improvements to this very soon which should make the parser (and error messages) much more accurate.
