### ISSUE TITLE
baudrate duplicate

### ISSUE THREAD

**Issue by vMeph** [winder/Universal-G-Code-Sender#754]
![1](https://user-images.githubusercontent.com/12812111/30244442-c3f1c3de-95b5-11e7-84dc-ad05c84727ef.png)

**Comment by winder** [comment]
If you right click the toolbar and select `Reset Toolbars` does the duplicate go away?

**Comment by vMeph** [comment]
no it doesnt go away

**Comment by vMeph** [comment]
ok i have removed, you have to grab and drag out to remove, 
no idea why it appear 2 times, was after i updated the UGS that showed the 2 baud rates
now is fix

thanks

**Comment by winder** [comment]
I was working on #735
