### ISSUE TITLE
UGS breaks lines when sending.

### ISSUE THREAD

**Issue by FKjolner** [winder/Universal-G-Code-Sender#755]
A file with the only line
`G90 G53 G0 Z-3`
is sent like this
```
G90 
G53 
G0 Z-3
```
This makes the machine "skip" the G53 (machine space) , instead acting the G0 Z-3 in G54 (work space)

If this line breakage is intentional, it needs some tweaking, either in general or for my board (xpro v3 with grbl1.1)

Any ideas?

Regards Fredrik

**Comment by FKjolner** [comment]
I found this in the settings, but no info on how to make the option available to me.
![ugs-command splitter](https://user-images.githubusercontent.com/31817321/30518801-e307863c-9b87-11e7-9cd5-8a68eb1df883.jpg)

Any Ideas?

Regards Fredrik

**Comment by winder** [comment]
This problem exists for a number of non-modal commands. Currently, that command splitter just looks for `G` which isn't right. Unfortunately, the command splitter is needed for other reasons (thus not being able to disable it). I'll need to look into this.
```
   - Non-Modal Commands: G4, G10L2, G10L20, G28, G30, G28.1, G30.1, G53, G92, G92.1
```

**Comment by FKjolner** [comment]
Thanks, I've been able to disable the command splitter in the .ugs\firmware_config\grbl.json but not found time to test it. 

For what reasons are the  command splitter needed? it might not impact my code.

regards Fredrik

**Comment by cdsmith66** [comment]
I'm not sure if this is the proper place to leave this comment, so I apologize in advance. 

I was running an older version of UGS on a Raspberry Pi 3 and came across this issue, so I downloaded your nightly build yesterday(3/28) and loaded that on to the Pi. However I'm still experiencing this issue and the command splitter setting is still appearing. 

I have confirmed that a fresh install on a windows system does not have this setting/issue. I still have the older UGS files on the Pi, so is it possible that the new nightly build is referencing an old file? Thanks for the help.

Regards, Chris

**Comment by whitetd** [comment]
What are you using to create your gcode? Use a preprocessor to break apart
the commands, that way if you have an error it does not ignore everything
after it.  It can also delete bad commands, and convert macros to usable
code. Like drilling macros to individual drill operations.

**Comment by cdsmith66** [comment]
@whitetd I'm using HSM Express to generate the gcode and I don't think the gcode is the issue because the same file runs perfectly fine using the windows version of UGS.

**Comment by cdsmith66** [comment]
@winder, so, I realized that i was using the "somewhat stable" version from July 28th which was before this issue was solved, my bad. However, the reason I was using that version was because I couldn't get the newest nightly build to run, similar to issue #918.
