### ISSUE TITLE
Optional Nightly Build pop up message 

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#758]
Can you make this have an option such as "never show again" or something? I've opened UGS at least a dozen times today due to controller issues and leaving the work shop and it gets a bit annoying ;)

**Comment by vMeph** [comment]
Yes i would love this to have a option to show or not show pop ups at start.
Its very annoying to have the pop ups, i know they there to warn if this or that is experimental but is a nightly build so i already know that can have some bugs etc..
A option to show warnings or not would be ideal

**Comment by winder** [comment]
This actually exists, but I never put it in the UI.

On mac it is the file `~/Library/Preferences/ugs/UniversalGcodeSender.json`
on windows it should be `/home/user/.UniversalGcodeSender.json`
and on linux `~/.UniversalGcodeSender.json`

Change `"showNightlyWarning": true,` to `false`

**Comment by jahnj0584** [comment]
For people with issues, notepad++ is able to open this file.

**Comment by jahnj0584** [comment]
It's on line 35

**Comment by vMeph** [comment]
Im not able to find the directory
Wouldnt then need to have a ide to be able to make those changes?

Wouldnt be possible to set this option under options somewhere with a box to check or something, it would be more easy for all users that dont want to see pop ups at start

**Comment by vMeph** [comment]
Where is it on windows?

**Comment by jahnj0584** [comment]
It's in users/documents/.ugs. You may have to enable hidden files

**Comment by vMeph** [comment]
Ok found it

**Comment by vMeph** [comment]
I still get the help pop up
This is a experimental feature.please use with caution
Report any bugs you find on github

**Comment by jahnj0584** [comment]
I left the comma after false and saved the file. Maybe you forgot

**Comment by vMeph** [comment]
usualy comes 2 pop ups one about nightly build and other about experimental feature
the nightly one disapear but not the experimental feature

**Comment by jahnj0584** [comment]
I only ever had the nightly message...

On Sep 10, 2017 10:27 PM, "Meph1" <notifications@github.com> wrote:

usualy comes 2 pop ups one about nightly build and other about experimental
feature
the nightly one disapear but not the experimental feature

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/winder/Universal-G-Code-Sender/issues/758#issuecomment-328392600>,
or mute the thread

**Comment by winder** [comment]
Close the auto leveling window to get rid of the second one

**Comment by vMeph** [comment]
thanks
