### ISSUE TITLE
Current feedrate display

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#760]
Feed over ride is one thing, but it'd be nice to see what the last F command value sent was, to help when re-posting a file at the new speeds! Spindle speed should also be shown somewhere is it is enabled.

**Comment by winder** [comment]
This will be part of #739

**Comment by jahnj0584** [comment]
Could you also seperate the feed and spindle over rides? When a job is
running you usually need to change both/one of them very quickly to stop a
bit from breaking. Kinda like how the job controller is set up by axis.
Have a vertical row per over ride option
