### ISSUE TITLE
Dynamic windows?

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#761]
Is it within netbeans power to enable some dynamic windows or tools? For instance, when a file is sent, the jog controller is changed to the send progress window and the common actions toolbar could become the override window. 

Just a thought

**Comment by winder** [comment]
I was looking into this a little bit after your comment on the advanced probing plugin. There is a feature called "roles" that should be able to do this.

In the future, I want to have a "gcode editor" role as well. Different roles for disconnected/connected/streaming might make sense too.

**Comment by jahnj0584** [comment]
Just saw the new connection toolbar. I feel like that's good proof that what I'm asking for is possible if you so desire :)
