### ISSUE TITLE
Z probing values lost after error/stop

### ISSUE THREAD

**Issue by arnie74** [winder/Universal-G-Code-Sender#762]
using ugs platform 2.0 after Z probing and zeroing the tool to the bed, upon an error or stop/pause button press the probing values are reset and lost, so i have to re porbe everytime :-(

**Comment by winder** [comment]
I'll have to look into this, I've noticed the offset being reset when it wasn't supposed to but need to do some experiments to figure out exactly when and why.

Maybe I need use work coordinates instead of grbls tool offset feature (G43.1).

**Comment by arnie74** [comment]
Ive always used classic until now and never noticed it, only appears to be on GUI platform

**Comment by winder** [comment]
I'm changing this to use workspace coordinates instead of G43.1
