### ISSUE TITLE
"view gcode" window 

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#764]
Would be nice to have a tab beside the console to view the Gcode file that is loaded and allow for some changes manually or with a macro (change feed/spindle speed, rotate, scale, etc kinda like GCode ripper. First two are most valuable) and then auto saves it. You can't edit a file that's loaded already so you have to open a dummy file to release it, then reload just because you changed one line

**Comment by vMeph** [comment]
this could be very good specialy if add a visualisaion simulation

**Comment by jahnj0584** [comment]
Good idea. The line that is selected could glow a different colour in the
visualizer!

**Comment by winder** [comment]
It can already do that, but the code is really fragile so it usually doesn't work. The GCode editor is pretty low priority right now -- I'm trying to focus on 2.0 milestone tasks.

![](http://winder.github.io/ugs_website/img/platform/editor.png)

**Comment by jahnj0584** [comment]
Awesome!

**Comment by vMeph** [comment]
@winder what is 2.0 milestone?

**Comment by winder** [comment]
I tagged a bunch of tickets that I want to finish before having the first official 2.0 release. https://github.com/winder/Universal-G-Code-Sender/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0

**Comment by winder** [comment]
Going to close this for now, it isn't going to happen anytime soon.
