### ISSUE TITLE
Visualizer VS reality differences 

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#765]
An issue I have with some files is that lines are greyed out before the machine actually gets to them. Should/could the visualizer be edited to only consider lines at and behind the tool tip are "sent" ?

**Comment by winder** [comment]
Lines are sent to GRBL ahead of time, that's what the gray means. If the lines are long linear movements that could mean they are grayed out pretty far in advance. You're probably right, that distinction isn't really useful to most people.

Highlighting the line segment currently being executed might be interesting.

**Comment by jahnj0584** [comment]
Ideally itd be both. Orange line is where the tool is currently
on/following and grey is whatever it has already passed and cut.

Would that be too hard to do?

**Comment by winder** [comment]
It would be trickier than you'd think, I doubt I'll ever work on this.
