### ISSUE TITLE
Hard Alarm blocks UGS Jog

### ISSUE THREAD

**Issue by vMeph** [winder/Universal-G-Code-Sender#775]
every time there is a alarm hiting end stops,  you reset arduino and Jog buttons become grey
cant acess jog unless you close UGS platform and open again, its very annoying

**Comment by winder** [comment]
I'm pretty sure this is a GRBL feature to prevent GUIs from ignoring the error. The machine controller is completely disabled until you reset. You don't need to restart UGS, just close the connection and re-open it. You should also see the `MSG:Reset to continue` message which is [described here](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Interface#feedback-messages):
```
[MSG:Reset to continue] - Critical event message. Reset is required before Grbl accepts
 any other commands. This prevents ongoing command streaming and risking a motion
 before the alarm is acknowledged. Only hard or soft limit errors send this message
 immediately after the ALARM:x code.
```
