### ISSUE TITLE
Laser/Spindle display $32 also G54 .. G59 Selection/Display

### ISSUE THREAD

**Issue by RoadkillUK** [winder/Universal-G-Code-Sender#776]
I don't know if this is how it's done but I would like to suggest a couple of 'enhancements'.

Would it be possible to display if the machine is is Laser or Spindle mode (I keep forgetting)?

Also is it possible to add buttons (highlighted) for the G54 to G59 work positions?

Thanks, Lee. #

**Comment by winder** [comment]
I'm not sure I'm ready to open the Spindle/Laser can of worms yet, but better status reporting is definitely on the roadmap: #739

**Comment by RoadkillUK** [comment]
Thanks for listening :)
