### ISSUE TITLE
Can I help with a translation?

### ISSUE THREAD

**Issue by ScorpionBW** [winder/Universal-G-Code-Sender#780]
I would like to help translate the program into Portuguese Brazil.

**Comment by winder** [comment]
Yes, any translation work is appreciated. You can sign up for our translation project here:
https://poeditor.com/projects/view?id=52743

Let us know if you have any trouble.

**Comment by ScorpionBW** [comment]
Then help me with a project to grbl

**Comment by winder** [comment]
I'm not sure what you mean: http://winder.github.io/ugs_website/contrib/translation/

**Comment by ScorpionBW** [comment]
I've already translated everything that was missing from your program. I ask you to help me with another program or extension for yours.
