### ISSUE TITLE
Backlash compensation plugin / implementation

### ISSUE THREAD

**Issue by FakeName21** [winder/Universal-G-Code-Sender#789]
Hey, is there a way to compensate the backlash of my machine by analyzing the G-Code and the doing the following?
1) Read every row
2) Look for any axis movement
3) Check if that movement changed direction
4) Get the backlash to compensate from the users settings for each axis 
5) Add that too the coordinates given
6) Send G-Code

If not will this be implemented ?

I'm using GRBL and an Arduino.
Unfortunately I cannot compensate the rather huge backlash mechanically and neither is electronically an option since as far as I know the Arduino is already at its limit when running GRBL

**Comment by winder** [comment]
This could be implemented fairly easily using a gcode processor. I'm not
planning to work on it though.

http://winder.github.io/ugs_website/dev/gcode_processor/#tutorial-creating-a-new-commandprocessor
