### ISSUE TITLE
when i try to run Uinversal Gcode Sender V.1.0.7  this occurs " No core dump will be written. Minidumps are not enabled by default on client versions of Windows " what shall i do pls Help me 

### ISSUE THREAD

**Issue by sofoniyas** [winder/Universal-G-Code-Sender#792]

**Comment by winder** [comment]
Try a newer version of UGS, this one is very old and there have been many fixed and improvements since then.

**Comment by sofoniyas** [comment]
tanks winder a lot, when i use UGS  V1.0.9 and connect the pc to the arduino the UGS V1.0.9 immediately closes

**Comment by winder** [comment]
Does the nightly build do that as well?

**Comment by sofoniyas** [comment]
yes, after setting the com ports when i press <open> it immediately closes and saves the error in Notepad extension. i attached it bellow if it is helping, i cant understand it . pls winder help me

[hs_err_pid5856.log](https://github.com/winder/Universal-G-Code-Sender/files/1524586/hs_err_pid5856.log)

**Comment by winder** [comment]
I haven't tried running UGS with Java-9 at this point,maybe Java-8 will work.
