### ISSUE TITLE
Dowel Maker Plugin

### ISSUE THREAD

**Issue by winder** [winder/Universal-G-Code-Sender#794]
I saw someone making dowels with their CNC recently. This seems like a good candidate for a UGS "Dowel Maker" plugin.

![screen shot 2017-11-07 at 9 13 43 am](https://user-images.githubusercontent.com/125509/32497896-10778e14-c39c-11e7-8ecc-2b5f7556e5d9.png)

**Comment by jahnj0584** [comment]
Conversational Gcode creation incoming????

**Comment by winder** [comment]
@jahnj0584 maybe :)

<img width="1009" alt="dowels" src="https://user-images.githubusercontent.com/125509/32554822-09fc54a2-c469-11e7-8f94-aa9f782b247b.png">

**Comment by jahnj0584** [comment]
Wicked. I'd be happy with one for rectangles, facing, and I guess this
counts as a circle?

**Comment by winder** [comment]
@jahnj0584 all of those sound even simpler than this one. I think the floodgate is open now so I should be able to make few of these pretty quickly once I finish up this up.

**Comment by vMeph** [comment]
@winder 
a cool plug in would be something like this
https://inkscape.org/pt/~Neon22/%E2%98%85lasercut-tabbed-box
would it be possible to do it
this wpuld be great to do boxes etc..
