### ISSUE TITLE
How to install platform on Raspberry Pi?

### ISSUE THREAD

**Issue by goloplo** [winder/Universal-G-Code-Sender#800]
I know is not a real issue, but is there anyway to install UGS Platform on Raspberry Pi?

**Comment by BusbyGT** [comment]
Yes.

Make sure Java 8 is installed by doing a "sudo apt-get install oracle-java8-jdk"
Extract the UGS Platform files into a directory.
Go to the bin directory and execute the "ugsplatform" file ("chmod +x ugsplatform" if it won't execute)

I've run it a lot on my RPi3 with no major issues.

**Comment by goloplo** [comment]
Thank you.

Is there any way to see the visualiser on RPI platform?

**Comment by maly-miller** [comment]
I have the same issue. Visualizer is not working for me. I even installed jogamp and it is not working. Did you have any luck?
