### ISSUE TITLE
UGS Platform on Rpi B+

### ISSUE THREAD

**Issue by khturnings** [winder/Universal-G-Code-Sender#802]
First - Will this actually run in a Pi Version 1 B+ - 512meg one?
Second - I have install Raspbian Stretch and updated it.
In the terminal windows I see this this error - libEGL warning: DRI2: failed to authenticate but the tool opens, slowly :)
Thirdly - I loaded a simple GCode file and tried to visualise it. This error then appears - A com.jogamp.opengl.GLException exception has occurred.

Any help appreciated.

Can you add some information to the user guide regarding required specifications and setup.
I found on my laptop a Lenovo G570 has a Intel HD 3000 graphics card - OpenGL is not supported so it did not work on that platform, even though I found that Linux might support it (My head hurts).
Can a switch be added that allows for OpenGL or DirectX?

Thanks in advance.
PS - happy to test or help if I can

**Comment by winder** [comment]
Unfortunately, the visualizer does not work for the RPi. See issue #47 

It should be possible to get it working because JOGL supports RPi, but nobody has provided a PR to fix it and I've been focused on other things.

**Comment by khturnings** [comment]
Thanks for your very speedy help - keep up the good work
