### ISSUE TITLE
Dowel Maker bug?

### ISSUE THREAD

**Issue by vMeph** [winder/Universal-G-Code-Sender#804]
if you select other tabs the dowel maker shouldnt show in visualizer
its a litle annoying 

![1](https://user-images.githubusercontent.com/12812111/32912802-1ad7d8fa-cb08-11e7-8c89-e1cc43e9651a.png)

**Comment by vMeph** [comment]
What i mean is every time you restart ugs is there!!!

**Comment by winder** [comment]
For now that's the expected behavior. My thinking is that you would open those plugins when you want to use them, then close them.
