### ISSUE TITLE
workflow helper not working

### ISSUE THREAD

**Issue by timon2jkl** [winder/Universal-G-Code-Sender#806]
This line is the first line  11-16 and 11-18 nightly 

(  java.lang.IllegalStateException: Cannot find TopComponent with preferredID WorkflowWindowTopComponent  )

is part of the error

**Comment by winder** [comment]
@timon2jkl thanks, I think this must have been broken for a very long time. When I converted the project from ant to maven I forgot to move the property file to the correct location. It should be fixed now.
