### ISSUE TITLE
Status Panel not effected by FRO 

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#807]
The feed rate is static to whatever the last F command was. It doesn't change if you add any override.

**Comment by jahnj0584** [comment]
Is this intentional since the DRO DOES change based on the CURRENT feedrate of the machine?

**Comment by winder** [comment]
Yes, this was intentional. The state window is basically trying to show the current output of `$G`, so for Feed it would be the target feed rate instead of the actual current.
