### ISSUE TITLE
First Launch Set up window

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#809]
Upon your first run the program asks what COM port + firmware, the baud rate to use, where gcode files are located, etc

**Comment by jahnj0584** [comment]
oh and seperate Z jog size as well.

**Comment by winder** [comment]
I'm not planning to do something like this. UGS does have some "global" preferences, but more and more the preferences are owned by individual plugins which would make this difficult to implement.
