### ISSUE TITLE
Recurring Error

### ISSUE THREAD

**Issue by rawkstar320** [winder/Universal-G-Code-Sender#81]
![capture](https://f.cloud.github.com/assets/2720753/785502/e07d0b14-ea81-11e2-8f70-4c96263c5366.PNG)
I am running V1.06 and am running into a very annoying error.  It reads: 

Error while starting file stream: Cannot stream while there are active commands (controller)

If i soft restart GRBL, the error does not go away.  The only way I have found to get the error to clear out is to close the UGS app and re open it.  Requireing me to re home my machine.  I should mention that this error comes up EVERY time that I try to run a program after finishing one program. (So I can only run "1" job before resetting everything)

Any thoughts?  Thanks all!

**Comment by sanotronics** [comment]
Hi! i know it is not the topic of the issue, but I can't soft reset GRBL from UGS...

I just started using it, and looked it up, and found CTRL+X is the command to soft reset, but when I try nothing happens... Tried als ^X with same result.

How do I soft reset from UGS?

**Comment by SkyJetty** [comment]
I'm getting this same error on one mac, but not another.  The only difference I can tell is the one I'm getting the error on is a 2007 MacBook Pro and the one that works is a 2013 MacBook Pro.  Both are running the same stable version 1.0.9 with Java v8 91.   The only other thing different is the OS version. The Older Mac was just clean installed with El Capitan 10.11.5 and my 2013 is running version 10.11.4 still.
