### ISSUE TITLE
Keyboard shortcut for Over rides disabled when file is sent

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#811]
No issue using CTRL+Home/End to do +/-10% of my FRO. If a file is sending though, only mouse clicks will work.

**Comment by winder** [comment]
Are the buttons in the menu disabled as well? This might be a more general problem where sometimes certain panels swallow shortcut events so they never get to the shortcut processor.

**Comment by jahnj0584** [comment]
no, they are fully functional as they should be. Only the KB shortcuts get "muted"
