### ISSUE TITLE
stepper motors won't react

### ISSUE THREAD

**Issue by Aeons001** [winder/Universal-G-Code-Sender#815]
hi,
so I'm building a CNC machine and I am using g code and when want to move motors by pressing the y or x or z nothing happens. 
please help.

**Comment by vMeph** [comment]
Did you set up GRBL settings

**Comment by Aeons001** [comment]
yes
well what do you mean

**Comment by vMeph** [comment]
I mean grbl $$ step motors configs etc...

**Comment by Aeons001** [comment]
yes thats set up

**Comment by Aeons001** [comment]
i got fix but know the motor moves and then again

**Comment by vMeph** [comment]
Did they ever moved?
If you set xy step size and feedrate on UGS on jog and move anything?

**Comment by Aeons001** [comment]
oh and how do i make the steps smooth?

**Comment by Aeons001** [comment]
they move no but the stepps are in bits
so they are smooth

**Comment by vMeph** [comment]
Im trying to understand what is your problem
If you using jog  and you set xy step size 1 will move step by step, yoi need to keep pressing to move or increase step size or in command line you do for exemple X100 and should move 100mm

**Comment by Aeons001** [comment]
so I got 2 motors working but one won't budge

**Comment by Aeons001** [comment]
ok so the sheild is a Popprint cnc sheild and drivers are drv8825

**Comment by Aeons001** [comment]
so know non of them work

**Comment by Aeons001** [comment]
but the one that does work is really hot

**Comment by vMeph** [comment]
Did you adjust the pot vrf of drivers correctly?

**Comment by Aeons001** [comment]
so I just adjusted the z and y-axis and they both work but the z-axis is just making a humming sound when manually tell it to move

**Comment by Aeons001** [comment]
I mean the x-axis doesn't work

**Comment by vMeph** [comment]
I did you try change the driver that dont works with one that works to see if is a driver problem?

**Comment by Aeons001** [comment]
so i just change them and restarted the ugs and now it isnt connecting

**Comment by Aeons001** [comment]
ok its connected

**Comment by Aeons001** [comment]
ok its deffently the driver

**Comment by vMeph** [comment]
The driver could be ok or bad,

You need to adjust the vrf pot with the correct voltage depending on your motor Amps, or if not correctly adjust it could not work

You can find many information and videos in how to it online

**Comment by Aeons001** [comment]
whatt would i search 
something on the line of ;
how to fix bad or broken stepper driver? or
how to adjust vrf pot to correct voltage

**Comment by vMeph** [comment]
How to adjust drv8825 drivers

**Comment by winder** [comment]
@vMeph thanks for helping with support!

**Comment by vMeph** [comment]
No problem!!!
