### ISSUE TITLE
UGS platform version will not start up

### ISSUE THREAD

**Issue by pixartist** [winder/Universal-G-Code-Sender#818]
After using it for a while UGS will not start on my lapton any more. The splash screen comes up and it loads to about 3/4 and then promptly vanishes. I redownloaded it and deleted the old version, nothing changed. Is there a config file somewhere that might be responsible ?

**Comment by vMeph** [comment]
You might need to delete the ugs hidden files on %appdata% hiden folder also

**Comment by winder** [comment]
Some people have run into OpenGL issues during startup recently, you'll need to run UGS from the command line to get the error message printed in the console, do you know how to do that? What is your OS?
