### ISSUE TITLE
UGS Google Group Announcement

### ISSUE THREAD

**Issue by winder** [winder/Universal-G-Code-Sender#825]
This is a general announcement. In an effort to recognize that UGS is a community of enthusiasts and to encourage more collaboration and discussion, there is now a [UGS google group](https://groups.google.com/forum/#!forum/universal-gcode-sender) where we can have discussions in a more casual environment.

There has been a trend recently with the UGS community being more and more engaged with GitHub Issues and more people eager to lend a hand when assistance is needed. Occasionally people even apologize for creating an off-topic question but do so anyway because they know that we have an amazing and friendly community that will help. This has been extremely encouraging as a signal that the UGS project is doing something right.

Despite our community I still receive a lot of support emails, many people are reluctant to create an "Issue" just to ask a question. But until now there was no other way to access our community. So in an effort to encourage this sort of collaboration I've created a google group. Moving forward I will be updating the README and website to direct people to the google group for support and discussions and leaving GitHub Issues to track bugs and suggestions.

Personally, I would like to thank everyone who contributes to UGS every day. Without your support and encouragement, UGS would not be where it is today.

**Comment by breiler** [comment]
Closing as there is information about the discussion group on the github start page.
