### ISSUE TITLE
Not fully localized error on start

### ISSUE THREAD

**Issue by aidaskni** [winder/Universal-G-Code-Sender#835]
I got error on program startup if non English lang selected.
[](url)
![untitled](https://user-images.githubusercontent.com/8092357/33527438-d7e95ca8-d859-11e7-86e6-3dd2db59707f.png)

**Comment by winder** [comment]
The terms on POEditor hadn't been updated in a few weeks and some were missing. If you take a look now you should be able to add the missing terms. This notification is intended to let people know that their language has fallen out of date. If you'd like to skip the pull request step you can create a ticket like this one and ask me to update the files.
