### ISSUE TITLE
checkboxes for checking the home switch conditions for X Y, and Z are missing

### ISSUE THREAD

**Issue by rlwoodjr** [winder/Universal-G-Code-Sender#837]
In the latest, version the checkboxes for checking the home switch conditions for X Y, and Z are missing. This is a valuable tool for troubleshooting.  Was it eliminated or moved to another page? 

I would really like to have this functionality to help troubleshoot customer machines.

Thanks,
Bob

**Comment by winder** [comment]
Hey Bob, I had removed them. That panel was getting too tall and I wasn't sure how to resolve it. I've re-enabled them for now, soon we'll (hopefully) have a new design. There is some discussion going on here: https://groups.google.com/forum/#!topic/universal-gcode-sender/ajd8I_7LPpY

I think the ALARM area in the new design would also display any enabled pin states.

**Comment by rlwoodjr** [comment]
Thank you very much.
Bob
