### ISSUE TITLE
How to reset visualiser window?

### ISSUE THREAD

**Issue by rjclocks** [winder/Universal-G-Code-Sender#844]
I am using UGS on a MacBook with the built in trackpad instead of a mouse and can't seem to find a way to un-zoom or simply reset the visualiser window when I have zoomed in.

I hope that I have just missed something silly...

**Comment by winder** [comment]
Pinch gestures sort of work but it can be very wonky at times.

It's not just you, UGS still needs this basic functionality but I haven't gotten to it yet. There are a bunch of usability improvements outlined in #737
