### ISSUE TITLE
UGSplatform #901 crashed during long carve

### ISSUE THREAD

**Issue by kenfritz** [winder/Universal-G-Code-Sender#855]
Build: USGplatform #901 (Installed 12/13/17)
PC: Win10, Java 8.0.1510.12

Problem: UGS crashed during 130,000 line gcode carve. It had completed 80% before crashing out of UGS. Crash log file included.

I had not had this happen before with previous versions of UGS.

[hs_err_pid9768.log](https://github.com/winder/Universal-G-Code-Sender/files/1560244/hs_err_pid9768.log)

**Comment by BarrettLowe** [comment]
Haven't used UGS before this but I had the same thing. I'm on Linux but I may revert to something in the past and see how it goes.
