### ISSUE TITLE
UGS screen starts to show up but then disappears.

### ISSUE THREAD

**Issue by rlwoodjr** [winder/Universal-G-Code-Sender#870]
I have a customer that clicks the UGS screen and it shows the splash screen then disappears. He is running Windows 10

We have tried:
Clearing the cache
Deleting the UGS Platform folder and reinstalling it
Re-installed the latest Java

It was working for a while, then it just stopped.

Any ideas?

**Comment by winder** [comment]
discussion here: https://groups.google.com/forum/#!topic/universal-gcode-sender/vEtnHSg8yUY
