### ISSUE TITLE
Request that the default baud rate is 115200

### ISSUE THREAD

**Issue by rlwoodjr** [winder/Universal-G-Code-Sender#871]
Would it be possible to make the default baud rate 115200?

**Comment by winder** [comment]
It already should be the default, I'm not sure how long ago that change was made.

**Comment by vMeph** [comment]
@winder just installed the UGS platform on my other labtop and default baudrate is 9600

**Comment by rlwoodjr** [comment]
Thanks!
Bob

**Comment by winder** [comment]
@vMeph is that the first time you installed any version of UGS on that
computer?

**Comment by vMeph** [comment]
@winder yes
Just bought new labtop

**Comment by jahnj0584** [comment]
wasnt this just fixed?

**Comment by breiler** [comment]
I could reproduce the issue when clearing all settings and starting UGS.

**Comment by winder** [comment]
Fixed with #900, thank you @breiler
