### ISSUE TITLE
Dimension Changes from Vcarve pro to UGS 

### ISSUE THREAD

**Issue by heerenz** [winder/Universal-G-Code-Sender#872]
i created a work space of 10"x10"x.5". when i uploaded my file toolpaths into UGS the project size has changed throwing my project off and not allowing it to run. I am running BobsCNC

**Comment by winder** [comment]
In what way do you think UGS changed your project size? It shouldn't change that sort of thing, there isn't even an advanced feature to do anything like that yet.
