### ISSUE TITLE
installing on Pi. double clicking jar file opens archiver? 

### ISSUE THREAD

**Issue by RussMaGuss** [winder/Universal-G-Code-Sender#874]
Not sure what I'm doing wrong. I double click the jar file and it just opens the archiver. Not sure what the next step is. This is the first time using a Raspberry Pi. I installed UGCS on my windows computer a while ago but am brand new to raspberry pi. Do I open it in the terminal somehow? what commands am I supposed to send? Thank you in advance! 

-Russ

**Comment by winder** [comment]
Different Linux distributions are all different when it comes to what happens when you double-click something.

From the command line you can always run a jar file with `java -jar <jar file>`, this should work fine with UGS on a RPi

**Comment by RussMaGuss** [comment]
I tried doing that and it says "unable to acces jarfile UniversalGcodeSender.jar" 
Thank you for the speedy response, I appreciate the help!
