### ISSUE TITLE
Machine status panel remains at zero

### ISSUE THREAD

**Issue by oliveat** [winder/Universal-G-Code-Sender#879]
Well after a lot of reading and fiddling I have version 1.1 installed on my apple and version1.09 Gcode sender as well. The resets all work and no longer give error messages but machine status panel does not change ie it remains at zero. What to do?, regards, Richard

**Comment by oliveat** [comment]
Just downloaded the Platform version and it runs well, please ignore above issue

**Comment by winder** [comment]
The reason is that GRBLs status protocol changed in v1.1, so you need to use one of the 2.0 builds for it to work properly.
