### ISSUE TITLE
UGS integration with HA?

### ISSUE THREAD

**Issue by vMeph** [winder/Universal-G-Code-Sender#880]
@winder is there any way that it could integrate UGS with Homeassistant, and expand project?

**Comment by flounderscore** [comment]
What are you wanting it to do? Send machine status to HA?

**Comment by vMeph** [comment]
Ya have status etc.. emergency stops etc..

**Comment by winder** [comment]
This could be done with a plugin pretty easily if someone wants to give it a shot.
