### ISSUE TITLE
Command line options, are there any?

### ISSUE THREAD

**Issue by hedefalk** [winder/Universal-G-Code-Sender#882]
I'm looking to open up UGS at the end of a toolchain script, is there a way to just pass a gcode file to  open it up straight away?

I see that args are passed to the netbeans executable from the script, but I can't find any more info…

**Comment by winder** [comment]
Yes, there is. For both the platform and classic version you can pass `--open <filename>`

**Comment by winder** [comment]
That feature was added for this plugin: https://github.com/tapnair/UGS_Fusion

**Comment by hedefalk** [comment]
@winder Thx!
