### ISSUE TITLE
Could not find Java 1.8 or higher.

### ISSUE THREAD

**Issue by MajorTwip** [winder/Universal-G-Code-Sender#885]
Enviroment:

Win 10 Pro fresh install. Installed JDK 9.
Path to JDK. java -version works.

Error: Could not find Java 1.8 or higher.

After installing JRE 8 parallel it worked.

**Comment by winder** [comment]
Strange, seems that the JDK 9 installer didn't setup (or no longer uses) the java home property.

A workaround is to update your `ugsplatform.conf` file (in the `etc` directory) to point to your JDK 9 installation:
https://stackoverflow.com/questions/29052219/cannot-find-java-please-use-the-jdkhome-switch
