### ISSUE TITLE
Accuracy of classic UGS interface  is not good.

### ISSUE THREAD

**Issue by mubarak111nsu** [winder/Universal-G-Code-Sender#886]
I tested my CNC using The classic UGS interface. But It does not gives accurate output.

**Comment by rmisko11** [comment]
Is it possible it is a case of 'garbage in, garbage out'?

**Comment by whitetd** [comment]
no explanation of what inaccuracies your having!

**Comment by mubarak111nsu** [comment]
I just tried to make a triangle by layer by layer. In each layer, the length and width increase with a small amount.

**Comment by whitetd** [comment]
post you files

**Comment by winder** [comment]
Sounds like you need to configure grbl, specifically the steps/mm settings:
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#100-101-and-102--xyz-stepsmm

**Comment by mubarak111nsu** [comment]
Yes sir. I did set steps/mm accurately. If I use v1.09, then I get very accurate output but not so fast. When I use latest version, then I get fast output but not accurate.
![untitled](https://user-images.githubusercontent.com/21698962/36007137-0079c150-0d0f-11e8-81b8-564d234fd49d.png)

G-code file not supporting here, If you send me email then I could send you the G-code file.
