### ISSUE TITLE
Display file name in visualizer 

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#890]
just a the title in basic text. Bottom edge probably?

**Comment by breiler** [comment]
It could be a bit messy adding this kind of information to the visualizer window. The text would disappear among everything else if the user was to zoom in on a model: ![screenshot 2018-02-11 08 34 14](https://user-images.githubusercontent.com/8962024/36070941-65003f66-0f06-11e8-9264-e92d0dff361b.png)

There is a planned task for adding the file name in both the main window title and status bar (#736), can we wait until it's implemented, maybe it will be good enough?

**Comment by jahnj0584** [comment]
But the text would be a static location and size?

**Comment by breiler** [comment]
Yeah sure. My point was that I don't think it creates any value if the text isn't readable. 
Anyhow, it shouldn't be too hard to add and could be optional as everything else in the visualizer.

**Comment by winder** [comment]
This is fixed with #896, I think having it in the title and status line should be good. What do you think @jahnj0584?

**Comment by jahnj0584** [comment]
@winder its nice, but it should NOT replace the standard file toolbar that we had last week.

**Comment by breiler** [comment]
The issue #736 specified the removal of the filename text field. To leave just the label and browse button didn't seem as clean as to having just an icon:

![screenshot 2018-02-19 06 32 44](https://user-images.githubusercontent.com/8962024/36363675-1c6868b6-153f-11e8-91d1-453c6e3dccb8.png)

So what do you mean? I don't understand what would the old file toolbar provide that couldn't be replaced with an open icon?

**Comment by jahnj0584** [comment]
Maybe it's just my inertia of the design but my eyes keep expecting to see
that white bar to load or see what's open. I'm a fan of larger icons, the
easier it is to click the better. I'll eventually get a touch screen and
these new small icons would cause some grief.
