### ISSUE TITLE
UGS pause halfway through job

### ISSUE THREAD

**Issue by jdvdh** [winder/Universal-G-Code-Sender#894]
Hi. I am new to CNC. Build 3 axis router with attached laser. UGS will pause at random, and resume when I press the external resume button. Any idea what the problem can be?

**Comment by winder** [comment]
If there is an error with the gcode UGS will pause the program. What output do you see in the console when this happens?

**Comment by jdvdh** [comment]
If I run the same gcode again it will stop somewhere else. The console goes yellow and if I can remember correctly it says hold, similar as if pressed the feed/hold button.

**Comment by winder** [comment]
If it is happening in random locations this could be an electronics issue,
have you tried disconnecting the external buttons?

**Comment by jdvdh** [comment]
It is on the todo-list for tonight along with ground wires to the stepper-motor brackets and a new usb cable.

**Comment by jdvdh** [comment]
Ok so I disconnected the external buttons and it ran without any problems. So how can I fix the problem with the buttons?

**Comment by winder** [comment]
@jdvdh I think there are some circuit diagrams for reducing noise on the grbl wiki.

**Comment by jdvdh** [comment]
Thanks

**Comment by jdvdh** [comment]
will the wiring be the same as for the noise reduction in limit switches?
https://github.com/gnea/grbl/wiki/Wiring-Limit-Switches

**Comment by jdvdh** [comment]
Good day.

 

I am running win 10 UGplatform v2.0. I cannot get pendant (10.0.0.108:8080) to connect. Could it be that the port is blocked? 

 

Regards

 

J.D. van den Heever



 

Cell: 082 873 2784
