### ISSUE TITLE
Pendant issues:

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#904]
Just trying it out
this is all low priority to the rest of the program 
Feed rate is always set to 1, which sucks in metric.....Should just use rapids.
Step size should be a checkbox instead of a dropdown
Landscape orientation
Shortcuts should actually just show macros

**Comment by sjauquet** [comment]
hello,
seems the issue is still there with the latest nightbuild (01/december/2108)
This makes the pendant unusable in metrics :-/
Thanks !

**Comment by breiler** [comment]
Please give the latest build a try, this should now be resolved.
