### ISSUE TITLE
Empty windows when starting UGS with Sway/Awesome/i3wm

### ISSUE THREAD

**Issue by carneeki** [winder/Universal-G-Code-Sender#905]
When using the Sway / Awesome / i3 window managers on Linux, an empty or broken window may appear.

I noticed this when moving away from GNOME 3 to Sway. This can be fixed by placing the following line at the start of run_platform.sh:

`export _JAVA_AWT_WM_NONREPARENTING=1`

This find might benefit others, and could prove a timesaver if it were documented somewhere here. The popup to say I was running a nightly build was much smaller than it should have been, but the standard window resize shortcut `$mod+R` ("Windows Key + R" in Sway, might be "Alt + R" in i3) allows it, and other popups inside UGS to be resized.

Thanks!

**Comment by winder** [comment]
Thanks, there seems to be a lot of activity around tiling window managers. Just spent most of the morning reading about them, and the new Wayland compositor.

Do you know what other side effects this environment variable might have for traditional window managers? I haven't updated the shell script for everybody, but used your suggestion and added a [section about it in the troubleshooting documentation](http://winder.github.io/ugs_website/guide/troubleshooting/#linux-non-reparenting-window-managers).
