### ISSUE TITLE
visualizer does not refresh when selecting new files in workflow helper

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#906]
actually, it causes the whole thing to be laggy!

**Comment by breiler** [comment]
Does the same problem occur if you are not using the workflow helper? Is this a new problem?
How many _frames per second_ does it say in the visualizer window?

**Comment by jahnj0584** [comment]
No it always refreshes the visualizer if you open a file with the command
itself.

**Comment by breiler** [comment]
I can't reproduce your issue:
![workflow helper](https://user-images.githubusercontent.com/8962024/37653097-f394e336-2c3d-11e8-989a-9a4b87ab7c69.gif)

How many frames per second does it say it's rendering in in the Visualizer window?
Is there something with the files you're loading (are they big, contain many arcs etc.)

**Comment by breiler** [comment]
Closing as extra information wasn't provided
