### ISSUE TITLE
Work and machine positions

### ISSUE THREAD

**Issue by jryanfam** [winder/Universal-G-Code-Sender#920]
I am using the X Carve. No matter where I jog the machine. The work and machine positions remain at zero

**Comment by winder** [comment]
This usually means the status report setting is incorrect, please check out the GRBL documentation. If that doesn't work re-open the ticket with more information about your software and operating system versions.

[GRBL v1.1 documentation](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#10---status-report-mask)
[GRBL v0.9 documentation](https://github.com/grbl/grbl/wiki/Configuring-Grbl-v0.9#10---status-report-maskbinary)
