### ISSUE TITLE
Visualizer Jog-to units always in mm

### ISSUE THREAD

**Issue by DougF42** [winder/Universal-G-Code-Sender#921]
When I right-click in the visualizer window, the 'jog to' units are always in mm, even though I've set the interface to 'inches'.  I am using the 'nightly build' on the website as of 25 Feb 2018.

**Comment by Lizichka** [comment]
What version are you using? Where do you switch interface to "inches"?

**Comment by breiler** [comment]
There are three different unit settings at play:
  * Firmware settings for reporting units ($13)
  * Units Mode (G20, G21)
  * Jog units (internal UGS setting)

Maybe we have one setting too many? How about:
  * Use the firmware settings for units in the visualizer
  * Removing the internal jog units setting and use the firmware setting instead
  * Change the jog-menu to use the firmware setting

**Comment by breiler** [comment]
I'm currently looking into this but need to double check the generated command for this.
I was thinking of using this format to move to a absolute position: `G21G90G1X1Y2Z3F1000`
* G20 or G21 will be used depending which preferred units are being used
* G90 for absolute coordinates
* XYZ
* Feed rate in the selected units

Does this look correct?
