### ISSUE TITLE
No Serial Ports Found

### ISSUE THREAD

**Issue by vleroylr** [winder/Universal-G-Code-Sender#922]
Hi, I am using the Universal G Code Sender, my pc detects the USB port and also de COM port (when I use that connector instead of the USB), it detects it (when I use the serial cable) in the COM10 port, but even if I put that in the port text box it won't recognize it... any help please?, I'm using it on Win10

**Comment by breiler** [comment]
What hardware are you using?
What version of GRBL are you using?

**Comment by winder** [comment]
@vleroylr it sounds like you might not have your controllers serial driver installed, please check with the manufacturer to find the correct driver.

For instance if you're using an arduino try this: https://www.arduino.cc/en/Guide/Windows

**Comment by mgorman0178** [comment]
Hi my machine stopped halfway thought what i was doing! I checked my software and an error message come up saying COM3 port was busy!? I turned it of and on but still same message! What do i do? Oh and the visualize don't work aswell???
