### ISSUE TITLE
tiny text

### ISSUE THREAD

**Issue by elevalther** [winder/Universal-G-Code-Sender#923]
I don¨t know why the text are so tiiny, I cant hardly read it
![tiny text](https://user-images.githubusercontent.com/32070564/36762107-5c2f330a-1c22-11e8-9940-1a8012efbe6f.PNG)
do you have any solution

**Comment by breiler** [comment]
Are you running HiDPI?

In that case you could try to edit the start-windows.bat with the line:
`java -Dsun.java2d.uiScale=2 -jar -Xmx256m UniversalGcodeSender.jar` 

If this doesn't work, check this issue: #623

**Comment by elevalther** [comment]
Thanks Joacim

I¨m not the biggest pc - specialist - I didn¨t know What was a HiDPi, now I
have looked it up, but there wasn¨t mentioned the range of the monitor, and
my monitor is (low range) 800x600, and (high range_
recommended) 3840 x2160

To change the setting, where/how do I have to do. ( java
-Dsun.java2d.uiScale=2 -jar -Xmx256m UniversalGcodeSender.jar )

Br

Valther

2018-03-01 15:43 GMT+01:00 Joacim Breiler <notifications@github.com>:

**Comment by breiler** [comment]
No worries!

I assume you've downloaded the UniversalGcodeSender-v1.0.9.zip and unzipped it somewhere. In it you have a file called **start-windows.bat**.

Open it in a text editor (notepad) and replace the existing line with:  **java -Dsun.java2d.uiScale=2 -jar -Xmx256m UniversalGcodeSender.jar**

**Comment by elevalther** [comment]
thanks again
As I told you i¨m  not the sharpest knife in the drawer when we are talking
about computer.
have a look at the screemshot - that what I fin when i open the unzipped
1.0.9 universal gcode sender

br
Valther

2018-03-02 11:07 GMT+01:00 Joacim Breiler <notifications@github.com>:

**Comment by elevalther** [comment]
sorry I found it

but when I i try to open the CMD window appears and disappers right away
br

Valther

2018-03-02 11:38 GMT+01:00 Valther Kjaer <elevalther@gmail.com>:

**Comment by elevalther** [comment]
when I open with the EDIT command, a Note pad files open, and I can change
the old text with the text you¨ve given me, and I save it, but the result
is still the same

br

Valther

2018-03-02 11:47 GMT+01:00 Valther Kjaer <elevalther@gmail.com>:

**Comment by elevalther** [comment]
Ones more; i don¨t if i¨m moving the right places
br

Valther

2018-03-02 12:01 GMT+01:00 Valther Kjaer <elevalther@gmail.com>:

**Comment by breiler** [comment]
That should have done it, but your Java-executable is probable not on the path and will not work.
Another option is checking out #623

**Comment by elevalther** [comment]
I have tried that way too, but I had no luck even I had to install Foxit
reader, as the way explained in the github isn¨t possible anymore as,
compatibility doesn¨t excist in the property window.

br

Valther

2018-03-02 13:17 GMT+01:00 Joacim Breiler <notifications@github.com>:

**Comment by breiler** [comment]
This should no longer be a problem with later versions of Java which will detect this automatically. In other case reopen this issue.

**Comment by elevalther** [comment]
thank Joacim


Den lør. 29. feb. 2020 kl. 08.42 skrev Joacim Breiler <
notifications@github.com>:

**Comment by kthornbloom** [comment]
Tiny UI elements in version 2.0... reopen?

![Capture](https://user-images.githubusercontent.com/3322795/76682423-9674dc80-65d2-11ea-8f36-2c978d33161d.PNG)

**Comment by breiler** [comment]
@kthornbloom I much rather start a new issue as this is a bit different. 

The newest version of NetBeans platform (which UGS platform is based on) is much better at handling scaling of icons and we should probably upgrade.

The version of UGS you are running now is a bit old though, could you give the latest version a try first?
