### ISSUE TITLE
Shortcuts 

### ISSUE THREAD

**Issue by kardinal7** [winder/Universal-G-Code-Sender#925]
I've been using this platform now for my work, and I miss one feature from the older UGS (0.9). Whenever I press the arrows I can control the machine. Even if change the point where the cursor is. Now I find it hard to know where is it possible to move all axis.
Also sometimes I can move the X & Y and not the Z. Other times only the Z.
The only way I've managed to do this, is to press the help button, cancel the pop-up window and then I can move all the axis.

**Comment by winder** [comment]
This is a known issue with all shortcuts in the platform version, I haven't found a solution yet. #779 is one idea so far but hasn't been built yet.
