### ISSUE TITLE
Homing : don't reset to 0

### ISSUE THREAD

**Issue by vichbcc** [winder/Universal-G-Code-Sender#926]
Hello !
For some reasons, when I'm homing my CNC with touch sensors, the X axis is not reseting to 0, but -45mm. The others axis are doing it well.
Quit and re open solved the trouble.

**Comment by jahnj0584** [comment]
Check soft limits and pull off distance

**Comment by breiler** [comment]
@vichbcc did it just happen once and you aren't able to reproduce the problem?

What versions are you running of:
 * Universal Gcode Sender
 * GRBL 

Could you please post the output of the command `$$`

**Comment by breiler** [comment]
Missing response from user, closing issue.
