### ISSUE TITLE
Add button to activate sleep mode

### ISSUE THREAD

**Issue by Harvie** [winder/Universal-G-Code-Sender#933]
Grbl 1.1 has feature, that it can go to sleep mode using $SLP command and wake up by reset.
Can you please add button for this? There's place just for one more button :-)

![image](https://user-images.githubusercontent.com/276504/36956964-7cf5f818-2031-11e8-90a3-3b3033681bb6.png)

**Comment by jahnj0584** [comment]
Can you add it as a macro?

**Comment by yaroslavVl** [comment]
Could you please add SLEEP button?!

**Comment by breiler** [comment]
This can be added as a macro
