### ISSUE TITLE
pendant 1mm/min 

### ISSUE THREAD

**Issue by electric1236** [winder/Universal-G-Code-Sender#934]
so I used to use grbl 0.9 and ugs (2.0) with their pendant web server when I upgraded to grbl 1.1 the pendant still worked but it had a feed rate of 1 mm/minute which makes it pretty much useless, can't find any setting to change it.

**Comment by jahnj0584** [comment]
Copy of #904

**Comment by breiler** [comment]
Closed as it's a duplicate
