### ISSUE TITLE
Audio feedback

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#935]
At surface level: A beep when job is complete (UGS sends a M30)

Additional: Whenever a certain command is sent. I slot guitar fretboards with a 0.5mm bit that sometimes/often breaks, so if i got a beep with every Z2 command, I'd know when to come over and look at the bit when it raises to the safety plane and see if its still there!

**Comment by winder** [comment]
Duplicate of #814
