### ISSUE TITLE
What pendant can be used?

### ISSUE THREAD

**Issue by adigitaldj1** [winder/Universal-G-Code-Sender#937]
I would like to use a pendant, what would be a good one to use?

**Comment by winder** [comment]
UGS doesn't have any special pendant handling at this time.

**Comment by petmakris** [comment]
I have a HB04 XHC pendant in hand, wireless, which outputs via HID. If UGS supports plugins or a way add functionality I could write this interface.

Came here looking for plugin support in UGS for this matter

**Comment by winder** [comment]
@petmakris UGS has plugin support, you can setup the boilerplate with this maven archetype:

https://github.com/winder/Universal-G-Code-Sender/tree/master/new-module-archetype

**Comment by petmakris** [comment]
Thanks winder, I already found this out.

**Comment by jasonhamilton** [comment]
Curious if you made any progress on this.  I have a HB04 pendant that I would like to use.
