### ISSUE TITLE
Request: Visualizer Origin Select

### ISSUE THREAD

**Issue by CNCQuilter** [winder/Universal-G-Code-Sender#938]
I am using UGSPlatform along with GRBL and hand-derived gcode to control a consumer level quilting machine. The gcode for sewing continuous designs/curves is derived either by hand or by Visual Basic and/or EXCEL mathematical functions. For me, it would be advantageous to be able to change the 0.0, 0.0 origin in the Visualizer Window. Out of a long ago acquired habit (and serendipitous for quilting), my origin starts at the upper left hand corner with X+ to the right and Y+ from top to bottom.
Is it possible to reset the 0.0. , 0.0 origin in the Visualizer to the top left corner?

Thank you.

**Comment by winder** [comment]
The visualizer isn't really intended to represent the machine at this point, it is purely centered around the gcode. Being able to define your machine space would be a cool feature at some point, and would make setup operations more interesting in the visualizer.

Also inverting the Y axis isn't something that I can support right now.

To have the visualizer show up this way you would need to configure your gcode in the X+ and Y- space.

**Comment by CNCQuilter** [comment]
Thanks for your reply, I really appreciate your efforts.

Dave Kender



________________________________

**Comment by jahnj0584** [comment]
Gcode ripper can swap your axis or even apply a rotation to the file

On Mar 10, 2018 8:15 AM, "CNCQuilter" <notifications@github.com> wrote:

Thanks for your reply, I really appreciate your efforts.

Dave Kender



________________________________
