### ISSUE TITLE
Gcode window for read and/or editing & Job's time estimation ?

### ISSUE THREAD

**Issue by Myke974** [winder/Universal-G-Code-Sender#946]
Hey there !
First, developpers&others, Thank you for the awesome job and Thank You for sharing opensource !
I'm actually using Universak Gcode Platform with cheap cnc shield V3 
![cnc_bureaumetal_19](https://user-images.githubusercontent.com/1829188/37433686-435e955c-27f6-11e8-9df6-aa8722c5bc0b.jpg)
and so far I got to use my homemade cheap CNC in plotter mode
![cnc_bureaumetal_20](https://user-images.githubusercontent.com/1829188/37433685-4326fba6-27f6-11e8-91d8-fc8e2e25eb84.jpg)
and since few days in Laser mode ! ! Everything is working like a charm ! 👍 
WooooooooooooooT ! ! 🤣 

Second : 2 questions : 
1] I can't find where to see the actual gcode of an imported file 😅 

2] Is there a way to have a job's time estimation ?

Regards

**Comment by jahnj0584** [comment]
You don't see the code. UGS only streams it to the arduino due to size issues. A built in text editor is in the works 

Send progress shows what you need.

**Comment by winder** [comment]
There used to be a way to export the processed gcode (i.e. the code after it has had comments/whitespace removed, decimals truncated, etc), but that feature never made it to the platform version of UGS.

@Myke974 is that the feature you're asking about with your first question?
