### ISSUE TITLE
Visualizer hates this file

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#948]
use the same processor for months without issue. For some reason it freaks out over this code. 

https://drive.google.com/open?id=18kdUcvOz1Rd1W3DEPlDHJ4zV5YLLAfXS

Edit: Ran it anyays. Had no issues

**Comment by jahnj0584** [comment]
working on permissions

**Comment by jahnj0584** [comment]
Permissed

**Comment by breiler** [comment]
The rendering is consistent with https://ncviewer.com/, closing the issue.
