### ISSUE TITLE
free GRBL post - spindle dwell, no G28, proper M5, spindle speed alarms, custom set retract coords

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#953]
Enjoy. I take no responsibility for anything that happens etc etc

https://drive.google.com/file/d/1SudPWHNdXibP85aHP4MyAplFZhjEu388/view?usp=sharing

**Comment by breiler** [comment]
While I appreciate tips and tricks I don't think this is the right forum for these kinds of posts. 
I mean, when do we close this "issue"?

**Comment by winder** [comment]
Thanks, but I agree with @breiler here. I'm not really sure what to do with this in the context of UGS issues/features.
