### ISSUE TITLE
UGS Google drive?

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#955]
It'd be cool if you uploaded/updated UGS on google drive, so that way we could automatically sync the latest ZIP file on our computers without having to visit the site. Doesnt take long to set up, just upload it and each person selects "add to my gdrive"! 

Good little  patch until auto update works?

**Comment by winder** [comment]
That isn't a direction I want to go in, mainly from an automation standpoint. The UGS deployment process is completely automated, I'm using cloudbees/sourceforge for file hosting currently. I've considered going back to my old GitHub "builds" project for the simplicity, or maybe try getting an open source account with artifactory.
