### ISSUE TITLE
inconsisten overrides

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#958]
Sometimes the overrides stay after a job is sent, and is applied to the next file sent (issue when its over 100%). Sometimes its reset and no longer active (issue when its under 100%).

Ive also had it once be applied, but the feed rate was what was programmed (no its not near my max speeds)

It should be a constant application, going off of my experience with Haas machines.

**Comment by zeevy** [comment]
Grbl firmware will reset the overrides after the program end command ie M02.
If your gocode file don't have "M02" as the last line, then Grbl will not reset the overrides.

**Comment by winder** [comment]
thanks @zeevy

**Comment by jahnj0584** [comment]
All my files are with the same post and end with m30

**Comment by zeevy** [comment]
m30 will also resets the feed overrides
