### ISSUE TITLE
UGS table visualizer screen

### ISSUE THREAD

**Issue by vMeph** [winder/Universal-G-Code-Sender#960]
@winder ,@breiler , @dastultz  UGS is looking better and better...
is there any way we could get a better visualize like http://chilipeppr.com/grbl style?
that would rox...

**Comment by winder** [comment]
The current visualizer is about as fancy as I can make it.

**Comment by dastultz** [comment]
A lot can be done with color choice:

<img width="749" alt="screen shot 2018-03-18 at 8 34 14 pm" src="https://user-images.githubusercontent.com/4334042/37573215-db5a8c10-2aeb-11e8-985b-1ccbf734c53e.png">

**Comment by jahnj0584** [comment]
Nice. A lot can be done with changing your keep tool down settings too ;)
