### ISSUE TITLE
UGS Platform 2.0 64 not opening after Windows Creators Update PLZ HELP

### ISSUE THREAD

**Issue by landbrad** [winder/Universal-G-Code-Sender#966]
### Steps to Reproduce the Problem

  1.
  1.
  1.

#### Version

- [x] UGS Platform 2.0 - Nightly Build
- [ ] UGS Platform 2.0 - Stable
- [ ] UGS Classic 2.0 - Nightly Build
- [ ] UGS Classic 2.0 - Stable
- [ ] UGS Classic 1.0.9
- [ ] UGS Classic 1.0.8
- [ ] UGS Classic 1.0.7

#### Operating system

- [x] Windows
- [ ] Linux
- [ ] Linux on RaspberryPI
- [ ] Mac OSX
- [ ] Other

#### Platform

- [x] GRBL 1.0 or later
- [ ] GRBL 0.9
- [ ] GRBL 0.8
- [ ] TinyG
- [ ] SmoothieBoard

**Comment by breiler** [comment]
What version of Java are you using?
(Open command terminal and run `java -version`)

**Comment by breiler** [comment]
Closing because additional information is missing.
