### ISSUE TITLE
Gcode sender 1.0.9 don't start

### ISSUE THREAD

**Issue by etayl** [winder/Universal-G-Code-Sender#975]
## Problem description 
when i double click the 'start-windows.bat' file. a black command line appears but then nothing happend

### Steps to Reproduce the Problem
each time i execute the gcode sender
#### Version
UGS v.1.0.9

#### Operating system

  Windows 10
 
#### Platform

  GRBL 1.1f
  

#### Other
![image](https://user-images.githubusercontent.com/5585206/37990785-eaa80690-320f-11e8-8f3d-2a9d212e7478.png)

**Comment by winder** [comment]
For starters, please give one of the nightly versions a try. You'll need it for GRBL 1.1 support. Does the problem still occur after that?
