### ISSUE TITLE
Plug-in Test probe

### ISSUE THREAD

**Issue by gelius59** [winder/Universal-G-Code-Sender#976]
When the probe is working, the algorithm is
Move down with a great speed to touch
Move upward 1 mm
Move to the bottom with a slow speed at a distance set in the plugin.
The distance is the same as for high speed.
I think the distance, for low speed, should be configurable in the plug-in on the setup tab.
Or equal to 2 or 3 mm
Sorry for my bad english

**Comment by winder** [comment]
Why would you need to configure the slow probe? Are you concerned that the plate will move between the fast and slow probe operations?

**Comment by breiler** [comment]
There is a setting for the retract amount after the first probe:
![image](https://github.com/winder/Universal-G-Code-Sender/assets/8962024/45e674df-8d35-43b1-8bdd-cbbf0d5e420a)
