### ISSUE TITLE
UGS Doesnt recognize macro deletion

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#980]
## Problem description 
I deleted macro #4 in my options. It reflects as such by changing the name field back to 4 and the macro is removed from my macro toolbox. Other macros now act out of order

### Actual Behavior
Macro 6 (in my case, probe Z) now still reads probe Z in the toolbox, but enacts the action of macro 5 which is home all axis.

### Steps to Reproduce the Problem
Create macros for 1,2,3
Delete macro 1
Macro 3 will now send the commands that macro 2 is designed to do.

#### Version
Feb 18 platform

#### Operating system
  Windows 7
#### Platform
  GRBL 1.1f

**Comment by gixxergreko** [comment]
Having the same problem
