### ISSUE TITLE
Homing machine should set soft limits that are respected by jog.

### ISSUE THREAD

**Issue by RecceDG** [winder/Universal-G-Code-Sender#982]
Turn on machine.

Connect.

Select "Home Machine" which clears initial alarm and moves machine to limit switches.

Machine now knows machine 0,0,0.

Attempting to jog machine will indeed try and move past the physical stops, causing a significant emotional event.

The jog module should refuse to move the machine past machine zero.

**Comment by breiler** [comment]
Duplicate of #983. Soft limits were not activated.
