### ISSUE TITLE
Two instances of UGS.

### ISSUE THREAD

**Issue by BallscrewBob** [winder/Universal-G-Code-Sender#996]
## Feature request
Ability to run two instances of UGS v2.0 nightly
Built a second machine but if I try open a new instance it just re-opens the existing instance.
Is there a method to do this easily ?

**Comment by winder** [comment]
There are some directions for how to do this here, let me know if that doesn't work and I can try playing around with the settings:
http://wiki.netbeans.org/FaqMultipleIdeInstances

**Comment by BallscrewBob** [comment]
NICE !...I dont use Mac';s but thats a great help...I can script that into
a new shortcut in Windows.
Will let you know how it works and thanks for the help.
Much appreciated.

**Comment by winder** [comment]
The link I shared earlier has the windows command as well, it looks very similar but also includes a cache directory. That seems odd to me, maybe it's optional. You should be able to get it working though.
